//! Unified theme: a single source of truth for all phi color roles.
//!
// Every consumer — the mux compositor (via `phi-grid`), the markdown renderer,
// the inline session TUI, and the CLI glyphs — derives its palette from a
// `Theme` generated by [`generate_theme`].  This replaces the previous
// arrangement where four independent palette systems each re-derived colors
// from the same `TerminalColors` with duplicated logic.
//!
// The `Theme` uses [`Rgb`] (the same type `TerminalColors` uses) so it is
// crate-agnostic.  Consumers that need a different color type (e.g.
// `phi_grid::Color`) convert at the adapter boundary.

use crate::palette::{Rgb, TerminalColors};

// ---------------------------------------------------------------------------
// Theme — the unified role set
// ---------------------------------------------------------------------------

/// The single source of truth for every color role in phi.
///
/// Generated by [`generate_theme`] from the host terminal's reported colors
/// (OSC 10/11/4).  Each field is an `Rgb` triple so the struct is independent
/// of any consumer's native color type.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Theme {
    // --- Core text / surface ---
    /// Primary text color (terminal foreground).
    pub foreground: Rgb,
    /// Terminal background.
    pub background: Rgb,
    /// Muted / secondary text.
    pub muted: Rgb,
    /// Heading text (slightly brighter than muted).
    pub heading: Rgb,

    // --- Text value ramp (crush-style four-level hierarchy) ---
    // Hierarchy is carried by luminance, not hue: `foreground` is the
    // primary level; these three are progressively quieter blends of the
    // foreground toward the background. Every muted surface picks a level
    // instead of relying on the terminal's uncontrolled SGR `DIM`.
    /// Secondary text — body content one step below primary (tool output).
    pub text_secondary: Rgb,
    /// Tertiary text — annotations, hints, truncation notices, arg values.
    pub text_tertiary: Rgb,
    /// Ghost text — structural marks: rules, fence borders, placeholders.
    pub text_ghost: Rgb,

    // --- Surfaces (gray ramp derived from background) ---
    /// Canvas / panel background (gray ramp level 2).
    pub surface: Rgb,
    /// Raised surface — statusbar, overlays (gray ramp level 3).
    pub surface_raised: Rgb,
    /// Border / divider color (gray ramp level 7).
    pub border: Rgb,

    // --- Accents ---
    /// Primary accent (ANSI 6 / cyan).
    pub accent: Rgb,
    /// Secondary accent (ANSI 5 / magenta).
    pub accent_2: Rgb,

    // --- Status ---
    /// Running / active indicator (ANSI 10 / bright green).
    pub running: Rgb,
    /// Success (ANSI 2 / green).
    pub success: Rgb,
    /// Subtle success tint (surface blended toward green).
    pub success_subtle: Rgb,
    /// Warning (ANSI 3 / yellow).
    pub warning: Rgb,
    /// Error (ANSI 1 / red).
    pub error: Rgb,

    // --- ANSI palette (resolved) ---
    /// The full 16-entry ANSI palette, resolved from the terminal or the
    /// 256-color cube fallback.
    pub ansi: [Rgb; 16],

    // --- Chat / inline TUI roles ---
    /// Tool accent (ANSI 3 / yellow, bold).
    pub tool_accent: Rgb,
    /// Tool title text (ANSI 7 / white, bold).
    pub tool_title: Rgb,
    /// Tool output text (ANSI 8 / bright black).
    pub tool_output: Rgb,
    /// Sub-LLM / subcall accent (ANSI 5 / magenta, bold).
    pub subcall_accent: Rgb,
    /// Path-like argument (ANSI 4 / blue).
    pub path: Rgb,
    /// String-like argument (ANSI 2 / green).
    pub string: Rgb,
    /// Number / duration (ANSI 3 / yellow).
    pub number: Rgb,
    /// User-echo text (ANSI 7 / white).
    pub user_fg: Rgb,
    /// Assistant prose (ANSI 7 / white).
    pub assistant_fg: Rgb,
    /// Panel / REPL fence (ANSI 5 / magenta).
    pub panel_repl: Rgb,

    // --- Chat backgrounds (terminal bg tinted toward an ANSI color) ---
    /// User message background (bg tinted toward ANSI 4).
    pub user_message_bg: Rgb,
    /// Tool pending background (bg tinted toward ANSI 8).
    pub tool_pending_bg: Rgb,
    /// Tool success background (bg tinted toward ANSI 2).
    pub tool_success_bg: Rgb,
    /// Tool error background (bg tinted toward ANSI 1).
    pub tool_error_bg: Rgb,
    /// REPL block background (bg tinted toward ANSI 8).
    pub repl_bg: Rgb,

    // --- Nested tool backgrounds (slightly brighter than the base) ---
    // When a tool card is rendered inside a REPL block, it sits on the
    // same colour as the block's outer background. These "nested"
    // variants are a few steps brighter so the inner card stands out
    // from its enclosing container.
    /// Nested tool pending background (brightened `tool_pending_bg`).
    pub tool_pending_bg_nested: Rgb,
    /// Nested tool success background (brightened `tool_success_bg`).
    pub tool_success_bg_nested: Rgb,
    /// Nested tool error background (brightened `tool_error_bg`).
    pub tool_error_bg_nested: Rgb,

    // --- Chrome ---
    /// Chrome agent label (ANSI 7 / white, bold).
    pub chrome_agent: Rgb,
    /// Chrome cost figure (ANSI 2 / green, bold).
    pub chrome_cost: Rgb,
    /// Chrome directory (ANSI 10 / bright green, bold).
    pub chrome_dir: Rgb,
    /// Chrome model name (ANSI 13 / bright magenta, bold).
    pub chrome_model: Rgb,
    /// Statusbar background (gray ramp level 3, same as surface_raised).
    pub statusbar_bg: Rgb,

    // --- Thinking levels ---
    /// Off (ANSI 8 / bright black, bold).
    pub thinking_off: Rgb,
    /// Minimal (ANSI 7 / white, bold).
    pub thinking_minimal: Rgb,
    /// Low (ANSI 4 / blue, bold).
    pub thinking_low: Rgb,
    /// Medium (ANSI 6 / cyan, bold).
    pub thinking_medium: Rgb,
    /// High (ANSI 5 / magenta, bold).
    pub thinking_high: Rgb,
    /// Extra-high (ANSI 13 / bright magenta, bold).
    pub thinking_xhigh: Rgb,

    // --- Markdown roles ---
    /// REPL fence (ANSI 5 / magenta).
    pub md_repl_fence: Rgb,
    /// Marker accent (ANSI 4 / blue).
    pub md_marker_accent: Rgb,
    /// Task done marker (ANSI 2 / green).
    pub md_task_done: Rgb,
    /// Quote bar (ANSI 5 / magenta).
    pub md_quote_bar: Rgb,
    /// Subheading (ANSI 13 / bright magenta).
    pub md_subhead: Rgb,
    /// Output base text (ANSI 7 / white).
    pub md_out_base: Rgb,
    /// Output error (ANSI 1 / red).
    pub md_out_err: Rgb,
    /// Output warning (ANSI 3 / yellow).
    pub md_out_warn: Rgb,
    /// Output ok (ANSI 2 / green).
    pub md_out_ok: Rgb,
    /// Output path (ANSI 4 / blue).
    pub md_out_path: Rgb,
    /// Output number (ANSI 3 / yellow).
    pub md_out_num: Rgb,
    /// Output string (ANSI 2 / green).
    pub md_out_str: Rgb,
    /// Output URL (ANSI 6 / cyan).
    pub md_out_url: Rgb,
    /// Diff added (ANSI 2 / green).
    pub md_diff_add: Rgb,
    /// Diff removed (ANSI 1 / red).
    pub md_diff_del: Rgb,

    // --- Syntax highlighting ---
    /// Comment (ANSI 8 / bright black).
    pub syntax_comment: Rgb,
    /// Keyword (ANSI 5 / magenta).
    pub syntax_keyword: Rgb,
    /// String (ANSI 2 / green).
    pub syntax_string: Rgb,
    /// Number (ANSI 3 / yellow).
    pub syntax_number: Rgb,
    /// Function (ANSI 4 / blue).
    pub syntax_function: Rgb,
    /// Type (ANSI 6 / cyan).
    pub syntax_type: Rgb,
    /// Operator (ANSI 6 / cyan).
    pub syntax_operator: Rgb,
    /// Variable (foreground).
    pub syntax_variable: Rgb,
    /// Builtin (ANSI 1 / red).
    pub syntax_builtin: Rgb,

    // --- CLI glyphs ---
    /// Active / in-flight glyph (ANSI 4 / blue).
    pub glyph_active: Rgb,
    /// OK / success glyph (ANSI 2 / green).
    pub glyph_ok: Rgb,
    /// Error glyph (ANSI 1 / red).
    pub glyph_err: Rgb,
}

// ---------------------------------------------------------------------------
// Mode detection
// ---------------------------------------------------------------------------

/// Light or dark mode, derived from the terminal background luminance.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Mode {
    Dark,
    Light,
}

pub fn terminal_mode(colors: &TerminalColors) -> Mode {
    let c = colors.background;
    if luminance_rgb(c.0, c.1, c.2) > 127 {
        Mode::Light
    } else {
        Mode::Dark
    }
}

// ---------------------------------------------------------------------------
// Theme generation
// ---------------------------------------------------------------------------

/// Generate a complete [`Theme`] from the host terminal's reported colors.
///
/// This is the **single derivation path** — every role (surfaces, accents,
/// status, chat, markdown, syntax, CLI glyphs) is resolved here from one
/// ANSI→role mapping table and one gray-scale generator.  All consumers build
/// their palette structs from the returned `Theme`.
pub fn generate_theme(colors: &TerminalColors) -> Theme {
    let mode = terminal_mode(colors);
    let bg = colors.background;
    let fg = colors.foreground;
    let grays = generate_gray_scale(bg, mode);
    let muted = generate_muted_text(bg, mode);
    let ansi = ansi_from_terminal(colors);
    let col = |i: u8| -> Rgb { palette_color(colors, i) };

    let subtle_alpha = if matches!(mode, Mode::Dark) { 56 } else { 36 };

    Theme {
        // Core
        foreground: fg,
        background: bg,
        muted,
        heading: grays[9], // brighter than muted

        // Text value ramp: deliberate, roughly equal luminance steps from
        // primary (fg) down toward the background.
        text_secondary: fade_toward(bg, fg, 200),
        text_tertiary: fade_toward(bg, fg, 140),
        text_ghost: fade_toward(bg, fg, 80),

        // Surfaces
        surface: grays[2],
        surface_raised: grays[3],
        border: grays[7],

        // Accents
        accent: col(6),
        accent_2: col(5),

        // Status
        running: col(10),
        success: col(2),
        success_subtle: fade_toward(grays[2], col(2), subtle_alpha),
        warning: col(3),
        error: col(1),

        // ANSI
        ansi,

        // Chat / inline TUI
        tool_accent: col(3),
        tool_title: col(7),
        tool_output: col(8),
        subcall_accent: col(5),
        path: col(4),
        string: col(2),
        number: col(3),
        user_fg: col(7),
        assistant_fg: col(7),
        panel_repl: col(5),

        // Chat backgrounds
        user_message_bg: tint_bg(bg, colors, 4),
        tool_pending_bg: tint_bg(bg, colors, 8),
        tool_success_bg: tint_bg(bg, colors, 2),
        tool_error_bg: tint_bg(bg, colors, 1),
        repl_bg: tint_bg(bg, colors, 8),

        // Nested tool backgrounds: brighten the base bg so a tool card
        // nested inside a REPL block (which uses the same base bg) is
        // distinguishable from its enclosing container.
        tool_pending_bg_nested: brighten(tint_bg(bg, colors, 8), 8),
        tool_success_bg_nested: brighten(tint_bg(bg, colors, 2), 8),
        tool_error_bg_nested: brighten(tint_bg(bg, colors, 1), 8),

        // Chrome
        chrome_agent: col(7),
        chrome_cost: col(2),
        chrome_dir: col(10),
        chrome_model: col(13),
        statusbar_bg: grays[3],

        // Thinking levels
        thinking_off: col(8),
        thinking_minimal: col(7),
        thinking_low: col(4),
        thinking_medium: col(6),
        thinking_high: col(5),
        thinking_xhigh: col(13),

        // Markdown
        md_repl_fence: col(5),
        md_marker_accent: col(4),
        md_task_done: col(2),
        md_quote_bar: col(5),
        md_subhead: col(13),
        md_out_base: col(7),
        md_out_err: col(1),
        md_out_warn: col(3),
        md_out_ok: col(2),
        md_out_path: col(4),
        md_out_num: col(3),
        md_out_str: col(2),
        md_out_url: col(6),
        md_diff_add: col(2),
        md_diff_del: col(1),

        // Syntax
        syntax_comment: col(8),
        syntax_keyword: col(5),
        syntax_string: col(2),
        syntax_number: col(3),
        syntax_function: col(4),
        syntax_type: col(6),
        syntax_operator: col(6),
        syntax_variable: fg,
        syntax_builtin: col(1),

        // CLI glyphs
        glyph_active: col(4),
        glyph_ok: col(2),
        glyph_err: col(1),
    }
}

/// Standard ANSI 16-color palette + black background / gray foreground, used
/// as the fallback when the terminal doesn't answer OSC probes (SSH, CI, etc.).
pub fn default_terminal_colors() -> TerminalColors {
    const STD: [Rgb; 16] = [
        Rgb(0x00, 0x00, 0x00),
        Rgb(0x80, 0x00, 0x00),
        Rgb(0x00, 0x80, 0x00),
        Rgb(0x80, 0x80, 0x00),
        Rgb(0x00, 0x00, 0x80),
        Rgb(0x80, 0x00, 0x80),
        Rgb(0x00, 0x80, 0x80),
        Rgb(0xc0, 0xc0, 0xc0),
        Rgb(0x80, 0x80, 0x80),
        Rgb(0xff, 0x00, 0x00),
        Rgb(0x00, 0xff, 0x00),
        Rgb(0xff, 0xff, 0x00),
        Rgb(0x00, 0x00, 0xff),
        Rgb(0xff, 0x00, 0xff),
        Rgb(0x00, 0xff, 0xff),
        Rgb(0xff, 0xff, 0xff),
    ];
    TerminalColors {
        background: Rgb(0x00, 0x00, 0x00),
        foreground: Rgb(0xc0, 0xc0, 0xc0),
        palette: STD.map(Some),
    }
}

// ---------------------------------------------------------------------------
// Color utilities (shared — no more duplicates)
// ---------------------------------------------------------------------------

/// Linearly interpolate `from` toward `target` by `mix` (0..255).
pub fn fade_toward(from: Rgb, target: Rgb, mix: u8) -> Rgb {
    let blend = |a: u8, b: u8| -> u8 {
        let a = u16::from(a);
        let b = u16::from(b);
        let mix = u16::from(mix);
        (((a * (255 - mix)) + (b * mix)) / 255) as u8
    };
    Rgb(
        blend(from.0, target.0),
        blend(from.1, target.1),
        blend(from.2, target.2),
    )
}

/// Saturating-add `amount` to each channel.
pub fn brighten(c: Rgb, amount: u8) -> Rgb {
    Rgb(
        c.0.saturating_add(amount),
        c.1.saturating_add(amount),
        c.2.saturating_add(amount),
    )
}

pub fn luminance_rgb(r: u8, g: u8, b: u8) -> u32 {
    (u32::from(r) * 299 + u32::from(g) * 587 + u32::from(b) * 114) / 1000
}

/// Resolve an ANSI palette index to an `Rgb` via the 256-color cube.
pub fn ansi_index_to_rgb(idx: u8) -> Rgb {
    let (r, g, b) = match idx {
        0 => (0x1d, 0x23, 0x2f),
        1 => (0xf7, 0x76, 0x8e),
        2 => (0x6f, 0xc7, 0x88),
        3 => (0xf4, 0xd0, 0x6b),
        4 => (0x7a, 0xa2, 0xf7),
        5 => (0xbb, 0x9a, 0xf7),
        6 => (0x7d, 0xd8, 0xe8),
        7 => (0xc8, 0xd3, 0xf5),
        8 => (0x44, 0x4b, 0x6a),
        9 => (0xff, 0x9e, 0xb0),
        10 => (0x8b, 0xde, 0xa3),
        11 => (0xfa, 0xe3, 0x8c),
        12 => (0x91, 0xb7, 0xff),
        13 => (0xce, 0xb6, 0xff),
        14 => (0x99, 0xe2, 0xf0),
        15 => (0xe5, 0xe9, 0xf0),
        16..=231 => {
            let index = idx - 16;
            let r = index / 36;
            let g = (index % 36) / 6;
            let b = index % 6;
            (cube_component(r), cube_component(g), cube_component(b))
        }
        232..=255 => {
            let shade = 8 + (idx - 232) * 10;
            (shade, shade, shade)
        }
    };
    Rgb(r, g, b)
}

const fn cube_component(component: u8) -> u8 {
    if component == 0 {
        0
    } else {
        55 + component * 40
    }
}

/// Format an `Rgb` as a foreground SGR escape: truecolor where the
/// terminal supports it, quantized to xterm-256 where it doesn't.
pub fn fg_escape(c: Rgb) -> String {
    crate::color_cap::fg_sequence(c)
}

/// Format an `Rgb` as a background SGR escape (see [`fg_escape`]).
pub fn bg_escape(c: Rgb) -> String {
    crate::color_cap::bg_sequence(c)
}

/// Format an `Rgb` as a bold + foreground SGR escape (see [`fg_escape`]).
pub fn bold_fg_escape(c: Rgb) -> String {
    format!("\x1b[1m{}", crate::color_cap::fg_sequence(c))
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

fn palette_color(colors: &TerminalColors, idx: u8) -> Rgb {
    colors.palette[idx as usize].unwrap_or_else(|| ansi_index_to_rgb(idx))
}

fn ansi_from_terminal(colors: &TerminalColors) -> [Rgb; 16] {
    let mut out = [Rgb(0, 0, 0); 16];
    for i in 0..16u8 {
        out[i as usize] = palette_color(colors, i);
    }
    out
}

/// Blend 20% of an ANSI tint into the terminal background for a subtle wash.
fn tint_bg(bg: Rgb, colors: &TerminalColors, ansi_idx: u8) -> Rgb {
    let tint = colors.palette[ansi_idx as usize].unwrap_or(bg);
    let blend = |bg_c: u8, tint_c: u8| -> u8 {
        ((f64::from(bg_c) * 0.8) + (f64::from(tint_c) * 0.2)).round() as u8
    };
    Rgb(
        blend(bg.0, tint.0),
        blend(bg.1, tint.1),
        blend(bg.2, tint.2),
    )
}

/// 12-step ramp (indices 1..=12; index 0 unused) derived from the terminal
/// background, matching opencode's `generateGrayScale`.
fn generate_gray_scale(bg: Rgb, mode: Mode) -> [Rgb; 13] {
    let mut grays = [Rgb(0, 0, 0); 13];
    let lum = luminance_rgb(bg.0, bg.1, bg.2);
    let dark = matches!(mode, Mode::Dark);

    for i in 1..=12u8 {
        let factor = f64::from(i) / 12.0;
        let (r, g, b) = if dark {
            if lum < 10 {
                let v = (factor * 0.4 * 255.0).floor() as u8;
                (v, v, v)
            } else {
                let new_lum = f64::from(lum) + (255.0 - f64::from(lum)) * factor * 0.4;
                let ratio = new_lum / f64::from(lum);
                scale_toward(bg.0, bg.1, bg.2, ratio, false)
            }
        } else if lum > 245 {
            let v = (255.0 - factor * 0.4 * 255.0).floor() as u8;
            (v, v, v)
        } else {
            let new_lum = f64::from(lum) * (1.0 - factor * 0.4);
            let ratio = new_lum / f64::from(lum);
            scale_toward(bg.0, bg.1, bg.2, ratio, true)
        };
        grays[i as usize] = Rgb(r, g, b);
    }
    grays
}

fn scale_toward(r: u8, g: u8, b: u8, ratio: f64, floor: bool) -> (u8, u8, u8) {
    let clamp = |v: f64| {
        let v = v * ratio;
        if floor { v.max(0.0) } else { v.min(255.0) }
    };
    (
        clamp(f64::from(r)) as u8,
        clamp(f64::from(g)) as u8,
        clamp(f64::from(b)) as u8,
    )
}

/// Port of opencode's `generateMutedTextColor`: a neutral gray tuned to the
/// background luminance so muted text stays readable in both modes.
fn generate_muted_text(bg: Rgb, mode: Mode) -> Rgb {
    let lum = luminance_rgb(bg.0, bg.1, bg.2);
    let gray = if matches!(mode, Mode::Dark) {
        if lum < 10 {
            180u16
        } else {
            ((160.0 + f64::from(lum) * 0.3).min(200.0)) as u16
        }
    } else if lum > 245 {
        75u16
    } else {
        ((100.0 - (255.0 - f64::from(lum)) * 0.2).max(60.0)) as u16
    };
    Rgb(gray as u8, gray as u8, gray as u8)
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    fn colors_from(bg: Rgb, fg: Rgb) -> TerminalColors {
        TerminalColors {
            background: bg,
            foreground: fg,
            palette: std::array::from_fn(|i| Some(Rgb(i as u8 * 8, i as u8 * 8, i as u8 * 8))),
        }
    }

    #[test]
    fn terminal_mode_splits_on_background_luminance() {
        assert_eq!(
            terminal_mode(&colors_from(Rgb(0, 0, 0), Rgb(255, 255, 255))),
            Mode::Dark
        );
        assert_eq!(
            terminal_mode(&colors_from(Rgb(255, 255, 255), Rgb(0, 0, 0))),
            Mode::Light
        );
    }

    #[test]
    fn generate_theme_maps_ansi_roles() {
        let colors = colors_from(Rgb(20, 20, 26), Rgb(220, 220, 220));
        let theme = generate_theme(&colors);

        assert_eq!(theme.accent, theme.ansi[6]);
        assert_eq!(theme.accent_2, theme.ansi[5]);
        assert_eq!(theme.error, theme.ansi[1]);
        assert_eq!(theme.success, theme.ansi[2]);
        assert_eq!(theme.warning, theme.ansi[3]);
        assert_eq!(theme.running, theme.ansi[10]);
        assert_eq!(theme.foreground, Rgb(220, 220, 220));
    }

    #[test]
    fn generate_theme_falls_back_to_cube_for_missing_palette() {
        let mut colors = colors_from(Rgb(0, 0, 0), Rgb(255, 255, 255));
        colors.palette[6] = None;
        let theme = generate_theme(&colors);
        assert_eq!(theme.accent, ansi_index_to_rgb(6));
    }

    #[test]
    fn text_ramp_descends_in_luminance() {
        let colors = colors_from(Rgb(20, 20, 26), Rgb(220, 220, 220));
        let theme = generate_theme(&colors);
        let lum = |c: Rgb| luminance_rgb(c.0, c.1, c.2);
        assert!(lum(theme.foreground) > lum(theme.text_secondary));
        assert!(lum(theme.text_secondary) > lum(theme.text_tertiary));
        assert!(lum(theme.text_tertiary) > lum(theme.text_ghost));
        assert!(lum(theme.text_ghost) > lum(theme.background));
    }

    #[test]
    fn muted_text_is_neutral_and_lighter_on_dark_than_background() {
        let colors = colors_from(Rgb(20, 20, 26), Rgb(220, 220, 220));
        let theme = generate_theme(&colors);
        assert_eq!(theme.muted.0, theme.muted.1);
        assert_eq!(theme.muted.1, theme.muted.2);
        assert!(u32::from(theme.muted.0) > luminance_rgb(20, 20, 26));
    }

    #[test]
    fn success_subtle_is_a_tint_toward_green() {
        let colors = colors_from(Rgb(20, 20, 26), Rgb(220, 220, 220));
        let theme = generate_theme(&colors);
        // The subtle tint should be between the surface and green, not equal to either.
        assert_ne!(theme.success_subtle, theme.surface);
        assert_ne!(theme.success_subtle, theme.success);
    }

    #[test]
    fn tint_bg_blends_80_20() {
        let colors = colors_from(Rgb(20, 20, 26), Rgb(220, 220, 220));
        let theme = generate_theme(&colors);
        // user_message_bg is bg tinted toward ANSI 4 (which is (32,32,32) in test colors)
        let expected_r = ((20.0_f64 * 0.8) + (32.0 * 0.2)).round() as u8;
        assert_eq!(theme.user_message_bg.0, expected_r);
    }

    #[test]
    fn default_terminal_colors_is_valid() {
        let colors = default_terminal_colors();
        let theme = generate_theme(&colors);
        assert_eq!(theme.foreground, Rgb(0xc0, 0xc0, 0xc0));
        assert_eq!(theme.background, Rgb(0, 0, 0));
    }

    #[test]
    fn fade_toward_interpolates() {
        assert_eq!(
            fade_toward(Rgb(0, 0, 0), Rgb(255, 255, 255), 128),
            Rgb(128, 128, 128)
        );
        assert_eq!(
            fade_toward(Rgb(0, 0, 0), Rgb(255, 255, 255), 0),
            Rgb(0, 0, 0)
        );
        assert_eq!(
            fade_toward(Rgb(0, 0, 0), Rgb(255, 255, 255), 255),
            Rgb(255, 255, 255)
        );
    }

    #[test]
    fn brighten_saturates() {
        assert_eq!(brighten(Rgb(200, 200, 200), 100), Rgb(255, 255, 255));
        assert_eq!(brighten(Rgb(100, 100, 100), 50), Rgb(150, 150, 150));
    }

    #[test]
    fn nested_tool_bgs_are_brighter_than_base() {
        let colors = colors_from(Rgb(20, 20, 26), Rgb(220, 220, 220));
        let theme = generate_theme(&colors);
        // Each nested variant should be strictly brighter than its base.
        assert_eq!(
            theme.tool_pending_bg_nested,
            brighten(theme.tool_pending_bg, 8)
        );
        assert_eq!(
            theme.tool_success_bg_nested,
            brighten(theme.tool_success_bg, 8)
        );
        assert_eq!(theme.tool_error_bg_nested, brighten(theme.tool_error_bg, 8));
    }

    // Escape-format tests pin the capability so they don't depend on the
    // harness environment (first force wins process-wide; harmless later).
    #[test]
    fn fg_escape_formats_truecolor() {
        crate::color_cap::force_color_capability(crate::color_cap::ColorCapability::TrueColor);
        assert_eq!(fg_escape(Rgb(130, 160, 230)), "\x1b[38;2;130;160;230m");
    }

    #[test]
    fn bold_fg_escape_includes_bold() {
        crate::color_cap::force_color_capability(crate::color_cap::ColorCapability::TrueColor);
        assert_eq!(
            bold_fg_escape(Rgb(255, 210, 120)),
            "\x1b[1m\x1b[38;2;255;210;120m"
        );
    }
}
