(in-package #:cl-user)

(defun run-base64-tests ()
  (labels ((check (ok message)
           (unless ok (error "base64: ~A" message)))
         (octets (&rest values)
           (make-array (length values) :element-type '(unsigned-byte 8)
                       :initial-contents values))
         (must-error (thunk message)
           (check (handler-case (progn (funcall thunk) nil)
                    (error () t)) message)))
    (dolist (case '(("" "") ("f" "Zg==") ("fo" "Zm8=")
                    ("foo" "Zm9v") ("foob" "Zm9vYg==")
                    ("fooba" "Zm9vYmE=") ("foobar" "Zm9vYmFy")))
      (destructuring-bind (plain encoded) case
        (check (string= (ekko/graphics:base64-encode
                         (sb-ext:string-to-octets plain :external-format :ascii)) encoded)
                "RFC 4648 encoding")
        (check (string= (sb-ext:octets-to-string
                         (ekko/graphics:base64-decode encoded)
                         :external-format :ascii) plain)
                "RFC 4648 decoding")
        (check (equalp (ekko/graphics:base64-decode
                        (sb-ext:string-to-octets encoded :external-format :ascii))
                       (sb-ext:string-to-octets plain :external-format :ascii))
                "octet API")))
    (let* ((source (octets 0 1 2 253 254 255))
           (encoded (ekko/graphics:base64-encode source))
           (wrapped (concatenate 'string "ignore:" encoded ":suffix")))
      (check (equalp (ekko/graphics:base64-decode wrapped :start 7 :end (+ 7 (length encoded))) source)
             "range API")
      (check (equalp (ekko/graphics:base64-decode (ekko/platform:text-bytes wrapped)
                                                :start 7 :end (+ 7 (length encoded))) source)
             "octet range API"))
    ;; Specialized hot loops must retain the public vector/range behavior.
    (let* ((backing (ekko/platform:text-bytes "!Zm9v?"))
           (displaced (make-array 4 :element-type '(unsigned-byte 8)
                                  :displaced-to backing :displaced-index-offset 1))
           (adjustable (make-array 10 :element-type '(unsigned-byte 8)
                                   :adjustable t :fill-pointer 4 :initial-element 0)))
      (replace adjustable displaced)
      (dolist (input (list displaced adjustable))
        (check (equalp (ekko/graphics:base64-decode input) (octets 102 111 111))
               "non-simple octets decode")
        (check (string= (ekko/graphics:base64-encode input) "Wm05dg==")
               "non-simple octets encode"))
      (check (equalp (ekko/graphics:base64-decode adjustable :start 4 :end 4) #())
             "empty non-simple range"))
    (dolist (bad '("A" "AAA" "====" "Zg=" "Zg===" "=AAA" "A=AA"
                   "Zm=8" "Zm9v=" "Zm9vYg=" "Zm9vYg==="
                   " Zg==" "Zg== "))
      (must-error (lambda () (ekko/graphics:base64-decode bad))
                  "malformed or whitespace input"))
    (dolist (bad (list (format nil "Zg~C==" #\Tab)
                       (format nil "Zg~C==" #\Newline)
                       (format nil "Zg==~C" #\Newline)))
      (must-error (lambda () (ekko/graphics:base64-decode bad))
                  "whitespace input"))
    (dolist (bad '("Zh==" "Zm9=" "Zm9vYg=\x"))
      (must-error (lambda () (ekko/graphics:base64-decode bad))
                  "non-canonical padding"))
    (must-error (lambda () (ekko/graphics:base64-decode "é===")) "non-ASCII input")
    (must-error (lambda () (ekko/graphics:base64-decode "AAAA" :start 3 :end 1)) "reversed range")
    (must-error (lambda () (ekko/graphics:base64-decode "AAAA" :end 5)) "out-of-bounds range")
    (loop for length from 0 to 257 do
      (let ((source (make-array length :element-type '(unsigned-byte 8))))
        (dotimes (i length)
          (setf (aref source i) (mod (+ (* i 73) 19) 256)))
        (check (equalp (ekko/graphics:base64-decode
                        (ekko/graphics:base64-encode source)) source)
               "varied length round trip")))
    (let ((source (make-array 256 :element-type '(unsigned-byte 8))))
      (dotimes (i 256) (setf (aref source i) i))
      (check (equalp (ekko/graphics:base64-decode
                      (ekko/graphics:base64-encode source)) source)
             "all byte values"))
    (format t "Base64 codec tests passed~%")
    t))
