(in-package #:cl-user)

(defun customization-check (ok message)
  (unless ok (error "Customization: ~A" message)))

(defun run-customization-tests ()
  ;; Mixed trees cover every cell once, apart from intentional column dividers.
  (let* ((tree (ekko/layout:split-pane (ekko/layout:split-pane 1 1 2 :columns) 2 3 :rows))
         (rects (ekko/layout:rectangles tree 81 30 1)))
    (customization-check (equal rects '((1 0 0 40 30) (2 41 0 40 15) (3 41 15 40 15))) "nested geometry")
    (customization-check (equal (ekko/layout:remove-pane tree 3) '(:columns 50 1 2)) "collapse closed branch")
    (customization-check (equal (ekko/layout:rectangles tree 2 3 3) '((3 0 0 2 3))) "small terminal focuses without losing tree")
    (customization-check (equal (ekko/layout:resize-split tree 3 10) '(:columns 50 1 (:rows 60 2 3))) "resize nearest ancestor")
    (customization-check (equal (ekko/layout:swap-panes tree 1 3) '(:columns 50 3 (:rows 50 2 1))) "swap stable IDs"))
  (let ((vt (ekko/vt:make-terminal :cols 8 :rows 3))
        (emit (lambda (&rest args) (declare (ignore args)))))
    (ekko/vt:feed vt (ekko/platform:text-bytes (format nil "one~C~%two~C~%three~C~%four" #\Return #\Return #\Return)) emit)
    (customization-check (equalp (ekko/vt:history-text vt) #("one" "two" "three" "four")) "scroll captures old row in order")
    (let ((frozen (ekko/vt:history-text vt)))
      (ekko/vt:feed vt (ekko/platform:text-bytes (format nil "~C[2Jchanged" #\Esc)) emit)
      (customization-check (equalp frozen #("one" "two" "three" "four")) "copy snapshot survives screen mutation"))
    (ekko/vt:feed vt (ekko/platform:text-bytes (format nil "~C[Hmain~C[?1049h~Calternate" #\Esc #\Esc #\Return)) emit)
    (ekko/vt:resize-terminal vt 6 4 8 16)
    (ekko/vt:feed vt (ekko/platform:text-bytes (format nil "~C[?1049l" #\Esc)) emit)
    (customization-check (string= (aref (ekko/vt:history-text vt) (ekko/vt:history-count (ekko/vt:terminal-history vt))) "main") "alternate resize preserves main screen")
    (let ((count (ekko/vt:history-count (ekko/vt:terminal-history vt))))
      (ekko/vt:feed vt (ekko/platform:text-bytes (format nil "~C[?1049h~20%~C[?1049l" #\Esc #\Esc)) emit)
      (customization-check (= count (ekko/vt:history-count (ekko/vt:terminal-history vt))) "alternate output excluded from history")))
  (let ((vt (ekko/vt:make-terminal :cols 1 :rows 1)))
    (dotimes (i 10005) (ekko/vt::remember-row vt (vector (list (write-to-string i) '(0)))))
    (customization-check (= 10000 (ekko/vt:history-count (ekko/vt:terminal-history vt))) "history row bound")
    (customization-check (string= "5" (aref (ekko/vt:history-text vt) 0)) "history evicts oldest"))
  (let ((vt (ekko/vt:make-terminal :cols 1 :rows 1))
        (row (make-array 500 :initial-element '("W" (0 38 2 255 255 255)))))
    (dotimes (i 1000) (ekko/vt::remember-row vt row))
    (customization-check (< (ekko/vt:history-count (ekko/vt:terminal-history vt)) 1000) "history byte bound evicts before row bound")
    (customization-check (<= (ekko/vt::history-bytes (ekko/vt:terminal-history vt)) (* 8 1024 1024)) "history accounted bytes"))
  (customization-check (string= "A界" (ekko/runtime::clip-copy-text "A界B" 3)) "copy clips by cells")
  (customization-check (string= "A" (ekko/runtime::clip-copy-text "A界B" 2)) "copy never cuts wide glyph")
  (let* ((panes (list (list 1 0 1 20 3 "upper" nil 0 0 nil nil nil)
                      (list 2 0 5 20 3 "lower" nil 0 0 nil nil nil)))
         (rows (ekko/runtime::scene-text-rows 20 9 2 panes '(:status "custom" :style (0 32)))))
    (customization-check (and (search "upper" (aref rows 0)) (not (search "lower" (aref rows 0)))
                              (search "lower" (aref rows 4)) (search "custom" (aref rows 8))) "horizontal split headers and status"))
  ;; Rebuilding owner contributions is the inverse: session state is deliberately
  ;; outside this registry, while every owned command/binding/option disappears.
  (let ((ekko/extensions::*components* nil))
    (ekko/builtins:install)
    (let ((before (ekko/extensions::registry)))
      (ekko/extensions:register-component :id :test :reads '(:focus))
      (ekko/extensions:register-command :component :test :name "zoom" :handler (lambda (s e) (declare (ignore s e)) nil))
      (ekko/extensions:bind-key :component :test :key "z" :command "zoom")
      (ekko/extensions:set-option :component :test :name :prefix :value "C-a")
      (ekko/extensions:set-option :component :test :name :shell :value '("sh"))
      (ekko/extensions:set-option :component :test :name :status-text :value "test")
      (ekko/extensions:set-option :component :test :name :status-style :value '(0 31))
      (ekko/extensions:unregister-component :test)
      (customization-check (equal before (ekko/extensions::registry)) "unmount restores all registrations and shadowed defaults")))
  (let* ((a (ekko/runtime::make-pane :id 1 :label "one" :vt (ekko/vt:make-terminal)))
         (b (ekko/runtime::make-pane :id 2 :label "two" :vt (ekko/vt:make-terminal)))
         (session (ekko/runtime::make-session :name "before" :panes (list a b) :tree '(:columns 50 1 2)
                    :registry (list :components
                                (loop for key in '(:session :focus :panes :layout)
                                      collect (list :id key :reads (list key) :hook t))))))
    (ekko/runtime::schedule-hooks session)
    (customization-check (= 4 (length (ekko/runtime::session-hooks session))) "all initial dependency consumers")
    (dolist (key '(:session :focus :panes :layout))
      (setf (ekko/runtime::session-hooks session) nil)
      (case key
        (:session (setf (ekko/runtime::session-name session) "after"))
        (:focus (setf (ekko/runtime::session-focus session) 1))
        (:panes (setf (ekko/runtime::pane-label a) "changed"))
        (:layout (setf (ekko/runtime::session-tree session) '(:rows 50 1 2))))
      (ekko/runtime::schedule-hooks session)
      (customization-check (equal (ekko/runtime::session-hooks session) (list key)) "exact declared consumers notified")))
  (format t "Customization, split layout and scrollback tests passed~%") t)
