(in-package #:ekko/runtime)

(defun run-desktop-tests ()
  (flet ((check (ok message) (unless ok (error "Desktop: ~A" message))))
    (let* ((a (make-pane :id 1 :vt (make-terminal)))
           (b (make-pane :id 2 :vt (make-terminal)))
           (session (make-session :panes (list a b) :tree '(:columns 50 1 2)
                                  :registry '(:components ((:id "desktop"))))))
      (layout session)
      (let ((original (session-rectangles session)))
        (apply-actions session nil '((:minimize :pane 1)) nil nil)
        (check (and (pane-minimized a) (eq b (focused-pane session))
                    (equal (mapcar #'first (session-rectangles session)) '(2))) "minimize focuses survivor")
        (apply-actions session nil '((:minimize :pane 2)) nil nil)
        (check (and (null (visible-panes session)) (not (session-stopping session))) "empty desktop stays alive")
        (scene-data session)
        (apply-actions session nil '((:restore :pane 1)) nil nil)
        (apply-actions session nil '((:restore :pane 2)) nil nil)
        (check (equal original (session-rectangles session)) "restore preserves split positions")
        (apply-actions session nil '((:zoom :pane 1)) nil nil)
        (check (and (eq a (focused-pane session)) (equal (visible-panes session) (list a))) "maximize targets unfocused pane")
        (apply-actions session nil '((:zoom :pane 1)) nil nil)
        (check (equal original (session-rectangles session)) "maximize restores layout"))
      (let ((span '(:x 0 :y 35 :text " _ " :sgr (0) :action (:minimize :pane 1))))
        (apply-actions session "desktop" (list (list :decorate :spans (list span))) t nil)
        (labels ((mouse (x up)
                   (input-mouse session (format nil "~C[<0;~D;561~C" #\Esc x (if up #\m #\M)))))
          (mouse 1 nil)
          (check (not (pane-minimized a)) "press alone cannot minimize")
          (mouse 81 t)
          (check (not (pane-minimized a)) "dragging off cancels control")
          (mouse 1 nil) (mouse 1 t)
          (check (pane-minimized a) "release activates control")
          (apply-actions session nil '((:restore :pane 1)) nil nil)
          (mouse 1 nil)
          (setf (session-decorations session) nil)
          (mouse 1 t)
          (check (not (pane-minimized a)) "removed decoration cancels pending click")))
      (let ((span (list :x (pane-x a) :y (pane-y a) :text "bad" :sgr '(0) :action '(:close :pane 1))))
        (setf (session-decorations session) (list (cons "desktop" (list span))))
        (check (null (decoration-action-at session (pane-x a) (pane-y a))) "application cells cannot be controls"))
      (check (handler-case (progn (validate-decoration-spans
                                    '((:x 0 :y 0 :text "x" :sgr (0) :action (:stop :pane 1)))) nil)
               (error () t)) "invalid chrome action rejected")))
  (format t "Desktop tests passed~%")
  t)
