(in-package #:ekko/runtime)

(defun run-desktop-tests ()
  (flet ((check (ok message) (unless ok (error "Desktop: ~A" message))))
    (let* ((a (make-pane :id 1 :vt (make-terminal)))
           (b (make-pane :id 2 :vt (make-terminal)))
           (session (make-session :panes (list a b) :tree '(:columns 50 1 2)
                                  :registry '(:components ((:id "desktop"))))))
      (layout session)
      (let ((original (session-rectangles session)))
        (apply-actions session nil '((:minimize :pane 1)) nil nil)
        (check (and (pane-minimized a) (eq b (focused-pane session))
                    (equal (mapcar #'first (session-rectangles session)) '(2))) "minimize focuses survivor")
        (apply-actions session nil '((:minimize :pane 2)) nil nil)
        (check (and (null (visible-panes session)) (not (session-stopping session))) "empty desktop stays alive")
        (scene-data session)
        (apply-actions session nil '((:restore :pane 1)) nil nil)
        (apply-actions session nil '((:restore :pane 2)) nil nil)
        (check (equal original (session-rectangles session)) "restore preserves split positions")
        (apply-actions session nil '((:zoom :pane 1)) nil nil)
        (check (and (eq a (focused-pane session)) (equal (visible-panes session) (list a))) "maximize targets unfocused pane")
        (apply-actions session nil '((:zoom :pane 1)) nil nil)
        (check (equal original (session-rectangles session)) "maximize restores layout"))
      (let ((span '(:x 0 :y 35 :text " _ " :sgr (0) :action (:minimize :pane 1))))
        (apply-actions session "desktop" (list (list :decorate :spans (list span))) t nil)
        (labels ((mouse (x up)
                   (input-mouse session (format nil "~C[<0;~D;561~C" #\Esc x (if up #\m #\M)))))
          (mouse 1 nil)
          (check (not (pane-minimized a)) "press alone cannot minimize")
          (mouse 81 t)
          (check (not (pane-minimized a)) "dragging off cancels control")
          (mouse 1 nil) (mouse 1 t)
          (check (pane-minimized a) "release activates control")
          (apply-actions session nil '((:restore :pane 1)) nil nil)
          (mouse 1 nil)
          (setf (session-decorations session) nil)
          (mouse 1 t)
          (check (not (pane-minimized a)) "removed decoration cancels pending click")))
      (let ((span (list :x (pane-x a) :y (pane-y a) :text "bad" :sgr '(0) :action '(:close :pane 1))))
        (setf (session-decorations session) (list (cons "desktop" (list span))))
        (check (null (decoration-action-at session (pane-x a) (pane-y a))) "application cells cannot be controls"))
      (check (handler-case (progn (validate-decoration-spans
                                    '((:x 0 :y 0 :text "x" :sgr (0) :action (:stop :pane 1)))) nil)
               (error () t)) "invalid chrome action rejected")))
  (run-window-resize-tests)
  (format t "Desktop tests passed~%")
  t)

(defun run-window-resize-tests ()
  (flet ((check (ok message) (unless ok (error "Resize: ~A" message))))
    (let* ((panes (loop for id from 1 to 4 collect (make-pane :id id :vt (make-terminal))))
           (session (make-session :panes panes :cols 120 :rows 40
                                 :tree '(:columns 50 (:rows 50 1 2) (:columns 50 3 4))
                                 :registry '(:components ((:id "desktop"))
                                             :options (:pane-insets (1 1 1 1))))))
      (layout session)
      (labels ((begin (id edge)
                 (begin-window-drag session "desktop" (list :pane id :drag edge) 20 10))
               (drag (dx dy &optional up)
                 (window-drag-mouse session (if up 0 32) (+ 20 dx) (+ 10 dy) up)))
        (let* ((x (1- (pane-outer-cols (first panes))))
               (span (list :pane 1 :x x :y 2 :text "│" :sgr '(0) :drag :right)))
          (setf (session-decorations session) (list (cons "desktop" (list span))))
          (update-window-hover session 35 x 2 nil)
          (check (window-hover-overlays session) "resizable border highlights on hover")
          (let ((revision (session-revision session)))
            (update-window-hover session 35 x 2 nil)
            (check (= revision (session-revision session)) "unchanged hover does not redraw"))
          (update-window-hover session 35 2 2 nil)
          (check (null (session-window-hover session)) "leaving border clears hover")
          (update-window-hover session 35 x 2 nil)
          (setf (session-decorations session) nil)
          (check (null (window-hover-overlays session)) "removed decoration leaves no highlight")
          (layout session)
          (check (null (session-window-hover session)) "layout clears stored hover"))
        (let ((before (copy-tree (session-tree session)))
              (rects (session-rectangles session)))
          (begin 1 :right)
          (check (eq (first (window-drag-split (session-window-drag session))) (session-tree session))
                 "nested pane edge selects ancestor split")
          (drag 12 0)
          (check (and (equal before (session-tree session)) (equal rects (session-rectangles session)))
                 "preview leaves application layout untouched")
          (check (window-drag-overlays session) "preview renders affected outlines")
          (drag 12 0 t)
          (check (> (second (session-tree session)) 50) "shared vertical border moves")
          (check (and (equal (third before) (third (session-tree session)))
                      (equal (fourth before) (fourth (session-tree session)))) "nested ratios preserved")
          (check (notany #'pane-floating panes) "resize never floats tiled panes"))
        (let ((before (copy-tree (session-tree session))))
          (begin 2 :top) (drag 0 4 t)
          (check (> (second (third (session-tree session))) 50) "lower pane top resizes row split")
          (check (= (second before) (second (session-tree session))) "row drag preserves ancestor ratio"))
        (let ((before (copy-tree (session-tree session))))
          (begin 3 :left) (drag -8 0)
          (input-key session (octets-from-list '(27)))
          (check (and (null (session-window-drag session)) (equal before (session-tree session)))
                 "Escape cancels resize")
          (setf (session-chrome-press session) nil)
          (begin 1 :left)
          (check (null (session-window-drag session)) "outside edge has no resize gesture")
          (begin 1 :right) (drag 0 5 t)
          (check (equal before (session-tree session)) "perpendicular motion leaves ratio unchanged"))
        (apply-actions session nil '((:minimize :pane 2)) nil nil)
        (let ((hidden (copy-tree (third (session-tree session)))))
          (begin 1 :right) (drag -10 0 t)
          (check (equal hidden (third (session-tree session))) "hidden sibling keeps its stored split"))
        (begin 1 :right) (drag -1000 0 t)
        (check (every (lambda (p) (or (pane-minimized p)
                                    (and (>= (pane-outer-cols p) 3) (>= (pane-outer-rows p) 3)))) panes)
               "minimum sizes hold at extreme drag")
        (apply-actions session nil '((:zoom :pane 1)) nil nil)
        (begin 1 :right)
        (check (null (session-window-drag session)) "maximized pane cannot resize hidden tiles")
        (apply-actions session nil '((:zoom :pane 1)) nil nil)
        (apply-actions session nil '((:float :pane 1 :rect (10 8 30 15))) nil nil)
        (begin 1 :top-left) (drag 4 3 t)
        (check (equal (pane-floating (first panes)) '(14 11 26 12)) "top-left resize anchors opposite corner")
        (begin 1 :top-right) (drag 4 2 t)
        (check (equal (pane-floating (first panes)) '(14 13 30 10)) "top-right resize anchors opposite corner")
        (begin 1 :top-left) (drag -1000 -1000 t)
        (check (equal (pane-floating (first panes)) '(0 0 44 23)) "viewport clamp keeps opposite corner fixed")
        (begin 1 :right) (drag 3 0)
        (layout session)
        (check (null (session-window-drag session)) "layout changes cancel stale gesture")))))
