(in-package #:cl-user)

(defun check (condition message)
  (unless condition (error "Geometry test failed: ~A" message)))

(defun covers-point-p (rect x y)
  (and (<= (ekko/scene:rect-x rect) x)
       (< x (ekko/scene:rect-right rect))
       (<= (ekko/scene:rect-y rect) y)
       (< y (ekko/scene:rect-bottom rect))))

(defun check-geometry-properties ()
  ;; Independent point-membership oracle; no use of intersection/subtraction.
  (let ((seed 7062026))
    (labels ((next (n)
               (setf seed (mod (+ (* seed 1664525) 1013904223) (expt 2 32)))
               (mod seed n))
             (rectangle ()
               (ekko/scene:make-rect (- (next 12) 3) (- (next 12) 3)
                                    (1+ (next 10)) (1+ (next 10)))))
      (dotimes (case-number 100)
        (let* ((destination (rectangle)) (pane (rectangle))
               (client (rectangle)) (visible (rectangle))
               (overlays (list (rectangle) (rectangle)))
               (source (ekko/scene:make-rect 2 3 7 11))
               (fragments (ekko/scene:clip-placement
                           destination source pane client visible overlays)))
          (loop for y from -3 to 18 do
            (loop for x from -3 to 18 do
              (let* ((px (+ x 1/2)) (py (+ y 1/2))
                     (expected (and (every (lambda (r) (covers-point-p r px py))
                                           (list destination pane client visible))
                                    (notany (lambda (r) (covers-point-p r px py)) overlays)))
                     (count (count-if
                             (lambda (f) (covers-point-p
                                          (ekko/scene:mapped-fragment-destination f) px py))
                             fragments)))
                (check (= count (if expected 1 0))
                       (format nil "G06 seed 7062026 case ~D point ~D/~D" case-number x y)))))
          (dolist (f fragments)
            (let ((d (ekko/scene:mapped-fragment-destination f))
                  (s (ekko/scene:mapped-fragment-source f)))
              (check (= (* (- (ekko/scene:rect-x s) 2) (ekko/scene:rect-width destination))
                        (* (- (ekko/scene:rect-x d) (ekko/scene:rect-x destination)) 7))
                     "source x transform")
              (check (= (* (- (ekko/scene:rect-y s) 3) (ekko/scene:rect-height destination))
                        (* (- (ekko/scene:rect-y d) (ekko/scene:rect-y destination)) 11))
                     "source y transform")
              (check (= (* (ekko/scene:rect-width s) (ekko/scene:rect-width destination))
                        (* (ekko/scene:rect-width d) 7))
                     "source width preserves scale")
              (check (= (* (ekko/scene:rect-height s) (ekko/scene:rect-height destination))
                        (* (ekko/scene:rect-height d) 11))
                     "source height preserves scale"))))))))

(defun run-geometry-tests ()
  (check-geometry-properties)
  (let* ((source (ekko/scene:make-rect 1/3 2/5 100 80))
         (dest (ekko/scene:make-rect -10 5 50 40))
         (bounds (ekko/scene:make-rect 0 0 40 40))
         (fragments (ekko/scene:clip-placement dest source bounds bounds bounds)))
    (check (= (length fragments) 1) "negative offset clipped")
    (let ((d (ekko/scene:mapped-fragment-destination (first fragments)))
          (s (ekko/scene:mapped-fragment-source (first fragments))))
      (check (and (= (ekko/scene:rect-x d) 0) (= (ekko/scene:rect-y d) 5)
                   (= (ekko/scene:rect-width d) 40)) "destination edge")
      (check (and (= (ekko/scene:rect-x s) 61/3) (= (ekko/scene:rect-width s) 80))
             "exact source mapping")))
  (let* ((all (ekko/scene:make-rect 0 0 10 10))
         (source (ekko/scene:make-rect 0 0 3 3))
         (overlay (ekko/scene:make-rect 3 2 4 5))
         (pieces (ekko/scene:clip-placement all source all all all (list overlay))))
    (check (= (length pieces) 4) "overlay splits into disjoint pieces")
    (check (= (reduce #'+ pieces :key (lambda (p) (ekko/scene:rect-area (ekko/scene:mapped-fragment-destination p)))) 80)
           "area after overlay"))
  (let* ((all (ekko/scene:make-rect 0 0 10 10))
         (source (ekko/scene:make-rect 0 0 10 10))
         (pieces (ekko/scene:clip-placement all source all all all (list all))))
    (check (null pieces) "fully occluded")
    (dolist (edge (list (ekko/scene:make-rect -5 0 15 10)
                        (ekko/scene:make-rect 0 -5 10 15)
                        (ekko/scene:make-rect 5 0 15 10)
                        (ekko/scene:make-rect 0 5 10 15)))
      (let* ((pieces (ekko/scene:clip-placement all source edge edge edge))
             (area (reduce #'+ pieces :initial-value 0
                           :key (lambda (p) (ekko/scene:rect-area
                                            (ekko/scene:mapped-fragment-destination p))))))
        (check (= area (if (or (plusp (ekko/scene:rect-x edge))
                               (plusp (ekko/scene:rect-y edge))) 50 100))
               "all clipping edges"))))
  (check (null (ekko/scene:rect-intersection (ekko/scene:make-rect 0 0 1 1)
                                             (ekko/scene:make-rect 1 1 2 2)))
         "half open empty edge")
  (let ((rejected nil))
    (handler-case (ekko/scene:make-rect 0 0 0 1)
      (error () (setf rejected t)))
    (check rejected "zero width rejected"))
  (let ((rejected nil))
    (handler-case
        (ekko/scene:clip-placement (ekko/scene:make-rect 0 0 10 10)
                                   (ekko/scene:make-rect 0 0 10 10)
                                   (ekko/scene:make-rect 0 0 10 10)
                                   (ekko/scene:make-rect 0 0 10 10)
                                   (ekko/scene:make-rect 0 0 10 10)
                                   (list (ekko/scene:make-rect 1 1 1 1))
                                   :max-fragments 1)
      (error () (setf rejected t)))
    (check rejected "fragment limit rejected"))
  (format t "G06 geometry tests passed~%") t)
