(defpackage #:ekko/graphics-demo-tests (:use #:cl))
(in-package #:ekko/graphics-demo-tests)
(defun check (value message) (unless value (error "Graphics demo test failed: ~A" message)))
(defun octets-string (vector)
  (map 'string #'code-char vector))
(defun drain (client &key (chunk most-positive-fixnum))
  (let ((result (make-array 0 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0)))
    (loop until
      (eq :drained
          (ekko/client:flush-transactions client
            (lambda (vector start count)
              (let ((amount (min chunk count)))
                (loop for i below amount do (vector-push-extend (aref vector (+ start i)) result))
                amount))
            :max-bytes most-positive-fixnum)))
    result))
(defun run-graphics-demo-tests ()
  (let ((a (ekko/client:make-attachment :max-bytes 4096 :max-transactions 4))
        (b (ekko/client:make-attachment :max-bytes 4096 :max-transactions 4)))
    (unwind-protect
         (let ((first (progn (ekko/graphics-demo:make-demo-transactions a) (drain a)))
               (second (progn (ekko/graphics-demo:replay b) (drain b))))
           (check (= (length first) (length second)) "complete stream lengths")
           (check (equalp first second) "complete replay stream"))
      (ekko/client:attachment-teardown a) (ekko/client:attachment-teardown b)))
  (let ((client (ekko/client:make-attachment :max-bytes 4096 :max-transactions 4)))
    (unwind-protect
         (let* ((transactions (ekko/graphics-demo:make-checkerboard-transactions client))
                (stream (drain client :chunk 3))
                (text (mapcar #'octets-string transactions)))
           (check (= 4 (length transactions)) "checkerboard has two cropped fragments per pane")
           (check (> (length stream) 192) "checkerboard exercises more than 64 short writes")
           (check (zerop (ekko/client:queued-transactions client)) "checkerboard fully drains")
           (dolist (wire text)
             (check (search "s=1,v=2" wire) "cropped source dimensions")
             (check (search ",c=1,r=1;" wire) "cell-sized cropped placement"))
           (check (and (search "[1;1H" (first text))
                       (search "[1;3H" (second text))
                       (search "[1;5H" (third text))
                       (search "[1;7H" (fourth text)))
                 "fragments stay in their pane-local positions")
           (check (equal '(255 220 40) (ekko/graphics-demo:checkerboard-pixel 0 0))
                 "checkerboard first pixel")
           (check (equal '(35 90 220) (ekko/graphics-demo:checkerboard-pixel 1 0))
                 "checkerboard alternating pixel"))
      (ekko/client:attachment-teardown client)))
  (dolist (fixture '(:checkerboard :native-checkerboard))
    (let ((a (ekko/client:make-attachment :max-bytes 4096 :max-transactions 8))
          (b (ekko/client:make-attachment :max-bytes 4096 :max-transactions 8)))
      (unwind-protect
           (let* ((transactions (ekko/graphics-demo:replay a :fixture fixture))
                  (short (drain a :chunk 3))
                  (full (progn (ekko/graphics-demo:replay b :fixture fixture) (drain b))))
             (check (equalp short full) "short writes converge to complete reconstruction")
             (check (= (length short) (reduce #'+ transactions :key #'length)) "no transaction truncation")
             (check (zerop (ekko/client:queued-bytes a)) "drained bytes released")
             (when (eq fixture :native-checkerboard)
               (check (= 8 (length transactions)) "four native fragments per pane")
               (let ((text (mapcar #'octets-string transactions)))
                 (check (every (lambda (wire) (not (search ",c=" wire))) text) "native dimensions without cell scaling")
                 (check (some (lambda (wire) (search ",X=0,Y=3;" wire)) text) "sub-cell vertical origin")
                 (check (some (lambda (wire) (search ",X=7,Y=3;" wire)) text) "sub-cell horizontal and vertical origin")
                 (check (some (lambda (wire) (search "s=9,v=9" wire)) text) "exact non-cell fragment extent"))))
        (ekko/client:attachment-teardown a)
        (ekko/client:attachment-teardown b))))
  (format t "M01 synthetic graphics demo tests passed~%") t)
