(defpackage #:ekko/client-tests (:use #:cl #:ekko/client))
(in-package #:ekko/client-tests)

(defun check (ok message)
  (unless ok (error "presentation: ~A" message)))

(defun must-error (thunk message)
  ;; The assertion cannot catch its own failure.
  (check (handler-case (progn (funcall thunk) nil) (error () t)) message))

(defun octets (&rest bytes)
  (make-array (length bytes) :element-type '(unsigned-byte 8) :initial-contents bytes))

(defun constant-writer (result)
  (lambda (&rest arguments) (declare (ignore arguments)) result))

(defun run-reply-tests ()
  (let* ((a (make-attachment :max-mappings 4))
         (red (allocate-outer-id a 1 1 7 0))
         (blue (allocate-outer-id a 2 1 7 0))
         (replacement (allocate-outer-id a 1 2 7 0))
         (missing (allocate-outer-id a 2 1 8 0)))
    (expect-outer-reply a red :upload 1 100)
    (expect-outer-reply a blue :upload 1 100)
    (expect-outer-reply a replacement :placement 2 100)
    (expect-outer-reply a missing :query 0 50)
    (check (eq :unknown (accept-outer-reply a 99 1 1 t)) "unknown response")
    (check (eq :mismatch (accept-outer-reply a red 2 1 t)) "wrong response shape")
    (multiple-value-bind (health kind) (accept-outer-reply a blue 1 2 nil)
      (check (and (eq :failed health) (eq :upload kind)) "reordered host failure"))
    (check (eq :accepted (accept-outer-reply a replacement 2 3 t)) "new incarnation response")
    (check (eq :accepted (accept-outer-reply a red 1 4 t)) "delayed old incarnation response")
    (check (eq :stale (accept-outer-reply a blue 1 5 t)) "duplicate cannot replace failure")
    (must-error (lambda () (expect-outer-reply a blue :upload 1 200)) "tombstone cannot be reused")
    (check (= 1 (expire-outer-replies a 50)) "missing reply expires at deadline")
    (check (zerop (expire-outer-replies a 51)) "expiration counted once")
    (check (eq :stale (accept-outer-reply a missing 0 51 t)) "late response discarded")
    (must-error (lambda () (expect-outer-reply a 5 :query 0 100)) "unallocated ID rejected")
    (attachment-teardown a)
    (check (zerop (hash-table-count (ekko/client::attachment-replies a))) "reply ownership teardown")
    (must-error (lambda () (accept-outer-reply a red 1 6 t)) "closed transport rejects response")
    (let* ((fresh (make-attachment)) (id (allocate-outer-id fresh 1 1 7 0)))
      (expect-outer-reply fresh id :query 0 10)
      (check (eq :stale (accept-outer-reply fresh id 0 10 t)) "receive enforces deadline")
      (attachment-teardown fresh))))

(defun run-presentation-tests ()
  (run-reply-tests)
  (let ((a (make-attachment :max-bytes 6 :max-transactions 2)))
    (check (= 1 (allocate-outer-id a 1 1 7 0 1)) "first outer ID")
    (check (= 1 (allocate-outer-id a 1 1 7 0 1)) "stable identity")
    (check (= 2 (allocate-outer-id a 2 1 7 0 1)) "G01 colliding child identities")
    (check (= 3 (allocate-outer-id a 1 2 7 0 1)) "new pane incarnation")
    (check (= 4 (allocate-outer-id a 1 1 7 1 1)) "new content generation")
    (check (= 5 (allocate-outer-id a 1 1 4294967295 0)) "maximum child ID")
    (must-error (lambda () (allocate-outer-id a 1 1 -1 0)) "negative child ID")
    (let ((one (octets 1 2 3)) (seen nil))
      (enqueue-transaction a one)
      (enqueue-transaction a (octets 4 5))
      (setf (aref one 0) 99)
      (check (eq :would-block (flush-transactions a (constant-writer :eagain))) "EAGAIN")
      (check (eq :would-block (flush-transactions a (constant-writer 0))) "zero progress")
      (check (= 5 (queued-bytes a)) "blocked accounting")
      (flet ((writer (v offset count)
               (check (plusp count) "no empty write")
               (push (aref v offset) seen)
               1))
        (check (eq :would-block (flush-transactions a #'writer :max-calls 1)) "call budget")
        (check (= 5 (queued-bytes a)) "partial vector remains allocated")
        (must-error (lambda () (enqueue-transaction a (octets 6 7))) "byte cap before copy")
        (check (eq :would-block (flush-transactions a #'writer :max-bytes 2)) "byte budget")
        (check (= 2 (queued-bytes a)) "retire first allocation")
        (check (= 1 (queued-transactions a)) "retire first transaction")
        (dolist (bad '(-1 3 nil :invalid))
          (must-error (lambda () (flush-transactions a (constant-writer bad))) "invalid writer result")
          (check (= 2 (queued-bytes a)) "invalid result preserves queue"))
        (check (eq :drained (flush-transactions a #'writer)) "drain")
        (check (equal (reverse seen) '(1 2 3 4 5)) "G04 serialization and copy isolation")))
    (check (zerop (queued-bytes a)) "drained memory")
    (check (zerop (queued-transactions a)) "drained count")
    (must-error (lambda () (enqueue-transaction a (octets))) "empty rejected")
    (must-error (lambda () (enqueue-transaction a #(1 2))) "non-octet vector rejected")
    (enqueue-transaction a (octets 6))
    (attachment-teardown a)
    (attachment-teardown a)
    (check (and (zerop (queued-bytes a)) (zerop (queued-transactions a))) "I10 teardown")
    (must-error (lambda () (enqueue-transaction a (octets 1))) "closed enqueue")
    (must-error (lambda () (allocate-outer-id a 1 1 7 0)) "closed allocate")
    (must-error (lambda () (flush-transactions a (constant-writer 1))) "closed flush"))
  (let ((a (make-attachment :max-transactions 1 :max-id 2)))
    (check (= 1 (allocate-outer-id a 1 1 0 0)) "zero logical ID")
    (check (= 2 (allocate-outer-id a 2 1 0 0)) "last available ID")
    (must-error (lambda () (allocate-outer-id a 3 1 0 0)) "G17 exhaustion")
    (check (= 2 (allocate-outer-id a 2 1 0 0)) "exhaustion preserves lookup")
    (enqueue-transaction a (octets 1))
    (must-error (lambda () (enqueue-transaction a (octets 2))) "transaction cap")
    (check (= 1 (queued-bytes a)) "rejection preserves accounting"))
  (let ((a (make-attachment :max-mappings 1)))
    (allocate-outer-id a 1 1 7 0)
    (must-error (lambda () (allocate-outer-id a 2 1 7 0)) "mapping quota"))
  (format t "G01/G04/G05/G17 presentation contract tests passed~%")
  t)
