(in-package #:cl-user)

(defun render-check (condition message)
  (unless condition (error "Render test failed: ~A" message)))

(defun render-output (viewer scene)
  (setf (ekko/runtime::viewer-io viewer) (ekko/runtime::make-wire :fd -1)
        (ekko/runtime::viewer-scene viewer) scene)
  (ekko/runtime::render-scene viewer)
  (ekko/platform:bytes-text
   (apply #'concatenate '(vector (unsigned-byte 8))
          (ekko/runtime::wire-queue (ekko/runtime::viewer-io viewer)))))

(defun run-render-tests ()
  (let* ((viewer (ekko/runtime::make-viewer))
         (placement (list 7 1 0 0 0 0))
         (pane (list 1 0 1 20 4 "fixture" nil 0 0 nil
                     (list (list (list 0 "LONG TEXT" '(0 31)))) (list placement)))
         (scene (list ekko/runtime::+wire-version+ 20 6 8 16 1 (list pane))))
    (setf (gethash '(1 7) (ekko/runtime::viewer-assets viewer))
          (list 1 64 32 32 (ekko/platform:octets 1)))
    (let ((text (render-output viewer scene)))
      (render-check (search "LONG TEXT" text) "initial text")
      (render-check (search "a=T" text) "initial upload"))
    (let ((text (render-output viewer scene)))
      (render-check (not (search "LONG TEXT" text)) "unchanged text suppressed")
      (render-check (not (search "_G" text)) "unchanged image suppressed"))
    ;; A new image generation must not redraw unchanged text.
    (setf (gethash '(1 7) (ekko/runtime::viewer-assets viewer))
          (list 2 64 32 32 (ekko/platform:octets 1))
          (second placement) 2)
    (let ((text (render-output viewer scene)))
      (render-check (search "a=T" text) "new generation upload")
      (render-check (not (search "LONG TEXT" text)) "graphics-only update skips text"))
    ;; Moving partly offscreen changes source clipping, but keeps the pixels.
    (setf (third placement) -8)
    (let ((text (render-output viewer scene)))
      (render-check (search "a=p" text) "placement update")
      (render-check (search "C=1" text) "placement preserves cursor")
      (render-check (search "x=8,y=0,w=56,h=32" text) "source clipping")
      (render-check (not (search "a=T" text)) "placement has no upload"))
    ;; Identical pixel crop still needs a new placement after cell size changes.
    (setf (fourth scene) 10)
    (render-check (search "a=p" (render-output viewer scene)) "cell-size placement invalidation")
    (setf (nth 10 pane) (list (list (list 0 "X" '(0 31)))))
    (let ((text (render-output viewer scene)))
      (render-check (search "X" text) "changed row emitted")
      (render-check (search (format nil "~C[0m~C[2;1H~A" #\Esc #\Esc
                                    (make-string 20 :initial-element #\Space)) text)
                    "shorter row clears old text with default rendition")
      (render-check (not (search "fixture" text)) "unchanged header skipped"))
    (setf (second scene) 21)
    (render-check (search "fixture" (render-output viewer scene)) "viewport change invalidates rows")
    (setf (nth 11 pane) nil)
    (render-check (search "a=d,d=I" (render-output viewer scene)) "removed image deleted"))
  (format t "render cache tests passed~%")
  t)
