(in-package #:cl-user)

(defun render-check (condition message)
  (unless condition (error "Render test failed: ~A" message)))

(defun render-output (viewer scene)
  (setf (ekko/runtime::viewer-io viewer) (ekko/runtime::make-wire :fd -1)
        (ekko/runtime::viewer-scene viewer) scene)
  (ekko/runtime::render-scene viewer)
  (ekko/platform:bytes-text
   (apply #'concatenate '(vector (unsigned-byte 8))
          (ekko/runtime::wire-queue (ekko/runtime::viewer-io viewer)))))

(defun run-render-tests ()
  (let ((viewer (ekko/runtime::make-viewer :exit-text "previous")))
    (dolist (text (list (string (code-char 27)) (string (code-char 133))
                       (make-string 513 :initial-element #\a) 42))
      (let ((packet (concatenate '(vector (unsigned-byte 8)) #(12)
                     (ekko/runtime::encode-scene
                      (list ekko/runtime::+wire-version+ 20 6 8 16 1 nil
                            (list :exit-text text))))))
        (render-check
         (handler-case (progn (ekko/runtime::receive-view viewer packet) nil)
           (error () t)) "malformed exit text rejected by viewer")
        (render-check (and (string= (ekko/runtime::viewer-exit-text viewer) "previous")
                           (null (ekko/runtime::viewer-awaiting-scene viewer)))
                      "invalid exit text does not alter retained lifecycle state"))))
  (let* ((viewer (ekko/runtime::make-viewer))
         (placement (list 7 1 0 0 0 0))
         (pane (list 1 0 1 20 4 "fixture" nil 0 0 nil
                     (list (list (list 0 "LONG TEXT" '(0 31)))) (list placement)
                     '(0 0 20 5)))
         (scene (list ekko/runtime::+wire-version+ 20 6 8 16 1 (list pane)
                      (list :decorations '((0 0 "fixture" (0 31)))))))
    (let ((framed-pane (list 9 2 2 16 4 "framed" nil 0 0 nil nil nil '(0 0 20 8)))
          (framed-placement (list 8 1 -12 0 0 0))
          (asset (list 1 64 32 32 (ekko/platform:octets 1))))
      (render-check
       (equal (ekko/runtime::clipped-image framed-pane framed-placement asset 8 16)
              '(16 32 12 0 52 32))
       "image clipping stays inside shifted content rectangle"))
    (setf (gethash '(1 7) (ekko/runtime::viewer-assets viewer))
          (list 1 64 32 32 (ekko/platform:octets 1)))
    (let ((text (render-output viewer scene)))
      (render-check (search "LONG TEXT" text) "initial text")
      (render-check (search "fixture" text) "initial published decoration")
      (render-check (search "a=T" text) "initial upload"))
    (let ((text (render-output viewer scene)))
      (render-check (not (search "LONG TEXT" text)) "unchanged text suppressed")
      (render-check (not (search "_G" text)) "unchanged image suppressed"))
    ;; Opaque overlay splits an existing placement and covers live text.
    (setf (getf (nth 7 scene) :overlays) '((2 1 "MENU" (0 30 46))))
    (let ((text (render-output viewer scene)))
      (render-check (search "MENU" text) "overlay composed after live text")
      (render-check (= 3 (hash-table-count (ekko/runtime::viewer-drawn viewer)))
                    "image fragments exclude overlay cells"))
    (let ((text (render-output viewer scene)))
      (render-check (not (search "_G" text)) "stable overlay does not retransmit images"))
    (setf (getf (nth 7 scene) :overlays) nil)
    (let ((text (render-output viewer scene)))
      (render-check (search "LONG TEXT" text) "dismiss restores covered terminal row")
      (render-check (= 1 (hash-table-count (ekko/runtime::viewer-drawn viewer)))
                    "dismiss removes obsolete fragments")
      (render-check (equal (third (gethash '(1 7 0) (ekko/runtime::viewer-drawn viewer)))
                           '(0 16 0 0 64 32)) "dismiss restores whole image"))
    ;; A new image generation must not redraw unchanged text.
    (setf (gethash '(1 7) (ekko/runtime::viewer-assets viewer))
          (list 2 64 32 32 (ekko/platform:octets 1))
          (second placement) 2)
    (let ((text (render-output viewer scene)))
      (render-check (search "a=T" text) "new generation upload")
      (render-check (not (search "LONG TEXT" text)) "graphics-only update skips text"))
    ;; Moving partly offscreen changes source clipping, but keeps the pixels.
    (setf (third placement) -8)
    (let ((text (render-output viewer scene)))
      (render-check (search "a=p" text) "placement update")
      (render-check (search "C=1" text) "placement preserves cursor")
      (render-check (search "x=8,y=0,w=56,h=32" text) "source clipping")
      (render-check (not (search "a=T" text)) "placement has no upload"))
    ;; Identical pixel crop still needs a new placement after cell size changes.
    (setf (fourth scene) 10)
    (render-check (search "a=p" (render-output viewer scene)) "cell-size placement invalidation")
    (setf (nth 10 pane) (list (list (list 0 "X" '(0 31)))))
    (let ((text (render-output viewer scene)))
      (render-check (search "X" text) "changed row emitted")
      (render-check (search (format nil "~C[0m~C[2;1H~A" #\Esc #\Esc
                                    (make-string 20 :initial-element #\Space)) text)
                    "shorter row clears old text with default rendition")
      (render-check (not (search "fixture" text)) "unchanged decoration skipped"))
    (setf (second scene) 21)
    (render-check (search "fixture" (render-output viewer scene)) "viewport change invalidates rows")
    (setf (nth 11 pane) nil)
    (render-check (search "a=d,d=I" (render-output viewer scene)) "removed image deleted"))
  (let ((pieces (ekko/runtime::overlay-image-crops '(0 0 0 0 80 64) nil 8 16 '((2 1 4 2)))))
    (render-check (= (loop for piece in pieces sum (* (fifth piece) (sixth piece)))
                     (- (* 80 64) (* 32 32))) "floating window excludes exactly its pixel area")
    (render-check (every (lambda (p) (and (= (first p) (third p)) (= (second p) (fourth p)))) pieces)
                  "occlusion preserves image source offsets"))
  (format t "render cache tests passed~%")
  t)
