(in-package #:cl-user)

(defun ekko-test (name condition)
  (unless condition (error "~A failed" name)))

(defun call-ekko (arguments)
  (let ((out (make-string-output-stream)) (err (make-string-output-stream)))
    (values (let ((*standard-output* out) (*error-output* err)) (ekko:main arguments))
            (get-output-stream-string out) (get-output-stream-string err))))

(defun run-ekko-tests ()
  (ekko-test "truecolor zero channel is not a reset"
             (equal (ekko/vt::update-rendition '(0 1 38 2 90 80 70) '(48 2 0 24 30 24))
                    '(0 1 38 2 90 80 70 48 2 0 24 30)))
  (ekko-test "SGR reset restores defaults"
             (equal (ekko/vt::update-rendition '(0 1 38 2 0 24 30) '(39 22)) '(0)))
  (ekko/graphics-demo-tests::run-graphics-demo-tests)
  (run-geometry-tests)
  (ekko/client-tests::run-presentation-tests)
  (ekko/runtime-tests::run-input-tests)
  (run-render-tests)
  (run-base64-tests)
  (run-graphics-parser-tests)
  (run-asset-tests)
  (ekko-test "version" (string= (ekko:version) "0.1.0"))
  (multiple-value-bind (status out err) (call-ekko nil)
    (ekko-test "no args" (and (null status) (search "Usage: ekko" out) (zerop (length err)))))
  (dolist (alias '("-h" "--help"))
    (multiple-value-bind (status out err) (call-ekko (list alias))
      (ekko-test "help" (and (null status) (search "--version" out) (zerop (length err))))))
  (multiple-value-bind (status out err) (call-ekko '("--version"))
    (ekko-test "version" (and (null status) (string= out (format nil "0.1.0~%")) (zerop (length err)))))
  (dolist (args '(("--bogus") ("--eval") ("--version" "extra") ("--help" "extra")))
    (multiple-value-bind (status out err) (call-ekko args)
      (ekko-test "invalid" (and (= status 2) (zerop (length out)) (plusp (length err))))))
  (format t "M00 tests passed~%")
  t)
