(in-package #:ekko/runtime)

(defun run-selection-tests ()
  (flet ((check (ok message) (unless ok (error "Selection: ~A" message))))
    (let* ((vt (make-terminal :cols 20 :rows 4))
           (pane (make-pane :id 1 :outer-cols 20 :outer-rows 4 :vt vt :io (make-wire :fd -1) :label "test"))
           (writer (make-wire :fd -1))
           (session (make-session :panes (list pane) :tree 1 :writer writer)))
      (feed vt (text-bytes (format nil "alpha beta~C~Csecond line" #\Return #\Newline))
            (lambda (&rest args) (declare (ignore args))))
      (labels ((mouse (button col row &optional release)
                 (input-mouse session (format nil "~C[<~D;~D;~D~C" #\Esc button
                                             (+ 1 (* col 8)) (+ 1 (* row 16))
                                             (if release #\m #\M)))))
        (mouse 0 1 0)
        (mouse 32 4 0)
        (check (equal (second (first (copy-display-lines pane))) '(1 "lpha" (0 48 5 238)))
               "partial row visibly highlighted")
        (mouse 0 4 0 t)
        (check (string= (session-clipboard session) "lpha") "forward drag")
        (check (null (wire-queue (pane-io pane))) "shell receives no selection escape bytes")
        (check (= 23 (aref (first (wire-queue writer)) 4)) "clipboard event queued")
        (let ((viewer (make-viewer :io (make-wire :fd -1))))
          (receive-view viewer (subseq (first (wire-queue writer)) 4))
          (check (string= (bytes-text (first (wire-queue (viewer-io viewer))))
                          (format nil "~C]52;c;bHBoYQ==~C\\" #\Esc #\Esc)) "OSC52 encoding"))
        (mouse 0 2 1)
        (mouse 32 6 0)
        (mouse 0 6 0 t)
        (check (string= (session-clipboard session) (format nil "beta~%sec")) "reverse multiline drag")
        (input-key session (text-bytes "X"))
        (check (null (pane-copy-lines pane)) "typing restores live output")
        (check (equalp (first (wire-queue (pane-io pane))) (text-bytes "X")) "typing reaches application")
        (setf (gethash 1000 (terminal-modes vt)) t (gethash 1006 (terminal-modes vt)) t)
        (mouse 0 1 0)
        (mouse 0 1 0 t)
        (check (null (pane-copy-lines pane)) "application tracking bypasses selection")
        (check (= 3 (length (wire-queue (pane-io pane)))) "application press and release forwarded")
        (clrhash (terminal-modes vt))
        (let ((other (make-pane :id 2 :x 21 :outer-x 21 :outer-cols 20 :outer-rows 4 :vt (make-terminal :cols 20 :rows 4))))
          (setf (session-panes session) (list pane other))
          (mouse 0 1 0)
          (mouse 32 24 0)
          (mouse 0 24 0 t)
          (check (string= (session-clipboard session) "lpha beta") "drag clips to original pane")
          (check (null (pane-copy-lines other)) "cross-pane drag leaves neighbor unchanged")
          (setf (session-panes session) (list pane))))
      (enter-copy pane (vector "a界éZ" "next"))
      (point-copy pane 2 0 t) (point-copy pane 3 0 nil)
      (check (string= (selected-copy-text pane) "界é") "whole wide glyph and combining mark")
      (point-copy pane 19 1 t)
      (check (string= (selected-copy-text pane) "") "trailing blanks are not fabricated")
      (leave-copy pane)
      (setf (wire-version writer) 11 (wire-queue writer) nil (wire-queue-tail writer) nil (wire-queued writer) 0)
      (publish-copy session "legacy")
      (check (and (null (wire-queue writer)) (string= (session-clipboard session) "legacy")) "legacy buffer without new packets")
      (enter-copy pane (coerce (loop for i below 20 collect (format nil "row~D" i)) 'vector))
      (setf (pane-copy-pointer pane) t)
      (scroll-copy pane -3)
      (check (= 13 (pane-copy-top pane)) "wheel moves viewport three rows")
      (scroll-copy pane 3)
      (check (null (pane-copy-lines pane)) "wheel bottom returns live")
      (check (handler-case (progn (apply-actions session :test '((:copy-point :x -1 :y 0)) nil nil) nil)
               (error () t)) "public coordinates validated")
      (check (null (pane-copy-lines pane)) "invalid action leaves state unchanged")))
  (let* ((vt (make-terminal :cols 12 :rows 2)) (pane (make-pane :vt vt)))
    (feed vt (text-bytes (format nil "~C[1;31;44mRED~C[0;32mGREEN" #\Esc #\Esc))
          (lambda (&rest args) (declare (ignore args))))
    (enter-copy pane)
    (point-copy pane 0 0 t) (point-copy pane 1 0 nil)
    (let ((runs (first (copy-display-lines pane))))
      (assert (equal (first runs) '(0 "RE" (0 1 31 48 5 238))))
      (assert (equal (second runs) '(2 "D" (0 1 31 44))))
      (assert (equal (third runs) '(3 "GREEN" (0 32)))))
    (feed vt (text-bytes (format nil "~C[H~C[0mNEW" #\Esc #\Esc))
          (lambda (&rest args) (declare (ignore args))))
    (assert (equal (first (first (copy-display-lines pane))) '(0 "RE" (0 1 31 48 5 238))))
    (leave-copy pane)
    (assert (null (pane-copy-cells pane))))
  (format t "Mouse selection and clipboard tests passed~%")
  t)
