//! Zellij-style pane separators: glyphs for the gap cells the server
//! reserves around pane content rects (see `PaneBorderStyle`). Pure
//! geometry — the daemon owns the reservation, this module only decides
//! which glyph lands in each reserved cell and whether it touches the
//! focused pane (so the renderer can tint it with the accent color).

use std::collections::HashSet;

use ekko_proto::{PaneBorderStyle, PaneRect};

/// One separator cell in canvas coordinates.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct BorderCell {
    pub col: i32,
    pub row: i32,
    pub ch: char,
    /// The cell touches the focused pane's content.
    pub focused: bool,
}

/// Compute every separator cell for the current pane layout. `panes` maps
/// pane ids to their canvas-local content rects. Returns an empty vec for
/// `PaneBorderStyle::None` and for single-pane compact layouts (no split,
/// no reserved cells).
pub fn border_cells(
    panes: &[(u64, PaneRect)],
    style: PaneBorderStyle,
    focused: u64,
) -> Vec<BorderCell> {
    match style {
        PaneBorderStyle::None => Vec::new(),
        PaneBorderStyle::Compact => compact_cells(panes, focused),
        PaneBorderStyle::Frame => frame_cells(panes, focused),
    }
}

fn covered(panes: &[(u64, PaneRect)], col: i32, row: i32) -> bool {
    panes.iter().any(|(_, rect)| {
        let (x, y) = (i32::from(rect.x), i32::from(rect.y));
        (x..x + i32::from(rect.cols)).contains(&col) && (y..y + i32::from(rect.rows)).contains(&row)
    })
}

/// The cell sits in the one-cell band ringing the focused pane's content.
fn touches_focused(panes: &[(u64, PaneRect)], focused: u64, col: i32, row: i32) -> bool {
    panes
        .iter()
        .find(|(id, _)| *id == focused)
        .is_some_and(|(_, rect)| {
            let (x, y) = (i32::from(rect.x), i32::from(rect.y));
            let (w, h) = (i32::from(rect.cols), i32::from(rect.rows));
            col >= x - 1 && col <= x + w && row >= y - 1 && row <= y + h
        })
}

/// Compact mode: shared one-cell boundary lines in the split gaps, with
/// box-drawing junctions resolved from each cell's connected neighbors.
fn compact_cells(panes: &[(u64, PaneRect)], focused: u64) -> Vec<BorderCell> {
    // Boundary cells generated by pane edges: a pane's right/bottom edge
    // line lives in the gap cell just past its content — but only where a
    // neighbor sits across the gap (a pane at the canvas edge has no
    // reserved cell beyond it in compact mode).
    let right_neighbor = |col: i32, row: i32| {
        panes.iter().any(|(_, rect)| {
            let (x, y) = (i32::from(rect.x), i32::from(rect.y));
            x == col + 1 && (y..y + i32::from(rect.rows)).contains(&row)
        })
    };
    let bottom_neighbor = |col: i32, row: i32| {
        panes.iter().any(|(_, rect)| {
            let (x, y) = (i32::from(rect.x), i32::from(rect.y));
            y == row + 1 && (x..x + i32::from(rect.cols)).contains(&col)
        })
    };
    let mut lines: HashSet<(i32, i32)> = HashSet::new();
    for (_, rect) in panes {
        let (x, y) = (i32::from(rect.x), i32::from(rect.y));
        let (w, h) = (i32::from(rect.cols), i32::from(rect.rows));
        for row in y..y + h {
            if right_neighbor(x + w, row) {
                lines.insert((x + w, row));
            }
        }
        for col in x..x + w {
            if bottom_neighbor(col, y + h) {
                lines.insert((col, y + h));
            }
        }
    }
    lines.retain(|&(col, row)| !covered(panes, col, row));

    // Junctions sit at gap-column × gap-row intersections that no pane
    // edge generated directly (the corner of a split touching another
    // split). Add them to a fixpoint so chained junctions connect.
    loop {
        let mut added = false;
        let cols: HashSet<i32> = lines.iter().map(|&(col, _)| col).collect();
        let rows: HashSet<i32> = lines.iter().map(|&(_, row)| row).collect();
        for &col in &cols {
            for &row in &rows {
                if lines.contains(&(col, row)) || covered(panes, col, row) {
                    continue;
                }
                let connects = [(0, -1), (0, 1), (-1, 0), (1, 0)]
                    .iter()
                    .any(|&(dc, dr)| lines.contains(&(col + dc, row + dr)));
                if connects {
                    // Only a genuine crossing: the cell must extend an
                    // existing line, not start a stray one. Require both a
                    // horizontal and a vertical neighbor eventually — the
                    // mask pass below degrades stubs to plain lines, so a
                    // single-direction add would draw a dangling segment.
                    let vertical =
                        lines.contains(&(col, row - 1)) || lines.contains(&(col, row + 1));
                    let horizontal =
                        lines.contains(&(col - 1, row)) || lines.contains(&(col + 1, row));
                    if vertical && horizontal {
                        lines.insert((col, row));
                        added = true;
                    }
                }
            }
        }
        if !added {
            break;
        }
    }

    let mut cells: Vec<BorderCell> = lines
        .iter()
        .map(|&(col, row)| {
            let up = lines.contains(&(col, row - 1));
            let down = lines.contains(&(col, row + 1));
            let left = lines.contains(&(col - 1, row));
            let right = lines.contains(&(col + 1, row));
            BorderCell {
                col,
                row,
                ch: junction_glyph(up, down, left, right),
                focused: touches_focused(panes, focused, col, row),
            }
        })
        .collect();
    cells.sort_by_key(|cell| (cell.row, cell.col));
    cells
}

/// Box-drawing glyph for a boundary cell, from its connected neighbors.
fn junction_glyph(up: bool, down: bool, left: bool, right: bool) -> char {
    match (up, down, left, right) {
        (true, true, true, true) => '┼',
        (false, true, true, true) => '┬',
        (true, false, true, true) => '┴',
        (true, true, false, true) => '├',
        (true, true, true, false) => '┤',
        (false, true, false, true) => '┌',
        (false, true, true, false) => '┐',
        (true, false, false, true) => '└',
        (true, false, true, false) => '┘',
        (true, true, false, false) => '│',
        (false, false, true, true) => '─',
        // Stubs (a line ending at the canvas edge): keep the line glyph.
        (true, false, false, false) | (false, true, false, false) => '│',
        (false, false, true, false) | (false, false, false, true) => '─',
        (false, false, false, false) => ' ',
    }
}

/// Frame mode: a full box around each pane's content, drawn in the ring of
/// reserved cells one past the content rect. Gaps are two cells wide, so
/// neighbor frames never share a cell.
fn frame_cells(panes: &[(u64, PaneRect)], focused: u64) -> Vec<BorderCell> {
    let mut cells = Vec::new();
    for &(id, rect) in panes {
        let (x, y) = (i32::from(rect.x), i32::from(rect.y));
        let (w, h) = (i32::from(rect.cols), i32::from(rect.rows));
        let (left, top) = (x - 1, y - 1);
        let (right, bottom) = (x + w, y + h);
        let is_focused = id == focused;
        for col in left..=right {
            for (row, ch) in [(top, '─'), (bottom, '─')] {
                let corner = if col == left {
                    Some(if row == top { '┌' } else { '└' })
                } else if col == right {
                    Some(if row == top { '┐' } else { '┘' })
                } else {
                    None
                };
                if !covered(panes, col, row) {
                    cells.push(BorderCell {
                        col,
                        row,
                        ch: corner.unwrap_or(ch),
                        focused: is_focused,
                    });
                }
            }
        }
        for row in top + 1..bottom {
            for (col, ch) in [(left, '│'), (right, '│')] {
                if !covered(panes, col, row) {
                    cells.push(BorderCell {
                        col,
                        row,
                        ch,
                        focused: is_focused,
                    });
                }
            }
        }
    }
    cells.sort_by_key(|cell| (cell.row, cell.col));
    cells
}

#[cfg(test)]
mod tests {
    use super::*;

    fn rect(x: u16, y: u16, cols: u16, rows: u16) -> PaneRect {
        PaneRect { x, y, cols, rows }
    }

    fn glyph_at(cells: &[BorderCell], col: i32, row: i32) -> Option<char> {
        cells
            .iter()
            .find(|cell| cell.col == col && cell.row == row)
            .map(|cell| cell.ch)
    }

    /// Two panes side by side, 12x8 canvas, gap col 5:
    /// `AAAAA│BBBBBB` — a single vertical line, focus tint on the left.
    #[test]
    fn compact_vertical_split_draws_a_straight_line() {
        let panes = [(1, rect(0, 0, 5, 8)), (2, rect(6, 0, 6, 8))];
        let cells = border_cells(&panes, PaneBorderStyle::Compact, 1);
        assert_eq!(cells.len(), 8);
        for row in 0..8 {
            assert_eq!(glyph_at(&cells, 5, row), Some('│'));
        }
        assert!(cells.iter().all(|cell| cell.focused));
        let unfocused = border_cells(&panes, PaneBorderStyle::Compact, 2);
        assert!(unfocused.iter().all(|cell| cell.focused));
        // A pane id that is not there: nothing is tinted.
        let none = border_cells(&panes, PaneBorderStyle::Compact, 99);
        assert!(none.iter().all(|cell| !cell.focused));
    }

    /// Quad layout (12x8, gap col 5, gap row 3): the crossing at (5, 3)
    /// must be a ┼, the line ends at the canvas edge plain ─/│.
    #[test]
    fn compact_quad_resolves_junctions() {
        let panes = [
            (1, rect(0, 0, 5, 3)),
            (2, rect(6, 0, 6, 3)),
            (3, rect(0, 4, 5, 4)),
            (4, rect(6, 4, 6, 4)),
        ];
        let cells = border_cells(&panes, PaneBorderStyle::Compact, 4);
        assert_eq!(glyph_at(&cells, 5, 3), Some('┼'));
        assert_eq!(glyph_at(&cells, 0, 3), Some('─'));
        assert_eq!(glyph_at(&cells, 11, 3), Some('─'));
        assert_eq!(glyph_at(&cells, 5, 0), Some('│'));
        assert_eq!(glyph_at(&cells, 5, 7), Some('│'));
        // Focus on pane 4 (bottom right): its top and left edges tinted,
        // pane 1's far edges not.
        let focused: HashSet<(i32, i32)> = cells
            .iter()
            .filter(|cell| cell.focused)
            .map(|cell| (cell.col, cell.row))
            .collect();
        assert!(focused.contains(&(5, 5))); // left edge beside pane 4
        assert!(focused.contains(&(8, 3))); // top edge above pane 4
        assert!(!focused.contains(&(0, 3))); // pane 1's bottom edge
        assert!(!focused.contains(&(5, 0))); // pane 1's right edge
    }

    /// T-junction: left pane full height, right split horizontally. The
    /// meeting cell is ├, not ┼ (no line continues left of it... wait, no:
    /// the horizontal line *ends* there, the vertical continues).
    #[test]
    fn compact_t_junction() {
        let panes = [
            (1, rect(0, 0, 5, 8)),
            (2, rect(6, 0, 6, 3)),
            (3, rect(6, 4, 6, 4)),
        ];
        let cells = border_cells(&panes, PaneBorderStyle::Compact, 1);
        assert_eq!(glyph_at(&cells, 5, 3), Some('├'));
        assert_eq!(glyph_at(&cells, 6, 3), Some('─'));
        assert_eq!(glyph_at(&cells, 11, 3), Some('─'));
    }

    /// A lone pane has no reserved cells in compact mode.
    #[test]
    fn compact_single_pane_draws_nothing() {
        let panes = [(1, rect(0, 0, 12, 8))];
        assert!(border_cells(&panes, PaneBorderStyle::Compact, 1).is_empty());
        assert!(border_cells(&panes, PaneBorderStyle::None, 1).is_empty());
    }

    /// Frame mode: two panes (12x8, margin 1, gap 2 — from the topology's
    /// frame reservation) each get a complete ring.
    #[test]
    fn frame_draws_a_ring_per_pane() {
        let panes = [(1, rect(1, 1, 4, 6)), (2, rect(7, 1, 4, 6))];
        let cells = border_cells(&panes, PaneBorderStyle::Frame, 2);
        // Pane 1 corners.
        assert_eq!(glyph_at(&cells, 0, 0), Some('┌'));
        assert_eq!(glyph_at(&cells, 5, 0), Some('┐'));
        assert_eq!(glyph_at(&cells, 0, 7), Some('└'));
        assert_eq!(glyph_at(&cells, 5, 7), Some('┘'));
        // Pane 2 corners, one column further right (its facing frame col).
        assert_eq!(glyph_at(&cells, 6, 0), Some('┌'));
        assert_eq!(glyph_at(&cells, 11, 0), Some('┐'));
        // Facing columns are distinct cells.
        assert_eq!(glyph_at(&cells, 5, 3), Some('│'));
        assert_eq!(glyph_at(&cells, 6, 3), Some('│'));
        // Focus tint follows the pane.
        let focused: HashSet<(i32, i32)> = cells
            .iter()
            .filter(|cell| cell.focused)
            .map(|cell| (cell.col, cell.row))
            .collect();
        assert!(focused.contains(&(6, 0)));
        assert!(!focused.contains(&(0, 0)));
        // Ring count: two perimeters of 6x8 cells each = 2*(2*6+2*8-4).
        assert_eq!(cells.len(), 2 * (2 * 6 + 2 * 8 - 4));
    }

    /// Frame cells never land on pane content, even on degenerate input
    /// where a ring would overlap a neighbor (no reserved gap).
    #[test]
    fn frame_skips_cells_covered_by_content() {
        let panes = [(1, rect(0, 0, 6, 8)), (2, rect(6, 0, 6, 8))];
        let cells = border_cells(&panes, PaneBorderStyle::Frame, 1);
        for cell in &cells {
            assert!(!covered(&panes, cell.col, cell.row));
        }
    }
}
