//! Cell-grid theme: color resolution for vt100 screen cells, plus the
//! `GeneratedTheme` adapter that converts the unified `ekko_tui::Theme` into
//! the mux `Color` space.
//!
//! The **unified theme** lives in `ekko_tui::theme` — a single `Theme` struct
//! with all color roles, generated by `ekko_tui::generate_theme`.  This module
//! keeps the `Color`-specific machinery (vt100 cell resolution, `brighten` /
//! `fade_toward` on the packed `Color` type, role-tag constants) and exposes
//! `GeneratedTheme` as a thin adapter so `ScenePalette` can stay in `Color`
//! space without duplicating any derivation logic.

use crate::color::Color;
use ekko_tui::palette::TerminalColors;
use ekko_tui::theme::generate_theme;
use ekko_tui::{Rgb, ansi_index_to_rgb};

// ---------------------------------------------------------------------------
// Transparent / cursor / selection constants (mux-specific, not theme roles)
// ---------------------------------------------------------------------------

pub const TRANSPARENT: Color = Color::rgba(0, 0, 0, 0);

const CURSOR: Color = Color::rgb(0x68, 0xFF, 0xD6);
const TERM_SELECTION_BG: Color = Color::rgb(0x6B, 0x50, 0xFF);
const TERM_SELECTION_FG: Color = Color::rgb(0xFF, 0xFA, 0xF1);

// ---------------------------------------------------------------------------
// Role-tag constants
// ---------------------------------------------------------------------------
// These are used as *identity tags* by `sidebar.rs` / `scene.rs`: a
// `SidebarRow.fg` is set to one of these constants, then `palette_color()`
// in `scene.rs` maps it back to the palette-resolved color.  They must exist
// as comparable `Color` values, but their actual RGB doesn't matter — only
// that they are distinct and that `palette_color()` knows about them.

pub const TEXT: Color = Color::rgb(0x01, 0x01, 0x01);
pub const MUTED: Color = Color::rgb(0x02, 0x02, 0x02);
pub const HEADING: Color = Color::rgb(0x03, 0x03, 0x03);
pub const ACCENT: Color = Color::rgb(0x04, 0x04, 0x04);
pub const ACCENT_2: Color = Color::rgb(0x05, 0x05, 0x05);
pub const RUNNING: Color = Color::rgb(0x06, 0x06, 0x06);
pub const WARNING: Color = Color::rgb(0x07, 0x07, 0x07);
pub const ERROR: Color = Color::rgb(0x08, 0x08, 0x08);
pub const SUCCESS: Color = Color::rgb(0x09, 0x09, 0x09);

pub const TERM_FG: Color = Color::rgb(0x0A, 0x0A, 0x0A);

// ---------------------------------------------------------------------------
// vt100 cell color resolution
// ---------------------------------------------------------------------------

pub fn default_ansi_palette() -> [Color; 16] {
    [
        Color::rgb(0x20, 0x1F, 0x26),
        Color::rgb(0xEB, 0x42, 0x68),
        Color::rgb(0x12, 0xC7, 0x8F),
        Color::rgb(0xF5, 0xEF, 0x34),
        Color::rgb(0x00, 0xA4, 0xFF),
        Color::rgb(0xFF, 0x60, 0xFF),
        Color::rgb(0x68, 0xFF, 0xD6),
        Color::rgb(0xBF, 0xBC, 0xC8),
        Color::rgb(0x4D, 0x4C, 0x57),
        Color::rgb(0xFF, 0x57, 0x7D),
        Color::rgb(0x00, 0xFF, 0xB2),
        Color::rgb(0xE8, 0xFF, 0x27),
        Color::rgb(0x71, 0x9A, 0xFC),
        Color::rgb(0xFF, 0x84, 0xFF),
        Color::rgb(0x4F, 0xBE, 0xFE),
        Color::rgb(0xDF, 0xDB, 0xDD),
    ]
}

pub fn screen_cell_colors(
    cell: &vt100::Cell,
    cursor_here: bool,
    selected: bool,
    default_fg: Color,
    default_bg: Color,
    ansi_palette: &[Color; 16],
) -> (Color, Color) {
    let mut fg = terminal_color(cell.fgcolor(), default_fg, ansi_palette);
    let mut bg = terminal_color(cell.bgcolor(), default_bg, ansi_palette);

    if cell.inverse() {
        std::mem::swap(&mut fg, &mut bg);
    }
    if cell.bold() {
        fg = brighten(fg, 18);
    }
    if cell.dim() {
        fg = fade_toward(fg, bg, 110);
    }
    if selected {
        return (TERM_SELECTION_FG, TERM_SELECTION_BG);
    }
    if cursor_here {
        return (Color::rgb(9, 12, 18), CURSOR);
    }

    (fg, bg)
}

fn terminal_color(color: vt100::Color, default: Color, ansi_palette: &[Color; 16]) -> Color {
    match color {
        vt100::Color::Default => default,
        vt100::Color::Idx(idx) if idx < 16 => ansi_palette[idx as usize],
        vt100::Color::Idx(idx) => ansi_index_to_color(idx),
        vt100::Color::Rgb(r, g, b) => Color::rgb(r, g, b),
    }
}

/// Resolve an ANSI 256-color index to a `Color` via the standard 256-color cube.
pub fn ansi_index_to_color(idx: u8) -> Color {
    let r = ansi_index_to_rgb(idx);
    Color::rgb(r.0, r.1, r.2)
}

/// Saturating-add `amount` to each channel.  ANSI-indexed colors pass through
/// unchanged (they are resolved by the terminal, not by us).
pub fn brighten(color: Color, amount: u8) -> Color {
    if color.ansi_index_value().is_some() {
        return color;
    }
    let (r, g, b) = color.rgb_components();
    Color::rgb(
        r.saturating_add(amount),
        g.saturating_add(amount),
        b.saturating_add(amount),
    )
}

/// Linearly interpolate `color` toward `target` by `mix` (0..255).
/// ANSI-indexed colors pass through (threshold behavior at mix 128).
pub fn fade_toward(color: Color, target: Color, mix: u8) -> Color {
    if color.ansi_index_value().is_some() || target.ansi_index_value().is_some() {
        return if mix < 128 { color } else { target };
    }
    let (r1, g1, b1) = color.rgb_components();
    let (r2, g2, b2) = target.rgb_components();
    let blend = |a: u8, b: u8| -> u8 {
        let a = u16::from(a);
        let b = u16::from(b);
        let mix = u16::from(mix);
        (((a * (255 - mix)) + (b * mix)) / 255) as u8
    };
    Color::rgb(blend(r1, r2), blend(g1, g2), blend(b1, b2))
}

// ---------------------------------------------------------------------------
// GeneratedTheme — thin adapter from the unified `Theme` to `Color` space
// ---------------------------------------------------------------------------

/// Colors resolved from the host terminal, in the mux `Color` space.
///
/// This is now a **thin adapter** over `ekko_tui::Theme` — it converts `Rgb`
/// values to `Color` so the mux compositor can stay in `Color` space.  All
/// derivation logic lives in `ekko_tui::generate_theme`.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct GeneratedTheme {
    pub fg: Color,
    pub bg: Color,
    pub surface_raised: Color,
    pub statusbar_fg: Color,
    pub statusbar_bg: Color,
    pub sidebar_bg: Color,
    pub border: Color,
    pub muted: Color,
    pub term_fg: Color,
    pub term_bg: Color,
    pub accent: Color,
    pub accent_2: Color,
    pub ansi: [Color; 16],
    pub running: Color,
    pub success: Color,
    pub success_subtle: Color,
    pub warning: Color,
    pub error: Color,
}

fn to_color(c: Rgb) -> Color {
    Color::rgb(c.0, c.1, c.2)
}

fn to_color_array(arr: [Rgb; 16]) -> [Color; 16] {
    let mut out = [Color::rgb(0, 0, 0); 16];
    for i in 0..16 {
        out[i] = to_color(arr[i]);
    }
    out
}

/// Generate a `GeneratedTheme` from the host terminal's reported colors.
///
/// Delegates to `ekko_tui::generate_theme` (the single derivation path) and
/// converts the resulting `Theme` to `Color` values.
pub fn generate_system(colors: &TerminalColors) -> GeneratedTheme {
    let t = generate_theme(colors);
    GeneratedTheme {
        fg: to_color(t.foreground),
        bg: to_color(t.surface),
        surface_raised: to_color(t.surface_raised),
        statusbar_fg: to_color(t.foreground),
        statusbar_bg: to_color(t.statusbar_bg),
        sidebar_bg: to_color(t.surface),
        border: to_color(t.border),
        muted: to_color(t.muted),
        term_fg: to_color(t.foreground),
        term_bg: to_color(t.surface),
        accent: to_color(t.accent),
        accent_2: to_color(t.accent_2),
        ansi: to_color_array(t.ansi),
        running: to_color(t.running),
        success: to_color(t.success),
        success_subtle: to_color(t.success_subtle),
        warning: to_color(t.warning),
        error: to_color(t.error),
    }
}

// Re-export the unified theme items so existing callers compile unchanged.
pub use ekko_tui::theme::{Mode, Theme, terminal_mode};
pub use ekko_tui::{default_terminal_colors, luminance_rgb};

// ---------------------------------------------------------------------------
// Spinner — re-exported from ekko-tui (single source of truth)
// ---------------------------------------------------------------------------

pub use ekko_tui::{SPINNER_FRAME_MS, SPINNER_FRAMES, spinner_frame_at, spinner_frame_index};

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use ekko_tui::palette::{Rgb, TerminalColors};

    fn colors_from(bg: Rgb, fg: Rgb) -> TerminalColors {
        TerminalColors {
            background: bg,
            foreground: fg,
            palette: std::array::from_fn(|i| Some(Rgb(i as u8 * 8, i as u8 * 8, i as u8 * 8))),
        }
    }

    #[test]
    fn terminal_mode_splits_on_background_luminance() {
        assert_eq!(
            terminal_mode(&colors_from(Rgb(0, 0, 0), Rgb(255, 255, 255))),
            Mode::Dark
        );
        assert_eq!(
            terminal_mode(&colors_from(Rgb(255, 255, 255), Rgb(0, 0, 0))),
            Mode::Light
        );
    }

    #[test]
    fn generate_system_maps_ansi_roles_and_surfaces() {
        let colors = colors_from(Rgb(20, 20, 26), Rgb(220, 220, 220));
        let theme = generate_system(&colors);

        // Accents/status follow the ANSI palette, not the background.
        assert_eq!(theme.accent, theme.ansi[6]);
        assert_eq!(theme.accent_2, theme.ansi[5]);
        assert_eq!(theme.error, theme.ansi[1]);
        assert_eq!(theme.success, theme.ansi[2]);
        assert_eq!(theme.warning, theme.ansi[3]);
        // Text mirrors the terminal foreground; the canvas is a generated surface.
        assert_eq!(theme.fg, Color::rgb(220, 220, 220));
        assert_eq!(theme.term_fg, theme.fg);
        assert_ne!(theme.bg, Color::rgb(20, 20, 26));
    }

    #[test]
    fn generate_system_falls_back_to_cube_colors_for_missing_palette_entries() {
        let mut colors = colors_from(Rgb(0, 0, 0), Rgb(255, 255, 255));
        colors.palette[6] = None;
        let theme = generate_system(&colors);
        assert_eq!(theme.accent, ansi_index_to_color(6));
    }

    #[test]
    fn muted_text_is_neutral_and_lighter_on_dark_than_background() {
        let colors = colors_from(Rgb(20, 20, 26), Rgb(220, 220, 220));
        let theme = generate_system(&colors);
        let (r, g, b) = theme.muted.rgb_components();
        assert_eq!(r, g);
        assert_eq!(g, b);
        assert!(u32::from(r) > luminance_rgb(20, 20, 26));
    }

    #[test]
    fn success_subtle_is_a_tint_toward_green() {
        let colors = colors_from(Rgb(20, 20, 26), Rgb(220, 220, 220));
        let theme = generate_system(&colors);
        let expected = fade_toward(theme.bg, theme.ansi[2], 56);
        assert_eq!(theme.success_subtle, expected);
    }

    fn cell_from_bytes(bytes: &[u8]) -> vt100::Cell {
        let mut parser = vt100::Parser::new(1, 8, 0);
        parser.process(bytes);
        parser.screen().cell(0, 0).unwrap().clone()
    }

    #[test]
    fn ansi_index_to_color_handles_base_cube_and_grayscale_ranges() {
        assert_eq!(ansi_index_to_color(1), Color::rgb(0xf7, 0x76, 0x8e));
        assert_eq!(ansi_index_to_color(16), Color::rgb(0, 0, 0));
        assert_eq!(ansi_index_to_color(231), Color::rgb(255, 255, 255));
        assert_eq!(ansi_index_to_color(232), Color::rgb(8, 8, 8));
        assert_eq!(ansi_index_to_color(255), Color::rgb(238, 238, 238));
    }

    #[test]
    fn indexed_colors_survive_brighten_and_fade() {
        let indexed = Color::ansi_index(12);
        let target = Color::rgb(100, 120, 140);
        assert_eq!(brighten(indexed, 20), indexed);
        assert_eq!(fade_toward(indexed, target, 64), indexed);
        assert_eq!(fade_toward(indexed, target, 192), target);
    }

    #[test]
    fn cell_colors_apply_selection_and_cursor_after_styles() {
        let styled = cell_from_bytes(b"\x1b[1;2;7mX");
        let bg = Color::rgb(10, 13, 18);
        let ansi = default_ansi_palette();
        assert_eq!(
            screen_cell_colors(&styled, false, true, TERM_FG, bg, &ansi),
            (TERM_SELECTION_FG, TERM_SELECTION_BG)
        );
        assert_eq!(
            screen_cell_colors(&styled, true, false, TERM_FG, bg, &ansi),
            (Color::rgb(9, 12, 18), Color::rgb(0x68, 0xFF, 0xD6))
        );
    }

    #[test]
    fn role_tag_constants_are_distinct() {
        // Every role tag must be a unique Color so palette_color() can
        // disambiguate them.
        let tags = [
            TEXT, MUTED, HEADING, ACCENT, ACCENT_2, RUNNING, WARNING, ERROR, SUCCESS,
        ];
        for i in 0..tags.len() {
            for j in (i + 1)..tags.len() {
                assert_ne!(tags[i], tags[j], "role tags {i} and {j} collide");
            }
        }
    }
}
