#!/usr/bin/env python3
"""Generate src/text-width.lisp from the pinned unicode-width crate."""
import argparse
import hashlib
import pathlib
import subprocess
import tempfile

ORACLE = r'''extern crate unicode_width;
use unicode_width::UnicodeWidthChar;
fn main() {
    let mut last: Option<usize> = None;
    let mut start = 0u32;
    for cp in 0..=0x10ffff {
        if (0xd800..=0xdfff).contains(&cp) { continue; }
        let c = char::from_u32(cp).unwrap();
        let width = c.width().unwrap_or(0);
        if Some(width) != last {
            if let Some(previous) = last {
                println!("{:X}..{:X} {}", start, cp - 1, previous);
            }
            start = cp;
            last = Some(width);
        }
    }
    println!("{:X}..{:X} {}", start, 0x10ffff, last.unwrap());
}'''

LICENSE = '''Copyright 2012-2015 The Rust Project Developers.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.'''

EXPECTED_FILES = {
    "src/lib.rs": "38c44436eac069bd8d11203f31ecfef8adfe92da1fce19ba00bdd25aa3fbbe20",
    "src/tables.rs": "c6ddb420c289517bb92973199fd2987b9608f29fc10bb33b5290f39b301ce92f",
    "LICENSE-MIT": "7b63ecd5f1902af1b63729947373683c32745c16a10e8e6292e2e2dcd7e90ae0",
}


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("crate", type=pathlib.Path, help="unpacked unicode-width crate")
    parser.add_argument("--rustc", default="rustc")
    parser.add_argument("--output", type=pathlib.Path, default=pathlib.Path("src/text-width.lisp"))
    args = parser.parse_args()
    source = args.crate / "src/lib.rs"
    if not source.is_file():
        raise SystemExit(f"missing crate source: {source}")
    for relative, expected in EXPECTED_FILES.items():
        path = args.crate / relative
        digest = hashlib.sha256(path.read_bytes()).hexdigest()
        if digest != expected:
            raise SystemExit(f"unexpected unicode-width 0.1.10 file hash: {path}")
    with tempfile.TemporaryDirectory() as temp:
        temp = pathlib.Path(temp)
        library = temp / "libunicode_width.rlib"
        binary = temp / "oracle"
        subprocess.run([args.rustc, "--crate-name", "unicode_width", "--crate-type", "lib",
                        "--edition=2018", str(source), "-o", str(library)], check=True)
        oracle = temp / "oracle.rs"
        oracle.write_text(ORACLE)
        subprocess.run([args.rustc, str(oracle), "--extern", f"unicode_width={library}",
                        "-o", str(binary)], check=True)
        rows = subprocess.check_output([str(binary)], text=True).splitlines()
    exceptions = []
    for row in rows:
        span, width = row.split()
        if int(width) != 1:
            start, end = span.split("..")
            exceptions.append((start, end, width))
    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("w") as output:
        output.write(";; Unicode scalar display widths matching unicode-width 0.1.10 ordinary mode.\n")
        output.write(";; Generated by scripts/generate-text-width.py from the checksum-verified crate.\n")
        output.write(";; SHA-256: c0edd1e5b14653f783770bce4a4dabb4a5108a5370a5f5d8cfe8710c361f6c8b\n")
        output.write(";; " + LICENSE.replace("\n", "\n;; ") + "\n")
        output.write(";; Controls map to width 0 because the crate returns None and its string API maps None to zero.\n")
        output.write("(defpackage #:ekko/text (:use #:cl) (:export #:display-width))\n(in-package #:ekko/text)\n")
        output.write("(defparameter *unicode-width-exceptions*\n  #(\n")
        for start, end, width in exceptions:
            output.write(f"    (#x{start} #x{end} {width})\n")
        output.write("  ))\n")
        output.write("""(defun scalar-display-width (character)
  (let ((code (char-code character)))
    (or (loop with low of-type fixnum = 0
              with high of-type fixnum = (1- (length *unicode-width-exceptions*))
              while (<= low high)
              for mid of-type fixnum = (+ low (ash (- high low) -1))
              for (start end width) = (aref *unicode-width-exceptions* mid)
              if (< code start)
                do (setf high (1- mid))
              else if (> code end)
                do (setf low (1+ mid))
              else
                return width)
        1)))
(defun display-width (value)
  "Return unicode-width 0.1.10 ordinary cell width for a character/string."
  (etypecase value
    (character (scalar-display-width value))
    (string (loop for character across value sum (scalar-display-width character)))))
""")


if __name__ == "__main__":
    main()
