(in-package #:ekko/runtime)

;; Short outline transitions use the existing overlay channel. Logical layout
;; commits once; animation ticks never touch application VT or PTY geometry.
(defstruct transition from to sgr started duration (step 0))
(defun pane-outer-rect (pane)
  (list (pane-outer-x pane) (pane-outer-y pane) (pane-outer-cols pane) (pane-outer-rows pane)))
(defun capture-transition (session action)
  (let* ((pane (or (pane-by-id session (getf (rest action) :pane)) (focused-pane session)))
         (op (first action)) (duration (option session :window-animation-ms 0)))
    (when (and (plusp duration) (session-writer session)
               (or (member op '(:minimize :restore :zoom :float :tile :place-window))
                   (and (eq op :focus) (pane-minimized pane))))
      (let* ((spans (loop for entry in (session-decorations session) append (cdr entry)))
             (dock (find-if (lambda (span)
                              (and (= (getf span :y) (1- (session-rows session)))
                                   (eql (getf (rest (getf span :action)) :pane) (pane-id pane)))) spans))
             (header (find-if (lambda (span)
                                (and (= (getf span :x) (pane-outer-x pane))
                                     (= (getf span :y) (pane-outer-y pane))
                                     (eql (getf (rest (getf span :action)) :pane) (pane-id pane)))) spans))
             (dock-rect (if dock (list (getf dock :x) (getf dock :y) (max 1 (span-width dock)) 1)
                            (list (floor (session-cols session) 2) (1- (session-rows session)) 1 1))))
        (list pane op (if (pane-minimized pane) dock-rect (pane-outer-rect pane)) dock-rect
              (copy-list (getf (or header dock) :sgr '(0 38 5 245))) duration)))))
(defun start-transition (session captured)
  (when captured
    (destructuring-bind (pane op from dock sgr duration) captured
      (let ((to (if (eq op :minimize) dock (pane-outer-rect pane))))
        (unless (equal from to)
          (setf (session-transition session)
                (make-transition :from from :to to :sgr sgr :started (now) :duration (/ duration 1000))))))))
(defun tick-transition (session)
  (let ((transition (session-transition session)))
    (when transition
      (let ((step (min 8 (floor (* 8 (/ (- (now) (transition-started transition))
                                       (transition-duration transition)))))))
        (unless (= step (transition-step transition))
          (setf (transition-step transition) step)
          (when (= step 8) (setf (session-transition session) nil))
          (incf (session-revision session)))))))
(defun transition-overlays (session)
  (let ((transition (session-transition session)))
    (when transition
      (let* ((progress (- 1 (expt (- 1 (/ (transition-step transition) 8)) 3)))
             (rect (mapcar (lambda (a b) (round (+ a (* (- b a) progress))))
                           (transition-from transition) (transition-to transition)))
             (sgr (transition-sgr transition)))
        (graphics-safe-outlines session (outline-spans rect sgr))))))
