(in-package #:ekko/runtime)

;; Short outline transitions use the existing overlay channel. Logical layout
;; commits once; animation ticks never touch application VT or PTY geometry.
(defstruct transition from to sgr started duration (step 0))
(defun pane-outer-rect (view pane)
  (let ((state (pane-state view (pane-id pane))))
    (list (pane-view-outer-x state) (pane-view-outer-y state)
          (pane-view-outer-cols state) (pane-view-outer-rows state))))
(defun capture-transition (view action)
  (let* ((pane (if (getf (rest action) :pane)
                   (pane-by-id (view-daemon view) (getf (rest action) :pane))
                   (focused-pane view)))
         (state (when pane (pane-state view (pane-id pane))))
         (op (first action)) (duration (option (view-daemon view) :window-animation-ms 0)))
    (when (and pane (plusp duration) (view-wire view)
               (or (member op '(:minimize :restore :zoom :float :tile :place-window))
                   (and (eq op :focus) (pane-view-minimized state))))
      (let* ((spans (loop for entry in (view-decorations view) append (rest entry)))
             (dock (find-if (lambda (span)
                              (and (= (getf span :y) (1- (view-rows view)))
                                   (eql (getf (rest (getf span :action)) :pane) (pane-id pane)))) spans))
             (header (find-if (lambda (span)
                                (and (= (getf span :x) (pane-view-outer-x state))
                                     (= (getf span :y) (pane-view-outer-y state))
                                     (eql (getf (rest (getf span :action)) :pane) (pane-id pane)))) spans))
             (dock-rect (if dock (list (getf dock :x) (getf dock :y) (max 1 (span-width dock)) 1)
                            (list (floor (view-cols view) 2) (1- (view-rows view)) 1 1))))
        (list pane op (if (pane-view-minimized state) dock-rect (pane-outer-rect view pane)) dock-rect
              (copy-list (getf (or header dock) :sgr '(0 38 5 245))) duration)))))
(defun start-transition (view captured)
  (when captured
    (destructuring-bind (pane op from dock sgr duration) captured
      (let ((to (if (eq op :minimize) dock (pane-outer-rect view pane))))
        (unless (equal from to)
          (setf (view-transition view)
                (make-transition :from from :to to :sgr sgr :started (now) :duration (/ duration 1000))))))))
(defun tick-transition (view)
  (let ((transition (view-transition view)))
    (when transition
      (let ((step (min 8 (floor (* 8 (/ (- (now) (transition-started transition))
                                       (transition-duration transition)))))))
        (unless (= step (transition-step transition))
          (setf (transition-step transition) step)
          (when (= step 8) (setf (view-transition view) nil))
          (incf (view-revision view)))))))
(defun transition-overlays (view)
  (let ((transition (view-transition view)))
    (when transition
      (let* ((progress (- 1 (expt (- 1 (/ (transition-step transition) 8)) 3)))
             (rect (mapcar (lambda (a b) (round (+ a (* (- b a) progress))))
                           (transition-from transition) (transition-to transition)))
             (sgr (transition-sgr transition)))
        (graphics-safe-outlines view (outline-spans rect sgr))))))
;; Entrance motion: spans that declare (:enter (id dx dy)) start offset by
;; (dx dy) and ease into place over :window-animation-ms, like transitions.
;; Each motion is (id started step). A group re-enters after it disappears.
(defun motion-duration (view)
  (/ (option (view-daemon view) :window-animation-ms 0) 1000))
(defun motion-step (view motion)
  (let ((duration (motion-duration view)))
    (if (plusp duration) (min 8 (floor (* 8 (/ (- (now) (second motion)) duration)))) 8)))
(defun motion-offset (view span)
  "SPAN's current (values dx dy), starting its group's motion on first sight."
  (let ((enter (getf span :enter)))
    (if (null enter)
        (values 0 0)
        (destructuring-bind (id dx dy) enter
          (let* ((motion (or (assoc id (view-motions view) :test #'equal)
                             (first (push (list id (now) 0) (view-motions view)))))
                 (remaining (expt (- 1 (/ (motion-step view motion) 8)) 3)))
            (values (round (* dx remaining)) (round (* dy remaining))))))))
(defun motions-running-p (view)
  (some (lambda (motion) (< (third motion) 8)) (view-motions view)))
(defun tick-motions (view)
  (let ((present (loop for span in (append (loop for entry in (view-decorations view) append (rest entry))
                                            (and (view-popup view) (popup-spans (view-popup view))))
                       when (getf span :enter) collect (first (getf span :enter)))))
    (setf (view-motions view)
          (remove-if-not (lambda (motion) (member (first motion) present :test #'equal)) (view-motions view)))
    (dolist (motion (view-motions view))
      (let ((step (motion-step view motion)))
        (unless (= step (third motion))
          (setf (third motion) step)
          (incf (view-revision view)))))))
