(defpackage #:ekko/builtins
  (:use #:cl #:ekko/extensions)
  (:export #:install))
(in-package #:ekko/builtins)

;; The default chrome is an ordinary decoration contribution.  Keeping this
;; policy here means the renderer only has to clip and compose spans; a
;; profile can replace it without changing the scene protocol.
(defun default-fit-label (text width)
  (let* ((safe (remove-if (lambda (c) (or (< (char-code c) 32)
                                          (> (char-code c) 126)))
                          (or text "")))
         (limit (max 0 width)))
    (format nil "~VA" limit (subseq safe 0 (min limit (length safe))))))

(defun default-decoration-span (x y text style &optional (rows 1))
  (list :x x :y y :text text :sgr style :rows rows))

(defun default-pane-title (pane)
  (format nil " ~D  ~A~A"
          (getf pane :id)
          (or (getf pane :display-label) (getf pane :label) "")
          (if (getf pane :exit)
              (format nil " [exit ~D]" (getf pane :exit))
              "")))

(defun default-pane-right-gap-p (pane panes column-gap)
  (destructuring-bind (x y width height) (getf pane :outer-rect)
    (let ((right (+ x width)))
      (and (plusp column-gap)
           (some (lambda (other)
                   (unless (eq other pane)
                     (destructuring-bind (other-x other-y other-width other-height)
                         (getf other :outer-rect)
                       (declare (ignore other-width))
                       (and (> other-x right)
                            (< other-y (+ y height))
                            (< y (+ other-y other-height))))))
                 panes)))))

(defun default-decorations (snapshot)
  (let* ((focus (getf snapshot :focus))
         (panes (remove-if-not (lambda (pane) (getf pane :visible t))
                               (getf snapshot :panes)))
         (viewport (getf snapshot :viewport))
         (cols (or (getf viewport :cols) 0))
         (rows (or (getf viewport :rows) 0))
         (gaps (or (getf viewport :gaps) '(1 0)))
         (column-gap (first gaps))
         (spans nil))
    (dolist (pane panes)
      (when (getf pane :visible t)
        (destructuring-bind (outer-x outer-y outer-width outer-height)
            (getf pane :outer-rect)
          (declare (ignore outer-height))
          (let ((x (getf pane :x)) (y (getf pane :y)))
            (when (and (integerp x) (integerp y) (< outer-y y)
                       (<= 0 outer-y) (< outer-y rows))
              (push (default-decoration-span
                      outer-x outer-y
                      (default-fit-label (default-pane-title pane) outer-width)
                      (if (eql (getf pane :id) focus) '(0 30 46) '(0 37 44)))
                    spans)))))
        (destructuring-bind (outer-x outer-y outer-width outer-height)
            (getf pane :outer-rect)
          (when (and (default-pane-right-gap-p pane panes column-gap)
                     (< (+ outer-x outer-width) cols))
            (push (default-decoration-span
                    (+ outer-x outer-width) outer-y "│" '(0 36) outer-height) spans))))
    (let ((chrome (getf snapshot :chrome-status)))
      (when (and chrome (plusp rows) (plusp cols)
                 (plusp (third (getf viewport :insets '(0 0 1 0)))))
        (push (default-decoration-span
                0 (1- rows)
                (default-fit-label (getf chrome :text) (1- cols))
                (getf chrome :style '(0 30 47)))
              spans)))
    (nreverse spans)))

(defun defaults-hook (snapshot event)
  (declare (ignore event))
  (list (action :decorate :spans (default-decorations snapshot))))

(defun install ()
  (register-component :id :defaults
                      :reads '(:focus :panes :viewport :zoom :chrome-status)
                      :handler #'defaults-hook)
  (set-option :component :defaults :name :prefix :value "C-b")
  (set-option :component :defaults :name :shell :value (list (or (uiop:getenv "SHELL") "/bin/sh") "-i"))
  (set-option :component :defaults :name :status-text
              :value " ekko | prefix: % / split  [ copy  ] paste  r reload  ? help  d detach")
  (set-option :component :defaults :name :status-style :value '(0 30 47))
  (dolist (spec '(("focus-next" (:focus-next)) ("zoom" (:zoom)) ("swap" (:swap))
                  ("resize-left" (:resize :delta -5)) ("resize-right" (:resize :delta 5))
                  ("detach" (:detach)) ("stop" (:stop)) ("close" (:close))
                  ("split-columns" (:split :axis :columns)) ("split-rows" (:split :axis :rows))
                  ("copy-mode" (:copy-mode)) ("copy-up" (:copy-move :delta -1))
                  ("copy-down" (:copy-move :delta 1)) ("copy-page-up" (:copy-move :delta -20))
                  ("copy-page-down" (:copy-move :delta 20)) ("copy-home" (:copy-edge :edge :start))
                  ("copy-end" (:copy-edge :edge :end)) ("copy-mark" (:copy-mark))
                  ("copy-selection" (:copy-selection)) ("copy-exit" (:copy-exit))
                  ("copy-search" (:copy-search)) ("copy-search-next" (:copy-search-next))
                  ("paste-buffer" (:paste-buffer)) ("reload" (:reload)) ("help" (:help))))
    (let ((actions (list (second spec))))
      (register-command :component :defaults :name (first spec)
                         :handler (lambda (snapshot event) (declare (ignore snapshot))
                                   (if (and (eq (caar actions) :split) (getf event :arguments))
                                       (list (append (first actions) (list :argv (getf event :arguments))))
                                       (copy-tree actions))))))
  (register-command :component :defaults :name "rename"
    :handler (lambda (snapshot event) (declare (ignore snapshot))
               (unless (= (length (getf event :arguments)) 1) (error "rename requires one label"))
               (list (action :rename :text (first (getf event :arguments))))))
  (loop for i from 1 to 9 do
    (let ((index (1- i)))
      (register-command :component :defaults :name (format nil "focus-~D" i)
        :handler (lambda (snapshot event) (declare (ignore event))
                   (let ((pane (nth index (value snapshot :panes))))
                     (when pane (list (action :focus :pane (getf pane :id)))))))
      (bind-key :component :defaults :key (write-to-string i) :command (format nil "focus-~D" i))))
  (dolist (pair '(("Tab" "focus-next") ("o" "focus-next") ("n" "focus-next") (" " "focus-next")
                  ("z" "zoom") ("s" "swap") ("<" "resize-left") (">" "resize-right")
                  ("d" "detach") ("q" "stop") ("x" "close") ("%" "split-columns")
                  ("/" "split-rows") ("[" "copy-mode") ("]" "paste-buffer") ("r" "reload") ("?" "help")))
    (bind-key :component :defaults :key (first pair) :command (second pair)))
  (dolist (pair '(("k" "copy-up") ("Up" "copy-up") ("j" "copy-down") ("Down" "copy-down")
                  ("b" "copy-page-up") ("PageUp" "copy-page-up") ("f" "copy-page-down") ("PageDown" "copy-page-down")
                  ("g" "copy-home") ("Home" "copy-home") ("G" "copy-end") ("End" "copy-end")
                  (" " "copy-mark") ("Enter" "copy-selection") ("y" "copy-selection")
                  ("q" "copy-exit") ("Escape" "copy-exit") ("/" "copy-search") ("n" "copy-search-next")))
    (bind-key :component :defaults :map :copy :key (first pair) :command (second pair))))
