(defpackage #:ekko/builtins
  (:use #:cl #:ekko/extensions)
  (:export #:install))
(in-package #:ekko/builtins)

(defun install ()
  (register-component :id :defaults :reads '(:session :focus :panes :layout))
  (set-option :component :defaults :name :prefix :value "C-b")
  (set-option :component :defaults :name :shell :value (list (or (uiop:getenv "SHELL") "/bin/sh") "-i"))
  (set-option :component :defaults :name :status-text
              :value " ekko | prefix: % / split  [ copy  ] paste  r reload  ? help  d detach")
  (set-option :component :defaults :name :status-style :value '(0 30 47))
  (dolist (spec '(("focus-next" (:focus-next)) ("zoom" (:zoom)) ("swap" (:swap))
                  ("resize-left" (:resize :delta -5)) ("resize-right" (:resize :delta 5))
                  ("detach" (:detach)) ("stop" (:stop)) ("close" (:close))
                  ("split-columns" (:split :axis :columns)) ("split-rows" (:split :axis :rows))
                  ("copy-mode" (:copy-mode)) ("copy-up" (:copy-move :delta -1))
                  ("copy-down" (:copy-move :delta 1)) ("copy-page-up" (:copy-move :delta -20))
                  ("copy-page-down" (:copy-move :delta 20)) ("copy-home" (:copy-edge :edge :start))
                  ("copy-end" (:copy-edge :edge :end)) ("copy-mark" (:copy-mark))
                  ("copy-selection" (:copy-selection)) ("copy-exit" (:copy-exit))
                  ("copy-search" (:copy-search)) ("copy-search-next" (:copy-search-next))
                  ("paste-buffer" (:paste-buffer)) ("reload" (:reload)) ("help" (:help))))
    (let ((actions (list (second spec))))
      (register-command :component :defaults :name (first spec)
                         :handler (lambda (snapshot event) (declare (ignore snapshot))
                                   (if (and (eq (caar actions) :split) (getf event :arguments))
                                       (list (append (first actions) (list :argv (getf event :arguments))))
                                       (copy-tree actions))))))
  (register-command :component :defaults :name "rename"
    :handler (lambda (snapshot event) (declare (ignore snapshot))
               (unless (= (length (getf event :arguments)) 1) (error "rename requires one label"))
               (list (action :rename :text (first (getf event :arguments))))))
  (loop for i from 1 to 9 do
    (let ((index (1- i)))
      (register-command :component :defaults :name (format nil "focus-~D" i)
        :handler (lambda (snapshot event) (declare (ignore event))
                   (let ((pane (nth index (value snapshot :panes))))
                     (when pane (list (action :focus :pane (getf pane :id)))))))
      (bind-key :component :defaults :key (write-to-string i) :command (format nil "focus-~D" i))))
  (dolist (pair '(("Tab" "focus-next") ("o" "focus-next") ("n" "focus-next") (" " "focus-next")
                  ("z" "zoom") ("s" "swap") ("<" "resize-left") (">" "resize-right")
                  ("d" "detach") ("q" "stop") ("x" "close") ("%" "split-columns")
                  ("/" "split-rows") ("[" "copy-mode") ("]" "paste-buffer") ("r" "reload") ("?" "help")))
    (bind-key :component :defaults :key (first pair) :command (second pair)))
  (dolist (pair '(("k" "copy-up") ("Up" "copy-up") ("j" "copy-down") ("Down" "copy-down")
                  ("b" "copy-page-up") ("PageUp" "copy-page-up") ("f" "copy-page-down") ("PageDown" "copy-page-down")
                  ("g" "copy-home") ("Home" "copy-home") ("G" "copy-end") ("End" "copy-end")
                  (" " "copy-mark") ("Enter" "copy-selection") ("y" "copy-selection")
                  ("q" "copy-exit") ("Escape" "copy-exit") ("/" "copy-search") ("n" "copy-search-next")))
    (bind-key :component :defaults :map :copy :key (first pair) :command (second pair))))
