(in-package #:ekko)

(defparameter *version* "0.1.0")

(defun version () *version*)

(defun usage (&optional (stream *standard-output*))
  (format stream "Ekko ~A~%~%Usage: ekko run [--session NAME] COMMAND [ARGS...] [::: COMMAND ...]~%       ekko attach|status|inspect|buffer|stop [NAME]~%       ekko config check|reload [NAME]~%       ekko command [--session NAME] COMMAND [ARGS...]~%       ekko split [--session NAME] columns|rows [COMMAND ARGS...]~%       ekko rename [--session NAME] LABEL~%       ekko doctor --restore-terminal~%~%Keys: Ctrl-b then % / split, Tab/1..9 focus, x close, z zoom, s swap,~%      </> resize, [ copy, ] paste, r reload, ? help, d detach, q stop.~%Config: $EKKO_CONFIG or $XDG_CONFIG_HOME/ekko/init.lisp.~%Default session: default. Sessions survive closing the client.~%Options: -h, --help; --version.~%" *version*))

(defun pane-commands (args)
  (let ((commands nil) (current nil))
    (dolist (arg args)
      (if (string= arg ":::") (progn (push (nreverse current) commands) (setf current nil))
          (push arg current)))
    (push (nreverse current) commands)
    (unless (and (<= (length commands) 16) (every #'identity commands))
      (error "Provide one to sixteen nonempty pane commands"))
    (nreverse commands)))

(defun runtime-command (arguments)
  (handler-case
      (let ((command (first arguments)) (args (rest arguments)))
        (cond
          ((string= command "--extension-worker") (ekko/runtime::extension-worker-main))
          ((member command '("run" "--serve" "command" "split" "rename") :test #'string=)
           (let ((name "default"))
             (when (string= command "--serve") (setf name (pop args)))
             (when (equal (first args) "--session") (pop args) (setf name (pop args)))
             (unless name (error "Missing session name"))
             (cond
               ((string= command "--serve") (ekko/runtime:serve name (pane-commands args)))
               ((string= command "run") (ekko/runtime:run-session name (pane-commands args)))
               (t
                (when (string= command "split")
                  (unless (member (first args) '("columns" "rows") :test #'equal) (error "split requires columns or rows"))
                  (setf args (cons (concatenate 'string "split-" (first args)) (rest args))))
                (when (string= command "rename") (setf args (cons "rename" args)))
                (unless args (error "Missing command"))
                (ekko/runtime:control-session name "command" args)))))
          ((string= command "config")
           (unless (and (member (first args) '("check" "reload") :test #'equal) (<= (length args) 2))
             (error "Usage: ekko config check|reload [NAME]"))
           (if (equal (first args) "reload")
               (ekko/runtime:control-session (or (second args) "default") "reload")
               (progn
                 (when (second args) (error "config check takes no session name"))
                 (ekko/runtime::initialize)
                 (let* ((path (ekko/runtime::config-path))
                        (worker (ekko/runtime::load-worker (ekko/runtime::config-source path) path *error-output*)))
                   (unwind-protect
                        (ekko/runtime::install-registry (ekko/runtime::make-session)
                                                       (ekko/runtime::extension-worker-registry worker))
                     (ekko/runtime::stop-worker worker))) 0)))
          ((member command '("attach" "status" "inspect" "buffer" "stop") :test #'string=)
           (when (> (length args) 1) (error "Unexpected argument"))
           (if (string= command "attach") (ekko/runtime:attach-session (or (first args) "default"))
               (ekko/runtime:control-session (or (first args) "default") command)))
          ((and (string= command "doctor") (equal args '("--restore-terminal"))) (ekko/runtime:restore-terminal))
          (t (error "Unknown command ~A" command))))
    (error (condition) (format *error-output* "ekko: ~A~%" condition) 2)))

(defun main (&optional (arguments (cdr sb-ext:*posix-argv*)))
  (cond
    ((null arguments) (usage))
    ((or (string= (first arguments) "-h")
         (string= (first arguments) "--help"))
     (if (rest arguments)
         (progn (format *error-output* "ekko: unexpected argument ~A~%" (second arguments)) 2)
         (usage)))
    ((string= (first arguments) "--version")
     (if (rest arguments)
         (progn (format *error-output* "ekko: unexpected argument ~A~%" (second arguments)) 2)
         (format t "~A~%" *version*)))
    ((member (first arguments) '("run" "--serve" "--extension-worker" "attach" "status" "inspect" "buffer" "stop" "config" "command" "split" "rename" "doctor") :test #'string=)
     (runtime-command arguments))
    (t
     (format *error-output* "ekko: unknown option ~A~%" (first arguments))
     (usage *error-output*)
     2)))

(defun executable-main ()
  (sb-ext:exit :code (or (main) 0)))
