(in-package #:ekko)

(defparameter *version* "0.1.0")
(defun version () *version*)

(defun usage (&optional (stream *standard-output*))
  (format stream "Ekko ~A~%~%Usage: ekko [--instance NAME] run [--detached] [COMMAND [ARGS...] [::: COMMAND ...]]~%       ekko attach|status|inspect|buffer [--view ID]~%       ekko list~%       ekko stop [--force]~%       ekko config check|reload~%       ekko command [--view ID] COMMAND [ARGS...]~%       ekko split [--view ID] columns|rows [COMMAND ARGS...]~%       ekko rename [--view ID] LABEL~%       ekko doctor --restore-terminal~%~%One daemon owns one workspace; clients attach concurrently.~%EKKO_INSTANCE selects explicit isolation.~%Config: $EKKO_CONFIG or $XDG_CONFIG_HOME/ekko/init.lisp.~%Options: -h, --help; --version.~%" *version*))

(defun pane-commands (args)
  (when (null args) (return-from pane-commands nil))
  (let ((commands nil) (current nil))
    (dolist (arg args)
      (if (string= arg ":::") (progn (push (nreverse current) commands) (setf current nil))
          (push arg current)))
    (push (nreverse current) commands)
    (unless (and (<= (length commands) 128) (every #'identity commands))
      (error "Provide one to 128 nonempty pane commands"))
    (nreverse commands)))

(defun view-number (value)
  (let ((number (and value (parse-integer value :junk-allowed nil))))
    (unless (and number (<= 1 number #xffffffff)) (error "--view requires a positive view ID"))
    number))

(defun command-options (args &key detached)
  (let ((view nil) (background nil))
    (loop while (and args (member (first args) '("--view" "--detached") :test #'equal)) do
      (let ((option (pop args)))
        (cond ((equal option "--view") (setf view (view-number (pop args))))
              (t (unless detached (error "--detached is only valid for run"))
                 (setf background t)))))
    (values args view background)))

(defun target-options (args &key force)
  (let ((view nil) (forced nil))
    (loop while args do
      (let ((arg (pop args)))
        (cond ((equal arg "--view") (setf view (view-number (pop args))))
              ((equal arg "--force") (unless force (error "--force is only valid for stop"))
               (setf forced t))
              (t (error "Unexpected argument ~A" arg)))))
    (values view forced)))

(defun runtime-command (arguments)
  (handler-case
      (let ((command (first arguments)) (args (rest arguments)))
        (cond
          ((string= command "--extension-worker")
           (when args (error "Unexpected worker argument"))
           (ekko/runtime:extension-worker-main))
          ((string= command "--serve")
           (when args (error "The workspace daemon takes no arguments"))
           (ekko/runtime:serve))
          ((member command '("run" "command" "split" "rename") :test #'string=)
           (multiple-value-bind (rest view detached) (command-options args :detached (string= command "run"))
             (cond
               ((string= command "run")
                (when view (error "run does not select an existing view; use attach"))
                (ekko/runtime:run (pane-commands rest) :detached detached))
               (t
                (when (string= command "split")
                  (unless (member (first rest) '("columns" "rows") :test #'equal) (error "split requires columns or rows"))
                  (setf rest (cons (concatenate 'string "split-" (first rest)) (rest rest))))
                (when (string= command "rename") (setf rest (cons "rename" rest)))
                (unless rest (error "Missing command"))
                (ekko/runtime:control "command" :arguments rest :view-id view)))))
          ((string= command "config")
           (unless (and (member (first args) '("check" "reload") :test #'equal) (<= (length args) 1))
             (error "Usage: ekko config check|reload"))
           (if (equal (first args) "reload")
               (ekko/runtime:control "reload")
               (progn
                 (ekko/runtime:initialize)
                 (let* ((path (ekko/runtime:config-path))
                        (worker (ekko/runtime:load-worker (ekko/runtime:config-source path) path *error-output*)))
                   (unwind-protect
                        (ekko/runtime:install-registry (ekko/runtime:make-daemon)
                                                       (ekko/runtime:extension-worker-registry worker))
                     (ekko/runtime:stop-worker worker))) 0)))
          ((member command '("attach" "status" "inspect" "buffer" "stop") :test #'string=)
           (multiple-value-bind (view force) (target-options args :force (string= command "stop"))
             (if (string= command "attach")
                 (ekko/runtime:attach view)
                 (ekko/runtime:control (if force "stop-force" command) :view-id view))))
          ((string= command "list")
           (when args (error "list takes no arguments"))
           (ekko/runtime:control "list"))
          ((and (string= command "doctor") (equal args '("--restore-terminal"))) (ekko/runtime:restore-terminal))
          (t (error "Unknown command ~A" command))))
    (error (condition)
      (ekko/runtime:note-client-error condition)
      (format *error-output* "ekko: ~A~%" condition)
      (when (ekko/runtime:version-mismatch-p condition)
        (format *error-output* "ekko: the running daemon is an older build; 'ekko stop' ends it (its panes will exit)~%"))
      2)))

(defun main (&optional (arguments (rest sb-ext:*posix-argv*)))
  (handler-case
      (let ((ekko/runtime:*instance* (or (uiop:getenv "EKKO_INSTANCE") "default")))
        (when (equal (first arguments) "--instance")
          (pop arguments)
          (setf ekko/runtime:*instance* (ekko/runtime:checked-name (or (pop arguments) (error "Missing instance name")) "Instance")))
        (cond
          ((null arguments) (usage))
          ((member (first arguments) '("-h" "--help") :test #'equal)
           (when (rest arguments) (error "Unexpected argument ~A" (second arguments))) (usage))
          ((equal (first arguments) "--version")
           (when (rest arguments) (error "Unexpected argument ~A" (second arguments)))
           (format t "~A~%" *version*))
          (t (runtime-command arguments))))
    (error (condition) (format *error-output* "ekko: ~A~%" condition) 2)))

(defun executable-main ()
  ;; An uncaught condition must not land in a Lisp debugger: the daemon's
  ;; stderr is a log file nobody answers, and a client's is a raw terminal.
  ;; Restore the terminal best-effort, record the failure, and exit.
  (setf sb-ext:*invoke-debugger-hook*
        (lambda (condition hook)
          (declare (ignore hook))
          (ignore-errors
            (ekko/runtime:emergency-restore)
            (ekko/runtime:note-client-error condition)
            (format *error-output* "ekko: fatal: ~A~%" condition))
          (sb-ext:exit :code 3 :abort t)))
  (sb-ext:exit :code (or (main) 0)))
