(in-package #:ekko)

(defparameter *version* "0.1.0")
(defun version () *version*)

(defun usage (&optional (stream *standard-output*))
  (format stream "Ekko ~A~%~%Usage: ekko [--instance NAME] run [--session NAME] [--detached] COMMAND [ARGS...] [::: COMMAND ...]~%       ekko attach|status|inspect|buffer [NAME] [--view ID]~%       ekko list~%       ekko stop [--force] [NAME]~%       ekko switch --view ID NAME~%       ekko config check|reload [NAME]~%       ekko command [--session NAME] [--view ID] COMMAND [ARGS...]~%       ekko split [--session NAME] [--view ID] columns|rows [COMMAND ARGS...]~%       ekko rename [--session NAME] [--view ID] LABEL~%       ekko doctor --restore-terminal~%~%One daemon owns all sessions. Clients can attach concurrently.~%Default session: default. EKKO_INSTANCE selects explicit isolation.~%Config: $EKKO_CONFIG or $XDG_CONFIG_HOME/ekko/init.lisp.~%Options: -h, --help; --version.~%" *version*))

(defun pane-commands (args)
  (let ((commands nil) (current nil))
    (dolist (arg args)
      (if (string= arg ":::") (progn (push (nreverse current) commands) (setf current nil))
          (push arg current)))
    (push (nreverse current) commands)
    (unless (and (<= (length commands) 128) (every #'identity commands))
      (error "Provide one to 128 nonempty pane commands"))
    (nreverse commands)))

(defun view-number (value)
  (let ((number (and value (parse-integer value :junk-allowed nil))))
    (unless (and number (<= 1 number #xffffffff)) (error "--view requires a positive view ID"))
    number))

(defun command-options (args &key detached)
  (let ((name "default") (view nil) (background nil))
    (loop while (and args (member (first args) '("--session" "--view" "--detached") :test #'equal)) do
      (let ((option (pop args)))
        (cond ((equal option "--session")
               (setf name (or (pop args) (error "Missing session name"))))
              ((equal option "--view") (setf view (view-number (pop args))))
              (t (unless detached (error "--detached is only valid for run"))
                 (setf background t)))))
    (values args name view background)))

(defun session-options (args &key force require-name)
  (let ((name nil) (view nil) (forced nil))
    (loop while args do
      (let ((arg (pop args)))
        (cond ((equal arg "--view") (setf view (view-number (pop args))))
              ((equal arg "--force") (unless force (error "--force is only valid for stop"))
               (setf forced t))
              ((or name (and (plusp (length arg)) (char= (char arg 0) #\-)))
               (error "Unexpected argument ~A" arg))
              (t (setf name arg)))))
    (when (and require-name (null name)) (error "Missing target session name"))
    (values (or name "default") view forced)))

(defun runtime-command (arguments)
  (handler-case
      (let ((command (first arguments)) (args (rest arguments)))
        (cond
          ((string= command "--extension-worker")
           (when args (error "Unexpected worker argument"))
           (ekko/runtime::extension-worker-main))
          ((string= command "--serve")
           (when args (error "The shared daemon takes no session or command arguments"))
           (ekko/runtime:serve))
          ((member command '("run" "command" "split" "rename") :test #'string=)
           (multiple-value-bind (rest name view detached) (command-options args :detached (string= command "run"))
             (cond
               ((string= command "run")
                (when view (error "run does not select an existing view; use attach"))
                (ekko/runtime:run-session name (pane-commands rest) :detached detached))
               (t
                (when (string= command "split")
                  (unless (member (first rest) '("columns" "rows") :test #'equal) (error "split requires columns or rows"))
                  (setf rest (cons (concatenate 'string "split-" (first rest)) (rest rest))))
                (when (string= command "rename") (setf rest (cons "rename" rest)))
                (unless rest (error "Missing command"))
                (ekko/runtime:control-session name "command" :arguments rest :view-id view)))))
          ((string= command "config")
           (unless (and (member (first args) '("check" "reload") :test #'equal) (<= (length args) 2))
             (error "Usage: ekko config check|reload [NAME]"))
           (if (equal (first args) "reload")
               (ekko/runtime:control-session (or (second args) "default") "reload")
               (progn
                 (when (second args) (error "config check takes no session name"))
                 (ekko/runtime::initialize)
                 (let* ((path (ekko/runtime::config-path))
                        (worker (ekko/runtime::load-worker (ekko/runtime::config-source path) path *error-output*)))
                   (unwind-protect
                        (ekko/runtime::install-registry (ekko/runtime::make-session)
                                                       (ekko/runtime::extension-worker-registry worker))
                     (ekko/runtime::stop-worker worker))) 0)))
          ((member command '("attach" "status" "inspect" "buffer" "stop") :test #'string=)
           (multiple-value-bind (name view force) (session-options args :force (string= command "stop"))
             (if (string= command "attach")
                 (ekko/runtime:attach-session name nil view)
                 (ekko/runtime:control-session name (if force "stop-force" command) :view-id view))))
          ((string= command "list")
           (when args (error "list takes no arguments"))
           (ekko/runtime:control-session nil "list"))
          ((string= command "switch")
           (multiple-value-bind (name view) (session-options args :require-name t)
             (unless view (error "switch requires --view ID"))
             (ekko/runtime:control-session nil "switch" :arguments (list name) :view-id view)))
          ((and (string= command "doctor") (equal args '("--restore-terminal"))) (ekko/runtime:restore-terminal))
          (t (error "Unknown command ~A" command))))
    (error (condition) (format *error-output* "ekko: ~A~%" condition) 2)))

(defun main (&optional (arguments (cdr sb-ext:*posix-argv*)))
  (handler-case
      (let ((ekko/runtime::*instance* (or (uiop:getenv "EKKO_INSTANCE") "default")))
        (when (equal (first arguments) "--instance")
          (pop arguments)
          (setf ekko/runtime::*instance* (ekko/runtime::checked-name (or (pop arguments) (error "Missing instance name")) "Instance")))
        (cond
          ((null arguments) (usage))
          ((member (first arguments) '("-h" "--help") :test #'equal)
           (when (rest arguments) (error "Unexpected argument ~A" (second arguments))) (usage))
          ((equal (first arguments) "--version")
           (when (rest arguments) (error "Unexpected argument ~A" (second arguments)))
           (format t "~A~%" *version*))
          (t (runtime-command arguments))))
    (error (condition) (format *error-output* "ekko: ~A~%" condition) 2)))

(defun executable-main ()
  (sb-ext:exit :code (or (main) 0)))
