(in-package #:ekko/runtime)

(defun option (daemon key &optional default)
  (getf (getf (daemon-registry daemon) :options) key default))
(defun layout-pane-ids (tree)
  "Validate a public layout tree and return its pane leaves."
  (let ((nodes 0))
    (labels ((walk (node)
               ;; Sixteen leaves need at most 31 nodes. Bound traversal before
               ;; descending so an invalid deep tree cannot exhaust the stack.
               (when (> (incf nodes) 255) (error "At most 128 layout leaves are supported"))
               (cond
                 ((and (integerp node) (plusp node)) (list node))
                 ((and (listp node) (= (length node) 4)
                       (member (first node) '(:columns :rows))
                       (typep (second node) '(integer 1 99)))
                  (append (walk (third node)) (walk (fourth node))))
                 (t (error "Invalid layout tree: ~S" tree)))))
      (walk tree))))
(defun validate-layout-tree (daemon tree)
  (let ((ids (layout-pane-ids tree))
        (existing (mapcar #'pane-id (daemon-panes daemon))))
    (unless (and (<= 1 (length ids) (option daemon :pane-budget 16))
                 (= (length ids) (length (remove-duplicates ids)))
                 (equal (sort (copy-list ids) #'<)
                        (sort (copy-list existing) #'<)))
      (error "Layout leaves must name each existing pane exactly once"))
    t))
(defun validate-component-state (value)
  (let ((active (make-hash-table :test #'eq)) (nodes 0) (bytes 0))
    (labels ((walk (x depth)
               (when (> depth 16) (error "Component state is too deep"))
               (when (> (incf nodes) 1024) (error "Component state has too many nodes"))
               (cond
                 ((or (null x) (eq x t) (keywordp x) (integerp x)) nil)
                 ((stringp x) (incf bytes (length (text-bytes x))))
                 ((consp x)
                  (let ((marked nil) (tail x))
                    (loop while (consp tail) do
                      (when (gethash tail active) (error "Cyclic component state"))
                      (setf (gethash tail active) t)
                      (push tail marked)
                      (walk (first tail) (1+ depth))
                      (setf tail (rest tail)))
                    (unless (null tail) (error "Component state needs proper lists"))
                    (dolist (cell marked) (remhash cell active))))
                 (t (error "Invalid component state value")))))
      (walk value 0)
      (when (> bytes 16384) (error "Component state exceeds 16 KiB")))
    t))
(defun component-state-bytes (entries)
  (loop for (owner . value) in entries
        sum (length (text-bytes (prin1-to-string (list owner value))))))
(defun copy-component-state (value)
  (if (consp value)
      (cons (copy-component-state (first value))
            (copy-component-state (rest value)))
      (if (stringp value) (copy-seq value) value)))
(defparameter *store-persist* t
  "NIL while staging a candidate so a rejected reload cannot write durable state.")
(defun store-namespace (owner)
  (unless owner (error "Store actions need a component owner"))
  (ekko/store:store-namespace owner))
(defun store-entries (daemon namespace)
  (rest (assoc namespace (daemon-store-entries daemon) :test #'equal)))
(defun store-set (daemon owner key value)
  "Return namespace and entries for OWNER with KEY set to VALUE, or removed."
  (let* ((namespace (store-namespace owner))
         (entries (remove key (store-entries daemon namespace) :key #'car :test #'equal)))
    (when value (push (cons key (copy-component-state value)) entries))
    (values namespace entries)))
(defun context-data (view &optional (registry (daemon-registry (view-daemon view))))
  "Return detached view state with static options read from REGISTRY."
  (let ((daemon (view-daemon view)) (options (getf registry :options)))
    (labels ((metadata (pane)
               (list :id (pane-id pane) :session *instance*
                     :label (pane-label pane) :name (pane-name pane) :argv (pane-argv pane)
                     :launch-kind (pane-launch-kind pane)
                     :creation-position (pane-creation-position pane)
                     :terminal-title (terminal-title (pane-vt pane))
                     :pid (pane-pid pane) :exit (pane-status pane))))
      (multiple-value-bind (insets pane-insets gaps width height) (workspace-geometry view registry)
        (declare (ignore width height))
        (let ((visible (visible-panes view))
              (tiled (workspace-rectangles view nil (tiled-tree view) registry)))
          ;; Copy at the boundary, including strings inside registry, component
          ;; and store values. No callback receives host-owned conses.
          (copy-component-state
            (list :session *instance*
                  :view (list :id (view-id view) :epoch (view-epoch view))
                  :all-panes (mapcar #'metadata (daemon-panes daemon))
                  :workspace (list :camera (list (view-camera-x view) (view-camera-y view)))
                  :mode (view-mode view) :time (get-universal-time)
                  :focus (view-focus-id view) :zoom (view-zoom view)
                  :viewport (list :cols (view-cols view) :rows (view-rows view)
                                  :cell-width (view-cw view) :cell-height (view-ch view)
                                  :reported-cell-width (view-reported-cw view)
                                  :reported-cell-height (view-reported-ch view)
                                  :insets insets :gaps gaps)
                  :geometry (list :pane-insets pane-insets
                                  :boundary-insets (geometry-value view :boundary-insets nil registry)
                                  :viewport-insets insets :split-gaps gaps)
                  :chrome-status (list :text (status-text view registry)
                                       :style (getf options :status-style '(0 30 47)))
                  :pane-notes (pane-note-data view registry)
                  :component-state (view-component-state view)
                  :store (daemon-store-entries daemon) :layout (daemon-tree daemon)
                  :panes (loop for pane in (view-panes view)
                               for vt = (pane-vt pane)
                               for state = (pane-state view (pane-id pane) nil)
                               collect
                           (append (metadata pane)
                             (list :minimized (pane-view-minimized state)
                                   :floating (pane-floating pane)
                                   :activity (pane-view-unseen-output state)
                                   :activation-order (pane-view-activation-order state)
                                   :layout-rect (rest (assoc (pane-id pane) tiled))
                                   :display-label
                                   (if (pane-view-copy-lines state)
                                       (format nil "~A [copy ~D/~D]" (pane-label pane)
                                               (1+ (pane-view-copy-cursor state))
                                               (length (pane-view-copy-lines state)))
                                       (pane-label pane))
                                   :cols (terminal-cols vt) :rows (terminal-rows vt)
                                   :view-cols (pane-view-cols state) :view-rows (pane-view-rows state)
                                   :pty-size (pane-pty-size pane)
                                   :x (pane-view-x state) :y (pane-view-y state)
                                   :outer-rect (list (pane-view-outer-x state) (pane-view-outer-y state)
                                                     (pane-view-outer-cols state) (pane-view-outer-rows state))
                                   :visible (not (null (find pane visible)))
                                   :history-rows (if (and (terminal-history vt)
                                                          (eq (terminal-screen vt) :main))
                                                     (history-count (terminal-history vt)) 0)))))))))))

(defun declared-context (context reads)
  "Detach CONTEXT to the read keys a callback is allowed to consume."
  (loop for key in reads append (list key (ekko/extensions:copy-data (getf context key)))))
(defun command-reads (registry name)
  (let* ((entry (find name (getf registry :commands)
                      :key (lambda (c) (getf c :name)) :test #'equal))
         (component (and entry (find (getf entry :owner) (getf registry :components)
                                     :key (lambda (c) (getf c :id)) :test #'equal))))
    (and component (getf component :reads))))
(defun layout-context (view)
  "Do not feed committed pane geometry back into its layout provider."
  (let ((context (context-data view)))
    (setf (getf context :panes)
          (loop for pane in (getf context :panes) collect
            (loop for (key value) on pane by #'cddr
                  unless (member key '(:x :y :outer-rect :layout-rect :visible
                                       :cols :rows :pty-size :view-cols :view-rows))
                    append (list key value))))
    context))
(defun validate-registry (registry)
  (unless (and (= (getf registry :api-version 0) 1)
               (<= (length (getf registry :components)) 64)
               (<= (length (getf registry :commands)) 256)
               (<= (length (getf registry :bindings)) 256)
               (<= (length (getf registry :keymaps)) 256))
    (error "Invalid extension registry"))
  (flet ((known (name) (find name (getf registry :keymaps) :key (lambda (m) (getf m :name)))))
    (when (and (getf (getf registry :options) :initial-keymap)
               (not (known (getf (getf registry :options) :initial-keymap))))
      (error "Initial keymap is not registered"))
    (dolist (binding (getf registry :bindings))
      (unless (or (member (getf binding :map) '(:prefix :copy)) (known (getf binding :map)))
        (error "Binding references unknown keymap"))))
  (dolist (binding (getf registry :bindings))
    (unless (or (null (getf binding :command))
                (find (getf binding :command) (getf registry :commands) :key (lambda (c) (getf c :name)) :test #'equal))
      (error "Binding references unknown command: ~A" (getf binding :command))))
  (dolist (keymap (getf registry :keymaps))
    (let ((fallback (getf keymap :unbound)))
      (when (and (stringp fallback)
                 (not (find fallback (getf registry :commands)
                            :key (lambda (c) (getf c :name)) :test #'equal)))
        (error "Keymap fallback references unknown command: ~A" fallback))))
  (validate-layout-registry registry)
  t)
(defun retained-owner-entries (entries registry)
  (remove-if-not (lambda (entry)
                   (find (first entry) (getf registry :components)
                         :key (lambda (component) (getf component :id)) :test #'equal)) entries))
(defun install-registry (daemon registry &optional preserve-quarantine)
  (validate-registry registry)
  (setf (daemon-registry daemon) registry (daemon-config-error daemon) nil)
  (incf (daemon-config-generation daemon))
  (let ((owners (getf registry :components)))
    (flet ((mounted (entry)
             (find (first entry) owners :key (lambda (c) (getf c :id)) :test #'equal)))
      (setf (daemon-hook-failures daemon) (remove-if-not #'mounted (daemon-hook-failures daemon)))
      (dolist (view (remove-if (lambda (view) (and preserve-quarantine (view-quarantined view)))
                                     (daemon-views daemon)))
        (when (equal (view-notice view) (view-error view)) (setf (view-notice view) ""))
        (setf (view-error view) nil (view-quarantined view) nil)
        (unless (find (view-mode view) (getf registry :keymaps) :key (lambda (m) (getf m :name)))
          (setf (view-mode view) (getf (getf registry :options) :initial-keymap)))
        (setf (view-component-state view) (remove-if-not #'mounted (view-component-state view))
              (view-geometry-contributions view) (remove-if-not #'mounted (view-geometry-contributions view))
              (view-contributions view) nil (view-decorations view) nil (view-pane-notes view) nil
              (view-hook-context view) nil (view-hooks view) nil)
        (let* ((panes (view-panes view)) (ids (mapcar #'pane-id panes)))
          (unless (member (view-focus-id view) ids)
            (setf (view-focus-id view) (first ids) (view-zoom view) nil))
          (dolist (id (loop for id being the hash-keys of (view-pane-states view)
                           unless (member id ids) collect id))
            (remhash id (view-pane-states view))))
        (reset-view-input view t)
        (reset-layout-state (view-layout-state view) registry)
        ;; Same-owner reload also reconstructs placement/camera effects.
        (setf (layout-state-requested-context (view-layout-state view)) nil
              (layout-state-requested-token (view-layout-state view)) nil
              (layout-state-committed-context (view-layout-state view)) nil
              (layout-state-committed-token (view-layout-state view)) nil)
        (clear-layout-provider view)
        (layout view))))
  (update-application-focus daemon)
  (incf (daemon-revision daemon)))
(defun command-pending-p (view)
  (let* ((daemon (view-daemon view)) (worker (daemon-worker daemon))
         (request (and worker (extension-worker-request worker))))
    (or (some (lambda (pending) (eq view (command-origin-view (pending-split-origin pending))))
              (daemon-pending-splits daemon))
        (member view (daemon-initialization-queue daemon))
        (and (consp request) (eq (first request) :initialize) (eq (second request) view))
        (and (command-request-p request) (eq (command-origin-view (command-request-origin request)) view))
        (some (lambda (request) (eq (command-origin-view (command-request-origin request)) view))
              (daemon-command-queue daemon))
        (and (daemon-candidate daemon)
             (or (null worker) (daemon-candidate-contexts daemon))))))
(defun defer-input (view kind data)
  (when (> (+ (view-input-bytes view) (length data)) 65536)
    (error "Pending command input exceeds 64 KiB"))
  (push (list (view-wire view) (view-epoch view) kind (copy-seq data)) (view-input-queue view))
  (incf (view-input-bytes view) (length data)))
(defun replay-input (view)
  (let ((pending (nreverse (view-input-queue view))))
    (setf (view-input-queue view) nil (view-input-bytes view) 0)
    (dolist (item pending)
      (destructuring-bind (wire epoch kind data) item
        (when (and wire (eq wire (view-wire view)) (= epoch (view-epoch view)))
          (server-packet view wire
            (concatenate '(vector (unsigned-byte 8)) (octets-from-list (list kind)) data)))))))
(defun replay-all-input (daemon)
  (dolist (view (daemon-views daemon)) (replay-input view)))
(defun semantic-key (bytes key)
  (or (rest (assoc (map 'string #'code-char bytes)
                 (loop for (suffix . value) in '(("[A" . :up) ("[B" . :down) ("[C" . :right) ("[D" . :left)
                                                 ("OA" . :up) ("OB" . :down) ("OC" . :right) ("OD" . :left)
                                                 ("[5~" . :page-up)
                                                 ("[6~" . :page-down) ("[H" . :home) ("[F" . :end))
                       collect (cons (concatenate 'string (string #\Esc) suffix) value)) :test #'equal))
      (rest (assoc key '((57350 . :left) (57351 . :right) (57352 . :up) (57353 . :down) (57354 . :page-up) (57355 . :page-down)
                        (57356 . :home) (57357 . :end)))) key))
(defun key-binding (view map key)
  (find-if (lambda (b) (and (eq map (getf b :map)) (equal key (getf b :key))))
                          (reverse (getf (daemon-registry (view-daemon view)) :bindings))))
(defun binding-key (bytes key modifiers)
  "Lookup key for a keymap binding. Control folds into the code as before; Alt,
Super and Shift stay distinct as (MODS . KEY), with bit 1 for Alt, bit 2 for Super
and bit 4 for Shift. Shift only rides along when ctrl, alt or super is present, so
unmodified chords are unchanged."
  (let ((semantic (semantic-key bytes key))
        (shift (logbitp 0 modifiers)) (alt (logbitp 1 modifiers)) (super (logbitp 3 modifiers)))
    (if (or alt super (and shift (logbitp 2 modifiers)))
        (cons (logior (if alt 1 0) (if super 2 0) (if shift 4 0)) semantic)
        semantic)))
(defun dispatch-binding (view map key)
  (let ((binding (key-binding view map key)))
    (when (and binding (getf binding :command))
      (handler-case (request-command view (getf binding :command)
                                     (list :arguments (getf binding :arguments)) nil)
        (error (e) (note-error view e))))))
(defun dispatch-keymap-fallback (view map key bytes &optional read-bytes)
  "Dispatch a named keymap fallback through the ordinary worker command path."
  (let* ((policy (find map (reverse (getf (daemon-registry (view-daemon view)) :keymaps))
                       :key (lambda (m) (getf m :name))))
         (fallback (and policy (getf policy :unbound))))
    (when (stringp fallback)
      (handler-case
          (request-command view fallback
                           (append (list :key (semantic-key bytes key)
                                         :bytes (coerce bytes 'list))
                                   (when (view-input-read-framed view)
                                     (list :read-bytes (and read-bytes (coerce read-bytes 'list))))) nil)
        (error (e) (note-error view e)))
      t)))
(defun dispatch-command-request (request)
  (let* ((origin (command-request-origin request)) (daemon (command-origin-daemon origin))
         (view (command-origin-view origin)) (worker (daemon-worker daemon)))
    (unless (origin-current-p origin) (error "Command view changed before dispatch"))
    (when (view-quarantined view) (error "View callbacks quarantined until a successful config reload"))
    (origin-target origin)
    (extension-send (extension-worker-output worker)
      (list :dispatch :command (command-request-name request)
            (command-request-snapshot request) (command-request-event request)))
    (setf (view-notice view) "" (extension-worker-request worker) request
          (extension-worker-deadline worker) (+ (now) 1/20))))
(defun request-command (view name event peer)
  (when (view-quarantined view)
    (error "View callbacks quarantined until a successful config reload"))
  (let* ((daemon (view-daemon view)) (worker (daemon-worker daemon))
         (origin (capture-origin view peer))
         (request (make-command-request :origin origin :name name
                                        :event (copy-component-state event)
                                        :snapshot (declared-context (context-data view)
                                                                    (command-reads (daemon-registry daemon) name)))))
    (unless (find name (getf (daemon-registry daemon) :commands)
                  :key (lambda (c) (getf c :name)) :test #'equal)
      (error "Unknown command: ~A" name))
    (unless worker (error "Extension worker is restarting; use config reload if recovery fails"))
    (when (>= (length (daemon-command-queue daemon)) 32) (error "Command queue full"))
    (setf (daemon-command-queue daemon) (append (daemon-command-queue daemon) (list request)))
    (schedule-work daemon)))
(defun command-reply (peer message &optional errorp)
  (when (and peer (>= (wire-fd peer) 0))
    (handler-case
        (progn (send-packet peer (if errorp 21 20) (text-bytes message)) (flush-wire peer))
      (error () (close-wire peer)))))
(defun error-text (error)
  (let ((message (princ-to-string error))) (subseq message 0 (min 1000 (length message)))))
(defun note-error (view error)
  (setf (view-error view) (error-text error)
        (view-notice view) (view-error view))
  (incf (view-revision view))
  (format *error-output* "view ~A: ~A~%" (view-id view) (view-notice view)))
(defun note-workspace-error (daemon error)
  (setf (daemon-config-error daemon) (error-text error))
  (incf (daemon-revision daemon))
  (format *error-output* "configuration ~A: ~A~%" *instance* (daemon-config-error daemon)))
(defun start-reload (daemon peer &optional recover source-worker)
  (when (daemon-candidate daemon) (error "A configuration reload is already running"))
  (when recover
    (unless source-worker (setf (daemon-recovery-budget daemon) (1+ (length (daemon-views daemon)))))
    (when (minusp (decf (daemon-recovery-budget daemon)))
      (error "Recovery budget exhausted; reload configuration explicitly")))
  (let* ((active (or source-worker (daemon-worker daemon)))
         (path (or (daemon-config-path daemon) (and active (extension-worker-path active))
                   (namestring (merge-pathnames "__ekko-empty-init__.lisp"
                                 (uiop:ensure-directory-pathname (or (daemon-launch-directory daemon) "."))))))
         (source (if (and recover active) (extension-worker-source active)
                     (config-file-source (daemon-config-path daemon)))))
    (setf (daemon-candidate daemon)
          (start-worker source path (format nil "~A.extensions.log" (socket-path))
                        :directory (daemon-launch-directory daemon)
                        :environment (daemon-launch-environment daemon))
          (daemon-reload-peer daemon) peer
          (daemon-candidate-views daemon) nil (daemon-candidate-results daemon) nil
          (daemon-candidate-contexts daemon) nil (daemon-candidate-layouts daemon) nil
          (daemon-candidate-stage daemon) :load (daemon-candidate-members daemon) nil)
    (setf (extension-worker-recovery (daemon-candidate daemon)) recover)))
(defun hook-context-current-p (view request)
  (let* ((daemon (view-daemon view))
         (component (find (hook-request-owner request) (getf (daemon-registry daemon) :components)
                          :key (lambda (c) (getf c :id)) :test #'equal))
         (current (context-data view)))
    (and (origin-current-p (hook-request-origin request)) component
         (every (lambda (key) (equal (getf (hook-request-snapshot request) key) (getf current key)))
                (getf component :reads)))))
(defun initialization-components (registry)
  (remove-if-not (lambda (c) (getf c :initialize)) (getf registry :components)))
(defun initialization-context (view registry)
  (let ((context (context-data view registry)))
    (unless (find (getf context :mode) (getf registry :keymaps) :key (lambda (m) (getf m :name)))
      (setf (getf context :mode) (getf (getf registry :options) :initial-keymap)))
    (unless (find (getf context :focus) (getf context :panes) :key (lambda (pane) (getf pane :id)))
      (setf (getf context :focus) (getf (first (getf context :panes)) :id)
            (getf context :zoom) nil))
    (setf (getf context :component-state)
          (remove-if-not (lambda (entry)
                           (find (first entry) (getf registry :components)
                                 :key (lambda (c) (getf c :id)) :test #'equal))
                         (getf context :component-state)))
    context))
(defun initialization-current-p (view worker &optional before)
  (let* ((registry (extension-worker-registry worker))
         (before (or before (extension-worker-initialization-context worker)))
         (current (initialization-context view registry))
         (reads (append '(:component-state :mode)
                        (loop for c in (initialization-components registry) append (getf c :reads)))))
    (every (lambda (key) (equal (getf before key) (getf current key))) reads)))
(defun begin-initialization (view worker reason)
  (let* ((registry (extension-worker-registry worker))
         ;; Keep the implicit staleness keys even when no initializer reads them.
         (context (declared-context
                    (initialization-context view registry)
                    (append '(:component-state :mode)
                            (loop for c in (initialization-components registry)
                                  append (getf c :reads))))))
    (setf (extension-worker-initialization-context worker) context
          (extension-worker-request worker) (list :initialize view context (capture-origin view))
          (extension-worker-deadline worker) (+ (now) 1/20))
    (extension-send (extension-worker-output worker)
                    (list :initialize context (list :type :initialize :reason reason)))))
(defun stage-initialization (view registry results)
  (unless (equal (mapcar (lambda (entry) (getf entry :owner)) results)
                 (mapcar (lambda (c) (getf c :id)) (initialization-components registry)))
    (error "Invalid initialization owners"))
  ;; Validation is pure. No shallow daemon/view copy can accidentally expose
  ;; shared pane mutations or durable writes during a rejected reload.
  (let ((state (copy-component-state (retained-owner-entries (view-component-state view) registry))))
    (dolist (result results)
      (let ((actions (getf result :actions)) (owner (getf result :owner)))
        (dolist (action actions)
          (unless (member (first action) '(:set-state :store-set :set-keymap :status :decorate))
            (error "Initialization may only set state, store, keymap, status or decorations")))
        (validate-actions view actions nil owner registry t)
        (let ((action (find :set-state actions :key #'first)))
          (when action
            (setf state (remove owner state :key #'car :test #'equal))
            (when (getf (rest action) :value)
              (push (cons owner (getf (rest action) :value)) state)))))
      ;; Commit validates each owner's replacement against earlier results,
      ;; not only the final state after later owners remove their entries.
      (when (> (component-state-bytes state) 16384) (error "Aggregate component state exceeds 16 KiB"))))
  (stage-store-actions (daemon-store-entries (view-daemon view)) results)
  (let ((spans (loop for result in results append
                (copy-list (getf (rest (find :decorate (getf result :actions) :key #'first :from-end t)) :spans)))))
    (when (> (length spans) 1024) (error "At most 1024 retained decoration spans are allowed"))
    (when (> (loop for span in spans sum (* (getf span :rows 1) (length (getf span :text)))) 16000)
      (error "Retained decoration text exceeds 16000 characters")))
  results)
(defun apply-initialization (view results)
  (dolist (result results)
    (apply-actions view (getf result :owner) (getf result :actions) nil nil))
  (setf (view-extension-initialized view) t (view-initialization-failure view) nil
        (daemon-initialization-queue (view-daemon view))
        (remove view (daemon-initialization-queue (view-daemon view)))))
(defun request-view (request)
  (typecase request
    (command-request (command-origin-view (command-request-origin request)))
    (hook-request (command-origin-view (hook-request-origin request)))
    (layout-request (first (layout-request-token request)))
    (cons (when (eq (first request) :initialize) (second request)))))
(defun layout-token (view)
  (list view (view-epoch view) (daemon-config-generation (view-daemon view))))
(defun fail-command (request error)
  (let* ((origin (command-request-origin request)) (view (command-origin-view origin)))
    (when (origin-current-p origin) (note-error view error))
    (command-reply (command-origin-peer origin) (princ-to-string error) t)))
(defun stage-store-actions (store results)
  "Validate aggregate writes against a detached store in commit order."
  (let ((store (copy-component-state store)))
    (dolist (result results store)
      (dolist (action (getf result :actions))
        (when (eq (first action) :store-set)
          (let* ((args (rest action)) (namespace (store-namespace (getf result :owner)))
                 (entries (remove (getf args :key) (rest (assoc namespace store :test #'equal))
                                  :key #'car :test #'equal)))
            (when (getf args :value)
              (push (cons (getf args :key) (copy-component-state (getf args :value))) entries))
            (when (> (component-state-bytes (list (cons namespace entries))) 16384)
              (error "Store namespace exceeds 16 KiB"))
            (setf store (acons namespace entries (remove namespace store :key #'car :test #'equal)))))))))
(defun candidate-view-context (view registry results)
  "Apply allowed initializer outputs only to a detached candidate snapshot."
  (let ((context (initialization-context view registry)) (contributions nil))
    (dolist (result results)
      (let ((owner (getf result :owner)))
        (dolist (action (getf result :actions))
          (let ((args (rest action)))
            (case (first action)
              (:set-state
               (setf (getf context :component-state)
                     (remove owner (getf context :component-state) :key #'car :test #'equal))
               (when (getf args :value)
                 (push (cons owner (copy-component-state (getf args :value))) (getf context :component-state))))
              (:set-keymap (setf (getf context :mode) (getf args :name)))
              (:status (setf contributions (acons owner (getf args :text)
                                                  (remove owner contributions :key #'car :test #'equal)))))))))
    (setf (getf context :store)
          (stage-store-actions (getf context :store)
            (loop for entry in (daemon-candidate-results (view-daemon view)) append (rest entry)))
          (getf context :pane-notes) nil
          (getf (getf context :chrome-status) :text) (status-text view registry contributions))
    context))
(define-condition candidate-stale (simple-error) ())
(defun check-candidate-members (daemon)
  (when (set-exclusive-or (daemon-candidate-members daemon) (daemon-views daemon) :test #'eq)
    (error 'candidate-stale :format-control "View membership changed; retry configuration reload")))
(defun candidate-participants (daemon candidate)
  (remove-if (lambda (view) (and (extension-worker-recovery candidate) (view-quarantined view)))
             (daemon-candidate-members daemon)))
(defun quarantine-view (view error)
  "An unchanged view callback cannot repeatedly kill its peers' shared worker."
  (let* ((daemon (view-daemon view))
         (message (format nil "~A; view callbacks quarantined until a successful config reload" (error-text error))))
    (setf (view-quarantined view) t (view-hooks view) nil
          (daemon-initialization-queue daemon) (remove view (daemon-initialization-queue daemon)))
    (reset-view-input view)
    (dolist (request (daemon-command-queue daemon))
      (when (eq view (command-origin-view (command-request-origin request))) (fail-command request message)))
    (setf (daemon-command-queue daemon)
          (remove-if (lambda (request) (eq view (command-origin-view (command-request-origin request))))
                     (daemon-command-queue daemon)))
    (note-error view message)))
(defun reject-candidate (daemon candidate error)
  (note-workspace-error daemon error)
  (command-reply (daemon-reload-peer daemon) (princ-to-string error) t)
  (stop-worker candidate)
  (setf (daemon-candidate daemon) nil (daemon-reload-peer daemon) nil
        (daemon-candidate-views daemon) nil (daemon-candidate-results daemon) nil
        (daemon-candidate-contexts daemon) nil (daemon-candidate-layouts daemon) nil
        (daemon-candidate-stage daemon) nil (daemon-candidate-members daemon) nil))
(defun commit-candidate (daemon candidate)
  (check-candidate-members daemon)
  (let ((registry (extension-worker-registry candidate)))
    (stage-store-actions (daemon-store-entries daemon)
      (loop for entry in (daemon-candidate-results daemon) append (rest entry)))
    (dolist (entry (daemon-candidate-contexts daemon))
      (unless (and (origin-current-p (third entry))
                   (initialization-current-p (first entry) candidate (second entry)))
        (error 'candidate-stale :format-control "Initialization dependencies changed; retry configuration reload")))
    (dolist (entry (daemon-candidate-layouts daemon))
      (destructuring-bind (view state request) entry
        (declare (ignore state))
        (when request
          (unless (layout-request-current-p request registry
                    (candidate-view-context view registry (rest (assoc view (daemon-candidate-results daemon))))
                    (layout-token view))
            (error 'candidate-stale :format-control "Layout dependencies changed; retry configuration reload")))))
    ;; Every candidate callback has passed before registrations or live output
    ;; change. Application content is outside this reconstruction boundary.
    (stop-worker (daemon-worker daemon))
    (setf (daemon-worker daemon) candidate (daemon-candidate daemon) nil)
    (install-registry daemon registry (extension-worker-recovery candidate))
    (dolist (entry (daemon-candidate-results daemon)) (apply-initialization (first entry) (rest entry)))
    (dolist (entry (daemon-candidate-layouts daemon))
      (destructuring-bind (view state request) entry
        (when request
          (setf (view-layout-state view) state
                (layout-state-requested-token state) (layout-token view)
                (layout-state-committed-token state) (layout-token view))
          (apply-actions view (layout-state-owner state)
                         (list (list :place-panes :version 1 :placements (layout-state-placements state)
                                     :camera (layout-state-camera state))) :layout nil))))
    (setf (daemon-candidate-results daemon) nil (daemon-candidate-contexts daemon) nil
          (daemon-candidate-layouts daemon) nil (daemon-candidate-stage daemon) nil
          (daemon-candidate-members daemon) nil
          (extension-worker-initialization-context candidate) nil)
    (unless (extension-worker-recovery candidate)
      (setf (daemon-disabled-hooks daemon) nil (daemon-hook-failures daemon) nil))
    (command-reply (daemon-reload-peer daemon) "")
    (setf (daemon-reload-peer daemon) nil)
    (replay-all-input daemon)))
(defun service-candidate (daemon buffer)
  (let ((candidate (daemon-candidate daemon)) (failed-request nil) (callback-failed nil))
    (when candidate
      (handler-case
          (progn
            (unless (eq (daemon-candidate-stage daemon) :load) (check-candidate-members daemon))
            (when (extension-worker-request candidate)
              (let* ((request (extension-worker-request candidate))
                     (response (progn
                                 (setf failed-request request)
                                 (handler-case (poll-worker candidate buffer)
                                   (error (e) (setf callback-failed t) (error e))))))
                (when response
                  (when (eq (first response) :error)
                    (setf callback-failed t) (error "~A" (second response)))
                  (setf (extension-worker-request candidate) nil)
                  (cond
                    ((eq request :load)
                     (unless (eq (first response) :ready) (error "Invalid extension load reply"))
                     (validate-registry (second response))
                     ;; Quarantined views keep their last valid owner output.
                     ;; Do not reuse it with silently changed registrations.
                     (when (and (extension-worker-recovery candidate)
                                (some #'view-quarantined (daemon-views daemon))
                                (not (equal (second response) (daemon-registry daemon))))
                       (error "Recovery registry changed; reload configuration explicitly"))
                     (setf (extension-worker-registry candidate) (second response)
                           (daemon-candidate-stage daemon) :initialize
                           (daemon-candidate-members daemon) (copy-list (daemon-views daemon))
                           (daemon-candidate-views daemon) (candidate-participants daemon candidate)))
                    ((layout-request-p request)
                     (let* ((view (first (layout-request-token request)))
                            (entry (assoc view (daemon-candidate-layouts daemon)))
                            (registry (extension-worker-registry candidate))
                            (context (candidate-view-context view registry (rest (assoc view (daemon-candidate-results daemon))))))
                       (unless (eq :committed (complete-layout (second entry) request registry context (layout-token view) response))
                         (error 'candidate-stale :format-control "Layout dependencies changed; retry configuration reload"))))
                    (t
                     (let ((view (second request)))
                       (unless (and (origin-current-p (fourth request))
                                    (initialization-current-p view candidate (third request)))
                         (error 'candidate-stale :format-control "Initialization dependencies changed; retry configuration reload"))
                       (unless (eq (first response) :initialized) (error "Invalid initialization reply"))
                       (stage-initialization view (extension-worker-registry candidate) (second response))
                       (push (cons view (second response)) (daemon-candidate-results daemon))
                       (push (list view (third request) (fourth request)) (daemon-candidate-contexts daemon))))))))
            (when (and (null (extension-worker-request candidate))
                       (or (null (daemon-worker daemon)) (null (extension-worker-request (daemon-worker daemon)))))
              (check-candidate-members daemon)
              (when (and (eq (daemon-candidate-stage daemon) :initialize) (null (daemon-candidate-views daemon)))
                (setf (daemon-candidate-stage daemon) :layout
                      (daemon-candidate-views daemon) (candidate-participants daemon candidate)))
              (case (daemon-candidate-stage daemon)
                (:initialize
                 (begin-initialization (pop (daemon-candidate-views daemon)) candidate
                                       (if (extension-worker-recovery candidate) :recovery :reload)))
                (:layout
                 (if (daemon-candidate-views daemon)
                     (let* ((view (pop (daemon-candidate-views daemon))) (state (make-layout-state))
                            (registry (extension-worker-registry candidate))
                            (context (candidate-view-context view registry (rest (assoc view (daemon-candidate-results daemon)))))
                            (request (schedule-layout candidate state registry context (layout-token view))))
                       (push (list view state request) (daemon-candidate-layouts daemon)))
                     (commit-candidate daemon candidate))))))
        (error (e)
          (let* ((view (and failed-request (request-view failed-request)))
                 (retry (and (extension-worker-recovery candidate)
                             (or (typep e 'candidate-stale)
                                 (and callback-failed view
                                      (or (layout-request-p failed-request)
                                          (and (consp failed-request) (eq (first failed-request) :initialize))))))))
            (when (and retry callback-failed view) (quarantine-view view e))
            (reject-candidate daemon candidate e)
            (when retry
              (handler-case (start-reload daemon nil t candidate)
                (error (recovery-error) (note-workspace-error daemon recovery-error))))
            (when (and (null (daemon-worker daemon)) (null (daemon-candidate daemon)))
              (dolist (request (daemon-command-queue daemon)) (fail-command request e))
              (setf (daemon-command-queue daemon) nil))
            (replay-all-input daemon)))))))

(defun service-extensions (daemon buffer)
  (service-candidate daemon buffer)
  (let ((worker (daemon-worker daemon)))
    (when worker
      (handler-case
          (let ((response (poll-worker worker buffer)) (request (extension-worker-request worker)))
            (when response
              (setf (extension-worker-request worker) nil)
              (handler-case
                  (let ((view (request-view request)))
                    (when (eq (first response) :error) (error "~A" (second response)))
                    (cond
                      ((layout-request-p request)
                       (when (eq :committed (complete-layout (view-layout-state view) request
                                              (daemon-registry daemon) (context-data view)
                                              (layout-token view) response))
                         (apply-actions view (layout-request-owner request)
                                        (getf (second response) :actions) :layout nil)))
                      ((and (consp request) (eq (first request) :initialize))
                       (unless (and (origin-current-p (fourth request))
                                    (initialization-current-p view worker (third request)))
                         (error "View changed during initialization"))
                       (unless (eq (first response) :initialized) (error "Invalid initialization reply"))
                       (stage-initialization view (daemon-registry daemon) (second response))
                       (apply-initialization view (second response))
                       (setf (extension-worker-initialization-context worker) nil))
                      (t
                       (unless (eq (first response) :result) (error "Invalid extension result"))
                       (cond
                         ((command-request-p request)
                          (let ((origin (command-request-origin request)))
                            (unless (origin-current-p origin) (error "Command view changed before completion"))
                            (let ((result (apply-actions view (getf (second response) :owner)
                                                         (getf (second response) :actions) nil origin)))
                              (unless (or (eq result :pending)
                                          (eq (command-origin-peer origin) (daemon-reload-peer daemon)))
                                (command-reply (command-origin-peer origin) "")))))
                         ((hook-request-p request)
                          (note-hook-answered daemon (hook-request-owner request))
                          (when (hook-context-current-p view request)
                            (apply-actions view (getf (second response) :owner) (getf (second response) :actions)
                                           t (hook-request-origin request))))))))
                (error (e)
                  (if (command-request-p request) (fail-command request e)
                      (progn
                        (when (layout-request-p request)
                          (fail-layout (view-layout-state (request-view request)) request e))
                        (when (and (consp request) (eq (first request) :initialize))
                          (setf (view-initialization-failure (request-view request))
                                (list (fourth request) (third request))))
                        (when (request-view request) (note-error (request-view request) e))))))
              ;; Hand a newly free active-worker slot to a loaded candidate
              ;; before input replay can queue another continuously eligible hook.
              (service-candidate daemon buffer)
              (replay-all-input daemon)))
        (error (e)
          (let* ((request (extension-worker-request worker)) (view (request-view request))
                 (view-callback (and view (or (layout-request-p request)
                                              (and (consp request) (eq (first request) :initialize))))))
            (if view-callback (quarantine-view view e) (note-workspace-error daemon e))
            (when (command-request-p request) (fail-command request e))
            (when (hook-request-p request) (note-hook-timeout daemon (hook-request-owner request)))
            (when (layout-request-p request)
              (fail-layout (view-layout-state view) request e))
            ;; A failed active worker cannot be the fallback for a rejected
            ;; user candidate. Reject that transaction, then recover its last
            ;; accepted source rather than the newly edited file.
            (when (daemon-candidate daemon)
              (reject-candidate daemon (daemon-candidate daemon)
                                "Active callback failed during reload; retry configuration reload"))
            (handler-case (start-reload daemon nil t)
              (error (recovery-error) (note-workspace-error daemon recovery-error)))
            (stop-worker worker) (setf (daemon-worker daemon) nil))))))
  (complete-pending-splits daemon)
  (schedule-hooks daemon)
  ;; A view without initializers can become ready without another response.
  ;; Replay after scheduling, not inside it, so enqueueing input cannot recurse
  ;; through synchronous initialization. The saved wire/epoch keeps framing.
  (dolist (view (daemon-views daemon))
    (when (and (view-input-queue view) (not (command-pending-p view)))
      (handler-case (replay-input view)
        (error (e) (note-error view e))))))
(defconstant +hook-deadline+ 1/2)
(defconstant +hook-timeout-limit+ 3)
(defun note-hook-timeout (daemon owner)
  (let ((entry (assoc owner (daemon-hook-failures daemon) :test #'equal)))
    (if entry (incf (rest entry)) (push (cons owner 1) (daemon-hook-failures daemon)))
    (when (>= (rest (assoc owner (daemon-hook-failures daemon) :test #'equal)) +hook-timeout-limit+)
      (pushnew owner (daemon-disabled-hooks daemon) :test #'equal)
      (dolist (view (daemon-views daemon))
        (setf (view-hooks view) (remove owner (view-hooks view) :test #'equal))))))
(defun note-hook-answered (daemon owner)
  (setf (daemon-hook-failures daemon) (remove owner (daemon-hook-failures daemon) :key #'car :test #'equal)))
(defun views-after (views previous)
  (let ((tail (member previous views)))
    (if tail (append (rest tail) (ldiff views (rest tail))) views)))
(defun schedule-view-work (daemon worker kind)
  (let ((registry (daemon-registry daemon)))
    (dolist (view (views-after (daemon-views daemon)
                              (rest (assoc kind (daemon-dispatch-cursors daemon)))))
      (when (and (not (view-quarantined view))
                 (case kind
                   (:initialize (member view (daemon-initialization-queue daemon)))
                   (:layout (view-extension-initialized view))
                   (:hook (and (view-extension-initialized view) (view-hooks view)))))
        (let ((layoutp (member kind '(:initialize :layout)))
              (id (when (eq kind :hook) (pop (view-hooks view)))))
          (handler-case
              (let ((context (context-data view)) (state (view-layout-state view))
                    (token (layout-token view)))
                (case kind
                  (:initialize
                   ;; Retry a failed initializer only after its declared reads
                   ;; or origin changes, not because unrelated time advanced.
                   (let ((failure (view-initialization-failure view)))
                     (unless (and failure (origin-current-p (first failure))
                                  (initialization-current-p view worker (second failure)))
                       ;; Failed geometry blocks only this view's initializer.
                       (if (layout-state-current-p state registry context token)
                           (progn
                             (setf layoutp nil)
                             (if (initialization-components registry)
                                 (begin-initialization view worker :attach)
                                 (apply-initialization view nil)))
                           (schedule-layout worker state registry context token)))))
                  (:layout (schedule-layout worker state registry context token))
                  (:hook
                   (let* ((snapshot (declared-context
                                      context
                                      (getf (find id (getf registry :components)
                                                  :key (lambda (c) (getf c :id)) :test #'equal)
                                            :reads)))
                          (request (make-hook-request :origin (capture-origin view)
                                                      :owner id :snapshot snapshot)))
                     (extension-send (extension-worker-output worker)
                                     (list :dispatch :hook id snapshot (list :type :change)))
                     (setf (extension-worker-request worker) request
                           (extension-worker-deadline worker) (+ (now) +hook-deadline+))))))
            (error (e)
              (when layoutp (setf (layout-state-error (view-layout-state view)) (error-text e)))
              ;; BEGIN-INITIALIZATION installs its request before sending it.
              ;; Failed sends cannot leave that view owning the shared worker.
              (when (eq kind :initialize)
                (let ((request (extension-worker-request worker)))
                  (when (and (not layoutp) request)
                    ;; Retain the exact origin and detached pre-send snapshot
                    ;; already captured by BEGIN-INITIALIZATION.
                    (setf (view-initialization-failure view)
                          (list (fourth request) (third request)))))
                (setf (extension-worker-request worker) nil
                      (extension-worker-initialization-context worker) nil))
              (note-error view e)))
          (when (extension-worker-request worker)
            (let ((cursor (assoc kind (daemon-dispatch-cursors daemon))))
              (if cursor (setf (rest cursor) view)
                  (push (cons kind view) (daemon-dispatch-cursors daemon))))
            (return (extension-worker-request worker))))))))
(defun schedule-work (daemon)
  (let ((worker (daemon-worker daemon)))
    (when (and worker (null (extension-worker-request worker)))
      ;; At most four kinds and one pass over each view; never drain a busy
      ;; client's work before checking its peers. Only one callback is queued.
      (loop for offset below 4
            for turn = (mod (+ (daemon-work-turn daemon) offset) 4)
            for kind = (nth turn '(:initialize :command :layout :hook)) do
        (if (eq kind :command)
            (let ((request
                    (find-if (lambda (request)
                               (let ((origin (command-request-origin request)))
                                 (or (not (origin-current-p origin))
                                     (not (member (command-origin-view origin)
                                                  (daemon-initialization-queue daemon))))))
                             (daemon-command-queue daemon))))
              (when request
                (setf (daemon-command-queue daemon) (remove request (daemon-command-queue daemon) :count 1))
                (let ((origin (command-request-origin request)))
                  (handler-case (dispatch-command-request request)
                    (error (e)
                      (fail-command request e)
                      (when (origin-current-p origin)
                        (handler-case (replay-input (command-origin-view origin))
                          (error (input-error) (note-error (command-origin-view origin) input-error)))))))))
            (schedule-view-work daemon worker kind))
        (when (extension-worker-request worker)
          (setf (daemon-work-turn daemon) (mod (1+ turn) 4))
          (return (extension-worker-request worker)))))))
(defun schedule-hooks (daemon)
  ;; Collect detached snapshots even while another callback owns the worker.
  ;; Pending owners remain FIFO when dependencies change again before dispatch.
  (dolist (view (daemon-views daemon))
    (when (and (view-extension-initialized view) (not (view-quarantined view)))
      (handler-case
          (let ((context (context-data view)) (previous (view-hook-context view)))
            (unless (equal context previous)
              (let ((changed (loop for key in ekko/extensions:*context-keys*
                                   unless (and previous (equal (getf context key) (getf previous key))) collect key)))
                (dolist (component (getf (daemon-registry daemon) :components))
                  (let ((id (getf component :id)))
                    (when (and (getf component :hook)
                               (not (member id (daemon-disabled-hooks daemon) :test #'equal))
                               (or (null previous) (intersection changed (getf component :reads)))
                               (not (member id (view-hooks view) :test #'equal)))
                      (setf (view-hooks view) (append (view-hooks view) (list id)))))))
              (setf (view-hook-context view) context)))
        (error (e) (note-error view e)))))
  (schedule-work daemon))

(defun valid-decoration-text-p (text)
  (and (stringp text)
       (every (lambda (char)
                (let ((code (char-code char)))
                  (and (>= code 32) (/= code 127) (not (<= #x80 code #x9f))))) text)))
(defun validate-decoration-spans (spans &optional menu-p)
  (unless (and (listp spans) (<= (length spans) 1024))
    (error "At most 1024 decoration spans are allowed"))
  (let ((total 0))
    (dolist (span spans)
      (unless (and (listp span) (evenp (length span))) (error "Malformed decoration span: ~S" span))
      (let ((keys nil))
        (loop for (key value) on span by #'cddr do
          (unless (member key '(:x :y :text :sgr :rows :overlay :action :context-command :command :arguments :hover-sgr :wheel-command :middle-command :pane :drag)) (error "Unknown decoration field: ~S" key))
          (when (member key keys) (error "Duplicate decoration field: ~S" key))
          (push key keys))
        (let ((x (getf span :x)) (y (getf span :y)) (text (getf span :text))
              (sgr (getf span :sgr)) (rows (getf span :rows 1)))
          (unless (and (integerp x) (<= 0 x 499) (integerp y) (<= 0 y 299)
                       (member (getf span :overlay) '(nil t))
                       (integerp rows) (<= 1 rows 300)
                       (valid-decoration-text-p text)
                       (listp sgr) (<= (length sgr) 16)
                       (every (lambda (n) (and (integerp n) (<= 0 n 255))) sgr))
            (error "Invalid decoration span: ~S" span))
          (when (or (getf span :pane) (getf span :drag))
            (unless (and (not menu-p) (typep (getf span :pane) '(integer 1 *))
                         (member (getf span :drag) '(nil :move :left :right :top :bottom :top-left :top-right :bottom-left :bottom-right)))
              (error "Invalid window handle")))
          (let ((action (getf span :action)) (command (getf span :command))
                (context (getf span :context-command)) (hover (getf span :hover-sgr))
                (wheel (getf span :wheel-command)) (middle (getf span :middle-command)))
            (when action
              (unless (or (and (listp action) (= (length action) 3)
                               (member (first action) '(:focus :minimize :restore :zoom :close :float :tile))
                               (eq (second action) :pane) (typep (third action) '(integer 1 *)))
                          (and (listp action) (= (length action) 5) (eq (first action) :split)
                               (eq (second action) :pane) (typep (third action) '(integer 1 *))
                               (eq (fourth action) :axis) (member (fifth action) '(:rows :columns))))
                (error "Invalid decoration action: ~S" action)))
            (when (or command context wheel middle)
              (unless (and (or (not command) (and (not action) (stringp command) (<= 1 (length command) 80)))
                           (or (not context) (and (not menu-p) (stringp context) (<= 1 (length context) 80)))
                           (or (not wheel) (and (stringp wheel) (<= 1 (length wheel) 80)))
                           (or (not middle) (and (stringp middle) (<= 1 (length middle) 80)))
                           (listp (getf span :arguments)) (<= (length (getf span :arguments)) 8)
                           (every (lambda (arg) (and (stringp arg) (<= (length arg) 512)))
                                  (getf span :arguments)))
                (error "Invalid decoration command")))
            (when hover
              (unless (and (listp hover) (<= (length hover) 16)
                           (every (lambda (n) (typep n '(integer 0 255))) hover))
                (error "Invalid hover style")))
            )
          (incf total (* rows (length text))))))
    (when (> total 16000) (error "Decoration text exceeds 16000 characters")))
  t)
(defun bounded-geometry-p (value length)
  (and (listp value) (= (length value) length)
       (every (lambda (n) (and (integerp n) (<= 0 n 16))) value)))
(defun validate-geometry-value (value)
  (unless (or (null value) (and (listp value) (evenp (length value))
                                (<= (length value) 8)))
    (error "Geometry value must be a proper property list"))
  (loop with seen = nil
        for (key item) on value by #'cddr do
    (unless (member key '(:pane-insets :boundary-insets :viewport-insets :split-gaps))
      (error "Unknown geometry field: ~S" key))
    (when (member key seen)
      (error "Duplicate geometry field: ~S" key))
    (push key seen)
    (unless (or (and (member key '(:pane-insets :boundary-insets :viewport-insets))
                     (bounded-geometry-p item 4))
                (and (eq key :split-gaps) (bounded-geometry-p item 2)))
      (error "Invalid geometry field: ~S" key)))
  (copy-tree value))
(defun validate-actions (view actions hook &optional owner
                              (registry (daemon-registry (view-daemon view))) staging)
  (when (eq hook :layout)
    (validate-layout-actions actions (getf (context-data view) :panes))
    (return-from validate-actions t))
  (unless (and (listp actions) (<= (length actions) 32)) (error "At most 32 actions are allowed"))
  (let ((primary-count 0) (mode-count 0) (state-count 0) (mode-before-primary nil) (primary-seen nil))
    (dolist (a actions)
      (unless (and (listp a) (oddp (length a))) (error "Malformed action: ~S" a))
      (let* ((op (first a)) (args (rest a)) (pane (getf args :pane))
             (keys (case op
                     (:pane-note '(:pane :text :sgr :duration))
                     (:send-input '(:pane :bytes)) (:set-keymap '(:name)) (:set-layout '(:tree)) (:set-state '(:value)) (:store-set '(:key :value)) (:set-geometry '(:value)) (:decorate '(:spans)) (:show-menu '(:spans :x :y)) (:split '(:pane :axis :argv)) (:focus '(:pane)) (:rename '(:pane :text)) (:resize '(:pane :delta))
                     (:stop '(:force))
                     (:copy-point '(:pane :x :y :start)) (:copy-scroll '(:pane :delta))
                     (:close '(:pane :focus :force)) ((:minimize :restore :zoom :tile) '(:pane)) (:float '(:pane :rect)) (:place-window '(:pane :target :edge)) (:copy-move '(:pane :delta)) (:copy-edge '(:pane :edge)) (:status '(:text))
                     (:copy-selection '(:pane))
                     ((:focus-next :swap :copy-mode :copy-mark
                       :copy-exit :copy-search :copy-search-next :paste-buffer :help) '(:pane))
                     ((:detach :reload) nil)
                     (otherwise (error "Unknown action: ~S" op)))))
        (loop for (key value) on args by #'cddr do (unless (member key keys) (error "Unknown action argument: ~S" key)))
        (unless (= (length (loop for (key value) on args by #'cddr collect key))
                   (length (remove-duplicates (loop for (key value) on args by #'cddr collect key))))
          (error "Duplicate action argument"))
        (when (and hook (not (member op '(:status :decorate))))
          (error "Change hooks may only contribute status or decorations"))
        (when (and pane (not (member pane (view-panes view) :key #'pane-id)))
          (error "Pane is outside this view's workspace: ~S" pane))
        (when (and (member :force args) (not (member (getf args :force) '(nil t))))
          (error "Force must be a boolean"))
        (case op
          (:set-keymap
           (incf mode-count)
           (when (> mode-count 1) (error "A batch may contain at most one keymap transition"))
           (unless primary-seen (setf mode-before-primary t))
           (unless (find (getf args :name) (getf registry :keymaps)
                         :key (lambda (m) (getf m :name)))
             (error "Unknown keymap")))
          ((:status :decorate :show-menu :pane-note :set-state :store-set)
           (when (member op '(:set-state :store-set))
             (incf state-count)
             (when (> state-count 1) (error "A batch may contain at most one state update"))
             (unless (find owner (getf registry :components)
                           :key (lambda (component) (getf component :id)) :test #'equal)
               (error "State needs a registered component owner")))
           (cond
             ((eq op :set-state) (validate-component-state (getf args :value)))
             ((eq op :store-set)
              (let ((key (getf args :key)))
                (unless (or (and (stringp key) (<= 1 (length key) 128))
                            (and (keywordp key) (<= (length (symbol-name key)) 128)))
                  (error "Invalid store key")))
              (validate-component-state (getf args :value))
              (multiple-value-bind (namespace entries)
                  (store-set (view-daemon view) owner (getf args :key) (getf args :value))
                (when (> (component-state-bytes (list (cons namespace entries))) 16384)
                  (error "Store namespace exceeds 16 KiB"))))))
          (:set-geometry
           (incf primary-count) (setf primary-seen t)
           (unless (find owner (getf registry :components)
                         :key (lambda (component) (getf component :id)) :test #'equal)
             (error "Geometry needs a registered component owner"))
           (validate-geometry-value (getf args :value)))
          (otherwise (incf primary-count) (setf primary-seen t)))
        (case op
          ((:float :tile :place-window)
           (when (and (eq op :float) (getf args :rect)
                      (not (and (listp (getf args :rect)) (= (length (getf args :rect)) 4)
                                (every (lambda (n) (typep n '(integer 0 500))) (getf args :rect)))))
             (error "Invalid window rectangle"))
           (when (eq op :place-window)
             (let ((target (pane-by-id (view-daemon view) (getf args :target))))
               (unless (and target (not (eq target (or (pane-by-id (view-daemon view) pane) (focused-pane view))))
                            (not (pane-floating target)) (not (pane-view-minimized (pane-state view (pane-id target))))
                            (member (getf args :edge) '(:left :right :top :bottom :center)))
                 (error "Invalid snap target")))))
          (:copy-point
           (unless (and (typep (getf args :x) '(integer 0 499))
                        (typep (getf args :y) '(integer 0 299))
                        (member (getf args :start) '(nil t)))
             (error "Invalid copy point")))
          (:copy-scroll
           (unless (typep (getf args :delta) '(integer -300 300)) (error "Invalid copy scroll")))
          (:send-input
           (unless (and (listp (getf args :bytes)) (<= (length (getf args :bytes)) 4096)
                        (every (lambda (b) (typep b '(unsigned-byte 8))) (getf args :bytes)))
             (error "Invalid input bytes")))

          (:stop (unless (member (getf args :force) '(nil t)) (error "Force must be boolean")))
          (:focus (unless pane (error "Focus needs a pane ID")))
          (:close
           (unless (member (getf args :force) '(nil t)) (error "Force must be boolean"))
           (when (member :focus args)
             (let ((replacement (pane-by-id (view-daemon view) (getf args :focus))))
               (unless (and replacement (not (eq replacement (focused-pane view))))
                 (error "Close focus must name a surviving pane")))))
          ((:status :rename) (unless (and (stringp (getf args :text)) (<= (length (getf args :text)) 512))
                              (error "Text must contain at most 512 characters")))
          (:show-menu
           (unless (and (find owner (getf registry :components)
                              :key (lambda (c) (getf c :id)) :test #'equal)
                        (typep (getf args :x) '(integer 0 499))
                        (typep (getf args :y) '(integer 0 299))
                        (<= 1 (length (getf args :spans)) 256))
             (error "Invalid menu owner or geometry"))
           (validate-decoration-spans (getf args :spans) t))
          (:decorate (validate-decoration-spans (getf args :spans)))
          (:pane-note
           (unless (and pane (valid-decoration-text-p (getf args :text))
                        (<= (length (getf args :text)) 512)
                        (typep (getf args :duration) '(integer 1 60000))
                        (listp (getf args :sgr)) (<= (length (getf args :sgr)) 16)
                        (every (lambda (n) (typep n '(integer 0 255))) (getf args :sgr)))
             (error "Invalid pane note")))
          ((:resize :copy-move) (unless (and (integerp (getf args :delta)) (<= -10000 (getf args :delta) 10000))
                                 (error "Invalid movement")))
          (:copy-edge (unless (member (getf args :edge) '(:start :end)) (error "Invalid edge")))
          (:set-layout (validate-layout-tree (view-daemon view) (getf args :tree)))
          (:split
           (unless (member (getf args :axis) '(:columns :rows)) (error "Invalid split axis"))
           (when (>= (length (daemon-panes (view-daemon view))) (option (view-daemon view) :pane-budget 16))
             (error "Workspace pane budget is exhausted"))
           (let ((argv (getf args :argv (option (view-daemon view) :shell '("/bin/sh" "-i")))))
             (unless (and (listp argv) (<= 1 (length argv) 64)
                          (every (lambda (s) (and (stringp s) (<= (length s) 4096) (not (find #\Null s)))) argv)
                          (plusp (length (first argv)))) (error "Invalid executable argument vector"))))))
    (when (> primary-count 1)
      (error "A batch may contain one view action plus status contributions"))
    (when (and (plusp primary-count) mode-before-primary)
      (error "A keymap transition must follow the view action"))
      (let ((state-action (find :set-state actions :key #'first)))
      (when (and state-action (not staging))
        (let* ((value (getf (rest state-action) :value))
               (entries (remove owner (retained-owner-entries (view-component-state view) registry)
                                :key #'car :test #'equal)))
          (when value
            (push (cons owner value) entries))
          (when (> (component-state-bytes entries) 16384)
            (error "Aggregate component state exceeds 16 KiB")))))
    ;; Contributions are bounded across the retained owner set as well as per
    ;; action. The invoking owner's replacement is staged in this calculation,
    ;; so a rejected batch cannot evict its previous contribution.
    (let ((replacement nil))
      (dolist (a actions)
        (when (eq (first a) :decorate)
          (setf replacement (copy-tree (getf (rest a) :spans)))))
      (when replacement
        (let ((entries (remove owner (unless staging (retained-owner-entries (view-decorations view) registry))
                              :key #'car :test #'equal)))
          (push (cons owner replacement) entries)
          (let ((count 0) (text-length 0))
            (dolist (entry entries)
              (incf count (length (rest entry)))
              (dolist (span (rest entry))
                (let ((rows (getf span :rows 1)))
                  (incf text-length (* rows (length (getf span :text)))))))
            (when (> count 1024) (error "At most 1024 retained decoration spans are allowed"))
            (when (> text-length 16000) (error "Retained decoration text exceeds 16000 characters")))))))))
(defun apply-actions (view owner actions hook origin)
  (let ((origin (or origin (capture-origin view))))
    (unless (and (eq view (command-origin-view origin)) (origin-current-p origin))
      (error "Action origin is no longer current"))
    (validate-actions view actions hook owner)
    (when (eq hook :layout)
      (commit-layout view owner (getf (rest (first actions)) :placements) (getf (rest (first actions)) :camera))
      (return-from apply-actions))
  ;; Complete a mode transition only after the primary action succeeds. This
  ;; keeps mode and status contributions out of a batch whose primary action
  ;; raises after partially updating its own state.
  (let ((primary (find-if (lambda (a) (and (not (member (first a) '(:status :decorate :show-menu :pane-note :set-state :store-set)))
                                           (not (eq (first a) :set-keymap)))) actions))
        (mode-transition (find-if (lambda (a) (eq (first a) :set-keymap)) actions)))
    (when primary
      (let* ((transition (capture-transition view primary))
             (result (apply-primary-action view (first primary) (rest primary) origin)))
        (when (pending-split-p result)
          (setf (pending-split-owner result) owner
                (pending-split-actions result) (remove primary actions :count 1))
          (return-from apply-actions :pending))
        (when (origin-current-p origin) (start-transition view transition))))
    (when mode-transition
      (apply-primary-action view (first mode-transition) (rest mode-transition) origin)))
  (dolist (a actions)
    (case (first a)
      (:show-menu (open-popup view owner (getf (rest a) :spans)
                              (getf (rest a) :x) (getf (rest a) :y)))
      (:pane-note
       (let* ((args (rest a))
              (existing (find-if (lambda (note)
                                   (and (equal owner (getf note :owner))
                                        (eql (getf args :pane) (getf note :pane))))
                                 (view-pane-notes view))))
         ;; Repeating an identical active note leaves its deadline intact.
         (unless (and existing (> (getf existing :until) (now))
                      (equal (getf args :text) (getf existing :text))
                      (equal (getf args :sgr) (getf existing :sgr)))
           (setf (view-pane-notes view)
                 (cons (list :owner owner :pane (getf args :pane)
                             :text (copy-seq (getf args :text)) :sgr (copy-list (getf args :sgr))
                             :until (+ (now) (/ (getf args :duration) 1000)))
                       (remove existing (view-pane-notes view)))))))
      (:status
       (setf (view-contributions view)
             (acons owner (getf (rest a) :text) (remove owner (view-contributions view) :key #'car :test #'equal))))
      (:decorate
       (setf (view-decorations view)
             (acons owner (copy-tree (getf (rest a) :spans))
                    (remove owner (view-decorations view) :key #'car :test #'equal))))
      (:set-state
       (let ((value (getf (rest a) :value)))
         (setf (view-component-state view)
               (remove owner (view-component-state view) :key #'car :test #'equal))
         (when value
           (push (cons owner (copy-component-state value))
                 (view-component-state view)))))
      (:store-set
       (multiple-value-bind (namespace entries)
           (store-set (view-daemon view) owner (getf (rest a) :key) (getf (rest a) :value))
         (setf (daemon-store-entries (view-daemon view))
               (acons namespace entries
                      (remove namespace (daemon-store-entries (view-daemon view)) :key #'car :test #'equal)))
         (when *store-persist*
           (handler-case (ekko/store:store-write namespace entries)
             (error (e) (note-error view (format nil "store write failed: ~A" e)))))))
      (:set-geometry
       (let ((value (validate-geometry-value (getf (rest a) :value))))
         (setf (view-geometry-contributions view)
               (remove owner (view-geometry-contributions view) :key #'car :test #'equal))
         (when value
           (push (cons owner value) (view-geometry-contributions view)))
         (layout view)))))
  (when actions
    (incf (view-revision view))
    (reconcile-size (view-daemon view)))))
(defun ensure-pane-close (view pane force)
  (unless force
    (when (some (lambda (other)
                  (and (not (eq other view)) (view-live-p other) (member pane (visible-panes other))))
                (daemon-views (view-daemon view)))
      (error "Pane is shown by another view; use force to close it"))))
(defun apply-primary-action (view op args origin)
  (let* ((daemon (view-daemon view))
         (pane (unless (member op '(:set-keymap :set-layout :set-geometry :detach :stop :reload))
                 (if (getf args :pane)
                     (or (pane-by-id daemon (getf args :pane)) (error "Unknown pane"))
                     (origin-target origin))))
         (id (and pane (pane-id pane)))
         (state (and pane (pane-state view id))))
    (case op
      (:set-keymap
       (setf (view-mode view) (getf args :name) (view-prefix view) nil
             (view-key-fragment view) nil (view-key-fragment-mode view) nil))
      (:set-layout
       (unless (equal (command-origin-layout origin) (daemon-tree daemon))
         (error "Layout changed before the command completed"))
       (setf (daemon-tree daemon) (copy-tree (getf args :tree)))
       (layout-all-views daemon))
      (:split
       (when (>= (length (daemon-panes daemon)) (option daemon :pane-budget 16))
         (error "Workspace pane budget is exhausted"))
       (let* ((argv (copy-list (getf args :argv (option daemon :shell '("/bin/sh" "-i")))))
              (new-id (allocate-pane-id daemon))
              (new (make-pane :id new-id :daemon daemon :argv argv
                              :label (file-namestring (first argv))
                              :vt (make-terminal :cols (terminal-cols (pane-vt pane))
                                                 :rows (terminal-rows (pane-vt pane))
                                                 :cw (view-cw view) :ch (view-ch view))
                              :launch-kind (if (member :argv args) :command :shell)
                              :creation-position (1+ (length (daemon-panes daemon)))))
              (pending (make-pending-split :pane new :origin origin)))
         (setf (daemon-tree daemon)
               (ekko/layout:split-pane (daemon-tree daemon) id new-id (getf args :axis))
               (daemon-panes daemon) (append (daemon-panes daemon) (list new))
               (view-zoom view) nil)
         (push pending (daemon-pending-splits daemon))
         (layout-all-views daemon)
         (set-focus view new-id t)
         pending))
      (:close
       (ensure-pane-close view pane (getf args :force))
       (if (= (length (daemon-panes daemon)) 1)
           (request-stop daemon view (getf args :force))
           (progn
             (close-pane pane)
             (clear-screen (pane-graphics pane) :main) (clear-screen (pane-graphics pane) :alternate)
             (when (pane-pid pane) (push (cons pane (+ (now) 1)) (daemon-retired daemon)))
             (setf (daemon-panes daemon) (remove pane (daemon-panes daemon))
                   (daemon-tree daemon) (ekko/layout:remove-pane (daemon-tree daemon) id))
             (dolist (other (daemon-views daemon)) (prune-view-pane other id))
             (when (getf args :focus) (set-focus view (getf args :focus)))
             (layout-all-views daemon))))
      (:rename
       (setf (pane-label pane) (getf args :text) (pane-name pane) (getf args :text))
       (incf (daemon-revision daemon)))
      (:focus (set-focus view id))
      (:focus-next
       (let* ((panes (view-panes view)) (at (or (position pane panes) 0)))
         (set-focus view (pane-id (nth (mod (1+ at) (length panes)) panes)))))
      (:float
       (setf (pane-floating pane)
             (clamp-window-rect view (or (getf args :rect) (pane-floating pane)
               (list (+ (pane-view-outer-x state) 3) (+ (pane-view-outer-y state) 2)
                     (max 20 (floor (* (pane-view-outer-cols state) 3) 4))
                     (max 8 (floor (* (pane-view-outer-rows state) 3) 4)))))
             (pane-view-minimized state) nil (view-zoom view) nil)
       (set-focus view id) (record-activation view pane) (layout-all-views daemon))
      (:tile
       (setf (pane-floating pane) nil (pane-view-minimized state) nil (view-zoom view) nil)
       (set-focus view id) (layout-all-views daemon))
      (:place-window
       (let* ((target (getf args :target)) (edge (getf args :edge)))
         (unless (pane-by-id daemon target) (error "Unknown pane"))
         (setf (daemon-tree daemon)
           (if (eq edge :center) (ekko/layout:swap-panes (daemon-tree daemon) id target)
               (labels ((insert-at (node)
                          (if (integerp node)
                              (if (= node target)
                                  (list (if (member edge '(:left :right)) :columns :rows) 50
                                        (if (member edge '(:left :top)) id target)
                                        (if (member edge '(:left :top)) target id)) node)
                              (list (first node) (second node) (insert-at (third node)) (insert-at (fourth node))))))
                 (insert-at (ekko/layout:remove-pane (daemon-tree daemon) id)))))
         (setf (pane-floating pane) nil (pane-view-minimized state) nil (view-zoom view) nil)
         (set-focus view id) (layout-all-views daemon)))
      (:minimize
       (setf (pane-view-minimized state) t (view-zoom view) nil
             (view-drag view) nil (view-paste-target view) nil)
       (let ((next (find-if-not (lambda (p) (pane-view-minimized (pane-state view (pane-id p)))) (view-panes view))))
         (when (and next (eql id (view-focus-id view))) (set-focus view (pane-id next))))
       (layout view))
      (:restore (setf (pane-view-minimized state) nil (view-zoom view) nil) (set-focus view id) (layout view))
      (:zoom
       (let ((restore (and (view-zoom view) (eql id (view-focus-id view)))))
         (setf (pane-view-minimized state) nil)
         (set-focus view id) (setf (view-zoom view) (not restore)))
       (layout view))
      (:swap
       (let ((panes (daemon-panes daemon)))
         (when (> (length panes) 1)
           (setf (daemon-tree daemon)
                 (ekko/layout:swap-panes (daemon-tree daemon) id
                   (pane-id (nth (mod (1+ (position pane panes)) (length panes)) panes))))
           (layout-all-views daemon))))
      (:resize
       (setf (daemon-tree daemon) (ekko/layout:resize-split (daemon-tree daemon) id (getf args :delta)))
       (layout-all-views daemon))
      (:detach
       (when (view-wire view) (setf (wire-closing (view-wire view)) t))
       (detach-view view))
      (:stop (request-stop daemon view (getf args :force)))
      (:reload (start-reload daemon (command-origin-peer origin)))
      (:help
       (enter-copy view pane
         (coerce (cons "Registered prefix bindings (q exits)"
                       (loop for b in (reverse (getf (daemon-registry daemon) :bindings))
                             when (eq (getf b :map) :prefix) collect
                             (format nil "~A -> ~A (~A)" (getf b :key) (getf b :command) (getf b :owner)))) 'vector)))
      (:send-input (pane-input pane (octets-from-list (getf args :bytes))))
      (:copy-point (point-copy view pane (getf args :x) (getf args :y) (getf args :start)))
      (:copy-scroll (scroll-copy view pane (getf args :delta)))
      (:copy-mode (enter-copy view pane))
      (:copy-exit (leave-copy view pane))
      (:copy-move (when (pane-view-copy-lines state) (move-copy view pane (+ (pane-view-copy-cursor state) (getf args :delta)))))
      (:copy-edge (when (pane-view-copy-lines state)
                    (move-copy view pane (if (eq (getf args :edge) :start) 0 (1- (length (pane-view-copy-lines state)))))))
      (:copy-mark (when (pane-view-copy-lines state) (setf (pane-view-copy-mark state) (pane-view-copy-cursor state))))
      (:copy-selection
       (when (pane-view-copy-lines state)
         (publish-copy view (selected-copy-text view pane))
         (setf (pane-view-copy-flash-until state) (+ (now) 1/5))))
      (:copy-search (when (pane-view-copy-lines state) (setf (pane-view-search-input state) (octets 0))))
      (:copy-search-next (search-copy view pane))
      (:paste-buffer
       (let* ((text (daemon-clipboard daemon)) (bytes (text-bytes text))
              (bracketed (gethash 2004 (terminal-modes (pane-vt pane)))))
         (when (> (length bytes) 60000) (error "Paste exceeds pane input capacity; export with ekko buffer"))
         (pane-input pane (if bracketed
                              (concatenate '(vector (unsigned-byte 8)) #(27 91 50 48 48 126) bytes #(27 91 50 48 49 126)) bytes)))))))
(defun pending-layout-ready-p (pending)
  (let* ((pane (pending-split-pane pending)) (daemon (pane-daemon pane)) (ready t))
    ;; Wait for every participating live/home view. A quarantined view keeps
    ;; old output but cannot supply a layout for this new pane.
    (dolist (view (daemon-views daemon) ready)
      (when (and (not (view-quarantined view)) (member pane (view-panes view))
                 (or (view-live-p view) (eq view (daemon-home-view (view-daemon view)))))
        (let ((state (view-layout-state view)))
          ;; Visit all participants even if an earlier layout is still pending.
          ;; A failed peer must reject startup rather than block it indefinitely.
          (when (layout-state-error state)
            (error "View ~A layout failed before pane startup: ~A" (view-id view) (layout-state-error state)))
          (unless (layout-state-current-p state (daemon-registry (view-daemon view))
                                          (context-data view) (layout-token view))
            (setf ready nil)))))))

(defun discard-pending-pane (daemon pane)
  (when (member pane (daemon-panes daemon))
    (setf (daemon-panes daemon) (remove pane (daemon-panes daemon))
          (daemon-tree daemon) (ekko/layout:remove-pane (daemon-tree daemon) (pane-id pane)))
    (dolist (view (daemon-views daemon)) (prune-view-pane view (pane-id pane)))
    (layout-all-views daemon)))
(defun complete-pending-splits (daemon)
  (dolist (pending (copy-list (daemon-pending-splits daemon)))
    (let* ((origin (pending-split-origin pending)) (view (command-origin-view origin))
           (pane (pending-split-pane pending)) (state (view-layout-state view)))
      (handler-case
          (progn
            (unless (origin-current-p origin) (error "View changed before pane startup"))
            (when (layout-state-error state) (error "Layout failed before pane startup: ~A" (layout-state-error state)))
            (when (pending-layout-ready-p pending)
              (spawn-pane pane)
              (setf (daemon-pending-splits daemon) (remove pending (daemon-pending-splits daemon)))
              (apply-actions view (pending-split-owner pending) (pending-split-actions pending) nil origin)
              (command-reply (command-origin-peer origin) "")
              (replay-input view)))
        (error (e)
          (setf (daemon-pending-splits daemon) (remove pending (daemon-pending-splits daemon)))
          (close-pane pane)
          (when (pane-pid pane) (push (cons pane (+ (now) 1)) (daemon-retired daemon)))
          (discard-pending-pane daemon pane)
          (when (origin-current-p origin) (note-error view e))
          (command-reply (command-origin-peer origin) (princ-to-string e) t)
          (replay-input view))))))

(defun enter-copy (view pane &optional lines)
  (leave-copy view pane)
  (unless lines
    (setf (pane-view-copy-cells (pane-state view (pane-id pane))) (history-cells (pane-vt pane))
          lines (map 'vector #'ekko/vt:row-text (pane-view-copy-cells (pane-state view (pane-id pane))))))
  (setf (pane-view-copy-lines (pane-state view (pane-id pane))) lines (pane-view-copy-mark (pane-state view (pane-id pane))) nil (pane-view-search-input (pane-state view (pane-id pane))) nil)
  (move-copy view pane (1- (length lines))))
(defun move-copy (view pane cursor)
  (setf (pane-view-copy-cursor (pane-state view (pane-id pane))) (max 0 (min (1- (length (pane-view-copy-lines (pane-state view (pane-id pane))))) cursor))
        (pane-view-copy-top (pane-state view (pane-id pane))) (max 0 (min (pane-view-copy-top (pane-state view (pane-id pane))) (pane-view-copy-cursor (pane-state view (pane-id pane))))))
  (when (>= (pane-view-copy-cursor (pane-state view (pane-id pane))) (+ (pane-view-copy-top (pane-state view (pane-id pane))) (pane-view-rows (pane-state view (pane-id pane)))))
    (setf (pane-view-copy-top (pane-state view (pane-id pane))) (1+ (- (pane-view-copy-cursor (pane-state view (pane-id pane))) (pane-view-rows (pane-state view (pane-id pane))))))))
(defun clip-copy-text (text cols)
  (let ((width 0) (end 0))
    (loop for c across text for n = (ekko/vt:character-width c) do
      (when (> (+ width n) cols) (return))
      (incf width n) (incf end))
    (subseq text 0 end)))
(defun search-copy (view pane)
  (when (and (pane-view-copy-lines (pane-state view (pane-id pane))) (plusp (length (pane-view-search-text (pane-state view (pane-id pane))))))
    (let* ((lines (pane-view-copy-lines (pane-state view (pane-id pane))))
           (match (loop for step from 1 to (length lines) for i = (mod (+ (pane-view-copy-cursor (pane-state view (pane-id pane))) step) (length lines))
                        when (search (pane-view-search-text (pane-state view (pane-id pane))) (aref lines i) :test #'char-equal) return i)))
      (when match (move-copy view pane match)))))
(defun search-input-text (bytes)
  ;; Reads and the bounded input buffer can end inside a UTF-8 character.
  (loop for end from (length bytes) downto (max 0 (- (length bytes) 4))
        for text = (handler-case (bytes-text (subseq bytes 0 end)) (error () nil))
        when text return text finally (return "")))
(defun copy-search-input (view bytes)
  (let ((pane (focused-pane view)))
    (loop for byte across bytes do
      (case byte
        (27 (setf (pane-view-search-input (pane-state view (pane-id pane))) nil) (return))
        ((10 13) (setf (pane-view-search-text (pane-state view (pane-id pane))) (search-input-text (pane-view-search-input (pane-state view (pane-id pane)))) (pane-view-search-input (pane-state view (pane-id pane))) nil)
                 (search-copy view pane) (return))
        ((8 127) (let* ((input (pane-view-search-input (pane-state view (pane-id pane)))) (end (1- (length input))))
                   (when (>= end 0)
                     (loop while (and (plusp end) (= (logand (aref input end) #xc0) #x80)) do (decf end))
                     (setf (pane-view-search-input (pane-state view (pane-id pane))) (subseq input 0 end)))))
        (t (when (< (length (pane-view-search-input (pane-state view (pane-id pane)))) 256)
             (setf (pane-view-search-input (pane-state view (pane-id pane))) (concatenate '(vector (unsigned-byte 8)) (pane-view-search-input (pane-state view (pane-id pane))) (octets-from-list (list byte))))))))
    (incf (view-revision view))))
(defun status-text (view &optional (registry (daemon-registry (view-daemon view)))
                                  (contributions (view-contributions view)))
  (let* ((panes (view-panes view))
         (pane (or (find (view-focus-id view) panes :key #'pane-id) (first panes)))
         (state (and pane (pane-state view (pane-id pane) nil))))
    (cond ((and state (pane-view-search-input state))
           (format nil "Search: ~A" (search-input-text (pane-view-search-input state))))
          ((and state (pane-view-copy-lines state))
           "Copy: j/k move  b/f page  Space mark  Enter copy  / search  n next  q exit")
          ((plusp (length (view-notice view))) (view-notice view))
          (t (or (loop for component in (reverse (getf registry :components))
                       for contribution = (assoc (getf component :id) contributions :test #'equal)
                       when contribution return (rest contribution))
                 (getf (getf registry :options) :status-text ""))))))
(defun binding-key-label (key)
  "Render a binding key (plain key or (MODS . KEY) chord) as plain text."
  (cond ((consp key)
         (let* ((code (rest key))
                ;; A chord whose key part folded to a control code prints as Ctrl-<char>,
                ;; lowercase to match the shifted letter it stands for.
                (control (and (integerp code) (<= 1 code 26)
                              (not (member code '(9 10 13 27)))))
                (name (cond ((keywordp code) (string-downcase (symbol-name code)))
                            (control (string (char-downcase (code-char (+ 64 code)))))
                            ((and (integerp code) (<= 32 code 126)) (string (code-char code)))
                            (t (princ-to-string code)))))
           (concatenate 'string (if (logtest 1 (first key)) "M-" "")
                        (if (logtest 2 (first key)) "Super-" "")
                        (if control "Ctrl-" "")
                        (if (logtest 4 (first key)) "Shift-" "") name)))
        ((and (integerp key) (<= 1 key 26) (not (member key '(9 10 13 27))))
         (format nil "C-~C" (char-downcase (code-char (+ 64 key)))))
        ((and (integerp key) (<= 32 key 126)) (string (code-char key)))
        ((keywordp key) (string-downcase (symbol-name key)))
        (t (princ-to-string key))))
(defun json-string (string)
  (with-output-to-string (out)
    (write-char #\" out)
    (loop for c across string do
      (case c (#\" (write-string "\\\"" out)) (#\\ (write-string "\\\\" out))
            (otherwise (if (< (char-code c) 32) (format out "\\u~4,'0X" (char-code c)) (write-char c out)))))
    (write-char #\" out)))
(defun json-value (value)
  (cond ((null value) "null") ((eq value :false) "false") ((eq value t) "true") ((stringp value) (json-string value))
        ((keywordp value) (json-string (string-downcase (symbol-name value))))
        ((floatp value) (format nil "~F" value)) ((integerp value) (princ-to-string value))
        ((and (consp value) (eq (first value) :object))
         (format nil "{~{~A~^,~}}" (loop for (key val) on (rest value) by #'cddr
                                        collect (format nil "~A:~A" (json-value key) (json-value val)))))
        ((listp value) (format nil "[~{~A~^,~}]" (mapcar #'json-value value)))
        ((vectorp value) (format nil "[~{~A~^,~}]" (map 'list #'json-value value)))
        (t (error "Not JSON data"))))
(defun component-state-json-value (value)
  ;; Plain state must not be interpreted as the inspector's :object/:false
  ;; representation. Preserve keyword values as strings and lists as arrays.
  (cond ((consp value) (map 'vector #'component-state-json-value value))
        ((keywordp value) (string-downcase (symbol-name value)))
        (t value)))
(defun inspect-json (view)
  (let* ((daemon (view-daemon view))
         (registry (daemon-registry daemon))
         (context (context-data view)))
    (labels ((pane-json-data (pane)
               (cons :object
                     (loop for (key value) on pane by #'cddr append
                       (list (case key
                               (:launch-kind :launch_kind)
                               (:creation-position :creation_position)
                               (:terminal-title :terminal_title)
                               (:activation-order :activation_order)
                               (:layout-rect :layout_rect)
                               (:pty-size :pty_size)
                               (:view-cols :view_cols) (:view-rows :view_rows)
                               (:outer-rect :outer_rect) (:history-rows :history_rows)
                               (otherwise key))
                             (if (member key '(:minimized :activity :visible))
                                 (if value t :false) value))))))
      (json-value
        (list :object :generation (daemon-config-generation daemon)
              :error (or (view-error view) (daemon-config-error daemon))
              :quarantined (if (view-quarantined view) t :false)
              :session (getf context :session) :view_id (view-id view) :epoch (view-epoch view)
              :all-panes (mapcar #'pane-json-data (getf context :all-panes))
              :workspace (cons :object (getf context :workspace))
              :focus (getf context :focus) :mode (getf context :mode)
              :popup (when (view-popup view)
                       (let ((popup (view-popup view)))
                         (list :object :owner (popup-owner popup) :x (popup-x popup) :y (popup-y popup)
                               :selected (popup-selected popup))))
              :zoom (if (getf context :zoom) t :false)
              :viewport (cons :object (getf context :viewport))
              :chrome-status (cons :object (getf context :chrome-status))
              :panes (mapcar #'pane-json-data (getf context :panes))
              :pane-notes (mapcar (lambda (note) (cons :object note)) (getf context :pane-notes))
              :geometry (list* :object :contributions
                               (loop for (owner . value) in (view-geometry-contributions view)
                                     collect (list :object :owner owner :value (copy-component-state value)))
                               (getf context :geometry))
              :keymaps (mapcar (lambda (m) (cons :object m)) (getf registry :keymaps))
              :disabled-hooks (daemon-disabled-hooks daemon)
              :decorations (loop for (owner . spans) in (view-decorations view)
                                 collect (list :object :owner owner
                                               :spans (loop for span in spans collect
                                                        (list :object :x (getf span :x)
                                                              :y (getf span :y)
                                                              :text (getf span :text)
                                                              :action (getf span :action)
                                                              :command (getf span :command)
                                                              :has_menu (if (getf span :context-command) t :false)
                                                              :sgr (getf span :sgr)
                                                              :rows (getf span :rows 1)
                                                              :overlay (if (getf span :overlay) t :false)))))
              :contributions (loop for (owner . text) in (view-contributions view)
                                   collect (list :object :owner owner :text text))
              :component-state (loop for (owner . value) in (getf context :component-state)
                                    collect (list :object :owner owner :value (component-state-json-value value)))
              :options (cons :object (getf registry :options)) :layout (getf context :layout)
              :components (mapcar (lambda (c) (cons :object c)) (getf registry :components))
              :commands (mapcar (lambda (c) (cons :object c)) (getf registry :commands))
              :bindings (mapcar (lambda (entry)
                                  (cons :object
                                        (loop for (key value) on entry by #'cddr
                                              append (list key (if (eq key :key)
                                                                   (binding-key-label value) value)))))
                                (getf registry :bindings)))))))
(defun split-arguments (bytes)
  (loop for start = 0 then (1+ end) for end = (position 0 bytes :start start)
        collect (bytes-text (subseq bytes start end)) while end))
