(in-package #:ekko/runtime)

(defun option (session key &optional default)
  (getf (getf (session-registry session) :options) key default))
(defun context-data (session)
  (list :session (session-name session) :focus (pane-id (focused-pane session))
        :layout (copy-tree (session-tree session))
        :panes (loop for p in (session-panes session) collect
                 (list :id (pane-id p) :label (pane-label p) :pid (pane-pid p)
                       :cols (terminal-cols (pane-vt p)) :rows (terminal-rows (pane-vt p)) :exit (pane-status p)))))
(defun install-registry (session registry)
  (unless (and (= (getf registry :api-version 0) 1)
               (<= (length (getf registry :components)) 64)
               (<= (length (getf registry :commands)) 256)
               (<= (length (getf registry :bindings)) 256))
    (error "Invalid extension registry"))
  (dolist (binding (getf registry :bindings))
    (unless (or (null (getf binding :command))
                (find (getf binding :command) (getf registry :commands) :key (lambda (c) (getf c :name)) :test #'equal))
      (error "Binding references unknown command: ~A" (getf binding :command))))
  (setf (session-registry session) registry (session-config-error session) nil
        (session-contributions session) nil (session-hook-context session) nil (session-hooks session) nil)
  (incf (session-config-generation session)) (incf (session-revision session)))
(defun command-pending-p (session)
  (or (session-command-queue session)
      (and (session-worker session) (eq (first (extension-worker-request (session-worker session))) :command))
      (and (null (session-worker session)) (session-candidate session))))
(defun defer-input (session kind data)
  (when (> (+ (session-input-bytes session) (length data)) 65536) (error "Pending command input exceeds 64 KiB"))
  (push (cons kind data) (session-input-queue session)) (incf (session-input-bytes session) (length data)))
(defun replay-input (session)
  (let ((pending (nreverse (session-input-queue session))))
    (setf (session-input-queue session) nil (session-input-bytes session) 0)
    (dolist (item pending)
      (when (session-writer session)
        (server-packet session (session-writer session)
          (concatenate '(vector (unsigned-byte 8)) (octets-from-list (list (car item))) (cdr item)))))))
(defun semantic-key (bytes key)
  (or (cdr (assoc (map 'string #'code-char bytes)
                 (loop for (suffix . value) in '(("[A" . :up) ("[B" . :down) ("[5~" . :page-up)
                                                 ("[6~" . :page-down) ("[H" . :home) ("[F" . :end))
                       collect (cons (concatenate 'string (string #\Esc) suffix) value)) :test #'equal))
      (cdr (assoc key '((57352 . :up) (57353 . :down) (57354 . :page-up) (57355 . :page-down)
                        (57356 . :home) (57357 . :end)))) key))
(defun dispatch-binding (session map key)
  (let ((binding (find-if (lambda (b) (and (eq map (getf b :map)) (eql key (getf b :key))))
                          (reverse (getf (session-registry session) :bindings)))))
    (when (and binding (getf binding :command))
      (handler-case (request-command session (getf binding :command) (list :arguments nil) nil)
        (error (e) (note-error session e))))))
(defun request-command (session name event peer)
  (unless (find name (getf (session-registry session) :commands) :key (lambda (c) (getf c :name)) :test #'equal)
    (error "Unknown command: ~A" name))
  (let ((worker (session-worker session)))
    (unless worker (error "Extension worker is restarting; use config reload if recovery fails"))
    (when (extension-worker-request worker)
      (when (>= (length (session-command-queue session)) 32) (error "Command queue full"))
      (setf (session-command-queue session) (append (session-command-queue session) (list (list name event peer))))
      (return-from request-command))
    (extension-send (extension-worker-output worker) (list :dispatch :command name (context-data session) event))
    (setf (session-notice session) ""
          (extension-worker-request worker) (list :command name peer)
          (extension-worker-deadline worker) (+ (now) 1/20))))
(defun command-reply (peer message &optional errorp)
  (when (and peer (>= (wire-fd peer) 0))
    (handler-case
        (progn (send-packet peer (if errorp 21 20) (text-bytes message)) (flush-wire peer))
      (error () (close-wire peer)))))
(defun note-error (session error)
  (let ((message (subseq (princ-to-string error) 0 (min 1000 (length (princ-to-string error))))))
    (setf (session-config-error session) message (session-notice session) message)
    (incf (session-revision session))
    (format *error-output* "configuration: ~A~%" message)))
(defun start-reload (session peer &optional recover)
  (when (session-candidate session) (error "A configuration reload is already running"))
  (let* ((active (session-worker session)) (path (if active (extension-worker-path active) (config-path)))
         (source (if (and recover active) (extension-worker-source active) (config-source path))))
    (setf (session-candidate session)
          (start-worker source path (concatenate 'string (socket-path (session-name session)) ".extensions.log"))
          (extension-worker-recovery (session-candidate session)) recover
          (session-reload-peer session) peer)))
(defun service-extensions (session buffer)
  (let ((candidate (session-candidate session)))
    (when candidate
      (handler-case
          (progn
            (when (eq (extension-worker-request candidate) :load)
              (let ((response (poll-worker candidate buffer)))
                (when response
                  (unless (eq (first response) :ready) (error "~A" (second response)))
                  ;; Validate on a detached session before replacing registrations.
                  (let ((trial (make-session))) (install-registry trial (second response)))
                  (setf (extension-worker-registry candidate) (second response)
                        (extension-worker-request candidate) nil))))
            (when (and (null (extension-worker-request candidate))
                       (or (null (session-worker session)) (null (extension-worker-request (session-worker session)))))
              (stop-worker (session-worker session))
              (setf (session-worker session) candidate (session-candidate session) nil)
              (install-registry session (extension-worker-registry candidate))
              (unless (extension-worker-recovery candidate) (setf (session-disabled-hooks session) nil))
              (setf (session-notice session) "")
              (command-reply (session-reload-peer session) "") (setf (session-reload-peer session) nil)
              (replay-input session)))
        (error (e)
          (note-error session e) (command-reply (session-reload-peer session) (princ-to-string e) t)
          (stop-worker candidate) (setf (session-candidate session) nil (session-reload-peer session) nil)
          (unless (session-worker session)
            (dolist (command (session-command-queue session))
              (command-reply (third command) "Extension recovery failed; use config reload" t))
            (setf (session-command-queue session) nil)
            (replay-input session))))))
  (let ((worker (session-worker session)))
    (when worker
      (handler-case
          (let ((response (poll-worker worker buffer)) (request (extension-worker-request worker)))
            (when response
              (setf (extension-worker-request worker) nil)
              (handler-case
                  (progn
                    (when (eq (first response) :error) (error "~A" (second response)))
                    (unless (eq (first response) :result) (error "Invalid extension result"))
                    (when (or (eq (first request) :command) (equal (third request) (context-data session)))
                      (apply-actions session (getf (second response) :owner) (getf (second response) :actions)
                                     (eq (first request) :hook) (when (eq (first request) :command) (third request))))
                    (when (and (eq (first request) :command) (not (eq (third request) (session-reload-peer session))))
                      (command-reply (third request) "")))
                (error (e) (note-error session e)
                  (when (eq (first request) :command) (command-reply (third request) (princ-to-string e) t))))
              (replay-input session)))
        (error (e)
          (let ((request (extension-worker-request worker)))
            (note-error session e)
            (when (and (listp request) (eq (first request) :command))
              (command-reply (third request) (princ-to-string e) t))
            ;; Recover from the last successfully loaded source, even if the file
            ;; on disk has since become invalid. Never reload inside a callback.
            (when (and (listp request) (eq (first request) :hook))
              (pushnew (second request) (session-disabled-hooks session) :test #'equal))
            (handler-case
                (unless (session-candidate session) (start-reload session nil t))
              (error (recovery-error) (note-error session recovery-error)))
            (stop-worker worker) (setf (session-worker session) nil))))))
  (let ((worker (session-worker session)))
    (when (and worker (null (extension-worker-request worker)) (session-command-queue session))
      (let ((command (pop (session-command-queue session))))
        (handler-case (apply #'request-command session command)
          (error (e) (note-error session e) (command-reply (third command) (princ-to-string e) t)
            (replay-input session))))))
  (schedule-hooks session))
(defun schedule-hooks (session)
  (let ((context (context-data session)) (previous (session-hook-context session)))
    (unless (equal context previous)
      (let ((changed (loop for key in ekko/extensions::*context-keys*
                           unless (and previous (equal (getf context key) (getf previous key))) collect key)))
        (dolist (component (getf (session-registry session) :components))
          (when (and (getf component :hook)
                     (not (member (getf component :id) (session-disabled-hooks session) :test #'equal))
                     (intersection changed (getf component :reads)))
            (pushnew (getf component :id) (session-hooks session) :test #'equal))))
      (setf (session-hook-context session) context)))
  (let ((worker (session-worker session)))
    (when (and worker (null (extension-worker-request worker)) (session-hooks session))
      (let ((id (pop (session-hooks session))) (context (context-data session)))
        (setf (extension-worker-request worker) (list :hook id context)
              (extension-worker-deadline worker) (+ (now) 1/20))
        (extension-send (extension-worker-output worker)
                        (list :dispatch :hook id context (list :type :change)))))))

(defun validate-actions (session actions hook)
  (unless (and (listp actions) (<= (length actions) 32)) (error "At most 32 actions are allowed"))
  (when (> (count-if (lambda (a) (not (eq (first a) :status))) actions) 1)
    (error "A batch may contain one session action plus status contributions"))
  (dolist (a actions)
    (unless (and (listp a) (oddp (length a))) (error "Malformed action: ~S" a))
    (let* ((op (first a)) (args (rest a)) (pane (getf args :pane))
           (keys (case op
                   (:split '(:axis :argv)) (:focus '(:pane)) (:rename '(:pane :text)) (:resize '(:delta))
                   (:copy-move '(:delta)) (:copy-edge '(:edge)) (:status '(:text))
                   ((:focus-next :zoom :swap :detach :stop :close :copy-mode :copy-mark :copy-selection
                     :copy-exit :copy-search :copy-search-next :paste-buffer :reload :help) nil)
                   (otherwise (error "Unknown action: ~S" op)))))
      (loop for (key value) on args by #'cddr do (unless (member key keys) (error "Unknown action argument: ~S" key)))
      (unless (= (length (loop for (key value) on args by #'cddr collect key))
                 (length (remove-duplicates (loop for (key value) on args by #'cddr collect key))))
        (error "Duplicate action argument"))
      (when (and hook (not (eq op :status))) (error "Change hooks may only contribute status"))
      (when (and pane (not (pane-by-id session pane))) (error "Unknown pane: ~S" pane))
      (case op
        (:focus (unless pane (error "Focus needs a pane ID")))
        ((:status :rename) (unless (and (stringp (getf args :text)) (<= (length (getf args :text)) 512))
                            (error "Text must contain at most 512 characters")))
        ((:resize :copy-move) (unless (and (integerp (getf args :delta)) (<= -10000 (getf args :delta) 10000))
                               (error "Invalid movement")))
        (:copy-edge (unless (member (getf args :edge) '(:start :end)) (error "Invalid edge")))
        (:split
         (unless (member (getf args :axis) '(:columns :rows)) (error "Invalid split axis"))
         (when (>= (length (session-panes session)) 16) (error "At most 16 panes are supported"))
         (let ((argv (getf args :argv (option session :shell '("/bin/sh" "-i")))))
           (unless (and (listp argv) (<= 1 (length argv) 64)
                        (every (lambda (s) (and (stringp s) (<= (length s) 4096) (not (find #\Null s)))) argv)
                        (plusp (length (first argv)))) (error "Invalid executable argument vector"))))))))
(defun apply-actions (session owner actions hook peer)
  (validate-actions session actions hook)
  (dolist (a actions)
    (unless (eq (first a) :status) (apply-session-action session (first a) (rest a) peer)))
  (dolist (a actions)
    (when (eq (first a) :status)
      (setf (session-contributions session)
            (acons owner (getf (rest a) :text) (remove owner (session-contributions session) :key #'car :test #'equal)))))
  (when actions (incf (session-revision session))))
(defun apply-session-action (session op args peer)
  (let* ((pane (or (and (getf args :pane) (pane-by-id session (getf args :pane))) (focused-pane session)))
         (id (pane-id pane)))
    (case op
      (:split
       (let* ((argv (copy-list (getf args :argv (option session :shell '("/bin/sh" "-i")))))
              (new-id (session-next-pane-id session)))
         ;; Acquire the only fallible resource before changing any logical state.
         (multiple-value-bind (fd pid) (spawn argv 80 24 (session-cw session) (session-ch session))
           (let ((new (make-pane :id new-id :pid pid :io (make-wire :fd fd) :vt (make-terminal)
                                 :argv argv :label (file-namestring (first argv)))))
             (setf (session-panes session) (append (session-panes session) (list new))
                   (session-tree session) (ekko/layout:split-pane (session-tree session) id new-id (getf args :axis))
                   (session-zoom session) nil)
             (incf (session-next-pane-id session))
             (set-focus session (1- (length (session-panes session))))))))
      (:close
       (if (= (length (session-panes session)) 1) (setf (session-stopping session) t)
           (let ((focus (focused-pane session)))
             (close-pane pane)
             (clear-screen (pane-graphics pane) :main) (clear-screen (pane-graphics pane) :alternate)
             (push (cons pane (+ (now) 1)) (session-retired session))
             (setf (session-panes session) (remove pane (session-panes session))
                   (session-tree session) (ekko/layout:remove-pane (session-tree session) id)
                   (session-focus session) (or (position focus (session-panes session)) 0)
                   (session-drag session) nil (session-paste-target session) nil)
             (layout session))))
      (:rename (setf (pane-label pane) (getf args :text)))
      (:focus (set-focus session (position pane (session-panes session))))
      (:focus-next (set-focus session (mod (1+ (session-focus session)) (length (session-panes session)))))
      (:zoom (setf (session-zoom session) (not (session-zoom session))) (layout session))
      (:swap (when (> (length (session-panes session)) 1)
               (setf (session-tree session)
                     (ekko/layout:swap-panes (session-tree session) id
                       (pane-id (nth (mod (1+ (session-focus session)) (length (session-panes session))) (session-panes session)))))
               (layout session)))
      (:resize (setf (session-tree session) (ekko/layout:resize-split (session-tree session) id (getf args :delta))) (layout session))
      (:detach (when (session-writer session) (send-packet (session-writer session) 22)))
      (:stop (setf (session-stopping session) t))
      (:reload (start-reload session peer))
      (:help (enter-copy pane (coerce (cons "Registered prefix bindings (q exits)"
                       (loop for b in (reverse (getf (session-registry session) :bindings))
                             when (eq (getf b :map) :prefix) collect
                               (format nil "~A -> ~A (~A)" (getf b :key) (getf b :command) (getf b :owner)))) 'vector)))
      (:copy-mode (enter-copy pane (history-text (pane-vt pane))))
      (:copy-exit (setf (pane-copy-lines pane) nil (pane-search-input pane) nil))
      (:copy-move (when (pane-copy-lines pane) (move-copy pane (+ (pane-copy-cursor pane) (getf args :delta)))))
      (:copy-edge (when (pane-copy-lines pane) (move-copy pane (if (eq (getf args :edge) :start) 0 (1- (length (pane-copy-lines pane)))))))
      (:copy-mark (when (pane-copy-lines pane) (setf (pane-copy-mark pane) (pane-copy-cursor pane))))
      (:copy-selection
       (when (pane-copy-lines pane)
         (let* ((start (min (or (pane-copy-mark pane) (pane-copy-cursor pane)) (pane-copy-cursor pane)))
                (end (max (or (pane-copy-mark pane) (pane-copy-cursor pane)) (pane-copy-cursor pane)))
                (text (format nil "~{~A~^~%~}" (coerce (subseq (pane-copy-lines pane) start (1+ end)) 'list))))
           (when (> (length (text-bytes text)) (* 1024 1024)) (error "Copy exceeds 1 MiB"))
           (setf (session-clipboard session) text (pane-copy-lines pane) nil (session-notice session) "Copied to Ekko buffer"))))
      (:copy-search (when (pane-copy-lines pane) (setf (pane-search-input pane) (octets 0))))
      (:copy-search-next (search-copy pane))
      (:paste-buffer
       (let* ((text (session-clipboard session)) (bytes (text-bytes text))
              (bracketed (gethash 2004 (terminal-modes (pane-vt pane)))))
         (when (> (length bytes) 60000) (error "Paste exceeds pane input capacity; export with ekko buffer"))
         (pane-input pane (if bracketed (concatenate '(vector (unsigned-byte 8)) #(27 91 50 48 48 126) bytes #(27 91 50 48 49 126)) bytes)))))))
(defun reap-retired (session)
  (setf (session-retired session)
        (remove-if (lambda (entry)
                     (let ((result (reap (pane-pid (car entry)))))
                       (when (>= (now) (cdr entry)) (signal-group (pane-pid (car entry)) 9))
                       (/= result -11)))
                   (session-retired session))))
(defun enter-copy (pane lines)
  (setf (pane-copy-lines pane) lines (pane-copy-mark pane) nil (pane-search-input pane) nil)
  (move-copy pane (1- (length lines))))
(defun move-copy (pane cursor)
  (setf (pane-copy-cursor pane) (max 0 (min (1- (length (pane-copy-lines pane))) cursor))
        (pane-copy-top pane) (max 0 (min (pane-copy-top pane) (pane-copy-cursor pane))))
  (when (>= (pane-copy-cursor pane) (+ (pane-copy-top pane) (terminal-rows (pane-vt pane))))
    (setf (pane-copy-top pane) (1+ (- (pane-copy-cursor pane) (terminal-rows (pane-vt pane)))))))
(defun clip-copy-text (text cols)
  (let ((width 0) (end 0))
    (loop for c across text for n = (ekko/vt::character-width c) do
      (when (> (+ width n) cols) (return))
      (incf width n) (incf end))
    (subseq text 0 end)))
(defun copy-display-lines (pane)
  (move-copy pane (pane-copy-cursor pane))
  (loop for i from (pane-copy-top pane) below (min (length (pane-copy-lines pane))
                                                 (+ (pane-copy-top pane) (terminal-rows (pane-vt pane))))
        for selected = (if (pane-copy-mark pane)
                           (<= (min (pane-copy-mark pane) (pane-copy-cursor pane)) i
                               (max (pane-copy-mark pane) (pane-copy-cursor pane)))
                           (= i (pane-copy-cursor pane)))
        collect (list (list 0 (clip-copy-text (aref (pane-copy-lines pane) i) (terminal-cols (pane-vt pane)))
                            (if selected '(0 7) '(0))))))
(defun search-copy (pane)
  (when (and (pane-copy-lines pane) (plusp (length (pane-search-text pane))))
    (let* ((lines (pane-copy-lines pane))
           (match (loop for step from 1 to (length lines) for i = (mod (+ (pane-copy-cursor pane) step) (length lines))
                        when (search (pane-search-text pane) (aref lines i) :test #'char-equal) return i)))
      (when match (move-copy pane match)))))
(defun search-input-text (bytes)
  ;; Reads and the bounded input buffer can end inside a UTF-8 character.
  (loop for end from (length bytes) downto (max 0 (- (length bytes) 4))
        for text = (handler-case (bytes-text (subseq bytes 0 end)) (error () nil))
        when text return text finally (return "")))
(defun copy-search-input (session bytes)
  (let ((pane (focused-pane session)))
    (loop for byte across bytes do
      (case byte
        (27 (setf (pane-search-input pane) nil) (return))
        ((10 13) (setf (pane-search-text pane) (search-input-text (pane-search-input pane)) (pane-search-input pane) nil)
                 (search-copy pane) (return))
        ((8 127) (let* ((input (pane-search-input pane)) (end (1- (length input))))
                   (when (>= end 0)
                     (loop while (and (plusp end) (= (logand (aref input end) #xc0) #x80)) do (decf end))
                     (setf (pane-search-input pane) (subseq input 0 end)))))
        (t (when (< (length (pane-search-input pane)) 256)
             (setf (pane-search-input pane) (concatenate '(vector (unsigned-byte 8)) (pane-search-input pane) (octets-from-list (list byte))))))))
    (incf (session-revision session))))
(defun status-text (session)
  (let ((pane (focused-pane session)))
    (cond ((pane-search-input pane) (format nil "Search: ~A" (search-input-text (pane-search-input pane))))
          ((pane-copy-lines pane) "Copy: j/k move  b/f page  Space mark  Enter copy  / search  n next  q exit")
          ((plusp (length (session-notice session))) (session-notice session))
          ((session-contributions session)
           (loop for component in (reverse (getf (session-registry session) :components))
                 for contribution = (assoc (getf component :id) (session-contributions session) :test #'equal)
                 when contribution return (cdr contribution)))
          (t (option session :status-text "")))))

(defun json-string (string)
  (with-output-to-string (out)
    (write-char #\" out)
    (loop for c across string do
      (case c (#\" (write-string "\\\"" out)) (#\\ (write-string "\\\\" out))
            (otherwise (if (< (char-code c) 32) (format out "\\u~4,'0X" (char-code c)) (write-char c out)))))
    (write-char #\" out)))
(defun json-value (value)
  (cond ((null value) "null") ((eq value :false) "false") ((eq value t) "true") ((stringp value) (json-string value))
        ((keywordp value) (json-string (string-downcase (symbol-name value))))
        ((floatp value) (format nil "~F" value)) ((integerp value) (princ-to-string value))
        ((and (consp value) (eq (first value) :object))
         (format nil "{~{~A~^,~}}" (loop for (key val) on (rest value) by #'cddr
                                        collect (format nil "~A:~A" (json-value key) (json-value val)))))
        ((listp value) (format nil "[~{~A~^,~}]" (mapcar #'json-value value)))
        (t (error "Not JSON data"))))
(defun inspect-json (session)
  (let ((registry (session-registry session)))
    (json-value
      (list :object :generation (session-config-generation session) :error (session-config-error session)
            :disabled-hooks (session-disabled-hooks session)
            :contributions (loop for (owner . text) in (session-contributions session)
                                 collect (list :object :owner owner :text text))
            :options (cons :object (getf registry :options)) :layout (session-tree session)
            :components (mapcar (lambda (c) (cons :object c)) (getf registry :components))
            :commands (mapcar (lambda (c) (cons :object c)) (getf registry :commands))
            :bindings (mapcar (lambda (c) (cons :object c)) (getf registry :bindings))))))
(defun split-arguments (bytes)
  (loop for start = 0 then (1+ end) for end = (position 0 bytes :start start)
        collect (bytes-text (subseq bytes start end)) while end))
