(in-package #:ekko/runtime)

(defun option (session key &optional default)
  (getf (getf (session-registry session) :options) key default))
(defun layout-pane-ids (tree)
  "Validate a public layout tree and return its pane leaves."
  (let ((nodes 0))
    (labels ((walk (node)
               ;; Sixteen leaves need at most 31 nodes. Bound traversal before
               ;; descending so an invalid deep tree cannot exhaust the stack.
               (when (> (incf nodes) 31) (error "At most 16 layout leaves are supported"))
               (cond
                 ((and (integerp node) (plusp node)) (list node))
                 ((and (listp node) (= (length node) 4)
                       (member (first node) '(:columns :rows))
                       (typep (second node) '(integer 1 99)))
                  (append (walk (third node)) (walk (fourth node))))
                 (t (error "Invalid layout tree: ~S" tree)))))
      (walk tree))))
(defun validate-layout-tree (session tree)
  (let ((ids (layout-pane-ids tree))
        (existing (mapcar #'pane-id (session-panes session))))
    (unless (and (<= 1 (length ids) 16)
                 (= (length ids) (length (remove-duplicates ids)))
                 (equal (sort (copy-list ids) #'<)
                        (sort (copy-list existing) #'<)))
      (error "Layout leaves must name each existing pane exactly once"))
    t))
(defun validate-component-state (value)
  (let ((active (make-hash-table :test #'eq)) (nodes 0) (bytes 0))
    (labels ((walk (x depth)
               (when (> depth 16) (error "Component state is too deep"))
               (when (> (incf nodes) 1024) (error "Component state has too many nodes"))
               (cond
                 ((or (null x) (eq x t) (keywordp x) (integerp x)) nil)
                 ((stringp x) (incf bytes (length (text-bytes x))))
                 ((consp x)
                  (let ((marked nil) (tail x))
                    (loop while (consp tail) do
                      (when (gethash tail active) (error "Cyclic component state"))
                      (setf (gethash tail active) t)
                      (push tail marked)
                      (walk (car tail) (1+ depth))
                      (setf tail (cdr tail)))
                    (unless (null tail) (error "Component state needs proper lists"))
                    (dolist (cell marked) (remhash cell active))))
                 (t (error "Invalid component state value")))))
      (walk value 0)
      (when (> bytes 16384) (error "Component state exceeds 16 KiB")))
    t))
(defun component-state-bytes (entries)
  (loop for (owner . value) in entries
        sum (length (text-bytes (prin1-to-string (list owner value))))))
(defun copy-component-state (value)
  (if (consp value)
      (cons (copy-component-state (car value))
            (copy-component-state (cdr value)))
      (if (stringp value) (copy-seq value) value)))
(defun context-data (session)
  (multiple-value-bind (insets pane gaps width height) (session-geometry session)
    (declare (ignore width height))
    (let ((visible (visible-panes session))
          (tiled (session-rectangles session nil)))
      (list :session (session-name session) :mode (session-mode session)
            :focus (pane-id (focused-pane session)) :zoom (session-zoom session)
            :viewport (list :cols (session-cols session) :rows (session-rows session)
                            :cell-width (session-cw session) :cell-height (session-ch session)
                            :reported-cell-width (session-reported-cw session)
                            :reported-cell-height (session-reported-ch session)
                            :insets insets :gaps gaps)
            :geometry (list :pane-insets pane
                            :boundary-insets (geometry-value session :boundary-insets nil)
                            :viewport-insets insets :split-gaps gaps)
            :chrome-status (list :text (status-text session)
                                 :style (option session :status-style '(0 30 47)))
            :pane-notes (pane-note-data session)
            :component-state (loop for (owner . value) in (session-component-state session)
                                   collect (cons (copy-seq owner) (copy-component-state value)))
            :layout (copy-tree (session-tree session))
            :panes (loop for p in (session-panes session) collect
                     (let ((vt (pane-vt p)))
                       (list :id (pane-id p) :label (pane-label p)
                             :name (and (pane-name p) (copy-seq (pane-name p)))
                             :argv (mapcar #'copy-seq (pane-argv p))
                             :launch-kind (pane-launch-kind p)
                             :creation-position (pane-creation-position p)
                             :terminal-title (and (terminal-title vt)
                                                  (copy-seq (terminal-title vt)))
                             :activation-order (pane-activation-order p)
                             :layout-rect (copy-list (rest (assoc (pane-id p) tiled)))
                             :display-label (if (pane-copy-lines p)
                                                (format nil "~A [copy ~D/~D]" (pane-label p)
                                                        (1+ (pane-copy-cursor p))
                                                        (length (pane-copy-lines p)))
                                                (pane-label p))
                             :pid (pane-pid p) :cols (terminal-cols vt) :rows (terminal-rows vt)
                             :pty-size (copy-list (pane-pty-size p))
                             :x (pane-x p) :y (pane-y p)
                             :outer-rect (list (pane-outer-x p) (pane-outer-y p)
                                               (pane-outer-cols p) (pane-outer-rows p))
                             :visible (not (null (find p visible)))
                             :history-rows (if (and (terminal-history vt)
                                                    (eq (terminal-screen vt) :main))
                                               (history-count (terminal-history vt)) 0)
                             :exit (pane-status p))))))))
(defun install-registry (session registry)
  (unless (and (= (getf registry :api-version 0) 1)
               (<= (length (getf registry :components)) 64)
               (<= (length (getf registry :commands)) 256)
               (<= (length (getf registry :bindings)) 256)
               (<= (length (getf registry :keymaps)) 256))
    (error "Invalid extension registry"))
  (flet ((known (name) (find name (getf registry :keymaps) :key (lambda (m) (getf m :name)))))
    (when (and (getf (getf registry :options) :initial-keymap)
               (not (known (getf (getf registry :options) :initial-keymap))))
      (error "Initial keymap is not registered"))
    (dolist (binding (getf registry :bindings))
      (unless (or (member (getf binding :map) '(:prefix :copy)) (known (getf binding :map)))
        (error "Binding references unknown keymap"))))
  (dolist (binding (getf registry :bindings))
    (unless (or (null (getf binding :command))
                (find (getf binding :command) (getf registry :commands) :key (lambda (c) (getf c :name)) :test #'equal))
      (error "Binding references unknown command: ~A" (getf binding :command))))
  (dolist (keymap (getf registry :keymaps))
    (let ((fallback (getf keymap :unbound)))
      (when (and (stringp fallback)
                 (not (find fallback (getf registry :commands)
                            :key (lambda (c) (getf c :name)) :test #'equal)))
        (error "Keymap fallback references unknown command: ~A" fallback))))
  (unless (find (session-mode session) (getf registry :keymaps) :key (lambda (m) (getf m :name)))
    (setf (session-mode session) (getf (getf registry :options) :initial-keymap)
          (session-prefix session) nil (session-key-fragment session) nil
          (session-key-fragment-mode session) nil
          (session-input-read-bytes session) nil))
  (let ((owners (getf registry :components)))
    (setf (session-component-state session)
          (remove-if-not (lambda (entry)
                           (find (car entry) owners :key (lambda (c) (getf c :id)) :test #'equal))
                         (session-component-state session)))
    (setf (session-geometry-contributions session)
          (remove-if-not (lambda (entry)
                          (find (car entry) owners :key (lambda (c) (getf c :id)) :test #'equal))
                        (session-geometry-contributions session))))
  (setf (session-registry session) registry (session-config-error session) nil
        (session-contributions session) nil (session-decorations session) nil
        (session-pane-notes session) nil
        (session-hook-context session) nil (session-hooks session) nil)
  (incf (session-config-generation session))
  (if (and (session-panes session) (session-tree session))
      (layout session)
      (incf (session-revision session))))
(defun command-pending-p (session)
  (or (session-command-queue session)
      (and (session-worker session) (eq (first (extension-worker-request (session-worker session))) :command))
      (and (null (session-worker session)) (session-candidate session))))
(defun defer-input (session kind data)
  (when (> (+ (session-input-bytes session) (length data)) 65536) (error "Pending command input exceeds 64 KiB"))
  (push (list (session-writer session) kind data) (session-input-queue session)) (incf (session-input-bytes session) (length data)))
(defun replay-input (session)
  (let ((pending (nreverse (session-input-queue session))))
    (setf (session-input-queue session) nil (session-input-bytes session) 0)
    (dolist (item pending)
      (destructuring-bind (writer kind data) item
        (when (and writer (eq writer (session-writer session)))
          (server-packet session writer
            (concatenate '(vector (unsigned-byte 8)) (octets-from-list (list kind)) data)))))))
(defun semantic-key (bytes key)
  (or (cdr (assoc (map 'string #'code-char bytes)
                 (loop for (suffix . value) in '(("[A" . :up) ("[B" . :down) ("[C" . :right) ("[D" . :left)
                                                 ("OA" . :up) ("OB" . :down) ("OC" . :right) ("OD" . :left)
                                                 ("[5~" . :page-up)
                                                 ("[6~" . :page-down) ("[H" . :home) ("[F" . :end))
                       collect (cons (concatenate 'string (string #\Esc) suffix) value)) :test #'equal))
      (cdr (assoc key '((57350 . :left) (57351 . :right) (57352 . :up) (57353 . :down) (57354 . :page-up) (57355 . :page-down)
                        (57356 . :home) (57357 . :end)))) key))
(defun key-binding (session map key)
  (find-if (lambda (b) (and (eq map (getf b :map)) (eql key (getf b :key))))
                          (reverse (getf (session-registry session) :bindings))))
(defun dispatch-binding (session map key)
  (let ((binding (key-binding session map key)))
    (when (and binding (getf binding :command))
      (handler-case (request-command session (getf binding :command) (list :arguments nil) nil)
        (error (e) (note-error session e))))))
(defun dispatch-keymap-fallback (session map key bytes &optional read-bytes)
  "Dispatch a named keymap fallback through the ordinary worker command path."
  (let* ((policy (find map (reverse (getf (session-registry session) :keymaps))
                       :key (lambda (m) (getf m :name))))
         (fallback (and policy (getf policy :unbound))))
    (when (stringp fallback)
      (handler-case
          (request-command session fallback
                           (append (list :key (semantic-key bytes key)
                                         :bytes (coerce bytes 'list))
                                   (when (session-input-read-framed session)
                                     (list :read-bytes (and read-bytes (coerce read-bytes 'list))))) nil)
        (error (e) (note-error session e)))
      t)))
(defun request-command (session name event peer)
  (unless (find name (getf (session-registry session) :commands) :key (lambda (c) (getf c :name)) :test #'equal)
    (error "Unknown command: ~A" name))
  (let ((worker (session-worker session)))
    (unless worker (error "Extension worker is restarting; use config reload if recovery fails"))
    (when (extension-worker-request worker)
      (when (>= (length (session-command-queue session)) 32) (error "Command queue full"))
      (setf (session-command-queue session) (append (session-command-queue session) (list (list name event peer))))
      (return-from request-command))
    (extension-send (extension-worker-output worker) (list :dispatch :command name (context-data session) event))
    (setf (session-notice session) ""
          (extension-worker-request worker) (list :command name peer)
          (extension-worker-deadline worker) (+ (now) 1/20))))
(defun command-reply (peer message &optional errorp)
  (when (and peer (>= (wire-fd peer) 0))
    (handler-case
        (progn (send-packet peer (if errorp 21 20) (text-bytes message)) (flush-wire peer))
      (error () (close-wire peer)))))
(defun note-error (session error)
  (let ((message (subseq (princ-to-string error) 0 (min 1000 (length (princ-to-string error))))))
    (setf (session-config-error session) message (session-notice session) message)
    (incf (session-revision session))
    (format *error-output* "configuration: ~A~%" message)))
(defun start-reload (session peer &optional recover)
  (when (session-candidate session) (error "A configuration reload is already running"))
  (let* ((active (session-worker session)) (path (if active (extension-worker-path active) (config-path)))
         (source (if (and recover active) (extension-worker-source active) (config-source path))))
    (setf (session-candidate session)
          (start-worker source path (concatenate 'string (socket-path (session-name session)) ".extensions.log"))
          (extension-worker-recovery (session-candidate session)) recover
          (session-reload-peer session) peer)))
(defun hook-context-current-p (session request)
  (let* ((owner (second request))
         (component (find owner (getf (session-registry session) :components)
                          :key (lambda (entry) (getf entry :id)) :test #'equal))
         (snapshot (third request))
         (current (context-data session)))
    (and component
         (every (lambda (key) (equal (getf snapshot key) (getf current key)))
                (getf component :reads)))))
(defun service-extensions (session buffer)
  (let ((candidate (session-candidate session)))
    (when candidate
      (handler-case
          (progn
            (when (eq (extension-worker-request candidate) :load)
              (let ((response (poll-worker candidate buffer)))
                (when response
                  (unless (eq (first response) :ready) (error "~A" (second response)))
                  ;; Validate on a detached session before replacing registrations.
                  (let ((trial (make-session))) (install-registry trial (second response)))
                  (setf (extension-worker-registry candidate) (second response)
                        (extension-worker-request candidate) nil))))
            (when (and (null (extension-worker-request candidate))
                       (or (null (session-worker session)) (null (extension-worker-request (session-worker session)))))
              (stop-worker (session-worker session))
              (setf (session-worker session) candidate (session-candidate session) nil)
              (install-registry session (extension-worker-registry candidate))
              (unless (extension-worker-recovery candidate) (setf (session-disabled-hooks session) nil))
              (setf (session-notice session) "")
              (command-reply (session-reload-peer session) "") (setf (session-reload-peer session) nil)
              (replay-input session)))
        (error (e)
          (note-error session e) (command-reply (session-reload-peer session) (princ-to-string e) t)
          (stop-worker candidate) (setf (session-candidate session) nil (session-reload-peer session) nil)
          (unless (session-worker session)
            (dolist (command (session-command-queue session))
              (command-reply (third command) "Extension recovery failed; use config reload" t))
            (setf (session-command-queue session) nil)
            (replay-input session))))))
  (let ((worker (session-worker session)))
    (when worker
      (handler-case
          (let ((response (poll-worker worker buffer)) (request (extension-worker-request worker)))
            (when response
              (setf (extension-worker-request worker) nil)
              (handler-case
                  (progn
                    (when (eq (first response) :error) (error "~A" (second response)))
                    (unless (eq (first response) :result) (error "Invalid extension result"))
                    (when (or (eq (first request) :command)
                              (and (eq (first request) :hook)
                                   (hook-context-current-p session request)))
                      (apply-actions session (getf (second response) :owner) (getf (second response) :actions)
                                     (eq (first request) :hook) (when (eq (first request) :command) (third request))))
                    (when (and (eq (first request) :command) (not (eq (third request) (session-reload-peer session))))
                      (command-reply (third request) "")))
                (error (e) (note-error session e)
                  (when (eq (first request) :command) (command-reply (third request) (princ-to-string e) t))))
              (replay-input session)))
        (error (e)
          (let ((request (extension-worker-request worker)))
            (note-error session e)
            (when (and (listp request) (eq (first request) :command))
              (command-reply (third request) (princ-to-string e) t))
            ;; Recover from the last successfully loaded source, even if the file
            ;; on disk has since become invalid. Never reload inside a callback.
            (when (and (listp request) (eq (first request) :hook))
              (pushnew (second request) (session-disabled-hooks session) :test #'equal))
            (handler-case
                (unless (session-candidate session) (start-reload session nil t))
              (error (recovery-error) (note-error session recovery-error)))
            (stop-worker worker) (setf (session-worker session) nil))))))
  (let ((worker (session-worker session)))
    (when (and worker (null (extension-worker-request worker)) (session-command-queue session))
      (let ((command (pop (session-command-queue session))))
        (handler-case (apply #'request-command session command)
          (error (e) (note-error session e) (command-reply (third command) (princ-to-string e) t)
            (replay-input session))))))
  (schedule-hooks session))
(defun schedule-hooks (session)
  (let ((context (context-data session)) (previous (session-hook-context session)))
    (unless (equal context previous)
      (let ((changed (loop for key in ekko/extensions::*context-keys*
                           unless (and previous (equal (getf context key) (getf previous key))) collect key)))
        (dolist (component (getf (session-registry session) :components))
          (when (and (getf component :hook)
                     (not (member (getf component :id) (session-disabled-hooks session) :test #'equal))
                     (or (null previous) (intersection changed (getf component :reads))))
            (pushnew (getf component :id) (session-hooks session) :test #'equal))))
      (setf (session-hook-context session) context)))
  (let ((worker (session-worker session)))
    (when (and worker (null (extension-worker-request worker)) (session-hooks session))
      (let ((id (pop (session-hooks session))) (context (context-data session)))
        (setf (extension-worker-request worker) (list :hook id context)
              (extension-worker-deadline worker) (+ (now) 1/20))
        (extension-send (extension-worker-output worker)
                        (list :dispatch :hook id context (list :type :change)))))))

(defun valid-decoration-text-p (text)
  (and (stringp text)
       (every (lambda (char)
                (let ((code (char-code char)))
                  (and (>= code 32) (/= code 127) (not (<= #x80 code #x9f))))) text)))
(defun validate-decoration-spans (spans)
  (unless (and (listp spans) (<= (length spans) 1024))
    (error "At most 1024 decoration spans are allowed"))
  (let ((total 0))
    (dolist (span spans)
      (unless (and (listp span) (evenp (length span))) (error "Malformed decoration span: ~S" span))
      (let ((keys nil))
        (loop for (key value) on span by #'cddr do
          (unless (member key '(:x :y :text :sgr :rows :overlay)) (error "Unknown decoration field: ~S" key))
          (when (member key keys) (error "Duplicate decoration field: ~S" key))
          (push key keys))
        (let ((x (getf span :x)) (y (getf span :y)) (text (getf span :text))
              (sgr (getf span :sgr)) (rows (getf span :rows 1)))
          (unless (and (integerp x) (<= 0 x 499) (integerp y) (<= 0 y 299)
                       (member (getf span :overlay) '(nil t))
                       (integerp rows) (<= 1 rows 300)
                       (valid-decoration-text-p text)
                       (listp sgr) (<= (length sgr) 16)
                       (every (lambda (n) (and (integerp n) (<= 0 n 255))) sgr))
            (error "Invalid decoration span: ~S" span))
          (incf total (* rows (length text))))))
    (when (> total 16000) (error "Decoration text exceeds 16000 characters")))
  t)
(defun bounded-geometry-p (value length)
  (and (listp value) (= (length value) length)
       (every (lambda (n) (and (integerp n) (<= 0 n 16))) value)))
(defun validate-geometry-value (value)
  (unless (or (null value) (and (listp value) (evenp (length value))
                                (<= (length value) 8)))
    (error "Geometry value must be a proper property list"))
  (loop with seen = nil
        for (key item) on value by #'cddr do
    (unless (member key '(:pane-insets :boundary-insets :viewport-insets :split-gaps))
      (error "Unknown geometry field: ~S" key))
    (when (member key seen)
      (error "Duplicate geometry field: ~S" key))
    (push key seen)
    (unless (or (and (member key '(:pane-insets :boundary-insets :viewport-insets))
                     (bounded-geometry-p item 4))
                (and (eq key :split-gaps) (bounded-geometry-p item 2)))
      (error "Invalid geometry field: ~S" key)))
  (copy-tree value))
(defun validate-actions (session actions hook &optional owner)
  (unless (and (listp actions) (<= (length actions) 32)) (error "At most 32 actions are allowed"))
  (let ((primary-count 0) (mode-count 0) (state-count 0) (mode-before-primary nil) (primary-seen nil))
    (dolist (a actions)
      (unless (and (listp a) (oddp (length a))) (error "Malformed action: ~S" a))
      (let* ((op (first a)) (args (rest a)) (pane (getf args :pane))
             (keys (case op
                     (:pane-note '(:pane :text :sgr :duration))
                     (:send-input '(:bytes)) (:set-keymap '(:name)) (:set-layout '(:tree)) (:set-state '(:value)) (:set-geometry '(:value)) (:decorate '(:spans)) (:split '(:pane :axis :argv)) (:focus '(:pane)) (:rename '(:pane :text)) (:resize '(:delta))
                     (:close '(:focus)) (:copy-move '(:delta)) (:copy-edge '(:edge)) (:status '(:text))
                     ((:focus-next :zoom :swap :detach :stop :copy-mode :copy-mark :copy-selection
                       :copy-exit :copy-search :copy-search-next :paste-buffer :reload :help) nil)
                     (otherwise (error "Unknown action: ~S" op)))))
        (loop for (key value) on args by #'cddr do (unless (member key keys) (error "Unknown action argument: ~S" key)))
        (unless (= (length (loop for (key value) on args by #'cddr collect key))
                   (length (remove-duplicates (loop for (key value) on args by #'cddr collect key))))
          (error "Duplicate action argument"))
        (when (and hook (not (member op '(:status :decorate))))
          (error "Change hooks may only contribute status or decorations"))
        (when (and pane (not (pane-by-id session pane))) (error "Unknown pane: ~S" pane))
        (case op
          (:set-keymap
           (incf mode-count)
           (when (> mode-count 1) (error "A batch may contain at most one keymap transition"))
           (unless primary-seen (setf mode-before-primary t))
           (unless (find (getf args :name) (getf (session-registry session) :keymaps)
                         :key (lambda (m) (getf m :name)))
             (error "Unknown keymap")))
          ((:status :decorate :pane-note :set-state)
           (when (eq op :set-state)
             (incf state-count)
             (when (> state-count 1) (error "A batch may contain at most one state update"))
             (unless (find owner (getf (session-registry session) :components)
                           :key (lambda (component) (getf component :id)) :test #'equal)
               (error "State needs a registered component owner"))
             (validate-component-state (getf args :value))))
          (:set-geometry
           (incf primary-count) (setf primary-seen t)
           (unless (find owner (getf (session-registry session) :components)
                         :key (lambda (component) (getf component :id)) :test #'equal)
             (error "Geometry needs a registered component owner"))
           (validate-geometry-value (getf args :value)))
          (otherwise (incf primary-count) (setf primary-seen t)))
        (case op
          (:send-input
           (unless (and (listp (getf args :bytes)) (<= (length (getf args :bytes)) 4096)
                        (every (lambda (b) (typep b '(unsigned-byte 8))) (getf args :bytes)))
             (error "Invalid input bytes")))
          (:focus (unless pane (error "Focus needs a pane ID")))
          (:close
           (when (member :focus args)
             (let ((replacement (pane-by-id session (getf args :focus))))
               (unless (and replacement (not (eq replacement (focused-pane session))))
                 (error "Close focus must name a surviving pane")))))
          ((:status :rename) (unless (and (stringp (getf args :text)) (<= (length (getf args :text)) 512))
                              (error "Text must contain at most 512 characters")))
          (:decorate (validate-decoration-spans (getf args :spans)))
          (:pane-note
           (unless (and pane (valid-decoration-text-p (getf args :text))
                        (<= (length (getf args :text)) 512)
                        (typep (getf args :duration) '(integer 1 60000))
                        (listp (getf args :sgr)) (<= (length (getf args :sgr)) 16)
                        (every (lambda (n) (typep n '(integer 0 255))) (getf args :sgr)))
             (error "Invalid pane note")))
          ((:resize :copy-move) (unless (and (integerp (getf args :delta)) (<= -10000 (getf args :delta) 10000))
                                 (error "Invalid movement")))
          (:copy-edge (unless (member (getf args :edge) '(:start :end)) (error "Invalid edge")))
          (:set-layout (validate-layout-tree session (getf args :tree)))
          (:split
           (unless (member (getf args :axis) '(:columns :rows)) (error "Invalid split axis"))
           (when (>= (length (session-panes session)) 16) (error "At most 16 panes are supported"))
           (let ((argv (getf args :argv (option session :shell '("/bin/sh" "-i")))))
             (unless (and (listp argv) (<= 1 (length argv) 64)
                          (every (lambda (s) (and (stringp s) (<= (length s) 4096) (not (find #\Null s)))) argv)
                          (plusp (length (first argv)))) (error "Invalid executable argument vector"))))))
    (when (> primary-count 1)
      (error "A batch may contain one session action plus status contributions"))
    (when (and (plusp primary-count) mode-before-primary)
      (error "A keymap transition must follow the session action"))
      (let ((state-action (find :set-state actions :key #'first)))
      (when state-action
        (let* ((value (getf (rest state-action) :value))
               (entries (remove owner (session-component-state session)
                                :key #'car :test #'equal)))
          (when value
            (push (cons owner value) entries))
          (when (> (component-state-bytes entries) 16384)
            (error "Aggregate component state exceeds 16 KiB")))))
    ;; Contributions are bounded across the retained owner set as well as per
    ;; action. The invoking owner's replacement is staged in this calculation,
    ;; so a rejected batch cannot evict its previous contribution.
    (let ((replacement nil))
      (dolist (a actions)
        (when (eq (first a) :decorate)
          (setf replacement (copy-tree (getf (rest a) :spans)))))
      (when replacement
        (let ((entries (remove owner (session-decorations session)
                              :key #'car :test #'equal)))
          (push (cons owner replacement) entries)
          (let ((count 0) (text-length 0))
            (dolist (entry entries)
              (incf count (length (cdr entry)))
              (dolist (span (cdr entry))
                (let ((rows (getf span :rows 1)))
                  (incf text-length (* rows (length (getf span :text)))))))
            (when (> count 1024) (error "At most 1024 retained decoration spans are allowed"))
            (when (> text-length 16000) (error "Retained decoration text exceeds 16000 characters")))))))))
(defun apply-actions (session owner actions hook peer)
  (validate-actions session actions hook owner)
  ;; Complete a mode transition only after the primary action succeeds. This
  ;; keeps mode and status contributions out of a batch whose primary action
  ;; raises after partially updating its own state.
  (let ((primary (find-if (lambda (a) (and (not (member (first a) '(:status :decorate :pane-note :set-state)))
                                           (not (eq (first a) :set-keymap)))) actions))
        (mode-transition (find-if (lambda (a) (eq (first a) :set-keymap)) actions)))
    (when primary (apply-session-action session (first primary) (rest primary) peer))
    (when mode-transition
      (apply-session-action session (first mode-transition) (rest mode-transition) peer)))
  (dolist (a actions)
    (case (first a)
      (:pane-note
       (let* ((args (rest a))
              (existing (find-if (lambda (note)
                                   (and (equal owner (getf note :owner))
                                        (eql (getf args :pane) (getf note :pane))))
                                 (session-pane-notes session))))
         ;; Repeating an identical active note leaves its deadline intact.
         (unless (and existing (> (getf existing :until) (now))
                      (equal (getf args :text) (getf existing :text))
                      (equal (getf args :sgr) (getf existing :sgr)))
           (setf (session-pane-notes session)
                 (cons (list :owner owner :pane (getf args :pane)
                             :text (copy-seq (getf args :text)) :sgr (copy-list (getf args :sgr))
                             :until (+ (now) (/ (getf args :duration) 1000)))
                       (remove existing (session-pane-notes session)))))))
      (:status
       (setf (session-contributions session)
             (acons owner (getf (rest a) :text) (remove owner (session-contributions session) :key #'car :test #'equal))))
      (:decorate
       (setf (session-decorations session)
             (acons owner (copy-tree (getf (rest a) :spans))
                    (remove owner (session-decorations session) :key #'car :test #'equal))))
      (:set-state
       (let ((value (getf (rest a) :value)))
         (setf (session-component-state session)
               (remove owner (session-component-state session) :key #'car :test #'equal))
         (when value
           (push (cons owner (copy-component-state value))
                 (session-component-state session)))))
      (:set-geometry
       (let ((value (validate-geometry-value (getf (rest a) :value))))
         (setf (session-geometry-contributions session)
               (remove owner (session-geometry-contributions session) :key #'car :test #'equal))
         (when value
           (push (cons owner value) (session-geometry-contributions session)))
         (layout session)))))
  (when actions (incf (session-revision session))))
(defun apply-session-action (session op args peer)
  (let* ((pane (or (and (getf args :pane) (pane-by-id session (getf args :pane))) (focused-pane session)))
         (id (pane-id pane)))
    (case op
      (:set-keymap (setf (session-mode session) (getf args :name) (session-prefix session) nil
                         (session-key-fragment session) nil (session-key-fragment-mode session) nil))
      (:set-layout
       (setf (session-tree session) (copy-tree (getf args :tree)))
       (layout session))
      (:split
       (let* ((argv (copy-list (getf args :argv (option session :shell '("/bin/sh" "-i")))))
              (new-id (session-next-pane-id session))
              (new-tree (ekko/layout:split-pane (session-tree session) id new-id (getf args :axis)))
              (new-placeholder (make-pane :id new-id :vt (make-terminal :cols 1 :rows 1
                                                                          :cw (session-cw session)
                                                                          :ch (session-ch session))
                                  :argv argv
                                  :launch-kind (if (member :argv args) :command :shell)
                                  :creation-position (1+ (length (session-panes session)))))
              ;; Compute the post-split focused layout without changing the
              ;; live session. This lets the PTY start at its final size.
              (planned (make-session :name (session-name session)
                                     :panes (append (session-panes session) (list new-placeholder))
                                     :cols (session-cols session) :rows (session-rows session)
                                     :cw (session-cw session) :ch (session-ch session)
                                     :focus (length (session-panes session)) :zoom nil
                                     :registry (session-registry session) :tree new-tree))
              (rect (find new-id (session-rectangles planned) :key #'first))
              (x (if rect (second rect) 0)) (y (if rect (third rect) 0))
              (width (if rect (fourth rect) 1)) (height (if rect (fifth rect) 1)))
         (multiple-value-bind (cols rows) (content-size planned width height x y)
           ;; Acquire the only fallible resource before changing live logical
           ;; state. Existing panes are resized by set-focus after this spawn.
           (multiple-value-bind (fd pid)
               (multiple-value-call #'spawn argv cols rows (pty-cell-size session))
              (let ((new (make-pane :id new-id :pid pid :io (make-wire :fd fd)
                                   :vt (make-terminal :cols cols :rows rows
                                                       :cw (session-cw session) :ch (session-ch session))
                                   :argv argv :label (file-namestring (first argv))
                                   :launch-kind (if (member :argv args) :command :shell)
                                   :creation-position (1+ (length (session-panes session)))
                                   :pty-size (pty-size-for session cols rows))))
               (setf (session-panes session) (append (session-panes session) (list new))
                     (session-tree session) new-tree
                     (session-zoom session) nil)
               (incf (session-next-pane-id session))
               (set-focus session (1- (length (session-panes session))) t))))))
      (:close
       (if (= (length (session-panes session)) 1) (setf (session-stopping session) t)
           (let ((focus (focused-pane session)))
             (close-pane pane)
             (clear-screen (pane-graphics pane) :main) (clear-screen (pane-graphics pane) :alternate)
             (push (cons pane (+ (now) 1)) (session-retired session))
             (setf (session-panes session) (remove pane (session-panes session))
                   (session-tree session) (ekko/layout:remove-pane (session-tree session) id)
                   (session-focus session) (or (and (getf args :focus)
                                                   (position (getf args :focus) (session-panes session)
                                                             :key #'pane-id))
                                              (position focus (session-panes session)) 0)
                   (session-drag session) nil (session-paste-target session) nil)
             (when (eq pane focus) (record-activation session (focused-pane session)))
             (layout session)
             ;; Closing a pane must not leave a note for the removed pane in
             ;; the next snapshot.  Use the same expiry/pruning path as the
             ;; daemon maintenance loop now that the pane tree is committed.
             (expire-pane-notes session))))
      (:rename (setf (pane-label pane) (getf args :text)
                     (pane-name pane) (getf args :text)))
      (:focus (set-focus session (position pane (session-panes session))))
      (:focus-next (set-focus session (mod (1+ (session-focus session)) (length (session-panes session)))))
      (:zoom (setf (session-zoom session) (not (session-zoom session))) (layout session))
      (:swap (when (> (length (session-panes session)) 1)
               (setf (session-tree session)
                     (ekko/layout:swap-panes (session-tree session) id
                       (pane-id (nth (mod (1+ (session-focus session)) (length (session-panes session))) (session-panes session)))))
               (layout session)))
      (:resize (setf (session-tree session) (ekko/layout:resize-split (session-tree session) id (getf args :delta))) (layout session))
      (:detach (when (session-writer session) (send-packet (session-writer session) 22)))
      (:stop (setf (session-stopping session) t))
      (:reload (start-reload session peer))
      (:help (enter-copy pane (coerce (cons "Registered prefix bindings (q exits)"
                       (loop for b in (reverse (getf (session-registry session) :bindings))
                             when (eq (getf b :map) :prefix) collect
                               (format nil "~A -> ~A (~A)" (getf b :key) (getf b :command) (getf b :owner)))) 'vector)))
      (:send-input (pane-input pane (octets-from-list (getf args :bytes))))
      (:copy-mode (enter-copy pane (history-text (pane-vt pane))))
      (:copy-exit (setf (pane-copy-lines pane) nil (pane-search-input pane) nil))
      (:copy-move (when (pane-copy-lines pane) (move-copy pane (+ (pane-copy-cursor pane) (getf args :delta)))))
      (:copy-edge (when (pane-copy-lines pane) (move-copy pane (if (eq (getf args :edge) :start) 0 (1- (length (pane-copy-lines pane)))))))
      (:copy-mark (when (pane-copy-lines pane) (setf (pane-copy-mark pane) (pane-copy-cursor pane))))
      (:copy-selection
       (when (pane-copy-lines pane)
         (let* ((start (min (or (pane-copy-mark pane) (pane-copy-cursor pane)) (pane-copy-cursor pane)))
                (end (max (or (pane-copy-mark pane) (pane-copy-cursor pane)) (pane-copy-cursor pane)))
                (text (format nil "~{~A~^~%~}" (coerce (subseq (pane-copy-lines pane) start (1+ end)) 'list))))
           (when (> (length (text-bytes text)) (* 1024 1024)) (error "Copy exceeds 1 MiB"))
           (setf (session-clipboard session) text (pane-copy-lines pane) nil (session-notice session) "Copied to Ekko buffer"))))
      (:copy-search (when (pane-copy-lines pane) (setf (pane-search-input pane) (octets 0))))
      (:copy-search-next (search-copy pane))
      (:paste-buffer
       (let* ((text (session-clipboard session)) (bytes (text-bytes text))
              (bracketed (gethash 2004 (terminal-modes (pane-vt pane)))))
         (when (> (length bytes) 60000) (error "Paste exceeds pane input capacity; export with ekko buffer"))
         (pane-input pane (if bracketed (concatenate '(vector (unsigned-byte 8)) #(27 91 50 48 48 126) bytes #(27 91 50 48 49 126)) bytes)))))))
(defun reap-retired (session)
  (setf (session-retired session)
        (remove-if (lambda (entry)
                     (let ((result (reap (pane-pid (car entry)))))
                       (when (>= (now) (cdr entry)) (signal-group (pane-pid (car entry)) 9))
                       (/= result -11)))
                   (session-retired session))))
(defun enter-copy (pane lines)
  (setf (pane-copy-lines pane) lines (pane-copy-mark pane) nil (pane-search-input pane) nil)
  (move-copy pane (1- (length lines))))
(defun move-copy (pane cursor)
  (setf (pane-copy-cursor pane) (max 0 (min (1- (length (pane-copy-lines pane))) cursor))
        (pane-copy-top pane) (max 0 (min (pane-copy-top pane) (pane-copy-cursor pane))))
  (when (>= (pane-copy-cursor pane) (+ (pane-copy-top pane) (terminal-rows (pane-vt pane))))
    (setf (pane-copy-top pane) (1+ (- (pane-copy-cursor pane) (terminal-rows (pane-vt pane)))))))
(defun clip-copy-text (text cols)
  (let ((width 0) (end 0))
    (loop for c across text for n = (ekko/vt::character-width c) do
      (when (> (+ width n) cols) (return))
      (incf width n) (incf end))
    (subseq text 0 end)))
(defun copy-display-lines (pane)
  (move-copy pane (pane-copy-cursor pane))
  (loop for i from (pane-copy-top pane) below (min (length (pane-copy-lines pane))
                                                 (+ (pane-copy-top pane) (terminal-rows (pane-vt pane))))
        for selected = (if (pane-copy-mark pane)
                           (<= (min (pane-copy-mark pane) (pane-copy-cursor pane)) i
                               (max (pane-copy-mark pane) (pane-copy-cursor pane)))
                           (= i (pane-copy-cursor pane)))
        collect (list (list 0 (clip-copy-text (aref (pane-copy-lines pane) i) (terminal-cols (pane-vt pane)))
                            (if selected '(0 7) '(0))))))
(defun search-copy (pane)
  (when (and (pane-copy-lines pane) (plusp (length (pane-search-text pane))))
    (let* ((lines (pane-copy-lines pane))
           (match (loop for step from 1 to (length lines) for i = (mod (+ (pane-copy-cursor pane) step) (length lines))
                        when (search (pane-search-text pane) (aref lines i) :test #'char-equal) return i)))
      (when match (move-copy pane match)))))
(defun search-input-text (bytes)
  ;; Reads and the bounded input buffer can end inside a UTF-8 character.
  (loop for end from (length bytes) downto (max 0 (- (length bytes) 4))
        for text = (handler-case (bytes-text (subseq bytes 0 end)) (error () nil))
        when text return text finally (return "")))
(defun copy-search-input (session bytes)
  (let ((pane (focused-pane session)))
    (loop for byte across bytes do
      (case byte
        (27 (setf (pane-search-input pane) nil) (return))
        ((10 13) (setf (pane-search-text pane) (search-input-text (pane-search-input pane)) (pane-search-input pane) nil)
                 (search-copy pane) (return))
        ((8 127) (let* ((input (pane-search-input pane)) (end (1- (length input))))
                   (when (>= end 0)
                     (loop while (and (plusp end) (= (logand (aref input end) #xc0) #x80)) do (decf end))
                     (setf (pane-search-input pane) (subseq input 0 end)))))
        (t (when (< (length (pane-search-input pane)) 256)
             (setf (pane-search-input pane) (concatenate '(vector (unsigned-byte 8)) (pane-search-input pane) (octets-from-list (list byte))))))))
    (incf (session-revision session))))
(defun status-text (session)
  (let ((pane (focused-pane session)))
    (cond ((pane-search-input pane) (format nil "Search: ~A" (search-input-text (pane-search-input pane))))
          ((pane-copy-lines pane) "Copy: j/k move  b/f page  Space mark  Enter copy  / search  n next  q exit")
          ((plusp (length (session-notice session))) (session-notice session))
          ((session-contributions session)
           (loop for component in (reverse (getf (session-registry session) :components))
                 for contribution = (assoc (getf component :id) (session-contributions session) :test #'equal)
                 when contribution return (cdr contribution)))
          (t (option session :status-text "")))))

(defun json-string (string)
  (with-output-to-string (out)
    (write-char #\" out)
    (loop for c across string do
      (case c (#\" (write-string "\\\"" out)) (#\\ (write-string "\\\\" out))
            (otherwise (if (< (char-code c) 32) (format out "\\u~4,'0X" (char-code c)) (write-char c out)))))
    (write-char #\" out)))
(defun json-value (value)
  (cond ((null value) "null") ((eq value :false) "false") ((eq value t) "true") ((stringp value) (json-string value))
        ((keywordp value) (json-string (string-downcase (symbol-name value))))
        ((floatp value) (format nil "~F" value)) ((integerp value) (princ-to-string value))
        ((and (consp value) (eq (first value) :object))
         (format nil "{~{~A~^,~}}" (loop for (key val) on (rest value) by #'cddr
                                        collect (format nil "~A:~A" (json-value key) (json-value val)))))
        ((listp value) (format nil "[~{~A~^,~}]" (mapcar #'json-value value)))
        ((vectorp value) (format nil "[~{~A~^,~}]" (map 'list #'json-value value)))
        (t (error "Not JSON data"))))
(defun component-state-json-value (value)
  ;; Plain state must not be interpreted as the inspector's :object/:false
  ;; representation. Preserve keyword values as strings and lists as arrays.
  (cond ((consp value) (map 'vector #'component-state-json-value value))
        ((keywordp value) (string-downcase (symbol-name value)))
        (t value)))
(defun inspect-json (session)
  (let ((registry (session-registry session)))
    (multiple-value-bind (viewport pane gaps width height) (session-geometry session)
      (declare (ignore width height))
      (let ((visible (visible-panes session))
          (tiled (session-rectangles session nil)))
        (json-value
          (list :object :generation (session-config-generation session) :error (session-config-error session)
                :mode (session-mode session)
                :zoom (if (session-zoom session) t :false)
                :viewport (list :object :cols (session-cols session) :rows (session-rows session)
                                :cell-width (session-cw session) :cell-height (session-ch session)
                                :reported-cell-width (session-reported-cw session)
                                :reported-cell-height (session-reported-ch session)
                                :insets viewport :gaps gaps)
                :chrome-status (list :object :text (status-text session)
                                     :style (option session :status-style '(0 30 47)))
                :panes (loop for p in (session-panes session) for vt = (pane-vt p) collect
                         (list :object :id (pane-id p) :label (pane-label p)
                               :argv (pane-argv p) :name (pane-name p)
                               :launch_kind (pane-launch-kind p)
                               :creation_position (pane-creation-position p)
                               :terminal_title (terminal-title vt)
                               :activation_order (pane-activation-order p)
                               :layout_rect (copy-list (rest (assoc (pane-id p) tiled)))
                               :display-label (if (pane-copy-lines p)
                                                  (format nil "~A [copy ~D/~D]" (pane-label p)
                                                          (1+ (pane-copy-cursor p))
                                                          (length (pane-copy-lines p)))
                                                  (pane-label p))
                               :pid (pane-pid p) :cols (terminal-cols vt) :rows (terminal-rows vt)
                               :pty_size (copy-list (pane-pty-size p))
                               :x (pane-x p) :y (pane-y p)
                               :outer_rect (list (pane-outer-x p) (pane-outer-y p)
                                                 (pane-outer-cols p) (pane-outer-rows p))
                               :visible (if (find p visible) t :false)
                               :history_rows (if (and (terminal-history vt)
                                                      (eq (terminal-screen vt) :main))
                                                 (history-count (terminal-history vt)) 0)
                               :exit (pane-status p)))
                :pane-notes (mapcar (lambda (note) (cons :object note)) (pane-note-data session))
                :geometry (list :object :pane-insets pane
                                 :boundary-insets (geometry-value session :boundary-insets nil)
                                 :viewport-insets viewport :split-gaps gaps
                                 :contributions (loop for (owner . value) in (session-geometry-contributions session)
                                                      collect (list :object :owner owner :value (copy-tree value))))
                :keymaps (mapcar (lambda (m) (cons :object m)) (getf registry :keymaps))
                :disabled-hooks (session-disabled-hooks session)
                :decorations (loop for (owner . spans) in (session-decorations session)
                                   collect (list :object :owner owner
                                                 :spans (loop for span in spans collect
                                                          (list :object :x (getf span :x)
                                                                :y (getf span :y)
                                                                :text (getf span :text)
                                                                :sgr (getf span :sgr)
                                                                :rows (getf span :rows 1)
                                                                :overlay (if (getf span :overlay) t :false)))))
                :contributions (loop for (owner . text) in (session-contributions session)
                                     collect (list :object :owner owner :text text))
                :component-state (loop for (owner . value) in (session-component-state session)
                                      collect (list :object :owner owner :value (component-state-json-value value)))
                :options (cons :object (getf registry :options)) :layout (session-tree session)
                :components (mapcar (lambda (c) (cons :object c)) (getf registry :components))
                :commands (mapcar (lambda (c) (cons :object c)) (getf registry :commands))
                :bindings (mapcar (lambda (c) (cons :object c)) (getf registry :bindings))))))))
(defun split-arguments (bytes)
  (loop for start = 0 then (1+ end) for end = (position 0 bytes :start start)
        collect (bytes-text (subseq bytes start end)) while end))
