(in-package #:ekko/runtime)

;; One daemon owns exactly one workspace: every pane, view, the extension
;; worker and the durable component store live directly on the daemon.
;; The workspace persists across detach and ends on `stop', the last pane
;; exiting, or a signal; daemon lifetime is workspace lifetime.
(defstruct daemon path listener lock peers store
  (next-pane-id 1) (next-view-id 1)
  panes tree views home-view launch-directory launch-environment config-path
  retired worker candidate registry
  (config-generation 0) config-error command-queue disabled-hooks hook-failures
  (work-turn 0) dispatch-cursors (recovery-budget 0) (service-failures 0)
  reload-peer initialization-queue candidate-views candidate-results candidate-contexts
  candidate-layouts candidate-stage candidate-members pending-splits
  (clipboard "") (revision 0) (started (now))
  creation stopping torn-down (retire-until 0) quit)
(defstruct creation commands viewport peers (phase :load) initialization extra-requests)
(defstruct launch-request commands viewport directory environment config-path spawn-p)
(defvar *daemon* nil)
(defconstant +daemon-peer-limit+ 256)
(defconstant +retained-view-limit+ 8)

(defun allocate-pane-id (&optional (daemon *daemon*))
  (unless daemon (error "Pane allocation requires a daemon"))
  (when (> (daemon-next-pane-id daemon) #xffffffff) (error "Pane ID space exhausted"))
  (prog1 (daemon-next-pane-id daemon) (incf (daemon-next-pane-id daemon))))
(defun allocate-view-id (daemon)
  (when (> (daemon-next-view-id daemon) #xffffffff) (error "View ID space exhausted"))
  (prog1 (daemon-next-view-id daemon) (incf (daemon-next-view-id daemon))))
(defun workspace-ready-p (daemon)
  "Creation has committed the workspace and it is not being torn down."
  (and (daemon-home-view daemon) (null (daemon-creation daemon))
       (not (daemon-stopping daemon))))
(defun worker-log-path (daemon)
  (format nil "~A.extensions.log" (daemon-path daemon)))
(defun default-shell-argv (daemon)
  (option daemon :shell (list (or (uiop:getenv "SHELL") "/bin/sh") "-i")))

(defun spawn-pane (pane &key directory environment)
  "Acquire a pane's PTY using the same canonical decision as resize."
  (when (or (pane-io pane) (pane-pid pane)) (error "Pane already has a process"))
  (let* ((daemon (pane-daemon pane)) (vt (pane-vt pane)))
    (multiple-value-bind (cols rows source) (pane-sizing pane)
      (let* ((source (or source (daemon-home-view daemon)))
             (cols (or cols (terminal-cols vt))) (rows (or rows (terminal-rows vt)))
             (size (pty-size-for source cols rows)) (io (make-wire :fd -1)))
        (unless (equal (list cols rows (view-cw source) (view-ch source))
                       (list (terminal-cols vt) (terminal-rows vt) (terminal-cw vt) (terminal-ch vt)))
          (resize-terminal vt cols rows (view-cw source) (view-ch source)))
        (multiple-value-bind (cw ch) (pty-cell-size source)
          (multiple-value-bind (fd pid)
              (spawn (pane-argv pane) cols rows cw ch
                     :directory (or directory (daemon-launch-directory daemon))
                     :environment (or environment (daemon-launch-environment daemon)))
            (setf (wire-fd io) fd (pane-io pane) io (pane-pid pane) pid (pane-pty-size pane) size))))))
  pane)

(defun open-panes (daemon commands directory environment)
  "Append each argv in COMMANDS to the workspace and spawn it immediately."
  (when (> (+ (length (daemon-panes daemon)) (length commands))
           (option daemon :pane-budget 16))
    (error "Workspace pane budget is exhausted"))
  (dolist (argv commands)
    (let* ((home (daemon-home-view daemon))
           (pane (make-pane :id (allocate-pane-id daemon) :daemon daemon
                            :vt (make-terminal :cols 1 :rows 1 :cw (view-cw home) :ch (view-ch home))
                            :argv (copy-list argv) :label (file-namestring (first argv))
                            :launch-kind :command
                            :creation-position (1+ (reduce #'max (daemon-panes daemon)
                                                           :key #'pane-creation-position :initial-value 0)))))
      (setf (daemon-tree daemon)
            (if (daemon-panes daemon)
                (ekko/layout:split-pane (daemon-tree daemon)
                                        (pane-id (first (last (daemon-panes daemon))))
                                        (pane-id pane) :columns)
                (pane-id pane))
            (daemon-panes daemon) (append (daemon-panes daemon) (list pane)))
      (spawn-pane pane :directory directory
                       :environment (and environment (pane-environment environment)))))
  (dolist (view (daemon-views daemon)) (layout view))
  (incf (daemon-revision daemon)))

(defun request-data (bytes)
  "Read bounded plain data once at the local control boundary."
  (when (> (length bytes) (* 1024 1024)) (error "Control request exceeds 1 MiB"))
  (let ((value (decode-scene bytes)) (budget 65536))
    (labels ((check (item depth)
               (when (or (> depth 48) (minusp (decf budget))) (error "Control request too complex"))
               (typecase item
                 (cons (check (first item) (1+ depth)) (check (rest item) depth))
                 (string (when (or (> (length item) (* 512 1024)) (find #\Null item))
                           (error "Invalid control string")))
                 (integer (unless (<= 0 item #xffffffff) (error "Invalid control integer")))
                 (symbol (unless (or (null item) (eq item t) (keywordp item)) (error "Invalid control symbol")))
                 (t (error "Invalid control data")))))
      (check value 0))
    value))
(defun checked-viewport (viewport)
  (unless (and (listp viewport) (= (length viewport) 4)
               (every #'integerp viewport)
               (<= 5 (first viewport) 500) (<= 4 (second viewport) 300)
               (<= 1 (third viewport) 128) (<= 1 (fourth viewport) 256))
    (error "Invalid viewport"))
  viewport)
(defun absolute-path-p (path)
  (and (stringp path) (plusp (length path)) (char= (char path 0) #\/)))
(defun parse-launch-request (bytes)
  (let ((data (request-data bytes)))
    (unless (and (listp data) (<= 5 (length data) 6)) (error "Malformed workspace request"))
    (destructuring-bind (commands viewport directory environment config &optional spawn-p) data
      (unless (and (listp commands) (<= (length commands) 128)
                   (every (lambda (argv) (and (listp argv) (<= 1 (length argv) 256)
                                             (every #'stringp argv) (plusp (length (first argv))))) commands))
        (error "Provide at most 128 command argument vectors"))
      (when viewport (checked-viewport viewport))
      (unless (and (absolute-path-p directory) (uiop:directory-exists-p directory))
        (error "Workspace directory does not exist"))
      (unless (and (listp environment) (<= (length environment) 8192)
                   (every (lambda (entry)
                            (and (stringp entry) (let ((eq (position #\= entry))) (and eq (plusp eq)))))
                          environment))
        (error "Malformed workspace environment"))
      (unless (or (null config) (absolute-path-p config)) (error "Configuration path must be absolute"))
      (make-launch-request :commands commands :viewport (or viewport '(120 36 8 16))
                           :directory directory :environment environment :config-path config
                           :spawn-p spawn-p))))
(defun pane-environment (environment)
  (append (list "TERM=xterm-256color" (concatenate 'string "EKKO_INSTANCE=" *instance*))
          (remove-if (lambda (entry)
                       (member (subseq entry 0 (position #\= entry))
                               '("TERM" "EKKO_SESSION_NAME" "EKKO_INSTANCE" "TMUX" "STY") :test #'equal))
                     environment)))
(defun config-file-source (path)
  (if path
      (with-open-file (in path)
        (when (> (file-length in) 32768) (error "Configuration exceeds 32 KiB: ~A" path))
        (let ((source (make-string (file-length in))))
          (subseq source 0 (read-sequence source in))))
      ""))
(defun control-view (daemon wire &optional allow-ambiguous)
  (let* ((selected (wire-selected-view-id wire))
         (views (remove-if-not #'view-wire (daemon-views daemon))))
    (cond (selected (or (find selected (daemon-views daemon) :key #'view-id)
                        (error "Unknown view ~D" selected)))
          ((null views) (daemon-home-view daemon))
          ((null (rest views)) (first views))
          (allow-ambiguous nil)
          (t (error "Multiple attached views; specify --view ID")))))

(defun request-stop (daemon origin-view force)
  (unless force
    (when (some (lambda (view) (and (view-wire view) (not (eq view origin-view))))
                (daemon-views daemon))
      (error "Other clients are attached; use --force")))
  (setf (daemon-stopping daemon) t))
(defun begin-wire-binding (wire)
  (when (= (wire-binding-generation wire) #xffffffff)
    (send-packet wire 21 (text-bytes "Connection binding generation exhausted"))
    (setf (wire-closing wire) :sent)
    (when (wire-view wire) (detach-view (wire-view wire)))
    (return-from begin-wire-binding))
  (incf (wire-binding-generation wire))
  (setf (wire-binding-accepted wire) nil)
  (send-packet wire 24 (integers (list (wire-binding-generation wire)))))

(defun daemon-packet (daemon wire packet)
  (let ((kind (aref packet 0)) (data (subseq packet 1)))
    (unless (wire-greeted wire)
      (unless (= kind 0) (error "Incompatible Ekko wire version: a version-16 route is required"))
      (let ((route (request-data data)))
        (unless (and (listp route) (= (length route) 2) (eql (first route) +wire-version+))
          (error "Incompatible Ekko wire version; restart the client or daemon"))
        (destructuring-bind (version view-id) route
          (unless (or (null view-id) (typep view-id '(integer 1 #xffffffff))) (error "Invalid view ID"))
          (setf (wire-version wire) version (wire-selected-view-id wire) view-id
                (wire-greeted wire) t)))
      (return-from daemon-packet))
    (when (= kind 0) (error "Connection is already routed"))
    (when (= kind 14)
      (unless (and (zerop (length data)) (wire-attached wire) (wire-awaiting-scene wire))
        (error "Unexpected scene acknowledgement"))
      (acknowledge-scene wire) (return-from daemon-packet))
    (when (wire-closing wire) (return-from daemon-packet))
    (when (= kind 25)
      (unless (and (= (length data) 4) (wire-attached wire))
        (reject-protocol "Unexpected input binding acknowledgement"))
      (let ((generation (u32 data 0)))
        (unless (<= 1 generation (wire-binding-generation wire))
          (reject-protocol "Unknown input binding generation"))
        (when (= generation (wire-binding-generation wire))
          (setf (wire-binding-accepted wire) t)))
      (return-from daemon-packet))
    (when (member kind '(2 4 5 6 16))
      (unless (and (wire-attached wire) (<= 5 (length data) (+ 4 65536)))
        (reject-protocol "Malformed bound input packet"))
      (let ((generation (u32 data 0)))
        (unless (<= 1 generation (wire-binding-generation wire))
          (reject-protocol "Unknown input binding generation"))
        ;; A stale read/event must not touch the new view's paste or read state.
        (unless (and (= generation (wire-binding-generation wire)) (wire-binding-accepted wire))
          (return-from daemon-packet)))
      (setf data (subseq data 4)
            packet (concatenate '(vector (unsigned-byte 8)) (vector kind) data)))
    (when (= kind 8)
      (when (wire-attached wire) (error "An attached viewer cannot open panes"))
      (ensure-workspace daemon wire (parse-launch-request data))
      (return-from daemon-packet))
    (when (and (= kind 3) (member (bytes-text data) '("stop" "stop-force") :test #'equal))
      (request-stop daemon (wire-view wire) (equalp data (text-bytes "stop-force")))
      (send-packet wire 20 (text-bytes "{}")) (return-from daemon-packet))
    (when (and (= kind 3) (equalp data (text-bytes "list")))
      ;; One workspace per daemon: report it flat, tagged with the instance.
      (send-packet wire 20
        (text-bytes (json-value (list* :object :instance *instance*
                                       (rest (workspace-status-data daemon))))))
      (return-from daemon-packet))
    (unless (workspace-ready-p daemon)
      (error "Workspace is not ready; retry once startup finishes"))
    (case kind
      (1
       (when (wire-attached wire) (error "Already attached; use the resize packet"))
       (unless (and (= (length data) 20) (= (u32 data 0) +wire-version+))
         (error "Incompatible attach version"))
       (let* ((viewport (checked-viewport (loop for offset from 4 below 20 by 4 collect (u32 data offset))))
              (existing (when (wire-selected-view-id wire) (control-view daemon wire))))
         (apply #'attach-view daemon wire (allocate-view-id daemon) (append viewport (list existing)))
         (setf (wire-attached wire) t)
         (begin-wire-binding wire)))
      (17
       (unless (and (wire-view wire) (= (length data) 16)) (error "Unexpected viewport resize"))
       (apply #'resize-view (wire-view wire)
              (checked-viewport (loop for offset from 0 below 16 by 4 collect (u32 data offset)))))
      (otherwise
       (when (and (member kind '(2 4 5 6 15 16)) (not (wire-view wire)))
         (error "Input requires an attached view"))
       (let ((view (or (wire-view wire)
                       (control-view daemon wire
                                     (and (= kind 3) (member (bytes-text data) '("status" "buffer" "reload") :test #'equal))))))
         (cond
           ((and (= kind 3) (equalp data (text-bytes "status")))
            (send-packet wire 20 (text-bytes (status-json daemon view))))
           ((and (= kind 3) (equalp data (text-bytes "buffer")))
            (send-packet wire 20 (text-bytes (daemon-clipboard daemon))))
           ((and (= kind 3) (equalp data (text-bytes "reload"))) (start-reload daemon wire))
           (t (server-packet view wire packet))))))))

(defun ensure-workspace (daemon wire request)
  "Packet 8: create the workspace when absent, then open requested panes."
  (cond
    ((daemon-creation daemon)
     (let ((creation (daemon-creation daemon)))
       (pushnew wire (creation-peers creation))
       (when (and (launch-request-spawn-p request) (launch-request-commands request))
         (push request (creation-extra-requests creation)))))
    ((daemon-home-view daemon)
     (when (daemon-stopping daemon) (error "Workspace is stopping"))
     (when (launch-request-spawn-p request)
       (open-panes daemon (or (launch-request-commands request)
                              (list (default-shell-argv daemon)))
                   (launch-request-directory request)
                   (launch-request-environment request)))
     (send-packet wire 20 (text-bytes "{}")))
    (t
     (setf (daemon-launch-directory daemon) (launch-request-directory request)
           (daemon-launch-environment daemon) (pane-environment (launch-request-environment request))
           (daemon-config-path daemon) (launch-request-config-path request))
     (setf (daemon-creation daemon)
           (make-creation :commands (launch-request-commands request)
                          :viewport (launch-request-viewport request)
                          :peers (list wire))
           (daemon-worker daemon)
           (start-worker (config-file-source (daemon-config-path daemon))
                         (or (daemon-config-path daemon)
                             (namestring (merge-pathnames "__ekko-empty-init__.lisp"
                                                          (uiop:ensure-directory-pathname (daemon-launch-directory daemon)))))
                         (worker-log-path daemon)
                         :directory (daemon-launch-directory daemon)
                         :environment (daemon-launch-environment daemon))))))

(defun startup-tree (tree panes)
  "Initial layout leaves name command slots, not pane identities."
  (if (integerp tree)
      (or (and (<= 1 tree (length panes)) (pane-id (nth (1- tree) panes)))
          (error "Initial layout references unknown command slot ~D" tree))
      (list (first tree) (second tree) (startup-tree (third tree) panes) (startup-tree (fourth tree) panes))))
(defun prepare-workspace (daemon creation registry)
  (let* ((worker (daemon-worker daemon)) (viewport (creation-viewport creation)))
    (setf (extension-worker-registry worker) registry
          (extension-worker-request worker) nil)
    (install-registry daemon registry)
    (let ((commands (or (creation-commands creation) (list (default-shell-argv daemon))))
          (defaulted (null (creation-commands creation))))
      (when (> (length commands) (option daemon :pane-budget 16))
        (error "Startup commands exceed the configured pane budget"))
      (let ((initial (option daemon :initial-layout)))
        (when (and initial (/= (length commands) (length (ekko/extensions:initial-layout-leaves initial))))
          (error "Initial layout must contain one slot per startup command")))
      (setf (daemon-panes daemon)
            (loop for argv in commands for index from 1 collect
              (make-pane :id (allocate-pane-id daemon) :daemon daemon
                         :vt (make-terminal :cols 1 :rows 1 :cw (third viewport) :ch (fourth viewport))
                         :argv (copy-list argv) :label (file-namestring (first argv))
                         :launch-kind (if defaulted :shell :command) :creation-position index)))
      (setf (daemon-tree daemon) (pane-id (first (daemon-panes daemon))))
      (if (option daemon :initial-layout)
          (setf (daemon-tree daemon) (startup-tree (option daemon :initial-layout) (daemon-panes daemon)))
          (loop for (previous pane) on (daemon-panes daemon) while pane do
            (setf (daemon-tree daemon)
                  (ekko/layout:split-pane (daemon-tree daemon) (pane-id previous) (pane-id pane) :columns))))
      (let ((home (initialize-view (make-view :daemon daemon :id (allocate-view-id daemon)
                                              :focus-id (pane-id (first (daemon-panes daemon)))
                                              :cols (first viewport) :rows (second viewport)
                                              :cw (third viewport) :ch (fourth viewport)))))
        (set-focus home (view-focus-id home) t)
        (setf (creation-phase creation) :initial-layout)))))
(defun begin-created-initialization (daemon creation)
  (let ((home (daemon-home-view daemon)))
    (if (initialization-components (daemon-registry daemon))
        (progn (begin-initialization home (daemon-worker daemon) :startup)
               (setf (creation-phase creation) :initialize))
        (progn (apply-initialization home nil) (setf (creation-phase creation) :layout)))))
(defun service-created-initial-layout (daemon creation buffer)
  (let* ((home (daemon-home-view daemon)) (worker (daemon-worker daemon))
         (registry (daemon-registry daemon)) (state (view-layout-state home)))
    (unless (layout-provider registry)
      (begin-created-initialization daemon creation)
      (return-from service-created-initial-layout))
    (let ((request (extension-worker-request worker)))
      (when request
        (unless (layout-request-p request) (error "Unexpected initial layout request"))
        (let ((response (poll-worker worker buffer)))
          (when response
            (setf (extension-worker-request worker) nil)
            (when (eq :committed (complete-layout state request registry (context-data home) (layout-token home) response))
              (apply-actions home (layout-request-owner request) (getf (second response) :actions) :layout nil)
              (begin-created-initialization daemon creation)
              (return-from service-created-initial-layout))))))
    (when (null (extension-worker-request worker))
      (schedule-layout worker state registry (context-data home) (layout-token home)))))
(defun created-layout-ready-p (daemon)
  (let* ((view (daemon-home-view daemon)) (state (view-layout-state view)))
    (and (daemon-worker daemon) (null (daemon-candidate daemon))
         (null (extension-worker-request (daemon-worker daemon)))
         (null (layout-state-error state))
         (layout-state-current-p state (daemon-registry daemon) (context-data view) (layout-token view)))))
(defun finish-created-workspace (daemon creation)
  (let ((home (daemon-home-view daemon)))
    (reconcile-size daemon)
    (dolist (pane (daemon-panes daemon)) (spawn-pane pane))
    ;; With one workspace there is no competing writer: initializer store
    ;; actions publish straight into the durable shared store.
    (dolist (result (creation-initialization creation))
      (let ((actions (remove-if-not (lambda (action) (eq (first action) :store-set)) (getf result :actions))))
        (when actions (apply-actions home (getf result :owner) actions nil nil))))
    (let ((extras (nreverse (creation-extra-requests creation))))
      (setf (daemon-creation daemon) nil)
      (dolist (view (daemon-views daemon)) (layout view))
      (dolist (peer (creation-peers creation)) (command-reply peer "{}"))
      (dolist (request extras)
        (handler-case
            (open-panes daemon (launch-request-commands request)
                        (launch-request-directory request) (launch-request-environment request))
          (error (condition) (note-error home condition)))))))
(defun service-creation-phase (daemon creation buffer)
  (let ((worker (daemon-worker daemon)) (home (daemon-home-view daemon)))
    (handler-case
        (case (creation-phase creation)
          (:load
           (let ((response (poll-worker worker buffer)))
             (when response
               (unless (eq (first response) :ready) (error "~A" (second response)))
               (prepare-workspace daemon creation (second response)))))
          (:initial-layout (service-created-initial-layout daemon creation buffer))
          (:initialize
           (let ((response (poll-worker worker buffer)))
             (when response
               (unless (eq (first response) :initialized) (error "~A" (second response)))
               (unless (initialization-current-p home worker) (error "Startup initialization dependencies changed"))
               (stage-initialization home (daemon-registry daemon) (second response))
               (setf (creation-initialization creation) (second response))
               (let ((*store-persist* nil)) (apply-initialization home (second response)))
               (setf (extension-worker-request worker) nil
                     (extension-worker-initialization-context worker) nil
                     (layout-state-requested-context (view-layout-state home)) nil
                     (layout-state-requested-token (view-layout-state home)) nil
                     (creation-phase creation) :layout))))
          (:layout
           (service-extensions daemon buffer)
           (when (layout-state-error (view-layout-state home))
             (error "Initial layout failed: ~A" (layout-state-error (view-layout-state home))))
           (when (created-layout-ready-p daemon) (finish-created-workspace daemon creation))))
      (error (condition)
        (dolist (peer (creation-peers creation))
          (when (>= (wire-fd peer) 0) (command-reply peer (princ-to-string condition) t)))
        (reset-workspace daemon)))))

(defun reset-workspace (daemon)
  "A failed creation abandons every staged effect; the daemon stays up."
  (dolist (pane (daemon-panes daemon))
    (close-pane pane)
    (when (pane-pid pane) (push (cons pane (+ (now) 1)) (daemon-retired daemon))))
  (dolist (view (daemon-views daemon))
    (when (view-wire view) (setf (wire-closing (view-wire view)) t (wire-view (view-wire view)) nil)))
  (setf (daemon-panes daemon) nil (daemon-tree daemon) nil
        (daemon-views daemon) nil (daemon-home-view daemon) nil
        (daemon-registry daemon) nil (daemon-creation daemon) nil
        (daemon-command-queue daemon) nil (daemon-initialization-queue daemon) nil
        (daemon-pending-splits daemon) nil)
  (stop-worker (daemon-worker daemon)) (stop-worker (daemon-candidate daemon))
  (setf (daemon-worker daemon) nil (daemon-candidate daemon) nil))

(defun teardown-workspace (daemon)
  "Stop the workspace: clients get a final frame, panes get a bounded reap."
  (when (daemon-creation daemon)
    (dolist (peer (creation-peers (daemon-creation daemon)))
      (when (>= (wire-fd peer) 0) (command-reply peer "Workspace is stopping" t)))
    (setf (daemon-creation daemon) nil))
  (dolist (view (daemon-views daemon))
    (when (view-wire view) (setf (wire-closing (view-wire view)) t))
    (detach-view view))
  (stop-worker (daemon-worker daemon)) (stop-worker (daemon-candidate daemon))
  (setf (daemon-worker daemon) nil (daemon-candidate daemon) nil)
  (dolist (pane (daemon-panes daemon))
    (close-pane pane)
    (clear-screen (pane-graphics pane) :main) (clear-screen (pane-graphics pane) :alternate)
    (push (cons pane (+ (now) 1)) (daemon-retired daemon)))
  (setf (daemon-panes daemon) nil (daemon-tree daemon) nil
        (daemon-torn-down daemon) t (daemon-retire-until daemon) (+ (now) 1)))

(defun reap-retired (daemon)
  (setf (daemon-retired daemon)
        (remove-if
         (lambda (entry)
           (let* ((pane (first entry)) (pid (pane-pid pane)))
             (cond ((or (null pid) (pane-status pane)) t)
                   (t (let ((exit (reap pid)))
                        (cond ((>= exit 0) (setf (pane-status pane) exit) t)
                              ((= exit -11)
                               (when (>= (now) (rest entry)) (signal-group pid 9))
                               nil)
                              (t t)))))))
         (daemon-retired daemon))))
(defun trim-detached-views (daemon)
  "Keep home/live views and the eight newest detached extra view IDs."
  (let ((detached (sort (remove-if (lambda (view) (or (view-wire view) (eq view (daemon-home-view daemon))))
                                  (copy-list (daemon-views daemon))) #'> :key #'view-id)))
    (dolist (view (nthcdr (min +retained-view-limit+ (length detached)) detached))
      (incf (view-epoch view))
      (dolist (request (daemon-command-queue daemon))
        (when (eq view (command-origin-view (command-request-origin request)))
          (fail-command request "Detached view was reclaimed by the retention limit")))
      (setf (daemon-command-queue daemon)
            (remove view (daemon-command-queue daemon)
                    :key (lambda (request) (command-origin-view (command-request-origin request))))
            (daemon-initialization-queue daemon) (remove view (daemon-initialization-queue daemon))
            (daemon-views daemon) (remove view (daemon-views daemon))))))
(defun drop-daemon-peer (daemon peer)
  (when (wire-view peer) (detach-view (wire-view peer)))
  (close-wire peer)
  (setf (daemon-peers daemon) (remove peer (daemon-peers daemon))))

(defun workspace-deadline (daemon current)
  (let ((deadline (+ current 1)))
    (dolist (view (daemon-views daemon))
      (when (view-transition view) (setf deadline (min deadline (+ current 1/50))))
      (dolist (note (view-pane-notes view)) (setf deadline (min deadline (getf note :until))))
      (maphash (lambda (id state)
                 (declare (ignore id))
                 (when (pane-view-copy-flash-until state)
                   (setf deadline (min deadline (pane-view-copy-flash-until state)))))
               (view-pane-states view)))
    (dolist (worker (list (daemon-worker daemon) (daemon-candidate daemon)))
      (when (and worker (extension-worker-request worker))
        (setf deadline (min deadline (extension-worker-deadline worker)))))
    (dolist (pane (daemon-panes daemon))
      (let ((until (pane-sync-until pane)) (pending (store-pending (pane-graphics pane))))
        (when (and until (< current until)) (setf deadline (min deadline until)))
        (when pending (setf deadline (min deadline (+ (ekko/graphics:upload-at pending) 10))))))
    deadline))
(defun daemon-poll-items (daemon)
  (append (worker-events (daemon-worker daemon)) (worker-events (daemon-candidate daemon))
          (loop for pane in (daemon-panes daemon) when (pane-io pane)
                collect (cons (wire-fd (pane-io pane)) (wire-events (pane-io pane))))))
(defun service-workspace (daemon buffer)
  ;; Per-view and per-pane guards keep one fault from skipping every other
  ;; owner in the same pass; the caller still bounds whole-service failures.
  (dolist (view (daemon-views daemon))
    (handler-case
        (progn (tick-transition view) (expire-copy-flashes view) (expire-pane-notes view))
      (error (condition) (note-error view condition))))
  (service-extensions daemon buffer)
  (dolist (pane (daemon-panes daemon))
    (handler-case
        (progn
          (expire-upload (pane-graphics pane))
          (when (and (pane-pid pane) (null (pane-status pane)))
            (let ((exit (reap (pane-pid pane))))
              (when (>= exit 0) (setf (pane-status pane) exit) (incf (daemon-revision daemon))))))
      (error (condition)
        (format *error-output* "pane ~D: ~A~%" (pane-id pane) condition))))
  ;; The workspace ends when its last pane does.
  (when (and (daemon-panes daemon) (every #'pane-status (daemon-panes daemon)))
    (setf (daemon-stopping daemon) t)))
(defun service-pane-event (pane flags buffer)
  (handler-case
      (progn
        (when (logtest flags 4) (flush-wire (pane-io pane)))
        (when (logtest flags 25)
          (let ((n (read-fd (wire-fd (pane-io pane)) buffer)))
            (cond ((plusp n)
                   (incf (pane-output-bytes pane) n)
                   (note-pane-output (pane-daemon pane) pane)
                   (feed (pane-vt pane) (subseq buffer 0 n) (lambda (kind value) (pane-event pane kind value))))
                  ((not (member n '(-11 -4)))
                   (close-wire (pane-io pane)) (setf (pane-io pane) nil))))))
    (error (condition)
      (format *error-output* "pane ~D: ~A~%" (pane-id pane) condition)
      (close-pane pane))))
(defun service-daemon-peer (daemon peer)
  (cond
    ((minusp (wire-fd peer)) (drop-daemon-peer daemon peer))
    ((wire-closing peer)
     ;; Socket drainage is not terminal drainage. A last frame keeps its local
     ;; snapshot leases until the terminal-side ACK, even while stopping.
     (when (and (null (wire-awaiting-scene peer)) (null (wire-queue peer)))
       (if (eq (wire-closing peer) :sent)
           (drop-daemon-peer daemon peer)
           (progn (send-packet peer 22) (setf (wire-closing peer) :sent)))))
    (t
     (when (and (wire-view peer) (wire-binding-accepted peer))
       (publish-scene (wire-view peer) peer))
     (when (and (not (wire-attached peer)) (>= (- (now) (wire-at peer)) 10))
       (drop-daemon-peer daemon peer)))))
(defun service-peer-event (daemon peer flags buffer)
  (handler-case
      (progn
        (when (logtest flags 4) (flush-wire peer))
        (when (logtest flags 25)
          (dolist (packet (receive-packets peer buffer))
            (handler-case (daemon-packet daemon peer packet)
              (error (condition)
                (if (and (not (typep condition 'wire-protocol-error))
                         (wire-view peer) (not (wire-closing peer)))
                    (note-error (wire-view peer) condition)
                    (progn
                      (send-packet peer 21 (text-bytes (princ-to-string condition)))
                      (setf (wire-closing peer) :sent)
                      (when (wire-view peer) (detach-view (wire-view peer))))))))))
    (error (condition)
      (unless (search "disconnected" (princ-to-string condition))
        (format *error-output* "client: ~A~%" condition))
      (drop-daemon-peer daemon peer))))
(defun service-creation (daemon buffer)
  "Advance workspace creation until it has to wait for the worker.

A phase can finish without leaving a pending worker request: the :LOAD answer,
a committed initial layout and a skipped initialization all move the creation
straight into work that needs no I/O.  Waiting for the poll timeout after such
a transition put one idle second in front of every pane spawn, so service the
next phase immediately instead.  The loop stops on a pending request, an
unchanged phase, or a creation that was finished or rejected."
  (let ((creation (daemon-creation daemon)))
    (when creation
      (loop
        (let ((phase (creation-phase creation)) (worker (daemon-worker daemon)))
          (when (daemon-stopping daemon) (return))
          (service-creation-phase daemon creation buffer)
          (when (or (not (eq creation (daemon-creation daemon)))
                    (eq phase (creation-phase creation))
                    (and worker (extension-worker-request worker)))
            (return)))))))

(defun daemon-step (daemon buffer)
  (service-creation daemon buffer)
  (when (daemon-home-view daemon)
    ;; One bad pass reports into the workspace status instead of tearing it
    ;; down; only a persistently failing service still stops the workspace.
    (handler-case
        (progn
          (unless (daemon-stopping daemon) (service-workspace daemon buffer))
          (setf (daemon-service-failures daemon) 0))
      (error (condition)
        (note-workspace-error daemon condition)
        (when (>= (incf (daemon-service-failures daemon)) 25)
          (setf (daemon-stopping daemon) t)))))
  (when (and (daemon-stopping daemon) (not (daemon-torn-down daemon)))
    (teardown-workspace daemon))
  (reap-retired daemon)
  (when (and (daemon-torn-down daemon) (null (daemon-retired daemon))
             (or (every (lambda (peer) (and (null (wire-queue peer)) (null (wire-awaiting-scene peer))))
                        (daemon-peers daemon))
                 (> (now) (+ (daemon-retire-until daemon) 2))))
    (setf (daemon-quit daemon) t))
  (dolist (peer (copy-list (daemon-peers daemon)))
    (handler-case (service-daemon-peer daemon peer)
      (error (condition)
        (format *error-output* "client: ~A~%" condition) (drop-daemon-peer daemon peer))))
  (let* ((current (now)) (deadline (+ current 1))
         (panes (daemon-panes daemon)))
    (setf deadline (min deadline (workspace-deadline daemon current)))
    (when (daemon-torn-down daemon)
      (setf deadline (min deadline (max current (daemon-retire-until daemon)))))
    (dolist (peer (daemon-peers daemon))
      (unless (wire-attached peer) (setf deadline (min deadline (+ (wire-at peer) 10)))))
    (dolist (event (poll-fds
                   (append (list (cons (daemon-listener daemon) 1))
                           (daemon-poll-items daemon)
                           (loop for peer in (daemon-peers daemon) collect (cons (wire-fd peer) (wire-events peer))))
                   (max 0 (ceiling (* 1000 (- deadline current))))))
      (let* ((fd (first event)) (flags (rest event))
             (pane (find fd panes :key (lambda (pane) (when (pane-io pane) (wire-fd (pane-io pane)))))))
        (cond
          ((= fd (daemon-listener daemon))
           (loop repeat 32 for accepted = (accept-local fd) while (>= accepted 0) do
             (handler-case
                 (let ((peer (make-wire :fd accepted)))
                   (if (< (length (daemon-peers daemon)) +daemon-peer-limit+)
                       (push peer (daemon-peers daemon))
                       (unwind-protect
                            (progn (send-packet peer 21 (text-bytes "Daemon peer limit reached; retry later"))
                                   (flush-wire peer))
                         (close-wire peer))))
               ;; A vanished newcomer must not take the reactor down with it.
               (error (condition)
                 (format *error-output* "accept: ~A~%" condition)
                 (ignore-errors (close-fd accepted))))))
          (pane (service-pane-event pane flags buffer))
          (t (let ((peer (find fd (daemon-peers daemon) :key #'wire-fd)))
               (when peer (service-peer-event daemon peer flags buffer)))))))))

(defun serve ()
  (initialize) (server-signals)
  (let* ((path (socket-path))
         (ekko/store:*directory* (ekko/store:store-directory *instance*))
         (lock (checked (lock-file (concatenate 'string path ".lock")) "daemon lock"))
         (*daemon* (make-daemon :path path :lock lock :store (make-store-state :entries (ekko/store:store-load))))
         (buffer (octets 65536)) (running t))
    (dolist (signal (list sb-posix:sigterm sb-posix:sighup))
      (sb-sys:enable-interrupt signal (lambda (&rest arguments) (declare (ignore arguments)) (setf running nil))))
    (unwind-protect
         (progn
           (initialize-assets (concatenate 'string path ".frames/"))
           (when (probe-file path) (delete-file path))
           (setf (daemon-listener *daemon*) (checked (listen-local path) "listen"))
           ;; A mismatched-version client identifies this daemon by pidfile.
           (ignore-errors
             (with-open-file (out (concatenate 'string path ".pid") :direction :output
                                  :if-exists :supersede :if-does-not-exist :create)
               (format out "~D~%" (sb-posix:getpid))))
           (let ((step-failures 0))
             (loop while (and running (not (daemon-quit *daemon*))) do
               (handler-case
                   (progn (daemon-step *daemon* buffer) (setf step-failures 0))
                 (error (condition)
                   ;; A step fault must not silently strand every attached
                   ;; viewer: log, then retry with a pause. Persistent failure
                   ;; stops the workspace through the normal teardown path; a
                   ;; wedged reactor still exits instead of spinning forever.
                   (format *error-output* "reactor: ~A~%" condition)
                   (if (>= (incf step-failures) 3)
                       (progn
                         (setf (daemon-stopping *daemon*) t)
                         (when (>= step-failures 8) (error condition)))
                       (poll-fds nil 20)))))))
      (let ((daemon *daemon*))
        (when (or (daemon-home-view daemon) (daemon-creation daemon))
          (teardown-workspace daemon))
        (dolist (peer (copy-list (daemon-peers daemon))) (drop-daemon-peer daemon peer))
        (let ((deadline (+ (now) 11/10)))
          (loop while (and (daemon-retired daemon) (< (now) deadline)) do
            (reap-retired daemon) (when (daemon-retired daemon) (poll-fds nil 20))))
        (dolist (entry (daemon-retired daemon))
          (let ((pane (first entry)))
            (when (and (pane-pid pane) (null (pane-status pane))) (signal-group (pane-pid pane) 9))))))
    (when (daemon-listener *daemon*) (close-fd (daemon-listener *daemon*)))
    (when (probe-file path) (delete-file path))
    (ignore-errors (delete-file (concatenate 'string path ".pid")))
    (close-fd lock)))
