(in-package #:ekko/runtime)

(defstruct daemon path listener lock sessions creations peers retiring
  (next-pane-id 1) (next-view-id 1) (next-session-id 1) store)
(defstruct creation session commands viewport peers (phase :load) initialization store-snapshot)
(defstruct launch-request commands viewport directory environment config-path)
(defvar *daemon* nil)
(defconstant +daemon-session-limit+ 128)
(defconstant +daemon-creation-limit+ 16)
(defconstant +daemon-peer-limit+ 256)
(defconstant +retained-view-limit+ 8)

(defun allocate-pane-id (&optional (daemon *daemon*))
  (unless daemon (error "Pane allocation requires a daemon"))
  (when (> (daemon-next-pane-id daemon) #xffffffff) (error "Pane ID space exhausted"))
  (prog1 (daemon-next-pane-id daemon) (incf (daemon-next-pane-id daemon))))
(defun allocate-session-pane-id (session)
  (if (session-daemon session) (allocate-pane-id (session-daemon session))
      (prog1 (session-next-pane-id session) (incf (session-next-pane-id session)))))
(defun allocate-view-id (daemon)
  (when (> (daemon-next-view-id daemon) #xffffffff) (error "View ID space exhausted"))
  (prog1 (daemon-next-view-id daemon) (incf (daemon-next-view-id daemon))))
(defun find-session (name &optional (daemon *daemon*))
  (find name (daemon-sessions daemon) :key #'session-name :test #'equal))
(defun all-panes (&optional (daemon *daemon*))
  (loop for session in (daemon-sessions daemon) append (copy-list (session-panes session))))
(defun daemon-views (daemon)
  (loop for session in (daemon-sessions daemon) append (copy-list (session-views session))))
(defun daemon-pane-by-id (daemon id) (find id (all-panes daemon) :key #'pane-id))
(defun pane-owner (pane-or-id &optional (daemon *daemon*))
  (let ((pane (if (integerp pane-or-id) (daemon-pane-by-id daemon pane-or-id) pane-or-id)))
    (when pane (pane-session pane))))
(defun session-all-panes (session)
  (let ((daemon (session-daemon session)))
    (if daemon (remove-duplicates (append (all-panes daemon) (session-panes session)) :from-end t)
        (copy-list (session-panes session)))))
(defun session-all-views (session)
  (let ((daemon (session-daemon session)))
    (if daemon (remove-duplicates (append (daemon-views daemon) (session-views session)) :from-end t)
        (copy-list (session-views session)))))
(defun session-catalog (session)
  (loop for item in (if (session-daemon session)
                       (remove-duplicates (append (daemon-sessions (session-daemon session)) (list session)) :from-end t)
                       (list session))
        collect (list :name (copy-seq (session-name item)) :id (session-incarnation item)
                      :panes (mapcar #'pane-id (session-panes item))
                      :views (loop for view in (session-views item)
                                   collect (list :id (view-id view) :attached (not (null (view-wire view))))))))
(defun session-worker-log (session)
  (format nil "~A.~A.extensions.log" (daemon-path (session-daemon session)) (session-name session)))
(defun spawn-session-pane (pane)
  "Acquire a new pane's PTY using the same canonical decision as resize."
  (when (or (pane-io pane) (pane-pid pane)) (error "Pane already has a process"))
  (let ((session (pane-session pane)) (vt (pane-vt pane)))
    (multiple-value-bind (cols rows source) (pane-sizing pane)
      (let* ((source (or source (session-home-view session)))
             (cols (or cols (terminal-cols vt))) (rows (or rows (terminal-rows vt)))
             (size (pty-size-for source cols rows)) (io (make-wire :fd -1)))
        (unless (equal (list cols rows (view-cw source) (view-ch source))
                       (list (terminal-cols vt) (terminal-rows vt) (terminal-cw vt) (terminal-ch vt)))
          (resize-terminal vt cols rows (view-cw source) (view-ch source)))
        (multiple-value-bind (cw ch) (pty-cell-size source)
          (multiple-value-bind (fd pid)
              (spawn (pane-argv pane) cols rows cw ch :directory (session-launch-directory session)
                                                     :environment (session-launch-environment session))
            (setf (wire-fd io) fd (pane-io pane) io (pane-pid pane) pid (pane-pty-size pane) size))))))
  pane)

(defun request-data (bytes)
  "Read bounded plain data once at the local control boundary."
  (when (> (length bytes) (* 1024 1024)) (error "Control request exceeds 1 MiB"))
  (let ((value (decode-scene bytes)) (budget 65536))
    (labels ((check (item depth)
               (when (or (> depth 48) (minusp (decf budget))) (error "Control request too complex"))
               (typecase item
                 (cons (check (car item) (1+ depth)) (check (cdr item) depth))
                 (string (when (or (> (length item) (* 512 1024)) (find #\Null item))
                           (error "Invalid control string")))
                 (integer (unless (<= 0 item #xffffffff) (error "Invalid control integer")))
                 (symbol (unless (or (null item) (eq item t) (keywordp item)) (error "Invalid control symbol")))
                 (t (error "Invalid control data")))))
      (check value 0))
    value))
(defun checked-viewport (viewport)
  (unless (and (listp viewport) (= (length viewport) 4)
               (every #'integerp viewport)
               (<= 5 (first viewport) 500) (<= 4 (second viewport) 300)
               (<= 1 (third viewport) 128) (<= 1 (fourth viewport) 256))
    (error "Invalid viewport"))
  viewport)
(defun absolute-path-p (path)
  (and (stringp path) (plusp (length path)) (char= (char path 0) #\/)))
(defun parse-launch-request (bytes)
  (let ((data (request-data bytes)))
    (unless (and (listp data) (= (length data) 5)) (error "Malformed session creation request"))
    (destructuring-bind (commands viewport directory environment config) data
      (unless (and (listp commands) (<= 1 (length commands) 128)
                   (every (lambda (argv) (and (listp argv) (<= 1 (length argv) 256)
                                             (every #'stringp argv) (plusp (length (first argv))))) commands))
        (error "Provide one to 128 command argument vectors"))
      (when viewport (checked-viewport viewport))
      (unless (and (absolute-path-p directory) (uiop:directory-exists-p directory))
        (error "Session directory does not exist"))
      (unless (and (listp environment) (<= (length environment) 8192)
                   (every (lambda (entry)
                            (and (stringp entry) (let ((eq (position #\= entry))) (and eq (plusp eq)))))
                          environment))
        (error "Malformed session environment"))
      (unless (or (null config) (absolute-path-p config)) (error "Configuration path must be absolute"))
      (make-launch-request :commands commands :viewport (or viewport '(120 36 8 16))
                           :directory directory :environment environment :config-path config))))
(defun pane-environment (name environment)
  (append (list "TERM=xterm-256color" (concatenate 'string "EKKO_SESSION_NAME=" name)
                (concatenate 'string "EKKO_INSTANCE=" *instance*))
          (remove-if (lambda (entry)
                       (member (subseq entry 0 (position #\= entry))
                               '("TERM" "EKKO_SESSION_NAME" "EKKO_INSTANCE" "TMUX" "STY") :test #'equal))
                     environment)))
(defun session-config-source (path)
  (if path
      (with-open-file (in path)
        (when (> (file-length in) 32768) (error "Configuration exceeds 32 KiB: ~A" path))
        (let ((source (make-string (file-length in))))
          (subseq source 0 (read-sequence source in))))
      ""))
(defun control-view (session wire &optional allow-ambiguous)
  (let* ((selected (wire-selected-view-id wire))
         (views (remove-if-not #'view-wire (session-views session))))
    (cond (selected (or (find selected (session-views session) :key #'view-id)
                        (error "Unknown view ~D in session ~A" selected (session-name session))))
          ((null views) (session-home-view session))
          ((null (rest views)) (first views))
          (allow-ambiguous nil)
          (t (error "Session has multiple attached views; specify --view ID")))))
(defun selected-daemon-view (daemon wire)
  (or (wire-view wire)
      (and (wire-selected-view-id wire)
           (find (wire-selected-view-id wire) (daemon-views daemon) :key #'view-id))
      (error "Select an attached view with --view ID")))

(defun request-session-stop (session origin force)
  (unless force
    (when (some (lambda (view)
                  (and (view-wire view) (not (eq view origin))
                       (or (eq session (view-session view))
                           (some (lambda (pane) (member pane (visible-panes view))) (session-panes session)))))
                (session-all-views session))
      (error "Other clients are viewing this session; use --force")))
  (setf (session-stopping session) t))
(defun begin-wire-binding (wire)
  (when (= (wire-binding-generation wire) #xffffffff)
    (send-packet wire 21 (text-bytes "Connection binding generation exhausted"))
    (setf (wire-closing wire) :sent)
    (when (wire-view wire) (detach-view (wire-view wire)))
    (return-from begin-wire-binding))
  (incf (wire-binding-generation wire))
  (setf (wire-binding-accepted wire) nil)
  (send-packet wire 24 (integers (list (wire-binding-generation wire)))))
(defun switch-view-session (view name)
  (let ((wire (view-wire view)) (daemon (session-daemon (view-session view))))
    (unless wire (error "Session switching requires an attached view"))
    (let ((target (find-session (checked-name name) daemon)))
      (unless target (error "Unknown session ~A" name))
      (when (eq target (view-session view)) (return-from switch-view-session)))
    (setf (wire-pending-switch wire) name)
    (reset-view-input view)
    (incf (view-epoch view))))
(defun complete-session-switch (daemon wire)
  (let* ((old (wire-view wire)) (name (wire-pending-switch wire))
         (target (find-session name daemon)))
    (setf (wire-pending-switch wire) nil)
    (unless target
      (when old (note-error old (format nil "Session ~A no longer exists" name)))
      (return-from complete-session-switch))
    (unless old (error "Switch origin detached"))
    ;; View IDs name retained per-session state, not sockets. Returning can
    ;; reclaim the old home view; another attached client keeps its own view.
    (let ((viewport (list (view-cols old) (view-rows old) (view-cw old) (view-ch old))))
      (detach-view old)
      (setf (wire-route wire) name (wire-selected-view-id wire) nil (wire-revision wire) nil)
      (clrhash (wire-known wire))
      (apply #'attach-view target wire (allocate-view-id daemon) viewport)
      (begin-wire-binding wire))))

(defun daemon-packet (daemon wire packet)
  (let ((kind (aref packet 0)) (data (subseq packet 1)))
    (unless (wire-greeted wire)
      (unless (= kind 0) (error "Incompatible Ekko wire version: a version-15 route is required"))
      (let ((route (request-data data)))
        (unless (and (listp route) (= (length route) 3) (eql (first route) +wire-version+))
          (error "Incompatible Ekko wire version; restart the client or daemon"))
        (destructuring-bind (version name view-id) route
          (when name (checked-name name))
          (unless (or (null view-id) (typep view-id '(integer 1 #xffffffff))) (error "Invalid view ID"))
          (setf (wire-version wire) version (wire-route wire) name
                (wire-selected-view-id wire) view-id (wire-greeted wire) t)))
      (return-from daemon-packet))
    (when (= kind 0) (error "Connection is already routed"))
    (when (= kind 14)
      (unless (and (zerop (length data)) (wire-attached wire) (wire-awaiting-scene wire))
        (error "Unexpected scene acknowledgement"))
      (acknowledge-scene wire) (return-from daemon-packet))
    (when (wire-closing wire) (return-from daemon-packet))
    (when (= kind 25)
      (unless (and (= (length data) 4) (wire-attached wire))
        (reject-protocol "Unexpected input binding acknowledgement"))
      (let ((generation (u32 data 0)))
        (unless (<= 1 generation (wire-binding-generation wire))
          (reject-protocol "Unknown input binding generation"))
        (when (= generation (wire-binding-generation wire))
          (setf (wire-binding-accepted wire) t)))
      (return-from daemon-packet))
    (when (member kind '(2 4 5 6 16))
      (unless (and (wire-attached wire) (<= 5 (length data) (+ 4 65536)))
        (reject-protocol "Malformed bound input packet"))
      (let ((generation (u32 data 0)))
        (unless (<= 1 generation (wire-binding-generation wire))
          (reject-protocol "Unknown input binding generation"))
        ;; A stale read/event must not touch the new view's paste or read state.
        (unless (and (= generation (wire-binding-generation wire)) (wire-binding-accepted wire))
          (return-from daemon-packet)))
      (setf data (subseq data 4)
            packet (concatenate '(vector (unsigned-byte 8)) (vector kind) data)))
    (when (= kind 8)
      (when (wire-attached wire) (error "An attached viewer cannot create a session"))
      (unless (wire-route wire) (error "Creation requires a session name"))
      (ensure-session-request daemon wire (parse-launch-request data))
      (return-from daemon-packet))
    (when (= kind 9)
      (switch-view-session (selected-daemon-view daemon wire) (bytes-text data))
      (unless (wire-attached wire) (send-packet wire 20 (text-bytes "{}")))
      (return-from daemon-packet))
    (when (and (= kind 3) (equalp data (text-bytes "list")))
      (send-packet wire 20
        (text-bytes (json-value (list :object :wire_version +wire-version+ :daemon_pid (sb-posix:getpid)
                                     :instance *instance* :sessions (map 'vector #'session-status-data (daemon-sessions daemon))))))
      (return-from daemon-packet))
    (let ((session (or (and (wire-route wire) (find-session (wire-route wire) daemon))
                       (error "Unknown session ~A" (wire-route wire)))))
      (case kind
        (1
         (when (wire-attached wire) (error "Already attached; use the resize packet"))
         (unless (and (= (length data) 20) (= (u32 data 0) +wire-version+))
           (error "Incompatible attach version"))
         (let* ((viewport (checked-viewport (loop for offset from 4 below 20 by 4 collect (u32 data offset))))
                (existing (when (wire-selected-view-id wire) (control-view session wire))))
           (apply #'attach-view session wire (allocate-view-id daemon) (append viewport (list existing)))
           (setf (wire-attached wire) t)
           (begin-wire-binding wire)))
        (17
         (unless (and (wire-view wire) (= (length data) 16)) (error "Unexpected viewport resize"))
         (apply #'resize-view (wire-view wire)
                (checked-viewport (loop for offset from 0 below 16 by 4 collect (u32 data offset)))))
        (otherwise
         (when (and (member kind '(2 4 5 6 15 16)) (not (wire-view wire)))
           (error "Input requires an attached view"))
         (when (and (wire-pending-switch wire) (member kind '(2 4 5 6 15 16)))
           (return-from daemon-packet))
         (let ((view (or (wire-view wire)
                         (control-view session wire
                                       (and (= kind 3) (member (bytes-text data) '("status" "stop" "stop-force" "buffer" "reload") :test #'equal))))))
           (cond
             ((and (= kind 3) (equalp data (text-bytes "status")))
              (send-packet wire 20 (text-bytes (status-json session view))))
             ((and (= kind 3) (equalp data (text-bytes "buffer")))
              (send-packet wire 20 (text-bytes (session-clipboard session))))
             ((and (= kind 3) (equalp data (text-bytes "reload"))) (start-reload session wire))
             ((and (= kind 3) (member (bytes-text data) '("stop" "stop-force") :test #'equal))
              (request-session-stop session view (equalp data (text-bytes "stop-force")))
              (send-packet wire 20 (text-bytes "{}")))
             (t (server-packet view wire packet)))))))))

(defun ensure-session-request (daemon wire request)
  (let* ((name (wire-route wire))
         (existing (find-session name daemon))
         (pending (find name (daemon-creations daemon) :key (lambda (item) (session-name (creation-session item))) :test #'equal)))
    (cond (existing (send-packet wire 20 (text-bytes "{}")))
          (pending (pushnew wire (creation-peers pending)))
          (t
           (when (>= (+ (length (daemon-sessions daemon)) (length (daemon-creations daemon))
                        (length (daemon-retiring daemon))) +daemon-session-limit+)
             (error "Daemon session limit (~D) reached" +daemon-session-limit+))
           (when (>= (length (daemon-creations daemon)) +daemon-creation-limit+)
             (error "Concurrent session creation limit (~D) reached; retry later" +daemon-creation-limit+))
           (let* ((session (make-session :daemon daemon :name name
                                        :incarnation (prog1 (daemon-next-session-id daemon) (incf (daemon-next-session-id daemon)))
                                        :launch-directory (launch-request-directory request)
                                        :launch-environment (pane-environment name (launch-request-environment request))
                                        :config-path (launch-request-config-path request)
                                        ;; This unregistered candidate owns only staged effects.
                                        :store-state (make-store-state :entries (copy-tree (store-state-entries (daemon-store daemon))))))
                  (creation (make-creation :session session :commands (launch-request-commands request)
                                           :viewport (launch-request-viewport request) :peers (list wire))))
             (setf (session-worker session)
                   (start-worker (session-config-source (session-config-path session))
                                 (or (session-config-path session)
                                     (namestring (merge-pathnames "__ekko-empty-init__.lisp"
                                                                 (uiop:ensure-directory-pathname (session-launch-directory session)))))
                                 (session-worker-log session)
                                 :directory (session-launch-directory session) :environment (session-launch-environment session)))
             (push creation (daemon-creations daemon)))))))
(defun startup-tree (tree panes)
  "Initial layout leaves name command slots, not global pane identities."
  (if (integerp tree)
      (or (and (<= 1 tree (length panes)) (pane-id (nth (1- tree) panes)))
          (error "Initial layout references unknown command slot ~D" tree))
      (list (first tree) (second tree) (startup-tree (third tree) panes) (startup-tree (fourth tree) panes))))
(defun prepare-created-session (creation registry)
  (let* ((session (creation-session creation)) (daemon (session-daemon session))
         (viewport (creation-viewport creation)) (commands (creation-commands creation)))
    (setf (extension-worker-registry (session-worker session)) registry
          (extension-worker-request (session-worker session)) nil
          ;; Loading config can take seconds while other sessions commit store
          ;; writes. Capture the live base immediately before callbacks begin.
          (creation-store-snapshot creation) (copy-tree (store-state-entries (daemon-store daemon)))
          (session-store session) (copy-tree (creation-store-snapshot creation)))
    (install-registry session registry)
    (when (> (length commands) (option session :pane-budget 16))
      (error "Startup commands exceed the configured pane budget"))
    (let ((initial (option session :initial-layout)))
      (when (and initial (/= (length commands) (length (ekko/extensions::initial-layout-leaves initial))))
        (error "Initial layout must contain one slot per startup command")))
    (setf (session-panes session)
          (loop for argv in commands for index from 1 collect
            (make-pane :id (allocate-pane-id daemon) :session session
                       :vt (make-terminal :cols 1 :rows 1 :cw (third viewport) :ch (fourth viewport))
                       :argv (copy-list argv) :label (file-namestring (first argv))
                       :launch-kind :command :creation-position index)))
    (setf (session-tree session) (pane-id (first (session-panes session))))
    (if (option session :initial-layout)
        (setf (session-tree session) (startup-tree (option session :initial-layout) (session-panes session)))
        (loop for (previous pane) on (session-panes session) while pane do
          (setf (session-tree session)
                (ekko/layout:split-pane (session-tree session) (pane-id previous) (pane-id pane) :columns))))
    (let ((home (initialize-view (make-view :session session :id (allocate-view-id daemon)
                                           :focus-id (pane-id (first (session-panes session)))
                                           :cols (first viewport) :rows (second viewport)
                                           :cw (third viewport) :ch (fourth viewport)))))
      (set-focus home (view-focus-id home) t)
      (setf (creation-phase creation) :initial-layout))))
(defun begin-created-initialization (creation)
  (let* ((session (creation-session creation)) (home (session-home-view session)))
    (if (initialization-components (session-registry session))
        (progn (begin-initialization home (session-worker session) :startup)
               (setf (creation-phase creation) :initialize))
        (progn (apply-initialization home nil) (setf (creation-phase creation) :layout)))))
(defun service-created-initial-layout (creation buffer)
  (let* ((session (creation-session creation)) (home (session-home-view session))
         (worker (session-worker session)) (registry (session-registry session))
         (state (view-layout-state home)))
    (unless (layout-provider registry)
      (begin-created-initialization creation)
      (return-from service-created-initial-layout))
    (let ((request (extension-worker-request worker)))
      (when request
        (unless (layout-request-p request) (error "Unexpected initial layout request"))
        (let ((response (poll-worker worker buffer)))
          (when response
            (setf (extension-worker-request worker) nil)
            (when (eq :committed (complete-layout state request registry (context-data home) (layout-token home) response))
              (apply-actions home (layout-request-owner request) (getf (second response) :actions) :layout nil)
              (begin-created-initialization creation)
              (return-from service-created-initial-layout))))))
    (when (null (extension-worker-request worker))
      (schedule-layout worker state registry (context-data home) (layout-token home)))))
(defun created-layout-ready-p (session)
  (let* ((view (session-home-view session)) (state (view-layout-state view)))
    (and (session-worker session) (null (session-candidate session))
         (null (extension-worker-request (session-worker session)))
         (null (layout-state-error state))
         (layout-state-current-p state (session-registry session) (context-data view) (layout-token view)))))
(defun finish-created-session (daemon creation)
  (let* ((session (creation-session creation)) (home (session-home-view session))
         (registry (session-registry session))
         (store-readers (append (getf registry :components) (getf registry :layout-providers))))
    (when (and (some (lambda (entry) (member :store (getf entry :reads))) store-readers)
               (not (equal (creation-store-snapshot creation) (store-state-entries (daemon-store daemon)))))
      (error "Shared store changed during startup; retry run"))
    (reconcile-session-size session)
    (dolist (pane (session-panes session)) (spawn-session-pane pane))
    ;; Every fallible child has been acquired. Only now publish initializer store
    ;; actions into the authoritative shared object and durable namespaces.
    (setf (session-store-state session) (daemon-store daemon))
    (dolist (result (creation-initialization creation))
      (let ((actions (remove-if-not (lambda (action) (eq (first action) :store-set)) (getf result :actions))))
        (when actions (apply-actions home (getf result :owner) actions nil nil))))
    (setf (daemon-creations daemon) (remove creation (daemon-creations daemon)))
    (setf (daemon-sessions daemon) (append (daemon-sessions daemon) (list session)))
    (dolist (view (daemon-views daemon))
      (when (eq (option (view-session view) :workspace-scope :session) :all-panes) (layout view)))
    (dolist (peer (creation-peers creation)) (command-reply peer "{}"))))
(defun service-creation (daemon creation buffer)
  (let* ((session (creation-session creation)) (worker (session-worker session)) (home (session-home-view session)))
    (handler-case
        (case (creation-phase creation)
          (:load
           (let ((response (poll-worker worker buffer)))
             (when response
               (unless (eq (first response) :ready) (error "~A" (second response)))
               (prepare-created-session creation (second response)))))
          (:initial-layout (service-created-initial-layout creation buffer))
          (:initialize
           (let ((response (poll-worker worker buffer)))
             (when response
               (unless (eq (first response) :initialized) (error "~A" (second response)))
               (unless (initialization-current-p home worker) (error "Startup initialization dependencies changed"))
               (stage-initialization home (session-registry session) (second response))
               (setf (creation-initialization creation) (second response))
               (let ((*store-persist* nil)) (apply-initialization home (second response)))
               (setf (extension-worker-request worker) nil
                     (extension-worker-initialization-context worker) nil
                     (layout-state-requested-context (view-layout-state home)) nil
                     (layout-state-requested-token (view-layout-state home)) nil
                     (creation-phase creation) :layout))))
          (:layout
           (service-extensions session buffer)
           (when (layout-state-error (view-layout-state home))
             (error "Initial layout failed: ~A" (layout-state-error (view-layout-state home))))
           (when (created-layout-ready-p session) (finish-created-session daemon creation))))
      (error (condition)
        (dolist (peer (creation-peers creation))
          (when (>= (wire-fd peer) 0) (command-reply peer (princ-to-string condition) t)))
        (setf (daemon-creations daemon) (remove creation (daemon-creations daemon)))
        (retire-session daemon session)))))

(defun retire-session (daemon session)
  "Remove one ownership unit; defer process reaping and terminal leases."
  (let ((affected (remove-if-not
                   (lambda (view) (and (not (eq session (view-session view)))
                                       (intersection (session-panes session) (view-panes view))))
                   (daemon-views daemon))))
    (setf (session-stopping session) t
          (daemon-sessions daemon) (remove session (daemon-sessions daemon)))
    (dolist (view (session-views session))
      (when (view-wire view) (setf (wire-closing (view-wire view)) t))
      (detach-view view))
    (stop-worker (session-worker session)) (stop-worker (session-candidate session))
    (setf (session-worker session) nil (session-candidate session) nil)
    (dolist (pane (session-panes session))
      (close-pane pane)
      (clear-screen (pane-graphics pane) :main) (clear-screen (pane-graphics pane) :alternate)
      (dolist (view affected) (prune-view-pane view (pane-id pane))))
    (dolist (view affected) (layout view))
    (push (cons session (+ (now) 1)) (daemon-retiring daemon))))
(defun reap-retiring-sessions (daemon)
  (setf (daemon-retiring daemon)
        (remove-if
         (lambda (entry)
           (let ((pending nil))
             (dolist (pane (append (session-panes (car entry)) (mapcar #'car (session-retired (car entry)))))
               (when (and (pane-pid pane) (null (pane-status pane)))
                 (let ((exit (reap (pane-pid pane))))
                   (cond ((>= exit 0) (setf (pane-status pane) exit))
                         ((= exit -11)
                          (setf pending t)
                          (when (>= (now) (cdr entry)) (signal-group (pane-pid pane) 9)))))))
             (not pending)))
         (daemon-retiring daemon))))
(defun trim-detached-views (session)
  "Keep home/live views and the eight newest detached extra view IDs."
  (let ((detached (sort (remove-if (lambda (view) (or (view-wire view) (eq view (session-home-view session))))
                                  (copy-list (session-views session))) #'> :key #'view-id)))
    (dolist (view (nthcdr (min +retained-view-limit+ (length detached)) detached))
      (incf (view-epoch view))
      (dolist (request (session-command-queue session))
        (when (eq view (command-origin-view (command-request-origin request)))
          (fail-command request "Detached view was reclaimed by the retention limit")))
      (setf (session-command-queue session)
            (remove view (session-command-queue session)
                    :key (lambda (request) (command-origin-view (command-request-origin request))))
            (session-initialization-queue session) (remove view (session-initialization-queue session))
            (session-views session) (remove view (session-views session))))))
(defun drop-daemon-peer (daemon peer)
  (when (wire-view peer) (detach-view (wire-view peer)))
  (close-wire peer)
  (setf (daemon-peers daemon) (remove peer (daemon-peers daemon))))

(defun session-deadline (session current)
  (let ((deadline (+ current 1)))
    (dolist (view (session-views session))
      (when (view-transition view) (setf deadline (min deadline (+ current 1/50))))
      (dolist (note (view-pane-notes view)) (setf deadline (min deadline (getf note :until))))
      (maphash (lambda (id state)
                 (declare (ignore id))
                 (when (pane-view-copy-flash-until state)
                   (setf deadline (min deadline (pane-view-copy-flash-until state)))))
               (view-pane-states view)))
    (dolist (worker (list (session-worker session) (session-candidate session)))
      (when (and worker (extension-worker-request worker))
        (setf deadline (min deadline (extension-worker-deadline worker)))))
    (dolist (pane (session-panes session))
      (let ((until (pane-sync-until pane)) (pending (store-pending (pane-graphics pane))))
        (when (and until (< current until)) (setf deadline (min deadline until)))
        (when pending (setf deadline (min deadline (+ (ekko/graphics::upload-at pending) 10))))))
    deadline))
(defun session-poll-items (session)
  (append (worker-events (session-worker session)) (worker-events (session-candidate session))
          (loop for pane in (session-panes session) when (pane-io pane)
                collect (cons (wire-fd (pane-io pane)) (wire-events (pane-io pane))))))
(defun service-ready-session (session buffer)
  (dolist (view (session-views session))
    (tick-transition view) (expire-copy-flashes view) (expire-pane-notes view))
  (service-extensions session buffer)
  (reap-retired session)
  (dolist (pane (session-panes session))
    (expire-upload (pane-graphics pane))
    (when (and (pane-pid pane) (null (pane-status pane)))
      (let ((exit (reap (pane-pid pane))))
        (when (>= exit 0) (setf (pane-status pane) exit) (incf (session-revision session)))))))
(defun service-pane-event (pane flags buffer)
  (handler-case
      (progn
        (when (logtest flags 4) (flush-wire (pane-io pane)))
        (when (logtest flags 25)
          (let ((n (read-fd (wire-fd (pane-io pane)) buffer)))
            (cond ((plusp n)
                   (incf (pane-output-bytes pane) n)
                   (note-pane-output (pane-session pane) pane)
                   (feed (pane-vt pane) (subseq buffer 0 n) (lambda (kind value) (pane-event pane kind value))))
                  ((not (member n '(-11 -4)))
                   (close-wire (pane-io pane)) (setf (pane-io pane) nil))))))
    (error (condition)
      (format *error-output* "pane ~D: ~A~%" (pane-id pane) condition)
      (close-pane pane))))
(defun service-daemon-peer (daemon peer)
  (cond
    ((minusp (wire-fd peer)) (drop-daemon-peer daemon peer))
    ((wire-closing peer)
     ;; Socket drainage is not terminal drainage. A last frame keeps its local
     ;; snapshot leases until the terminal-side ACK, even after session stop.
     (when (and (null (wire-awaiting-scene peer)) (null (wire-queue peer)))
       (if (eq (wire-closing peer) :sent)
           (drop-daemon-peer daemon peer)
           (progn (send-packet peer 22) (setf (wire-closing peer) :sent)))))
    (t
     (when (and (wire-pending-switch peer) (null (wire-awaiting-scene peer)) (null (wire-queue peer)))
       (complete-session-switch daemon peer))
     (when (and (wire-view peer) (wire-binding-accepted peer))
       (publish-scene (wire-view peer) peer))
     (when (and (not (wire-attached peer)) (>= (- (now) (wire-at peer)) 10))
       (drop-daemon-peer daemon peer)))))
(defun service-peer-event (daemon peer flags buffer)
  (handler-case
      (progn
        (when (logtest flags 4) (flush-wire peer))
        (when (logtest flags 25)
          (dolist (packet (receive-packets peer buffer))
            (handler-case (daemon-packet daemon peer packet)
              (error (condition)
                (if (and (not (typep condition 'wire-protocol-error))
                         (wire-view peer) (not (wire-closing peer)))
                    (note-error (wire-view peer) condition)
                    (progn
                      (send-packet peer 21 (text-bytes (princ-to-string condition)))
                      (setf (wire-closing peer) :sent)
                      (when (wire-view peer) (detach-view (wire-view peer))))))))))
    (error (condition)
      (unless (search "disconnected" (princ-to-string condition))
        (format *error-output* "client: ~A~%" condition))
      (drop-daemon-peer daemon peer))))
(defun daemon-step (daemon buffer)
  (dolist (creation (copy-list (daemon-creations daemon))) (service-creation daemon creation buffer))
  (dolist (session (copy-list (daemon-sessions daemon)))
    (handler-case (unless (session-stopping session) (service-ready-session session buffer))
      (error (condition)
        (format *error-output* "session ~A: ~A~%" (session-name session) condition)
        (setf (session-stopping session) t)))
    (when (session-stopping session) (retire-session daemon session)))
  (reap-retiring-sessions daemon)
  (dolist (peer (copy-list (daemon-peers daemon)))
    (handler-case (service-daemon-peer daemon peer)
      (error (condition)
        (format *error-output* "client: ~A~%" condition) (drop-daemon-peer daemon peer))))
  (let* ((current (now)) (deadline (+ current 1))
         (sessions (append (daemon-sessions daemon) (mapcar #'creation-session (daemon-creations daemon))))
         (panes (all-panes daemon)))
    (dolist (session sessions) (setf deadline (min deadline (session-deadline session current))))
    (dolist (entry (daemon-retiring daemon)) (setf deadline (min deadline (max current (cdr entry)))))
    (dolist (peer (daemon-peers daemon))
      (unless (wire-attached peer) (setf deadline (min deadline (+ (wire-at peer) 10)))))
    (dolist (event (poll-fds
                   (append (list (cons (daemon-listener daemon) 1))
                           (loop for session in sessions append (session-poll-items session))
                           (loop for peer in (daemon-peers daemon) collect (cons (wire-fd peer) (wire-events peer))))
                   (max 0 (ceiling (* 1000 (- deadline current))))))
      (let* ((fd (car event)) (flags (cdr event))
             (pane (find fd panes :key (lambda (pane) (when (pane-io pane) (wire-fd (pane-io pane)))))))
        (cond
          ((= fd (daemon-listener daemon))
           (loop repeat 32 for accepted = (accept-local fd) while (>= accepted 0) do
             (let ((peer (make-wire :fd accepted)))
               (if (< (length (daemon-peers daemon)) +daemon-peer-limit+)
                   (push peer (daemon-peers daemon))
                   (unwind-protect
                        (progn (send-packet peer 21 (text-bytes "Daemon peer limit reached; retry later"))
                               (flush-wire peer))
                     (close-wire peer))))))
          (pane (service-pane-event pane flags buffer))
          (t (let ((peer (find fd (daemon-peers daemon) :key #'wire-fd)))
               (when peer (service-peer-event daemon peer flags buffer)))))))))

(defun serve ()
  (initialize) (server-signals)
  (let* ((path (socket-path))
         (ekko/store:*directory* (ekko/store:store-directory *instance*))
         (lock (checked (lock-file (concatenate 'string path ".lock")) "daemon lock"))
         (*daemon* (make-daemon :path path :lock lock :store (make-store-state :entries (ekko/store:store-load))))
         (buffer (octets 65536)) (running t))
    (dolist (signal (list sb-posix:sigterm sb-posix:sighup))
      (sb-sys:enable-interrupt signal (lambda (&rest arguments) (declare (ignore arguments)) (setf running nil))))
    (unwind-protect
         (progn
           (initialize-assets (concatenate 'string path ".frames/"))
           (when (probe-file path) (delete-file path))
           (setf (daemon-listener *daemon*) (checked (listen-local path) "listen"))
           (loop while running do (daemon-step *daemon* buffer)))
      (dolist (creation (daemon-creations *daemon*)) (retire-session *daemon* (creation-session creation)))
      (dolist (session (copy-list (daemon-sessions *daemon*))) (retire-session *daemon* session))
      (dolist (peer (copy-list (daemon-peers *daemon*))) (drop-daemon-peer *daemon* peer))
      (let ((deadline (+ (now) 11/10)))
        (loop while (and (daemon-retiring *daemon*) (< (now) deadline)) do
          (reap-retiring-sessions *daemon*) (when (daemon-retiring *daemon*) (poll-fds nil 20))))
      (dolist (entry (daemon-retiring *daemon*))
        (dolist (pane (append (session-panes (car entry)) (mapcar #'car (session-retired (car entry)))))
          (when (and (pane-pid pane) (null (pane-status pane))) (signal-group (pane-pid pane) 9))))
      (when (daemon-listener *daemon*) (close-fd (daemon-listener *daemon*)))
      (when (probe-file path) (delete-file path))
      (close-fd lock)))
  0)
