(defpackage #:ekko/extensions
  (:use #:cl)
  (:export #:register-component #:unregister-component #:register-command #:bind-key
           #:set-option #:value #:action #:api-version))
(in-package #:ekko/extensions)

(defun api-version () 1)
(defparameter *context-keys* '(:session :focus :panes :layout))
(defstruct component id reads handler commands bindings options)
(defvar *components* nil)
(defvar *reads* nil)
(defvar *dispatching* nil)
(defun registration-phase ()
  (when *dispatching* (error "Registrations change during config load; callbacks return actions")))
(defun name-string (name)
  (let ((text (string-downcase (string name))))
    (unless (and (<= 1 (length text) 80)
                 (every (lambda (c) (or (alphanumericp c) (find c "-_/"))) text))
      (error "Invalid registration name: ~S" name)) text))
(defun owner (id)
  (or (find (name-string id) *components* :key #'component-id :test #'equal)
      (error "Unknown component: ~A" id)))
(defun register-component (&key id (api-version 1) reads handler)
  (registration-phase)
  (unless (and (= api-version 1) (listp reads) (every (lambda (k) (member k *context-keys*)) reads)
               (or (null handler) (functionp handler)))
    (error "Invalid component API version, dependencies or handler"))
  (unregister-component id)
  (setf *components* (append *components* (list (make-component :id (name-string id) :reads reads :handler handler))))
  id)
(defun unregister-component (id)
  (registration-phase)
  (setf *components* (remove (name-string id) *components* :key #'component-id :test #'equal)) nil)
(defun register-command (&key component name handler)
  (registration-phase)
  (unless (functionp handler) (error "A command requires a function"))
  (let* ((owner (owner component)) (name (name-string name)))
    (setf (component-commands owner)
          (acons name handler (remove name (component-commands owner) :key #'car :test #'equal)))) name)
(defun key-code (key)
  (cond ((and (integerp key) (<= 0 key #x10ffff)) key)
        ((and (stringp key) (= (length key) 1)) (char-code (char key 0)))
        ((and (stringp key) (= (length key) 3) (string-equal key "C-" :end1 2)
              (alpha-char-p (char key 2))) (logand (char-code (char-upcase (char key 2))) 31))
        (t (or (cdr (assoc key '(("Tab" . 9) ("Enter" . 13) ("Escape" . 27)
                                 ("Up" . :up) ("Down" . :down) ("PageUp" . :page-up)
                                 ("PageDown" . :page-down) ("Home" . :home) ("End" . :end)) :test #'equal))
               (error "Unknown key: ~S" key)))))
(defun bind-key (&key component key command (map :prefix))
  (registration-phase)
  (unless (member map '(:prefix :copy)) (error "Unknown keymap: ~S" map))
  (let ((owner (owner component)) (key (list map (key-code key))))
    (setf (component-bindings owner)
          (acons key (and command (name-string command))
                 (remove key (component-bindings owner) :key #'car :test #'equal)))) nil)
(defun set-option (&key component name value)
  (registration-phase)
  (unless (case name
            (:prefix (and (integerp (key-code value)) (<= 1 (key-code value) 26)))
            (:shell (and (listp value) (<= 1 (length value) 64) (every (lambda (s) (and (stringp s) (<= (length s) 4096) (not (find #\Null s)))) value)
                         (plusp (length (first value)))))
            (:status-text (and (stringp value) (<= (length value) 512)))
            (:status-style (and (listp value) (<= (length value) 16)
                                (every (lambda (n) (and (integerp n) (<= 0 n 255))) value))))
    (error "Invalid option ~S: ~S" name value))
  (setf (getf (component-options (owner component)) name)
        (if (eq name :prefix) (key-code value) value)) nil)
(defun value (snapshot key)
  (unless (member key *reads*) (error "Undeclared snapshot dependency: ~S" key))
  (getf snapshot key))
(defun action (kind &rest arguments) (cons kind arguments))

(defun registry ()
  (list :api-version 1
        :components (loop for c in *components* collect
                     (list :id (component-id c) :reads (component-reads c) :hook (not (null (component-handler c)))))
        :commands (loop for c in *components* append
                    (loop for (name . fn) in (component-commands c) collect
                      (list :name name :owner (component-id c))))
        :bindings (loop for c in *components* append
                    (loop for (key . name) in (component-bindings c) collect
                      (list :map (first key) :key (second key) :command name :owner (component-id c))))
        :options (loop with options = nil for c in *components* do
                   (loop for (key val) on (component-options c) by #'cddr do (setf (getf options key) val))
                   finally (return options))))
(defun dispatch (kind name snapshot event)
  (let* ((c (if (eq kind :hook) (owner name)
                (or (find-if (lambda (c) (assoc name (component-commands c) :test #'equal)) (reverse *components*))
                    (error "Unknown command: ~A" name))))
         (fn (if (eq kind :hook) (component-handler c) (cdr (assoc name (component-commands c) :test #'equal))))
         (*reads* (component-reads c)) (*dispatching* t)
         (visible (loop for key in *reads* append (list key (copy-tree (getf snapshot key))))))
    (list :owner (component-id c) :actions (funcall fn visible (copy-tree event)))))
