(defpackage #:ekko/extensions
  (:use #:cl)
  (:export #:register-component #:unregister-component #:register-command #:bind-key
           #:register-keymap #:set-option #:value #:action #:api-version #:display-width))
(in-package #:ekko/extensions)

(defun display-width (value)
  "Return the ordinary Unicode terminal cell width of a character or string."
  (ekko/text:display-width value))

(defun api-version () 1)
(defparameter *context-keys* '(:session :focus :panes :layout :mode :zoom :viewport :chrome-status :pane-notes :component-state :geometry :time))
(defstruct component id reads handler initialize commands bindings options keymaps)
(defvar *components* nil)
(defvar *reads* nil)
(defvar *dispatching* nil)
(defun registration-phase ()
  (when *dispatching* (error "Registrations change during config load; callbacks return actions")))
(defun name-string (name)
  (let ((text (string-downcase (string name))))
    (unless (and (<= 1 (length text) 80)
                 (every (lambda (c) (or (alphanumericp c) (find c "-_/"))) text))
      (error "Invalid registration name: ~S" name)) text))
(defun owner (id)
  (or (find (name-string id) *components* :key #'component-id :test #'equal)
      (error "Unknown component: ~A" id)))
(defun register-component (&key id (api-version 1) reads handler initialize)
  (registration-phase)
  (unless (and (= api-version 1) (listp reads) (every (lambda (k) (member k *context-keys*)) reads)
               (or (null handler) (functionp handler))
               (or (null initialize) (functionp initialize)))
    (error "Invalid component API version, dependencies or handler"))
  (unregister-component id)
  (setf *components* (append *components* (list (make-component :id (name-string id) :reads reads :handler handler :initialize initialize))))
  id)
(defun unregister-component (id)
  (registration-phase)
  (setf *components* (remove (name-string id) *components* :key #'component-id :test #'equal)) nil)
(defun register-command (&key component name handler)
  (registration-phase)
  (unless (functionp handler) (error "A command requires a function"))
  (let* ((owner (owner component)) (name (name-string name)))
    (setf (component-commands owner)
          (acons name handler (remove name (component-commands owner) :key #'car :test #'equal)))) name)
(defparameter *named-keys*
  '(("Tab" . 9) ("Enter" . 13) ("Escape" . 27)
    ("Left" . :left) ("Right" . :right) ("Up" . :up) ("Down" . :down)
    ("PageUp" . :page-up) ("PageDown" . :page-down) ("Home" . :home) ("End" . :end)))
(defun named-key (token)
  (cdr (assoc token *named-keys* :test #'equal)))
(defun split-key-tokens (string)
  (loop with start = 0
        for index from 0 to (length string)
        when (or (= index (length string)) (char= (char string index) #\-))
          collect (subseq string start index)
          and do (setf start (1+ index))))
(defun key-modifier (token)
  (cond ((or (string-equal token "C") (string-equal token "Ctrl")) :ctrl)
        ((or (string-equal token "M") (string-equal token "Alt")) :alt)
        ((or (string-equal token "W") (string-equal token "Super") (string-equal token "Win")) :super)
        (t nil)))
(defun base-key-code (token)
  (or (named-key token)
      (when (= (length token) 1) (char-code (char token 0)))
      (error "Unknown key: ~S" token)))
(defun key-code (key)
  "Parse a key spec: integer code point, one character, named key, or a dash chord.
Control folds into the legacy control code; Alt and Super return (MODS . KEY) with
bit 1 for Alt and bit 2 for Super."
  (cond ((and (integerp key) (<= 0 key #x10ffff)) key)
        ((stringp key)
         (let ((tokens (split-key-tokens key)))
           (if (= 1 (length tokens))
               (base-key-code (first tokens))
               (let ((mods 0) (ctrl nil))
                 (dolist (token (butlast tokens))
                   (let ((modifier (key-modifier token)))
                     (unless modifier (error "Unknown key modifier: ~S" token))
                     (case modifier
                       (:ctrl (setf ctrl t))
                       (:alt (setf mods (logior mods 1)))
                       (:super (setf mods (logior mods 2))))))
                 (let ((base (base-key-code (car (last tokens)))))
                   (when ctrl
                     (unless (and (integerp base) (<= 64 base 127))
                       (error "Control chords need a printable ASCII base key: ~S" key))
                     (setf base (logand base 31)))
                   (if (zerop mods) base (cons mods base)))))))
        (t (error "Unknown key: ~S" key))))
(defun register-keymap (&key component name (unbound :forward))
  (registration-phase)
  (when (stringp unbound) (setf unbound (name-string unbound)))
  (unless (and (keywordp name) name (not (member name '(:prefix :copy)))
               (or (member unbound '(:forward :ignore :copy)) (stringp unbound)))
    (error "Invalid keymap name or unbound policy"))
  (name-string name)
  (let ((owner (owner component)))
    (setf (component-keymaps owner)
          (acons name unbound (remove name (component-keymaps owner) :key #'car))))
  name)
(defun bind-key (&key component key command (map :prefix) arguments)
  (registration-phase)
  (unless (and (keywordp map) map) (error "Invalid keymap: ~S" map))
  (when arguments
    (unless (and command (listp arguments) (<= 1 (length arguments) 8)
                 (every (lambda (argument) (and (stringp argument) (<= (length argument) 512))) arguments))
      (error "Invalid binding arguments")))
  (let* ((owner (owner component)) (key (list map (key-code key)))
         (value (and command (cons (name-string command) (and arguments (copy-list arguments))))))
    (setf (component-bindings owner)
          (acons key value (remove key (component-bindings owner) :key #'car :test #'equal)))) nil)
(defun bounded-geometry-p (value length)
  (and (listp value) (= (length value) length)
       (every (lambda (n) (and (integerp n) (<= 0 n 16))) value)))
(defun initial-layout-leaves (tree)
  "Validate a startup tree and return its one-based command slots."
  (let ((leaves nil) (nodes 0))
    (labels ((visit (node)
               (when (> (incf nodes) 31) (error "Initial layout exceeds sixteen panes"))
               (cond
                 ((typep node '(integer 1 16))
                  (when (member node leaves) (error "Duplicate initial layout slot ~D" node))
                  (push node leaves))
                 ((and (listp node) (= (length node) 4)
                       (member (first node) '(:columns :rows))
                       (typep (second node) '(integer 1 99)))
                  (visit (third node)) (visit (fourth node)))
                 (t (error "Invalid initial layout node ~S" node)))))
      (when tree (visit tree)))
    (unless (equal (sort (copy-list leaves) #'<)
                   (loop for slot from 1 to (length leaves) collect slot))
      (error "Initial layout must include each command slot from one"))
    (nreverse leaves)))
(defun set-option (&key component name value)
  (registration-phase)
  (unless (case name
            (:initial-keymap (or (null value) (and (keywordp value) (not (member value '(:prefix :copy))))))
            (:initial-layout (progn (initial-layout-leaves value) t))
            (:prefix (and (integerp (key-code value)) (<= 1 (key-code value) 26)))
            (:shell (and (listp value) (<= 1 (length value) 64) (every (lambda (s) (and (stringp s) (<= (length s) 4096) (not (find #\Null s)))) value)
                         (plusp (length (first value)))))
            (:viewer-exit-text
             (or (null value)
                 (and (stringp value) (<= (length value) 512)
                      (every (lambda (character)
                               (let ((code (char-code character)))
                                 (or (<= 32 code 126) (<= 160 code)))) value))))
            (:status-text (and (stringp value) (<= (length value) 512)))
            (:status-style (and (listp value) (<= (length value) 16)
                                (every (lambda (n) (and (integerp n) (<= 0 n 255))) value)))
            (:window-animation-ms (typep value '(integer 0 250)))
            (:erase-display-history (or (eq value t) (null value)))
            (:pane-insets (bounded-geometry-p value 4))
            (:boundary-insets (or (null value) (bounded-geometry-p value 4)))
            (:viewport-insets (bounded-geometry-p value 4))
            (:split-gaps (bounded-geometry-p value 2))
            (:pty-pixel-source (member value '(:effective :reported))))
    (error "Invalid option ~S: ~S" name value))
  (setf (getf (component-options (owner component)) name)
        (if (eq name :prefix) (key-code value) value)) nil)
(defun value (snapshot key)
  (unless (member key *reads*) (error "Undeclared snapshot dependency: ~S" key))
  (getf snapshot key))
(defun action (kind &rest arguments) (cons kind arguments))

(defun registry ()
  (list :api-version 1
        :components (loop for c in *components* collect
                     (list :id (component-id c) :reads (component-reads c) :hook (not (null (component-handler c)))
                           :initialize (not (null (component-initialize c)))))
        :keymaps (loop for c in *components* append
                   (loop for (name . unbound) in (component-keymaps c) collect
                     (list :name name :unbound unbound :owner (component-id c))))
        :commands (loop for c in *components* append
                    (loop for (name . fn) in (component-commands c) collect
                      (list :name name :owner (component-id c))))
        :bindings (loop for c in *components* append
                    (loop for (key . value) in (component-bindings c) collect
                      (list* :map (first key) :key (second key) :command (car value) :owner (component-id c)
                             (when (cdr value) (list :arguments (cdr value))))))
        :options (loop with options = nil for c in *components* do
                   (loop for (key val) on (component-options c) by #'cddr do (setf (getf options key) val))
                   finally (return options))))
(defun dispatch (kind name snapshot event)
  (let* ((c (if (member kind '(:hook :initialize)) (owner name)
                (or (find-if (lambda (c) (assoc name (component-commands c) :test #'equal)) (reverse *components*))
                    (error "Unknown command: ~A" name))))
         (fn (case kind (:hook (component-handler c)) (:initialize (component-initialize c))
               (otherwise (cdr (assoc name (component-commands c) :test #'equal)))))
         (*reads* (component-reads c)) (*dispatching* t)
         (visible (loop for key in *reads* append (list key (copy-tree (getf snapshot key))))))
    (list :owner (component-id c) :actions (funcall fn visible (copy-tree event)))))
