(defpackage #:ekko/graphics
  (:use #:cl)
  (:export #:make-store #:accept-command #:store-images #:store-pending #:store-revision
           #:store-frames #:store-errors #:store-bytes #:expire-upload #:clear-screen
           #:scroll-images #:image-id #:image-generation #:image-width #:image-height
           #:image-format #:image-data #:image-x #:image-y #:image-cols #:image-rows
           #:image-screen #:image-visible #:base64-encode #:base64-decode))
(in-package #:ekko/graphics)

(defparameter *alphabet* "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/")
(defparameter *decode-table*
  (let ((table (make-array 256 :element-type '(signed-byte 8) :initial-element -1)))
    (dotimes (i (length *alphabet*) table)
      (setf (aref table (char-code (char *alphabet* i))) i))))
(defun base64-encode (bytes)
  (declare (optimize (speed 3) (safety 2)))
  (check-type bytes (vector (unsigned-byte 8)))
  (unless (typep bytes '(simple-array (unsigned-byte 8) (*)))
    (return-from base64-encode (base64-encode (copy-seq bytes))))
  (let* ((n (length bytes)) (text (make-string (* 4 (ceiling n 3)) :element-type 'base-char :initial-element #\=)))
    (declare (type (simple-array (unsigned-byte 8) (*)) bytes)
             (type simple-base-string text))
    (loop for i fixnum from 0 below n by 3 for j fixnum from 0 by 4
          for bits = (+ (ash (aref bytes i) 16) (if (< (1+ i) n) (ash (aref bytes (1+ i)) 8) 0)
                        (if (< (+ i 2) n) (aref bytes (+ i 2)) 0)) do
      (setf (char text j) (char *alphabet* (ldb (byte 6 18) bits))
            (char text (1+ j)) (char *alphabet* (ldb (byte 6 12) bits)))
      (when (< (1+ i) n) (setf (char text (+ j 2)) (char *alphabet* (ldb (byte 6 6) bits))))
      (when (< (+ i 2) n) (setf (char text (+ j 3)) (char *alphabet* (ldb (byte 6 0) bits))))) text))
(defun base64-decode (input &key (start 0) (end (length input)))
  (declare (optimize (speed 3) (safety 2)))
  (unless (and (integerp start) (integerp end) (<= 0 start end (length input)))
    (error "Invalid base64 range"))
  ;; Public string callers retain their API. Graphics ingress uses the octet
  ;; branch directly, avoiding a full payload conversion/copy on every chunk.
  (when (stringp input)
    (return-from base64-decode
      (base64-decode (map '(vector (unsigned-byte 8)) #'char-code (subseq input start end)))))
  (check-type input (vector (unsigned-byte 8)))
  ;; Normalize uncommon adjustable/displaced vectors at the boundary. The
  ;; graphics parser already supplies simple octets; its hot loop needs no copy.
  (unless (typep input '(simple-array (unsigned-byte 8) (*)))
    (return-from base64-decode (base64-decode (subseq input start end))))
  (let* ((start (the fixnum start)) (end (the fixnum end))
         (n (- end start))
         (table *decode-table*)
         (padding (cond ((zerop n) 0)
                        ((= (aref input (1- end)) 61)
                         (if (and (> n 1) (= (aref input (- end 2)) 61)) 2 1))
                        (t 0))))
    (declare (type (simple-array (signed-byte 8) (256)) table)
             (type (simple-array (unsigned-byte 8) (*)) input))
    (unless (zerop (mod n 4)) (error "Invalid base64 length"))
    (let ((out (ekko/platform:octets (- (* 3 (floor n 4)) padding))))
      (declare (type (simple-array (unsigned-byte 8) (*)) out))
      (loop for i fixnum from start below end by 4 for target fixnum from 0 by 3 do
        (let ((bits 0))
          (declare (type (unsigned-byte 24) bits))
          (dotimes (k 4)
            (let* ((index (+ i k)) (code (aref input index))
                   (value (if (and (= code 61) (>= index (- end padding))) 0
                              (aref table code))))
              (when (minusp value) (error "Invalid base64 alphabet"))
              (setf bits (logior (ash bits 6) value))))
          ;; Padding replaces low-order groups with zeroes. Reject nonzero
          ;; unused bits in the last real group, without re-encoding the image.
          (when (= (+ i 4) end)
            (when (or (and (= padding 2) (not (zerop (logand bits #xffff))))
                      (and (= padding 1) (not (zerop (logand bits #xff)))))
              (error "Invalid base64 padding")))
          (dotimes (k (min 3 (- (length out) target)))
            (setf (aref out (+ target k)) (ldb (byte 8 (* 8 (- 2 k))) bits)))))
      out)))
(defstruct image id generation width height format data (x 0) (y 0) (cols 0) (rows 0) screen (visible t))
(defstruct upload keys chunks (bytes 0) (at (ekko/platform:now)) x y screen)
(defstruct store (images (make-hash-table)) pending (revision 0) (frames 0) (errors 0) (bytes 0) (next-id 1))
(defun header (text)
  (let ((keys (make-hash-table :test 'eql)))
    (dolist (part (uiop:split-string text :separator ","))
      (unless (and (>= (length part) 3) (char= (char part 1) #\=)
                   (not (gethash (char part 0) keys))) (error "Invalid graphics header"))
      (setf (gethash (char part 0) keys) (subseq part 2))) keys))
(defun number-key (keys key &optional (default 0))
  (let ((value (gethash key keys)))
    (if value (let ((n (parse-integer value)))
                (unless (<= 0 n #xffffffff) (error "Invalid graphics integer")) n) default)))
(defun key-is (keys key value &optional default) (string= (gethash key keys default) value))
(defun acknowledge (keys emit message)
  (let ((id (number-key keys #\i)) (quiet (number-key keys #\q)))
    (when (and (plusp id) (or (zerop quiet) (and (= quiet 1) (not (string= message "OK")))))
      (funcall emit :reply (format nil "~C_Gi=~D~A;~A~C\\" (code-char 27) id
                                  (if (gethash #\p keys) (format nil ",p=~D" (number-key keys #\p)) "")
                                  message (code-char 27))))))
(defun remove-image (store id)
  (let ((image (gethash id (store-images store))))
    (when image (decf (store-bytes store) (ekko/platform:asset-size (image-data image)))
          (ekko/platform:release-asset (image-data image))
          (remhash id (store-images store)) (incf (store-revision store)))))
(defun clear-screen (store screen)
  (let ((ids (loop for image being the hash-values of (store-images store)
                  when (eq (image-screen image) screen) collect (image-id image))))
    (dolist (id ids) (remove-image store id)))
  (setf (store-pending store) nil))
(defun expire-upload (store)
  (when (and (store-pending store) (>= (- (ekko/platform:now) (upload-at (store-pending store))) 10))
    (setf (store-pending store) nil) (incf (store-errors store))))
(defun scroll-images (store screen top bottom amount cw ch)
  (declare (ignore cw))
  (maphash (lambda (id image)
             (declare (ignore id))
             (when (and (eq screen (image-screen image))
                        (<= (* top ch) (image-y image) (* (1+ bottom) ch)))
               (decf (image-y image) (* amount ch)) (incf (store-revision store)))) (store-images store)))
(defun complete-upload (store upload vt emit)
  (let* ((keys (upload-keys upload)) (w (number-key keys #\s)) (h (number-key keys #\v))
         (format (number-key keys #\f 32)) (data (ekko/platform:octets (upload-bytes upload))))
    ;; CONCATENATE on hundreds of chunks takes the generic sequence path.
    ;; The upload already tracks its exact size; copy each byte range once.
    (loop with offset = 0 for chunk in (nreverse (upload-chunks upload))
          do (replace data chunk :start1 offset) (incf offset (length chunk)))
    (unless (and (member format '(24 32)) (<= 1 w 8192) (<= 1 h 8192)
                 (<= (* w h (/ format 8)) (* 32 1024 1024))) (error "Unsupported image format or dimensions"))
    (let* ((size (* w h (/ format 8)))
           (compressed (if (key-is keys #\o "z")
                           (progn (ekko/platform:decompress-bytes data size) data)
                           (progn (unless (= (length data) size) (error "Invalid image length"))
                                  (ekko/platform:compress-bytes data)))))
      (commit-image store upload vt emit compressed w h format))))

(defun commit-image (store upload vt emit compressed w h format)
  (let ((keys (upload-keys upload)))
      (if (key-is keys #\a "q") (acknowledge keys emit "OK")
          (let* ((id (number-key keys #\i)) (old (gethash id (store-images store))))
            (when (zerop id) (setf id (loop for n = (incf (store-next-id store)) unless (gethash n (store-images store)) return n)))
            (when (or (and (null old) (>= (hash-table-count (store-images store)) 64))
                      (> (+ (store-bytes store) (ekko/platform:asset-size compressed) (- (if old (ekko/platform:asset-size (image-data old)) 0))) (* 128 1024 1024)))
              (error "Pane image quota exceeded"))
            (when old
              (decf (store-bytes store) (ekko/platform:asset-size (image-data old)))
              (ekko/platform:release-asset (image-data old)))
            (incf (store-bytes store) (ekko/platform:asset-size compressed))
            (setf (gethash id (store-images store))
                  (make-image :id id :generation (incf (store-revision store)) :width w :height h :format format
                              :data compressed :x (+ (upload-x upload) (number-key keys #\X))
                              :y (+ (upload-y upload) (number-key keys #\Y))
                              :cols (number-key keys #\c) :rows (number-key keys #\r)
                              :screen (upload-screen upload) :visible (key-is keys #\a "T" "t")))
            (incf (store-frames store)) (acknowledge keys emit "OK")
            (when (and (key-is keys #\a "T") (zerop (number-key keys #\C)))
              (setf (ekko/vt:terminal-x vt) (min (1- (ekko/vt:terminal-cols vt))
                                                 (+ (ekko/vt:terminal-x vt) (ceiling w (ekko/vt:terminal-cw vt)))))
              (setf (ekko/vt:terminal-y vt) (min (1- (ekko/vt:terminal-rows vt))
                                                 (+ (ekko/vt:terminal-y vt) (1- (ceiling h (ekko/vt:terminal-ch vt))))))))))
)
(defun accept-command (store bytes vt emit)
  (unless (and (plusp (length bytes)) (= (aref bytes 0) 71)) (return-from accept-command))
  (let ((keys nil))
    (handler-case
        (let* ((semi (position 59 bytes))
               (text (map 'string #'code-char (subseq bytes 1 semi))))
          (setf keys (header text))
          (maphash (lambda (key value) (declare (ignore value))
                     (unless (find key "aftsvipCqmoXYd" :test #'char=) (error "Unsupported graphics key"))) keys)
          (unless (member (gethash #\t keys "d") '("d" "s") :test #'string=)
            (error "Unsupported graphics transfer medium"))
          (when (some (lambda (key) (gethash key keys)) '(#\U #\I #\P #\Q #\x #\y #\w #\h #\z #\c #\r))
            (error "Unsupported graphics placement key"))
          (when (and (gethash #\o keys) (not (key-is keys #\o "z"))) (error "Unsupported compression"))
          (cond
            ((key-is keys #\t "s")
             (unless (and (member (gethash #\a keys "t") '("t" "T" "q") :test #'string=)
                          (zerop (number-key keys #\m)) (not (gethash #\o keys)))
               (error "Shared transfers require one uncompressed RGB/RGBA frame"))
             (setf (store-pending store) nil)
             (let* ((w (number-key keys #\s)) (h (number-key keys #\v))
                    (format (number-key keys #\f 32)) (size (* w h (/ format 8)))
                    (id (number-key keys #\i)) (old (gethash id (store-images store))))
               (unless (and (member format '(24 32)) (<= 1 w 8192) (<= 1 h 8192)
                            (<= 1 size (* 32 1024 1024))
                            (or (key-is keys #\a "q")
                                (and (or old (< (hash-table-count (store-images store)) 64))
                                     (<= (+ (store-bytes store) size
                                            (- (if old (ekko/platform:asset-size (image-data old)) 0)))
                                         (* 128 1024 1024)))))
                 (error "Invalid dimensions or pane quota exceeded"))
               (let ((asset (ekko/platform:snapshot-asset
                              (ekko/platform:bytes-text (base64-decode bytes :start (if semi (1+ semi) (length bytes)))) size)))
                 (unwind-protect
                      (progn
                        (commit-image store
                          (make-upload :keys keys :x (* (ekko/vt:terminal-x vt) (ekko/vt:terminal-cw vt))
                                       :y (* (ekko/vt:terminal-y vt) (ekko/vt:terminal-ch vt))
                                       :screen (ekko/vt:terminal-screen vt))
                          vt emit asset w h format))
                   (unless (loop for image being the hash-values of (store-images store)
                                 thereis (eq asset (image-data image)))
                     (ekko/platform:release-asset asset))))))
            ((key-is keys #\a "d")
             (let ((kind (gethash #\d keys "a")))
               (cond ((member kind '("a" "A") :test #'string=) (clear-screen store (ekko/vt:terminal-screen vt)))
                     ((member kind '("i" "I") :test #'string=) (remove-image store (number-key keys #\i)))
                     (t (error "Unsupported delete")))))
            ((key-is keys #\a "p")
             (let ((image (gethash (number-key keys #\i) (store-images store))))
               (unless image (error "Unknown image"))
               (setf (image-x image) (* (ekko/vt:terminal-x vt) (ekko/vt:terminal-cw vt))
                     (image-y image) (* (ekko/vt:terminal-y vt) (ekko/vt:terminal-ch vt))
                     (image-visible image) t (image-cols image) (number-key keys #\c)
                     (image-rows image) (number-key keys #\r))
               (incf (store-revision store)) (acknowledge keys emit "OK")))
            (t
             (unless (member (gethash #\a keys "t") '("t" "T" "q") :test #'string=) (error "Unsupported graphics action"))
             (when (or (gethash #\a keys) (gethash #\s keys)) (setf (store-pending store) nil))
             (let* ((upload (or (store-pending store)
                                (make-upload :keys keys :x (* (ekko/vt:terminal-x vt) (ekko/vt:terminal-cw vt))
                                             :y (* (ekko/vt:terminal-y vt) (ekko/vt:terminal-ch vt))
                                             :screen (ekko/vt:terminal-screen vt))))
                    (chunk (base64-decode bytes :start (if semi (1+ semi) (length bytes)))))
               (when (> (+ (upload-bytes upload) (length chunk)) (* 32 1024 1024)) (error "Upload quota exceeded"))
               (unless (member (number-key keys #\m) '(0 1)) (error "Invalid continuation flag"))
               (incf (upload-bytes upload) (length chunk)) (push chunk (upload-chunks upload))
               (setf (upload-at upload) (ekko/platform:now) (store-pending store) upload)
               (when (zerop (number-key keys #\m))
                 (setf (store-pending store) nil keys (upload-keys upload))
                 (complete-upload store upload vt emit))))))
      (error ()
        (incf (store-errors store)) (setf (store-pending store) nil)
        (when keys (ignore-errors (acknowledge keys emit "ENOTSUP:unsupported or invalid graphics operation")))))))
