(in-package #:ekko/runtime)

;; A popup is attachment-local interaction state. Its spans, styles and actions
;; come from an ordinary decoration owner; the host only places and routes them.
(defstruct popup owner spans x y width height (scroll 0) selected pressed)
(defun span-width (span)
  (loop for c across (getf span :text) sum (ekko/vt:character-width c)))
(defun span-hit-p (span x y)
  (and (<= (getf span :x) x) (< x (+ (getf span :x) (span-width span)))
       (<= (getf span :y) y) (< y (+ (getf span :y) (getf span :rows 1)))))
(defun span-control-p (span)
  (or (getf span :action) (getf span :command)))
(defun activate-span (view owner span)
  (handler-case
      (if (getf span :command)
          (request-command view (getf span :command)
                           (list :arguments (getf span :arguments)) nil)
          (when (getf span :action)
            (apply-actions view owner (list (getf span :action)) nil nil)))
    (error (e) (note-error view e))))
(defun forget-popup-glows (view)
  (setf (view-glows view) (remove :popup (view-glows view) :key #'caar)))
(defun close-popup (view)
  (when (view-popup view)
    ;; A closed menu fades out where it was, without taking input.
    (when (plusp (animation-seconds view))
      (setf (view-popup-ghost view) (list (view-popup view) (now))))
    (setf (view-popup view) nil)
    (forget-popup-glows view)
    (incf (view-revision view))))
(defun open-popup (view owner spans x y)
  (let* ((width (min (view-cols view)
                     (loop for span in spans maximize (+ (getf span :x) (span-width span)))))
         (height (min (view-rows view)
                      (loop for span in spans maximize (+ (getf span :y) (getf span :rows 1))))))
    (setf (view-popup view)
          (make-popup :owner owner :spans (copy-tree spans)
                      :x (max 0 (min x (- (view-cols view) width)))
                      :y (max 0 (min y (- (view-rows view) height)))
                      :width width :height height)
          (view-drag view) nil (view-transition view) nil)
    (forget-popup-glows view)
    (incf (view-revision view))))
(defun popup-select (view index)
  (let* ((popup (view-popup view)) (span (and index (nth index (popup-spans popup)))))
    (unless (eql index (popup-selected popup))
      (when (popup-selected popup) (set-glow view (list :popup (popup-selected popup)) nil))
      (when index (set-glow view (list :popup index) t))
      (setf (popup-selected popup) index)
      (when span
        (setf (popup-scroll popup)
              (max 0 (min (getf span :y)
                          (max (popup-scroll popup) (- (1+ (getf span :y)) (popup-height popup)))))))
      (incf (view-revision view)))))
(defun popup-cycle (view delta)
  (let* ((popup (view-popup view))
         (indices (loop for span in (popup-spans popup) for index from 0
                        when (span-control-p span) collect index))
         (at (position (popup-selected popup) indices)))
    (when indices
      (popup-select view (nth (mod (+ (or at (if (plusp delta) -1 0)) delta)
                                      (length indices)) indices)))))
(defun popup-key (view key)
  (when (view-popup view)
    ;; Up/Down, Tab and the vim keys j/k move the picker selection; a span's
    ;; own :key activates it directly.
    (let* ((popup (view-popup view))
           (keyed (and (integerp key)
                       (find (string (code-char key)) (popup-spans popup)
                             :key (lambda (span) (getf span :key)) :test #'equal))))
      (cond ((member key '(27 7)) (close-popup view))
            (keyed (close-popup view) (activate-span view (popup-owner popup) keyed))
            ((member key '(:down 9 106)) (popup-cycle view 1))
            ((member key '(:up 107)) (popup-cycle view -1))
            ((eql key 13)
             (let ((span (and (popup-selected popup) (nth (popup-selected popup) (popup-spans popup)))))
               (close-popup view)
               (when span (activate-span view (popup-owner popup) span))))))
    t))
(defun popup-mouse (view button x y up)
  (let ((popup (view-popup view)))
    (when popup
      (let* ((inside (and (<= (popup-x popup) x) (< x (+ (popup-x popup) (popup-width popup)))
                          (<= (popup-y popup) y) (< y (+ (popup-y popup) (popup-height popup)))))
             (index (when inside
                      (position-if (lambda (span)
                                     (and (span-control-p span)
                                          (span-hit-p span (- x (popup-x popup))
                                                      (+ (- y (popup-y popup)) (popup-scroll popup)))))
                                   (popup-spans popup)))))
        (cond ((and (not up) (member button '(64 65))) (popup-cycle view (if (= button 64) -1 1)))
              ((and (not up) (< button 3) (not inside))
               (close-popup view) (setf (view-chrome-press view) :dismiss))
              ((= button 0)
               (if up
                   (let ((pressed (popup-pressed popup)))
                     (setf (popup-pressed popup) nil)
                     (when (and pressed (eql pressed index))
                       (let ((span (nth index (popup-spans popup))))
                         (close-popup view)
                         (activate-span view (popup-owner popup) span))))
                   (setf (popup-pressed popup) index))
               (when (view-popup view) (popup-select view index)))
              ((logbitp 5 button) (popup-select view index))))
      t)))
(defun popup-pieces (view popup &optional fading)
  "POPUP's cells: entering, or FADING out at that opacity. The selection's
highlight glows in and out rather than jumping between rows."
  (loop for span in (popup-spans popup) for index from 0
        for row = (- (getf span :y) (popup-scroll popup))
        when (<= 0 row (1- (popup-height popup)))
          append (multiple-value-bind (dx dy entering) (if fading (values 0 0 fading) (motion-offset view span))
                   (let ((level (if fading
                                    (if (eql index (popup-selected popup)) 1 0)
                                    (glow-at view (list :popup index)))))
                     (clip-decoration view nil
                       (list :x (+ (popup-x popup) (getf span :x) dx) :y (+ (popup-y popup) row dy)
                             :text (getf span :text)
                             :sgr (blend-sgr (getf span :sgr) (getf span :hover-sgr (getf span :sgr)) level)
                             :alpha entering))))))
(defun popup-overlays (view)
  (append
   (destructuring-bind (&optional ghost started) (view-popup-ghost view)
     (when ghost
       (popup-pieces view ghost (max 1/100 (- 1 (ease-out (animation-progress started (animation-seconds view 3/4))))))))
   (when (view-popup view) (popup-pieces view (view-popup view)))))
