(in-package #:ekko/runtime)

;; A popup is attachment-local interaction state. Its spans, styles and actions
;; come from an ordinary decoration owner; the host only places and routes them.
(defstruct popup owner spans x y width height (scroll 0) selected pressed)
(defun span-width (span)
  (loop for c across (getf span :text) sum (ekko/vt::character-width c)))
(defun span-hit-p (span x y)
  (and (<= (getf span :x) x) (< x (+ (getf span :x) (span-width span)))
       (<= (getf span :y) y) (< y (+ (getf span :y) (getf span :rows 1)))))
(defun span-control-p (span)
  (or (getf span :action) (getf span :command)))
(defun activate-span (session owner span)
  (handler-case
      (if (getf span :command)
          (request-command session (getf span :command)
                           (list :arguments (getf span :arguments)) nil)
          (when (getf span :action)
            (apply-actions session owner (list (getf span :action)) nil nil)))
    (error (e) (note-error session e))))
(defun close-popup (session)
  (when (session-popup session)
    (setf (session-popup session) nil)
    (incf (session-revision session))))
(defun open-popup (session owner spans x y)
  (let* ((width (min (session-cols session)
                     (loop for span in spans maximize (+ (getf span :x) (span-width span)))))
         (height (min (session-rows session)
                      (loop for span in spans maximize (+ (getf span :y) (getf span :rows 1))))))
    (setf (session-popup session)
          (make-popup :owner owner :spans (copy-tree spans)
                      :x (max 0 (min x (- (session-cols session) width)))
                      :y (max 0 (min y (- (session-rows session) height)))
                      :width width :height height)
          (session-drag session) nil (session-transition session) nil)
    (incf (session-revision session))))
(defun popup-select (session index)
  (let* ((popup (session-popup session)) (span (and index (nth index (popup-spans popup)))))
    (unless (eql index (popup-selected popup))
      (setf (popup-selected popup) index)
      (when span
        (setf (popup-scroll popup)
              (max 0 (min (getf span :y)
                          (max (popup-scroll popup) (- (1+ (getf span :y)) (popup-height popup)))))))
      (incf (session-revision session)))))
(defun popup-cycle (session delta)
  (let* ((popup (session-popup session))
         (indices (loop for span in (popup-spans popup) for index from 0
                        when (span-control-p span) collect index))
         (at (position (popup-selected popup) indices)))
    (when indices
      (popup-select session (nth (mod (+ (or at (if (plusp delta) -1 0)) delta)
                                      (length indices)) indices)))))
(defun popup-key (session key)
  (when (session-popup session)
    (cond ((member key '(27 7)) (close-popup session))
          ((member key '(:down 9)) (popup-cycle session 1))
          ((eq key :up) (popup-cycle session -1))
          ((eql key 13)
           (let* ((popup (session-popup session))
                  (span (and (popup-selected popup) (nth (popup-selected popup) (popup-spans popup)))))
             (close-popup session)
             (when span (activate-span session (popup-owner popup) span)))))
    t))
(defun popup-mouse (session button x y up)
  (let ((popup (session-popup session)))
    (when popup
      (let* ((inside (and (<= (popup-x popup) x) (< x (+ (popup-x popup) (popup-width popup)))
                          (<= (popup-y popup) y) (< y (+ (popup-y popup) (popup-height popup)))))
             (index (when inside
                      (position-if (lambda (span)
                                     (and (span-control-p span)
                                          (span-hit-p span (- x (popup-x popup))
                                                      (+ (- y (popup-y popup)) (popup-scroll popup)))))
                                   (popup-spans popup)))))
        (cond ((and (not up) (member button '(64 65))) (popup-cycle session (if (= button 64) -1 1)))
              ((and (not up) (< button 3) (not inside))
               (close-popup session) (setf (session-chrome-press session) :dismiss))
              ((= button 0)
               (if up
                   (let ((pressed (popup-pressed popup)))
                     (setf (popup-pressed popup) nil)
                     (when (and pressed (eql pressed index))
                       (let ((span (nth index (popup-spans popup))))
                         (close-popup session)
                         (activate-span session (popup-owner popup) span))))
                   (setf (popup-pressed popup) index))
               (when (session-popup session) (popup-select session index)))
              ((logbitp 5 button) (popup-select session index))))
      t)))
(defun popup-overlays (session)
  (let ((popup (session-popup session)))
    (when popup
      (loop for span in (popup-spans popup) for index from 0
            for row = (- (getf span :y) (popup-scroll popup))
            when (<= 0 row (1- (popup-height popup)))
            append (clip-decoration session nil
                     (list :x (+ (popup-x popup) (getf span :x)) :y (+ (popup-y popup) row)
                           :text (getf span :text)
                           :sgr (if (eql index (popup-selected popup))
                                    (getf span :hover-sgr (getf span :sgr)) (getf span :sgr))))))))
