(in-package #:ekko/runtime)

(defstruct pane id pid io vt (graphics (make-store)) argv label status (x 0) (y 0) (output-bytes 0))
(defstruct session name panes (cols 120) (rows 36) (cw 8) (ch 16) (focus 0)
  (split 50) zoom (swapped nil) (revision 0) writer (prefix nil) drag paste-target (started (now)))
(defun pane-input (pane bytes)
  (when (and (null (pane-status pane)) (pane-io pane))
    (when (> (+ (wire-queued (pane-io pane)) (length bytes)) 65536) (error "Pane input queue full"))
    (queue-bytes (pane-io pane) bytes)))
(defun pane-event (pane kind value)
  (let ((vt (pane-vt pane)) (graphics (pane-graphics pane)))
    (case kind
      (:reply (pane-input pane (text-bytes value)))
      (:graphics (accept-command graphics value vt (lambda (k v) (pane-event pane k v))))
      (:scroll (destructuring-bind (top bottom amount) value
                 (scroll-images graphics (terminal-screen vt) top bottom amount (terminal-cw vt) (terminal-ch vt))))
      (:screen (when (eq value :main) (clear-screen graphics :alternate)))
      (:reset (clear-screen graphics :main) (clear-screen graphics :alternate)))))
(defun visible-panes (session)
  (if (session-zoom session) (list (nth (session-focus session) (session-panes session)))
      (if (session-swapped session) (reverse (session-panes session)) (session-panes session))))
(defun layout (session)
  (let* ((panes (visible-panes session)) (cols (session-cols session))
         (rows (max 1 (- (session-rows session) 2)))
         (left (max 1 (min (- cols 2) (floor (* (1- cols) (session-split session)) 100)))))
    (loop for pane in panes for index from 0
          for width = (if (= (length panes) 1) cols (if (zerop index) left (max 1 (- cols left 1))))
          for x = (if (zerop index) 0 (1+ left)) do
      (setf (pane-x pane) x (pane-y pane) 1)
      (let ((vt (pane-vt pane)))
        (unless (equal (list width rows (session-cw session) (session-ch session))
                       (list (terminal-cols vt) (terminal-rows vt) (terminal-cw vt) (terminal-ch vt)))
          (resize-terminal vt width rows (session-cw session) (session-ch session))
          (when (pane-io pane)
            (resize (wire-fd (pane-io pane)) width rows (* width (session-cw session)) (* rows (session-ch session)))))))
  (incf (session-revision session))))
(defun set-focus (session index)
  (let* ((old (nth (session-focus session) (session-panes session)))
         (new (nth index (session-panes session))) (esc (code-char 27)))
    (when (and new (/= index (session-focus session)))
      (when (gethash 1004 (terminal-modes (pane-vt old))) (pane-input old (text-bytes (format nil "~C[O" esc))))
      (setf (session-focus session) index)
      (when (gethash 1004 (terminal-modes (pane-vt new))) (pane-input new (text-bytes (format nil "~C[I" esc))))
      (if (session-zoom session) (layout session) (incf (session-revision session))))))
(defun close-pane (pane)
  (when (pane-io pane)
    (signal-group (pane-pid pane) 1)
    (close-wire (pane-io pane)) (setf (pane-io pane) nil)))
(defun input-key (session bytes)
  ;; A client may coalesce ordinary key bytes.  Prefix handling still needs
  ;; to see the first byte as a complete key, then can forward the remainder
  ;; as one ordinary run.  Escape-led sequences are already framed by the
  ;; client and retain their existing CSI/Kitty handling below.
  (when (and (> (length bytes) 1) (/= (aref bytes 0) 27)
             (or (session-prefix session) (= (aref bytes 0) 2)))
    (let ((action (input-key session (subseq bytes 0 1))))
      (when (member action '(:detach :stop))
        (return-from input-key action))
      (return-from input-key (input-key session (subseq bytes 1)))))
  (let* ((text (map 'string #'code-char bytes)) (esc (code-char 27))
         (kitty (and (> (length text) 3) (char= (char text 0) esc) (char= (char text 1) #\[)
                     (char= (char text (1- (length text))) #\u)))
         (params (when kitty (parameters (subseq text 2 (1- (length text))))))
         (code (if kitty (first params) (and (= (length bytes) 1) (aref bytes 0))))
         (modifiers (if kitty (1- (max 1 (or (second params) 1))) 0))
         (key (if (and code (logbitp 2 modifiers) (<= 64 code 127)) (logand code 31) code))
         (pane (nth (session-focus session) (session-panes session))))
    (cond
      ((session-prefix session)
       (setf (session-prefix session) nil)
       (case key
         ((9 111 110 32) (set-focus session (mod (1+ (session-focus session)) (length (session-panes session)))))
         (49 (set-focus session 0)) (50 (when (> (length (session-panes session)) 1) (set-focus session 1)))
         (122 (setf (session-zoom session) (not (session-zoom session))) (layout session))
         (115 (setf (session-swapped session) (not (session-swapped session))) (layout session))
         (60 (setf (session-split session) (max 20 (- (session-split session) 5))) (layout session))
         (62 (setf (session-split session) (min 80 (+ (session-split session) 5))) (layout session))
         (100 :detach) (113 :stop) (120 (close-pane pane))
         (2 (pane-input pane (octets-from-list '(2))))
         (otherwise nil)))
      ((eql key 2) (setf (session-prefix session) t) nil)
      (t
       (cond
         ((and kitty (zerop (first (terminal-keyboards (pane-vt pane)))))
          (when (and key (<= 0 key #x10ffff) (not (<= #xd800 key #xdfff)))
            (pane-input pane (text-bytes (concatenate 'string (if (logbitp 1 modifiers) (string esc) "")
                                                     (string (code-char key)))))))
         ((and (gethash 1 (terminal-modes (pane-vt pane))) (= (length bytes) 3)
               (= (aref bytes 0) 27) (= (aref bytes 1) 91) (find (code-char (aref bytes 2)) "ABCDHF"))
          (pane-input pane (octets-from-list (list 27 79 (aref bytes 2)))))
         (t (pane-input pane bytes))) nil))))
(defun octets-from-list (items) (coerce items '(vector (unsigned-byte 8))))
(defun input-mouse (session text)
  (let* ((args (parameters (subseq text 3 (1- (length text)))))
         (button (first args)) (x (second args)) (y (third args))
         (up (char= (char text (1- (length text))) #\m))
         (cw (session-cw session)) (ch (session-ch session)))
    (unless (and (= (length args) 3) (<= 0 button 255) (plusp x) (plusp y)) (return-from input-mouse))
    (let* ((hit (find-if (lambda (p)
                           (and (< (* (pane-x p) cw) x (1+ (* (+ (pane-x p) (terminal-cols (pane-vt p))) cw)))
                                (< (* (pane-y p) ch) y (1+ (* (+ (pane-y p) (terminal-rows (pane-vt p))) ch)))))
                         (visible-panes session)))
           (pane (or (session-drag session) hit)))
      (when (and pane (not up) (zerop (logand button 96)) (< (logand button 3) 3))
        (set-focus session (position pane (session-panes session))) (setf (session-drag session) pane))
      (when pane
        (let* ((vt (pane-vt pane)) (modes (terminal-modes vt))
               (px (max 1 (min (* (terminal-cols vt) cw) (- x (* (pane-x pane) cw)))))
               (py (max 1 (min (* (terminal-rows vt) ch) (- y (* (pane-y pane) ch))))))
          (when (or (gethash 1003 modes) (and (gethash 1002 modes) (or (session-drag session) (zerop (logand button 32))))
                    (and (gethash 1000 modes) (zerop (logand button 32))))
            (unless (gethash 1016 modes) (setf px (ceiling px cw) py (ceiling py ch)))
            (when (gethash 1006 modes)
              (pane-input pane (text-bytes (format nil "~C[<~D;~D;~D~C" (code-char 27) button px py (if up #\m #\M))))))))
      (when up (setf (session-drag session) nil)))))
(defun pane-lines (vt)
  (loop for y below (terminal-rows vt) collect
    (let ((runs nil) (start 0) (attr nil) (chars (make-string-output-stream)))
      (loop for x below (terminal-cols vt) for cell = (aref (terminal-cells vt) (+ x (* y (terminal-cols vt)))) do
        (unless (equal attr (second cell))
          (when attr (push (list start (get-output-stream-string chars) attr) runs))
          (setf start x attr (second cell)))
        (write-string (first cell) chars))
      (when attr (push (list start (get-output-stream-string chars) attr) runs))
      (nreverse runs))))
(defun scene-data (session)
  (list +wire-version+ (session-cols session) (session-rows session) (session-cw session) (session-ch session)
        (pane-id (nth (session-focus session) (session-panes session)))
        (loop for pane in (visible-panes session) for vt = (pane-vt pane) collect
          (list (pane-id pane) (pane-x pane) (pane-y pane) (terminal-cols vt) (terminal-rows vt)
                (pane-label pane) (pane-status pane) (min (1- (terminal-cols vt)) (terminal-x vt))
                (terminal-y vt) (terminal-visible vt) (pane-lines vt)
                (loop for image being the hash-values of (store-images (pane-graphics pane))
                      when (and (image-visible image) (eq (image-screen image) (terminal-screen vt))) collect
                        (list (image-id image) (image-generation image) (image-x image) (image-y image)
                              (image-cols image) (image-rows image)))))))
(defun session-stamp (session)
  (list (session-revision session)
        (loop for pane in (session-panes session) collect
          (list (terminal-revision (pane-vt pane)) (store-revision (pane-graphics pane)) (pane-status pane)))))
(defun publish-scene (session wire)
  (let ((stamp (session-stamp session)))
    (when (and (null (wire-queue wire)) (null (wire-awaiting-scene wire))
               (not (equal stamp (wire-revision wire))))
      (let ((live (make-hash-table :test 'equal)))
        (dolist (pane (visible-panes session))
          (maphash (lambda (id image)
                     (when (and (image-visible image) (eq (image-screen image) (terminal-screen (pane-vt pane))))
                       (setf (gethash (list (pane-id pane) id) live) t)))
                   (store-images (pane-graphics pane))))
        (maphash (lambda (key value) (declare (ignore value))
                   (unless (gethash key live) (remhash key (wire-known wire)))) (wire-known wire)))
      (dolist (pane (visible-panes session))
        (maphash (lambda (id image)
                   (let ((key (list (pane-id pane) id)))
                     (when (and (image-visible image) (eq (image-screen image) (terminal-screen (pane-vt pane)))
                                (not (eql (gethash key (wire-known wire)) (image-generation image))))
                       (let ((data (image-data image))
                             (metadata (integers (list (pane-id pane) id (image-generation image)
                                                       (image-width image) (image-height image) (image-format image)))))
                         (send-packet wire (if (local-asset-p data) 13 11)
                           (concatenate '(vector (unsigned-byte 8)) metadata
                             (if (local-asset-p data) (text-bytes (local-asset-path data)) data))))
                       (setf (gethash key (wire-known wire)) (image-generation image)))))
                 (store-images (pane-graphics pane))))
      (dolist (pane (visible-panes session))
        (maphash (lambda (id image) (declare (ignore id))
                   (when (and (image-visible image)
                              (eq (image-screen image) (terminal-screen (pane-vt pane)))
                              (local-asset-p (image-data image)))
                     (push (retain-asset (image-data image)) (wire-leases wire))))
                 (store-images (pane-graphics pane))))
      (send-packet wire 12 (encode-scene (scene-data session)))
      (setf (wire-awaiting-scene wire) (now))
      (setf (wire-revision wire) stamp))))
(defun status-json (session)
  (let ((panes (loop for pane in (session-panes session) for vt = (pane-vt pane) for g = (pane-graphics pane) collect
                 (format nil "{~S:~D,~S:~D,~S:~A,~S:~D,~S:~D,~S:~D,~S:~D,~S:~D,~S:~D,~S:~D,~S:~D}"
                         "id" (pane-id pane) "pid" (pane-pid pane) "exit_code" (or (pane-status pane) "null")
                         "cols" (terminal-cols vt) "rows" (terminal-rows vt) "images" (hash-table-count (store-images g))
                         "frames" (store-frames g) "graphics_errors" (store-errors g) "image_bytes" (store-bytes g)
                         "pty_output_bytes" (pane-output-bytes pane)
                         "local_images" (loop for image being the hash-values of (store-images g)
                                              count (local-asset-p (image-data image)))))))
    (format nil "{~S:~D,~S:~S,~S:~D,~S:~D,~S:~F,~S:~D,~S:~A,~S:[~A]}~%"
            "wire_version" +wire-version+ "session" (session-name session) "daemon_pid" (sb-posix:getpid)
            "allocated_bytes" (sb-ext:get-bytes-consed)
            "gc_seconds" (coerce (/ sb-ext:*gc-run-time* internal-time-units-per-second) 'double-float)
            "snapshot_bytes" ekko/platform::*asset-bytes*
            "attached" (if (session-writer session) "true" "false") "panes"
            (format nil "~{~A~^,~}" panes))))
(defun server-packet (session wire packet)
  (let ((kind (aref packet 0)) (data (subseq packet 1)))
    (case kind
      (1
       (unless (and (= (length data) 20) (= (u32 data 0) +wire-version+))
         (send-packet wire 21 (text-bytes "Incompatible Ekko wire version")) (return-from server-packet))
       (when (and (session-writer session) (not (eq wire (session-writer session))))
         (send-packet wire 21 (text-bytes "This session already has an attached client")) (return-from server-packet))
       (let ((cols (u32 data 4)) (rows (u32 data 8)) (cw (u32 data 12)) (ch (u32 data 16)))
         (unless (and (<= 5 cols 500) (<= 4 rows 300) (<= 1 cw 128) (<= 1 ch 256)) (error "Invalid viewport"))
         (setf (session-cols session) cols (session-rows session) rows (session-cw session) cw (session-ch session) ch
               (session-writer session) wire (wire-attached wire) t)
         (layout session)))
      (14 (unless (and (= (length data) 0) (wire-attached wire) (wire-awaiting-scene wire))
            (error "Unexpected scene acknowledgement"))
          (acknowledge-scene wire))
      (2 (when (eq (session-writer session) wire)
           (let ((action (input-key session data)))
             (case action (:detach (send-packet wire 22)) (:stop :stop)))))
      (4 (when (eq (session-writer session) wire) (input-mouse session (bytes-text data))))
      (5 (when (eq (session-writer session) wire)
           (let* ((begin (equalp data (text-bytes (format nil "~C[200~~" (code-char 27)))))
                  (end (equalp data (text-bytes (format nil "~C[201~~" (code-char 27)))))
                  (pane (or (session-paste-target session) (nth (session-focus session) (session-panes session)))))
             (when begin (setf (session-paste-target session) pane))
             (when (or (not (or begin end)) (gethash 2004 (terminal-modes (pane-vt pane)))) (pane-input pane data))
             (when end (setf (session-paste-target session) nil)))))
      (6 (when (eq (session-writer session) wire)
           (let ((pane (nth (session-focus session) (session-panes session))))
             (when (gethash 1004 (terminal-modes (pane-vt pane))) (pane-input pane data)))))
      (3 (let ((command (bytes-text data)))
           (cond ((string= command "status") (send-packet wire 20 (text-bytes (status-json session))))
                 ((string= command "stop") (send-packet wire 20 (text-bytes "{}")) (flush-wire wire) :stop)
                 (t (error "Unknown control command")))))
      (otherwise (error "Unknown IPC message")))))
(defun serve (name commands)
  (initialize) (server-signals)
  (let* ((path (socket-path name)) (lock (checked (lock-file (concatenate 'string path ".lock")) "session lock"))
         (listener nil) (session (make-session :name name)) (peers nil) (buffer (octets 65536)) (running t))
    (dolist (sig (list sb-posix:sigterm sb-posix:sighup))
      (sb-sys:enable-interrupt sig (lambda (&rest arguments) (declare (ignore arguments)) (setf running nil))))
    (unwind-protect
         (progn
           (initialize-assets (concatenate 'string path ".frames/"))
           (when (probe-file path) (delete-file path))
           (setf listener (checked (listen-local path) "listen"))
           (sb-posix:setenv "TERM" "xterm-256color" 1)
           (sb-posix:unsetenv "TMUX") (sb-posix:unsetenv "STY")
           (loop for argv in commands for id from 1 do
             (multiple-value-bind (fd pid) (spawn argv 59 34 8 16)
               (push (make-pane :id id :pid pid :io (make-wire :fd fd) :vt (make-terminal :cols 59 :rows 34)
                                :argv argv :label (file-namestring (first argv))) (session-panes session))))
           (setf (session-panes session) (nreverse (session-panes session))) (layout session)
           (labels ((drop-peer (peer)
                      (when (eq peer (session-writer session))
                        (setf (session-writer session) nil (session-prefix session) nil (session-drag session) nil
                              (session-paste-target session) nil))
                      (close-wire peer) (setf peers (remove peer peers))))
             (loop while running do
               (dolist (pane (session-panes session))
                 (expire-upload (pane-graphics pane))
                 (when (null (pane-status pane))
                   (let ((exit (reap (pane-pid pane))))
                     (when (>= exit 0) (setf (pane-status pane) exit) (incf (session-revision session))))))
               (dolist (peer (copy-list peers))
                 (handler-case
                     (progn
                       (when (and (wire-awaiting-scene peer) (> (- (now) (wire-awaiting-scene peer)) 10))
                         (error "Presentation acknowledgement timed out"))
                       (when (wire-attached peer) (publish-scene session peer))
                       (when (and (not (wire-attached peer)) (>= (- (now) (wire-at peer)) 10)) (drop-peer peer)))
                   (error (e) (format *error-output* "client: ~A~%" e) (drop-peer peer))))
               ;; Housekeeping needs to run at the next upload/peer timeout, and
               ;; periodically to notice exited children.  Avoid waking every
               ;; frame while retaining prompt protocol timeout handling.
               (let* ((current (now))
                      (deadline (+ current 1)))
                 (dolist (pane (session-panes session))
                   (let ((pending (store-pending (pane-graphics pane))))
                     (when pending
                       (setf deadline (min deadline (+ (ekko/graphics::upload-at pending) 10))))))
                 (dolist (peer peers)
                   (unless (wire-attached peer)
                     (setf deadline (min deadline (+ (wire-at peer) 10)))))
                 (dolist (event (poll-fds
                              (append (list (cons listener 1))
                                      (loop for p in (session-panes session) when (pane-io p)
                                            collect (cons (wire-fd (pane-io p)) (wire-events (pane-io p))))
                                      (loop for peer in peers collect (cons (wire-fd peer) (wire-events peer))))
                              (max 0 (ceiling (* 1000 (- deadline current))))))
                 (let* ((fd (car event)) (flags (cdr event))
                        (pane (find fd (session-panes session) :key (lambda (p) (when (pane-io p) (wire-fd (pane-io p)))))))
                   (cond
                     ((= fd listener)
                      (let ((accepted (accept-local listener)))
                        (when (>= accepted 0)
                          (if (< (length peers) 8) (push (make-wire :fd accepted) peers) (close-fd accepted)))))
                     (pane
                      (handler-case
                          (progn
                            (when (logtest flags 4) (flush-wire (pane-io pane)))
                            (when (logtest flags 25)
                              (let ((n (read-fd fd buffer)))
                                (cond ((plusp n)
                                       (incf (pane-output-bytes pane) n)
                                       (feed (pane-vt pane) (subseq buffer 0 n) (lambda (k v) (pane-event pane k v))))
                                      ((not (member n '(-11 -4))) (close-wire (pane-io pane)) (setf (pane-io pane) nil))))))
                        (error (e) (format *error-output* "pane ~D: ~A~%" (pane-id pane) e) (close-pane pane))))
                     (t (let ((peer (find fd peers :key #'wire-fd)))
                          (when peer
                            (handler-case
                                (progn
                                  (when (logtest flags 4) (flush-wire peer))
                                  (when (logtest flags 25)
                                    (dolist (packet (receive-packets peer buffer))
                                      (when (eq :stop (server-packet session peer packet)) (setf running nil)))))
                              (error (e)
                                (unless (search "disconnected" (princ-to-string e)) (format *error-output* "client: ~A~%" e))
                                (drop-peer peer))))))))))))
      (dolist (peer peers) (close-wire peer))
      (dolist (pane (session-panes session))
        (close-pane pane)
        (clear-screen (pane-graphics pane) :main)
        (clear-screen (pane-graphics pane) :alternate))
      (let ((deadline (+ (now) 1)))
        (loop while (and (< (now) deadline) (some (lambda (p) (= -11 (reap (pane-pid p)))) (session-panes session)))
              do (poll-fds nil 20)))
      (dolist (pane (session-panes session))
        (when (= -11 (reap (pane-pid pane))) (signal-group (pane-pid pane) 9)))
      (when listener (close-fd listener))
      (when (probe-file path) (delete-file path)) (close-fd lock)))
  0))
