(in-package #:ekko/runtime)

(defstruct pane id pid io vt (graphics (make-store)) argv label status (x 0) (y 0) (output-bytes 0)
  copy-lines (copy-cursor 0) (copy-top 0) copy-mark search-input (search-text ""))
(defstruct session name panes (cols 120) (rows 36) (cw 8) (ch 16) (focus 0)
  zoom (revision 0) writer (prefix nil) drag paste-target (started (now))
  tree (next-pane-id 1) retired worker candidate registry (config-generation 0) config-error
  (contributions nil) hook-context (hooks nil) (input-queue nil) (input-bytes 0)
  command-queue disabled-hooks reload-peer (clipboard "") stopping (notice ""))
(defun pane-input (pane bytes)
  (when (and (null (pane-status pane)) (pane-io pane))
    (when (> (+ (wire-queued (pane-io pane)) (length bytes)) 65536) (error "Pane input queue full"))
    (queue-bytes (pane-io pane) bytes)))
(defun pane-event (pane kind value)
  (let ((vt (pane-vt pane)) (graphics (pane-graphics pane)))
    (case kind
      (:reply (pane-input pane (text-bytes value)))
      (:graphics (accept-command graphics value vt (lambda (k v) (pane-event pane k v))))
      (:scroll (destructuring-bind (top bottom amount) value
                 (scroll-images graphics (terminal-screen vt) top bottom amount (terminal-cw vt) (terminal-ch vt))))
      (:screen (when (eq value :main) (clear-screen graphics :alternate)))
      (:reset (clear-screen graphics :main) (clear-screen graphics :alternate)))))
(defun focused-pane (session) (nth (session-focus session) (session-panes session)))
(defun pane-by-id (session id)
  (find id (session-panes session) :key #'pane-id))
(defun session-rectangles (session)
  (ekko/layout:rectangles (session-tree session) (session-cols session) (1- (session-rows session))
                          (pane-id (focused-pane session)) (session-zoom session)))
(defun visible-panes (session)
  (mapcar (lambda (rect) (pane-by-id session (first rect))) (session-rectangles session)))
(defun layout (session)
  (dolist (rect (session-rectangles session))
    (destructuring-bind (id x y width height) rect
      (let* ((pane (pane-by-id session id)) (vt (pane-vt pane)) (rows (1- height)))
        (setf (pane-x pane) x (pane-y pane) (1+ y))
        (unless (equal (list width rows (session-cw session) (session-ch session))
                       (list (terminal-cols vt) (terminal-rows vt) (terminal-cw vt) (terminal-ch vt)))
          (resize-terminal vt width rows (session-cw session) (session-ch session))
          (when (pane-io pane)
            (resize (wire-fd (pane-io pane)) width rows (* width (session-cw session)) (* rows (session-ch session))))))))
  (incf (session-revision session)))
(defun set-focus (session index)
  (let* ((old (nth (session-focus session) (session-panes session)))
         (new (nth index (session-panes session))) (esc (code-char 27)))
    (when (and new (/= index (session-focus session)))
      (when (gethash 1004 (terminal-modes (pane-vt old))) (pane-input old (text-bytes (format nil "~C[O" esc))))
      (setf (session-focus session) index)
      (when (gethash 1004 (terminal-modes (pane-vt new))) (pane-input new (text-bytes (format nil "~C[I" esc))))
      (layout session))))
(defun close-pane (pane)
  (when (pane-io pane)
    (signal-group (pane-pid pane) 1)
    (close-wire (pane-io pane)) (setf (pane-io pane) nil)))
(defun input-key (session bytes)
  (when (command-pending-p session)
    (defer-input session 2 bytes) (return-from input-key))
  (when (and (> (length bytes) 1) (/= (aref bytes 0) 27))
    (let ((prefix (position (option session :prefix 2) bytes)))
      (when (and prefix (plusp prefix) (not (session-prefix session)))
        (input-key session (subseq bytes 0 prefix))
        (return-from input-key (input-key session (subseq bytes prefix))))))
  ;; A client may coalesce ordinary key bytes.  Prefix handling still needs
  ;; to see the first byte as a complete key, then can forward the remainder
  ;; as one ordinary run.  Escape-led sequences are already framed by the
  ;; client and retain their existing CSI/Kitty handling below.
  (when (and (> (length bytes) 1) (/= (aref bytes 0) 27)
             (or (session-prefix session) (and (pane-copy-lines (focused-pane session))
                                             (not (pane-search-input (focused-pane session))))
                 (= (aref bytes 0) (option session :prefix 2))))
    (let ((action (input-key session (subseq bytes 0 1))))
      (when (or (member action '(:detach :stop)) (command-pending-p session))
        (when (> (length bytes) 1) (defer-input session 2 (subseq bytes 1)))
        (return-from input-key action))
      (return-from input-key (input-key session (subseq bytes 1)))))
  (let* ((text (map 'string #'code-char bytes)) (esc (code-char 27))
         (kitty (and (> (length text) 3) (char= (char text 0) esc) (char= (char text 1) #\[)
                     (char= (char text (1- (length text))) #\u)))
         (params (when kitty (parameters (subseq text 2 (1- (length text))))))
         (code (if kitty (first params) (and (= (length bytes) 1) (aref bytes 0))))
         (modifiers (if kitty (1- (max 1 (or (second params) 1))) 0))
         (key (if (and code (logbitp 2 modifiers) (<= 64 code 127)) (logand code 31) code))
         (pane (nth (session-focus session) (session-panes session))))
    (cond
      ((session-prefix session)
       (setf (session-prefix session) nil)
       (if (eql key (option session :prefix 2))
           (pane-input pane (octets-from-list (list key)))
           (dispatch-binding session :prefix (semantic-key bytes key))))
      ((eql key (option session :prefix 2)) (setf (session-prefix session) t) nil)
      ((pane-search-input pane)
       (copy-search-input session (if (and kitty key (<= 0 key #x10ffff) (not (<= #xd800 key #xdfff)))
                                     (text-bytes (string (code-char key))) bytes)))
      ((pane-copy-lines pane) (dispatch-binding session :copy (semantic-key bytes key)))
      (t
       (cond
         ((and kitty (zerop (first (terminal-keyboards (pane-vt pane)))))
          (when (and key (<= 0 key #x10ffff) (not (<= #xd800 key #xdfff)))
            (pane-input pane (text-bytes (concatenate 'string (if (logbitp 1 modifiers) (string esc) "")
                                                     (string (code-char key)))))))
         ((and (gethash 1 (terminal-modes (pane-vt pane))) (= (length bytes) 3)
               (= (aref bytes 0) 27) (= (aref bytes 1) 91) (find (code-char (aref bytes 2)) "ABCDHF"))
          (pane-input pane (octets-from-list (list 27 79 (aref bytes 2)))))
         (t (pane-input pane bytes))) nil))))
(defun octets-from-list (items) (coerce items '(vector (unsigned-byte 8))))
(defun input-mouse (session text)
  (let* ((args (parameters (subseq text 3 (1- (length text)))))
         (button (first args)) (x (second args)) (y (third args))
         (up (char= (char text (1- (length text))) #\m))
         (cw (session-cw session)) (ch (session-ch session)))
    (unless (and (= (length args) 3) (<= 0 button 255) (plusp x) (plusp y)) (return-from input-mouse))
    (let* ((hit (find-if (lambda (p)
                           (and (< (* (pane-x p) cw) x (1+ (* (+ (pane-x p) (terminal-cols (pane-vt p))) cw)))
                                (< (* (pane-y p) ch) y (1+ (* (+ (pane-y p) (terminal-rows (pane-vt p))) ch)))))
                         (visible-panes session)))
           (pane (or (session-drag session) hit)))
      (when (and pane (not up) (zerop (logand button 96)) (< (logand button 3) 3))
        (set-focus session (position pane (session-panes session))) (setf (session-drag session) pane))
      (when (and pane (pane-copy-lines pane))
        (when (and (not up) (logtest button 64))
          (move-copy pane (+ (pane-copy-cursor pane) (if (oddp button) 3 -3)))
          (incf (session-revision session)))
        (when up (setf (session-drag session) nil))
        (return-from input-mouse))
      (when pane
        (let* ((vt (pane-vt pane)) (modes (terminal-modes vt))
               (px (max 1 (min (* (terminal-cols vt) cw) (- x (* (pane-x pane) cw)))))
               (py (max 1 (min (* (terminal-rows vt) ch) (- y (* (pane-y pane) ch))))))
          (when (or (gethash 1003 modes) (and (gethash 1002 modes) (or (session-drag session) (zerop (logand button 32))))
                    (and (gethash 1000 modes) (zerop (logand button 32))))
            (unless (gethash 1016 modes) (setf px (ceiling px cw) py (ceiling py ch)))
            (when (gethash 1006 modes)
              (pane-input pane (text-bytes (format nil "~C[<~D;~D;~D~C" (code-char 27) button px py (if up #\m #\M))))))))
      (when up (setf (session-drag session) nil)))))
(defun pane-lines (vt)
  (loop for y below (terminal-rows vt) collect
    (let ((runs nil) (start 0) (attr nil) (chars (make-string-output-stream)))
      (loop for x below (terminal-cols vt) for cell = (aref (terminal-cells vt) (+ x (* y (terminal-cols vt)))) do
        (unless (equal attr (second cell))
          (when attr (push (list start (get-output-stream-string chars) attr) runs))
          (setf start x attr (second cell)))
        (write-string (first cell) chars))
      (when attr (push (list start (get-output-stream-string chars) attr) runs))
      (nreverse runs))))
(defun scene-data (session)
  (list +wire-version+ (session-cols session) (session-rows session) (session-cw session) (session-ch session)
        (pane-id (nth (session-focus session) (session-panes session)))
        (loop for pane in (visible-panes session) for vt = (pane-vt pane) collect
          (list (pane-id pane) (pane-x pane) (pane-y pane) (terminal-cols vt) (terminal-rows vt)
                (if (pane-copy-lines pane) (format nil "~A [copy ~D/~D]" (pane-label pane)
                          (1+ (pane-copy-cursor pane)) (length (pane-copy-lines pane))) (pane-label pane)) (pane-status pane) (min (1- (terminal-cols vt)) (terminal-x vt))
                (terminal-y vt) (and (not (pane-copy-lines pane)) (terminal-visible vt))
                (if (pane-copy-lines pane) (copy-display-lines pane) (pane-lines vt))
                (loop for image being the hash-values of (store-images (pane-graphics pane))
                      when (and (not (pane-copy-lines pane)) (image-visible image) (eq (image-screen image) (terminal-screen vt))) collect
                        (list (image-id image) (image-generation image) (image-x image) (image-y image)
                              (image-cols image) (image-rows image)))))
        (list :status (status-text session) :style (option session :status-style '(0 30 47)))))
(defun session-stamp (session)
  (list (session-revision session)
        (loop for pane in (session-panes session) collect
          (list (terminal-revision (pane-vt pane)) (store-revision (pane-graphics pane)) (pane-status pane)))))
(defun publish-scene (session wire)
  (let ((stamp (session-stamp session)))
    (when (and (null (wire-queue wire)) (null (wire-awaiting-scene wire))
               (not (equal stamp (wire-revision wire))))
      (let ((live (make-hash-table :test 'equal)))
        (dolist (pane (visible-panes session))
          (maphash (lambda (id image)
                     (when (and (not (pane-copy-lines pane)) (image-visible image) (eq (image-screen image) (terminal-screen (pane-vt pane))))
                       (setf (gethash (list (pane-id pane) id) live) t)))
                   (store-images (pane-graphics pane))))
        (maphash (lambda (key value) (declare (ignore value))
                   (unless (gethash key live) (remhash key (wire-known wire)))) (wire-known wire)))
      (dolist (pane (visible-panes session))
        (maphash (lambda (id image)
                   (let ((key (list (pane-id pane) id)))
                     (when (and (not (pane-copy-lines pane)) (image-visible image) (eq (image-screen image) (terminal-screen (pane-vt pane)))
                                (not (eql (gethash key (wire-known wire)) (image-generation image))))
                       (let ((data (image-data image))
                             (metadata (integers (list (pane-id pane) id (image-generation image)
                                                       (image-width image) (image-height image) (image-format image)))))
                         (send-packet wire (if (local-asset-p data) 13 11)
                           (concatenate '(vector (unsigned-byte 8)) metadata
                             (if (local-asset-p data) (text-bytes (local-asset-path data)) data))))
                       (setf (gethash key (wire-known wire)) (image-generation image)))))
                 (store-images (pane-graphics pane))))
      (dolist (pane (visible-panes session))
        (maphash (lambda (id image) (declare (ignore id))
                   (when (and (not (pane-copy-lines pane)) (image-visible image)
                              (eq (image-screen image) (terminal-screen (pane-vt pane)))
                              (local-asset-p (image-data image)))
                     (push (retain-asset (image-data image)) (wire-leases wire))))
                 (store-images (pane-graphics pane))))
      (send-packet wire 12 (encode-scene (scene-data session)))
      (setf (wire-awaiting-scene wire) (now))
      (setf (wire-revision wire) stamp))))
(defun status-json (session)
  (json-value
    (list :object :wire_version +wire-version+ :session (session-name session)
          :daemon_pid (sb-posix:getpid)
          :extension_pid (when (session-worker session) (sb-ext:process-pid (extension-worker-process (session-worker session))))
          :allocated_bytes (sb-ext:get-bytes-consed)
          :gc_seconds (coerce (/ sb-ext:*gc-run-time* internal-time-units-per-second) 'double-float)
          :snapshot_bytes ekko/platform::*asset-bytes* :attached (if (session-writer session) t :false)
          :focus (pane-id (focused-pane session))
          :panes (loop for p in (session-panes session) for vt = (pane-vt p) for g = (pane-graphics p) collect
                  (list :object :id (pane-id p) :pid (pane-pid p) :label (pane-label p) :exit_code (pane-status p)
                        :cols (terminal-cols vt) :rows (terminal-rows vt) :x (pane-x p) :y (pane-y p)
                        :history_rows (if (terminal-history vt) (history-count (terminal-history vt)) 0)
                        :copy_mode (if (pane-copy-lines p) t :false)
                        :images (hash-table-count (store-images g)) :frames (store-frames g)
                        :graphics_errors (store-errors g) :image_bytes (store-bytes g)
                        :pty_output_bytes (pane-output-bytes p)
                        :local_images (loop for image being the hash-values of (store-images g)
                                            count (local-asset-p (image-data image))))))))
(defun server-packet (session wire packet)
  (let ((kind (aref packet 0)) (data (subseq packet 1)))
    (when (and (member kind '(2 4 5 6)) (eq (session-writer session) wire) (command-pending-p session))
      (defer-input session kind data) (return-from server-packet))
    (case kind
      (1
       (unless (and (= (length data) 20) (= (u32 data 0) +wire-version+))
         (send-packet wire 21 (text-bytes "Incompatible Ekko wire version")) (return-from server-packet))
       (when (and (session-writer session) (not (eq wire (session-writer session))))
         (send-packet wire 21 (text-bytes "This session already has an attached client")) (return-from server-packet))
       (let ((cols (u32 data 4)) (rows (u32 data 8)) (cw (u32 data 12)) (ch (u32 data 16)))
         (unless (and (<= 5 cols 500) (<= 4 rows 300) (<= 1 cw 128) (<= 1 ch 256)) (error "Invalid viewport"))
         (setf (session-cols session) cols (session-rows session) rows (session-cw session) cw (session-ch session) ch
               (session-writer session) wire (wire-attached wire) t)
         (layout session)))
      (14 (unless (and (= (length data) 0) (wire-attached wire) (wire-awaiting-scene wire))
            (error "Unexpected scene acknowledgement"))
          (acknowledge-scene wire))
      (2 (when (eq (session-writer session) wire)
           (let ((action (input-key session data)))
             (case action (:detach (send-packet wire 22)) (:stop :stop)))))
      (4 (when (eq (session-writer session) wire) (input-mouse session (bytes-text data))))
      (5 (when (eq (session-writer session) wire)
           (let* ((begin (equalp data (text-bytes (format nil "~C[200~~" (code-char 27)))))
                  (end (equalp data (text-bytes (format nil "~C[201~~" (code-char 27)))))
                  (pane (or (session-paste-target session) (nth (session-focus session) (session-panes session)))))
             (when begin (setf (session-paste-target session) pane))
             (when (or (not (or begin end)) (gethash 2004 (terminal-modes (pane-vt pane)))) (pane-input pane data))
             (when end (setf (session-paste-target session) nil)))))
      (6 (when (eq (session-writer session) wire)
           (let ((pane (nth (session-focus session) (session-panes session))))
             (when (gethash 1004 (terminal-modes (pane-vt pane))) (pane-input pane data)))))
      (7 (handler-case
             (let* ((parts (split-arguments data)) (name (first parts)))
               (request-command session name (list :arguments (rest parts)) wire))
           (error (e) (command-reply wire (princ-to-string e) t))))
      (3 (let ((command (bytes-text data)))
           (cond ((string= command "status") (send-packet wire 20 (text-bytes (status-json session))))
                 ((string= command "stop") (send-packet wire 20 (text-bytes "{}")) (flush-wire wire) :stop)
                 ((string= command "reload")
                  (handler-case (start-reload session wire)
                    (error (e) (note-error session e) (command-reply wire (princ-to-string e) t))))
                 ((string= command "inspect") (send-packet wire 20 (text-bytes (inspect-json session))))
                 ((string= command "buffer") (send-packet wire 20 (text-bytes (session-clipboard session))))
                 (t (error "Unknown control command")))))
      (otherwise (error "Unknown IPC message")))))
(defun serve (name commands)
  (initialize) (server-signals)
  (let* ((path (socket-path name)) (lock (checked (lock-file (concatenate 'string path ".lock")) "session lock"))
         (listener nil) (session (make-session :name name)) (peers nil) (buffer (octets 65536)) (running t))
    (dolist (sig (list sb-posix:sigterm sb-posix:sighup))
      (sb-sys:enable-interrupt sig (lambda (&rest arguments) (declare (ignore arguments)) (setf running nil))))
    (unwind-protect
         (progn
           (initialize-assets (concatenate 'string path ".frames/"))
           (when (probe-file path) (delete-file path))
           (setf (session-worker session)
                 (load-worker (config-source (config-path)) (config-path) (concatenate 'string path ".extensions.log")))
           (install-registry session (extension-worker-registry (session-worker session)))
           (sb-posix:setenv "EKKO_SESSION_NAME" name 1)
           (sb-posix:setenv "TERM" "xterm-256color" 1)
           (sb-posix:unsetenv "TMUX") (sb-posix:unsetenv "STY")
           (loop for argv in commands for id from 1 do
             (multiple-value-bind (fd pid) (spawn argv 59 34 8 16)
               (push (make-pane :id id :pid pid :io (make-wire :fd fd) :vt (make-terminal :cols 59 :rows 34)
                                :argv argv :label (file-namestring (first argv))) (session-panes session))))
           (setf (session-panes session) (nreverse (session-panes session))
                 (session-next-pane-id session) (1+ (length commands))
                 (session-tree session) (pane-id (first (session-panes session))))
           (loop for pane in (rest (session-panes session)) for previous = (first (session-panes session)) then pane do
             (setf (session-tree session) (ekko/layout:split-pane (session-tree session) (pane-id previous) (pane-id pane) :columns)))
           (layout session)
           (setf listener (checked (listen-local path) "listen"))
           (labels ((drop-peer (peer)
                      (when (eq peer (session-writer session))
                        (setf (session-writer session) nil (session-prefix session) nil (session-drag session) nil
                              (session-paste-target session) nil))
                      (close-wire peer) (setf peers (remove peer peers))))
             (loop while (and running (not (session-stopping session))) do
               (service-extensions session buffer)
               (reap-retired session)
               (dolist (pane (session-panes session))
                 (expire-upload (pane-graphics pane))
                 (when (null (pane-status pane))
                   (let ((exit (reap (pane-pid pane))))
                     (when (>= exit 0) (setf (pane-status pane) exit) (incf (session-revision session))))))
               (dolist (peer (copy-list peers))
                 (handler-case
                     (progn
                       (when (and (wire-awaiting-scene peer) (> (- (now) (wire-awaiting-scene peer)) 10))
                         (error "Presentation acknowledgement timed out"))
                       (when (wire-attached peer) (publish-scene session peer))
                       (when (and (not (wire-attached peer)) (>= (- (now) (wire-at peer)) 10)) (drop-peer peer)))
                   (error (e) (format *error-output* "client: ~A~%" e) (drop-peer peer))))
               ;; Housekeeping needs to run at the next upload/peer timeout, and
               ;; periodically to notice exited children.  Avoid waking every
               ;; frame while retaining prompt protocol timeout handling.
               (let* ((current (now))
                      (deadline (+ current 1)))
                 (dolist (worker (list (session-worker session) (session-candidate session)))
                   (when (and worker (extension-worker-request worker))
                     (setf deadline (min deadline (extension-worker-deadline worker)))))
                 (dolist (pane (session-panes session))
                   (let ((pending (store-pending (pane-graphics pane))))
                     (when pending
                       (setf deadline (min deadline (+ (ekko/graphics::upload-at pending) 10))))))
                 (dolist (peer peers)
                   (unless (wire-attached peer)
                     (setf deadline (min deadline (+ (wire-at peer) 10)))))
                 (dolist (event (poll-fds
                              (append (list (cons listener 1))
                                      (worker-events (session-worker session)) (worker-events (session-candidate session))
                                      (loop for p in (session-panes session) when (pane-io p)
                                            collect (cons (wire-fd (pane-io p)) (wire-events (pane-io p))))
                                      (loop for peer in peers collect (cons (wire-fd peer) (wire-events peer))))
                              (max 0 (ceiling (* 1000 (- deadline current))))))
                 (let* ((fd (car event)) (flags (cdr event))
                        (pane (find fd (session-panes session) :key (lambda (p) (when (pane-io p) (wire-fd (pane-io p)))))))
                   (cond
                     ((= fd listener)
                      (let ((accepted (accept-local listener)))
                        (when (>= accepted 0)
                          (if (< (length peers) 8) (push (make-wire :fd accepted) peers) (close-fd accepted)))))
                     (pane
                      (handler-case
                          (progn
                            (when (logtest flags 4) (flush-wire (pane-io pane)))
                            (when (logtest flags 25)
                              (let ((n (read-fd fd buffer)))
                                (cond ((plusp n)
                                       (incf (pane-output-bytes pane) n)
                                       (feed (pane-vt pane) (subseq buffer 0 n) (lambda (k v) (pane-event pane k v))))
                                      ((not (member n '(-11 -4))) (close-wire (pane-io pane)) (setf (pane-io pane) nil))))))
                        (error (e) (format *error-output* "pane ~D: ~A~%" (pane-id pane) e) (close-pane pane))))
                     (t (let ((peer (find fd peers :key #'wire-fd)))
                          (when peer
                            (handler-case
                                (progn
                                  (when (logtest flags 4) (flush-wire peer))
                                  (when (logtest flags 25)
                                    (dolist (packet (receive-packets peer buffer))
                                      (when (eq :stop (server-packet session peer packet)) (setf running nil)))))
                              (error (e)
                                (unless (search "disconnected" (princ-to-string e)) (format *error-output* "client: ~A~%" e))
                                (drop-peer peer))))))))))))
      (stop-worker (session-worker session)) (stop-worker (session-candidate session))
      (dolist (retired (session-retired session)) (signal-group (pane-pid (car retired)) 9) (reap (pane-pid (car retired))))
      (dolist (peer peers) (close-wire peer))
      (dolist (pane (session-panes session))
        (close-pane pane)
        (clear-screen (pane-graphics pane) :main)
        (clear-screen (pane-graphics pane) :alternate))
      (let ((deadline (+ (now) 1)))
        (loop while (and (< (now) deadline) (some (lambda (p) (= -11 (reap (pane-pid p)))) (session-panes session)))
              do (poll-fds nil 20)))
      (dolist (pane (session-panes session))
        (when (= -11 (reap (pane-pid pane))) (signal-group (pane-pid pane) 9)))
      (when listener (close-fd listener))
      (when (probe-file path) (delete-file path)) (close-fd lock)))
  0))
