(in-package #:ekko/runtime)

(defstruct pane id pid io vt (graphics (make-store)) argv label status
  (launch-kind :command) (creation-position 0) name
  pty-size
  (activation-order 0) (x 0) (y 0)
  (outer-x 0) (outer-y 0) (outer-cols 1) (outer-rows 1) (output-bytes 0)
  copy-lines (copy-cursor 0) (copy-top 0) copy-mark search-input (search-text ""))
(defstruct session name panes (cols 120) (rows 36) (cw 8) (ch 16)
  reported-cw reported-ch (focus 0)
  mode zoom (revision 0) (activation-sequence 0) writer (prefix nil) drag paste-target (started (now))
  paste-fallback paste-buffer (paste-overflow nil)
  tree (next-pane-id 1) retired worker candidate registry (config-generation 0) config-error
  (geometry-contributions nil) (contributions nil) (decorations nil) (pane-notes nil) hook-context (hooks nil) (input-queue nil) (input-bytes 0)
  (input-read-framed nil) (input-read-bytes nil)
  command-queue disabled-hooks reload-peer (clipboard "") stopping (notice "")
  key-fragment key-fragment-mode component-state)
(defun pty-cell-size (session)
  (if (eq (option session :pty-pixel-source :effective) :reported)
      (values (or (session-reported-cw session) 0) (or (session-reported-ch session) 0))
      (values (session-cw session) (session-ch session))))
(defun pty-size-for (session cols rows)
  (multiple-value-bind (cw ch) (pty-cell-size session)
    ;; winsize pixel fields are unsigned 16-bit values in the platform ABI.
    (list cols rows (logand #xffff (* cols cw)) (logand #xffff (* rows ch)))))
(defun paste-policy (session)
  (let ((map (session-mode session)))
    (getf (find map (reverse (getf (session-registry session) :keymaps))
              :key (lambda (entry) (getf entry :name))) :unbound)))
(defun finish-paste-fallback (session)
  (let ((command (session-paste-fallback session))
        (bytes (session-paste-buffer session))
        (overflow (session-paste-overflow session)))
    (setf (session-paste-fallback session) nil (session-paste-buffer session) nil
          (session-paste-overflow session) nil)
    (when (and (stringp command) (not overflow))
      (request-command session command (list :key nil :bytes (coerce bytes 'list) :paste t) nil))))
(defun expire-pane-notes (session &optional (time (now)))
  (let ((remaining (remove-if (lambda (note)
                                (or (<= (getf note :until) time)
                                    (not (pane-by-id session (getf note :pane)))))
                              (session-pane-notes session))))
    (unless (equal remaining (session-pane-notes session))
      (setf (session-pane-notes session) remaining)
      (incf (session-revision session)))))
(defun pane-note-data (session)
  (loop for component in (getf (session-registry session) :components)
        append (loop for note in (session-pane-notes session)
                     when (equal (getf component :id) (getf note :owner))
                       collect (list :owner (getf note :owner) :pane (getf note :pane)
                                     :text (copy-seq (getf note :text))
                                     :sgr (copy-list (getf note :sgr))))))
(defun pane-input (pane bytes)
  (when (and (null (pane-status pane)) (pane-io pane))
    (when (> (+ (wire-queued (pane-io pane)) (length bytes)) 65536) (error "Pane input queue full"))
    (queue-bytes (pane-io pane) bytes)))
(defun pane-event (pane kind value)
  (let ((vt (pane-vt pane)) (graphics (pane-graphics pane)))
    (case kind
      (:reply (pane-input pane (text-bytes value)))
      (:graphics (accept-command graphics value vt (lambda (k v) (pane-event pane k v))))
      (:scroll (destructuring-bind (top bottom amount) value
                 (scroll-images graphics (terminal-screen vt) top bottom amount (terminal-cw vt) (terminal-ch vt))))
      (:screen (when (eq value :main) (clear-screen graphics :alternate)))
      (:reset (clear-screen graphics :main) (clear-screen graphics :alternate)))))
(defun focused-pane (session) (nth (session-focus session) (session-panes session)))
(defun pane-by-id (session id)
  (find id (session-panes session) :key #'pane-id))
(defun geometry-value (session key default)
  "Resolve runtime owner geometry in registry order, then static options."
  (loop for component in (reverse (getf (session-registry session) :components))
        for owner = (getf component :id)
        for entry = (assoc owner (session-geometry-contributions session) :test #'equal)
        when (and entry (member key (cdr entry)))
          do (return-from geometry-value (copy-tree (getf (cdr entry) key))))
  (copy-tree (option session key default)))
(defun geometry-option (session key default length)
  (let ((value (geometry-value session key default)))
    (unless (and (listp value) (= (length value) length)
                 (every (lambda (n) (and (integerp n) (<= 0 n 16))) value))
      (error "Invalid geometry option ~S: ~S" key value))
    (copy-list value)))
(defun effective-insets (width height requested)
  "Cap top and left first, then bottom and right, leaving one cell."
  (let* ((top (min (first requested) (max 0 (1- height))))
         (left (min (fourth requested) (max 0 (1- width))))
         (bottom (min (third requested) (max 0 (- height top 1))))
         (right (min (second requested) (max 0 (- width left 1)))))
    (list top right bottom left)))
(defun requested-pane-insets (session x y width height)
  (let ((pane (geometry-option session :pane-insets '(1 0 0 0) 4))
        (boundary (geometry-value session :boundary-insets nil)))
    (when (and boundary x y)
      (multiple-value-bind (viewport ignored gaps vw vh) (session-geometry session)
        (declare (ignore ignored gaps))
        (loop for outside in (list (= y (first viewport))
                                   (= (+ x width) (+ (fourth viewport) vw))
                                   (= (+ y height) (+ (first viewport) vh))
                                   (= x (fourth viewport)))
              for offset from 0
              when outside do (setf (nth offset pane) (nth offset boundary)))))
    pane))
(defun content-size (session width height &optional x y)
  (let ((insets (effective-insets width height
                                (requested-pane-insets session x y width height))))
    (values (max 1 (- width (second insets) (fourth insets)))
            (max 1 (- height (first insets) (third insets))))))
(defun pane-minimums (tree pane boundary)
  ;; Tree topology identifies viewport edges before allocating rectangles.
  (labels ((walk (node edges)
             (if (integerp node)
                 (let ((insets (loop for inside in pane for outside in (or boundary pane)
                                     for edge in edges collect (if edge outside inside))))
                   (list (cons node (list (+ 1 (second insets) (fourth insets))
                                          (+ 1 (first insets) (third insets))))))
                 (let ((a (copy-list edges)) (b (copy-list edges)))
                   (if (eq (first node) :columns)
                       (setf (second a) nil (fourth b) nil)
                       (setf (third a) nil (first b) nil))
                   (append (walk (third node) a) (walk (fourth node) b))))))
    (walk tree '(t t t t))))
(defun session-geometry (session)
  (let* ((viewport (effective-insets
                   (session-cols session) (session-rows session)
                   (geometry-option session :viewport-insets '(0 0 1 0) 4)))
         (pane (geometry-option session :pane-insets '(1 0 0 0) 4))
         (gaps (geometry-option session :split-gaps '(1 0) 2))
         (width (max 1 (- (session-cols session) (second viewport) (fourth viewport))))
         (height (max 1 (- (session-rows session) (first viewport) (third viewport)))))
    (values viewport pane gaps width height)))
(defun session-rectangles (session &optional (zoom (session-zoom session)))
  (multiple-value-bind (viewport pane gaps width height) (session-geometry session)
    (let* ((left (fourth viewport)) (top (first viewport))
           (minimums (pane-minimums (session-tree session) pane
                                    (geometry-value session :boundary-insets nil))))
      (mapcar (lambda (rect)
                (list (first rect) (+ left (second rect)) (+ top (third rect))
                      (fourth rect) (fifth rect)))
              (ekko/layout:rectangles
               (session-tree session) width height (pane-id (focused-pane session)) zoom
               :leaf-min (lambda (id) (cdr (assoc id minimums)))
               :column-gap (first gaps) :row-gap (second gaps))))))
(defun visible-panes (session)
  (mapcar (lambda (rect) (pane-by-id session (first rect))) (session-rectangles session)))
(defun layout (session)
  ;; This is a VT policy option, so apply it to every pane before calculating
  ;; visibility. Hidden panes must retain the same behavior when shown again.
  (let ((erase-display-history (option session :erase-display-history nil)))
    (dolist (pane (session-panes session))
      (setf (terminal-erase-display-history (pane-vt pane)) erase-display-history)))
    ;; Hidden tiled panes retain their base content size while a focused pane
    ;; uses the viewport. Moving fullscreen focus must restore the old pane's
    ;; PTY instead of leaving an invisible application at fullscreen size.
    (dolist (rect (let ((shown (session-rectangles session)))
                   (append (when (session-zoom session)
                             (remove-if (lambda (rect) (assoc (first rect) shown))
                                        (session-rectangles session nil)))
                           shown)))
      (destructuring-bind (id x y width height) rect
        (let* ((pane (pane-by-id session id)) (vt (pane-vt pane))
             (insets (effective-insets width height
                                       (requested-pane-insets session x y width height)))
             (top (first insets)) (left (fourth insets)))
        (multiple-value-bind (cols rows) (content-size session width height x y)
        (setf (pane-outer-x pane) x (pane-outer-y pane) y
              (pane-outer-cols pane) width (pane-outer-rows pane) height
              (pane-x pane) (+ x left) (pane-y pane) (+ y top))
        (unless (equal (list cols rows (session-cw session) (session-ch session))
                       (list (terminal-cols vt) (terminal-rows vt) (terminal-cw vt) (terminal-ch vt)))
          (resize-terminal vt cols rows (session-cw session) (session-ch session)))
          (let ((desired (pty-size-for session cols rows)))
            (when (and (pane-io pane) (not (equal desired (pane-pty-size pane))))
              (checked (resize (wire-fd (pane-io pane)) cols rows (third desired) (fourth desired))
                       "PTY resize")
              (setf (pane-pty-size pane) desired)))))))
  (incf (session-revision session)))
(defun record-activation (session pane)
  (setf (pane-activation-order pane) (incf (session-activation-sequence session))))
(defun set-focus (session index &optional relayout)
  (let* ((old (nth (session-focus session) (session-panes session)))
         (new (nth index (session-panes session))) (esc (code-char 27)))
    (when (and new (/= index (session-focus session)))
      (let ((before (session-rectangles session)))
      (when (gethash 1004 (terminal-modes (pane-vt old))) (pane-input old (text-bytes (format nil "~C[O" esc))))
      (setf (session-focus session) index)
      (record-activation session new)
      (when (gethash 1004 (terminal-modes (pane-vt new))) (pane-input new (text-bytes (format nil "~C[I" esc))))
      ;; Ordinary selection changes do not resize application PTYs. Fullscreen
      ;; or a collapsed small layout can change geometry when focus moves.
      (if (or relayout (not (equal before (session-rectangles session))))
          (layout session)
          (incf (session-revision session)))))))
(defun utf8-width (byte)
  (cond ((<= 0 byte 127) 1)
        ((<= #xc2 byte #xdf) 2)
        ((<= #xe0 byte #xef) 3)
        ((<= #xf0 byte #xf4) 4)
        (t nil)))
(defun key-width (bytes)
  "First UTF-8 key width; NIL for a valid incomplete prefix, 1 for invalid input."
  (let* ((lead (and (plusp (length bytes)) (aref bytes 0)))
         (width (and lead (utf8-width lead))))
    (cond
      ((or (null width) (= width 1)) 1)
      ((loop for i from 1 below (min width (length bytes))
             for byte = (aref bytes i)
             thereis (or (not (<= #x80 byte #xbf))
                         (and (= i 1)
                              (or (and (= lead #xe0) (< byte #xa0))
                                  (and (= lead #xed) (> byte #x9f))
                                  (and (= lead #xf0) (< byte #x90))
                                  (and (= lead #xf4) (> byte #x8f)))))) 1)
      ((< (length bytes) width) nil)
      (t width))))
(defun utf8-codepoint (bytes)
  "Return one valid Unicode scalar, never a raw non-ASCII byte."
  (when (and (plusp (length bytes))
             (eql (key-width bytes) (length bytes))
             (eql (utf8-width (aref bytes 0)) (length bytes)))
    (char-code (char (bytes-text bytes) 0))))
(defun close-pane (pane)
  (when (pane-pid pane) (signal-group (pane-pid pane) 1))
  (when (pane-io pane) (close-wire (pane-io pane)) (setf (pane-io pane) nil)))
(defun input-key (session bytes &optional raw-input)
  ;; Client packets may end between UTF-8 bytes. Keep an incomplete modal key
  ;; until its continuation arrives; forwarding uses the original byte slice.
  (when (session-key-fragment session)
    (when (eql (session-mode session) (session-key-fragment-mode session))
      (setf bytes (concatenate '(vector (unsigned-byte 8)) (session-key-fragment session) bytes)))
    (setf (session-key-fragment session) nil (session-key-fragment-mode session) nil))
  ;; A framed read is consumed by its first complete semantic key.  Keep the
  ;; framing bit so later keys explicitly carry NIL read metadata.
  (when (command-pending-p session)
    (defer-input session 2 bytes) (return-from input-key))
  (when (and (null (session-mode session)) (> (length bytes) 1) (/= (aref bytes 0) 27))
    (let ((prefix (position (option session :prefix 2) bytes)))
      (when (and prefix (plusp prefix) (not (session-prefix session)))
        (input-key session (subseq bytes 0 prefix))
        (return-from input-key (input-key session (subseq bytes prefix))))))
  ;; A client may coalesce ordinary key bytes.  Prefix handling still needs
  ;; to see the first byte as a complete key, then can forward the remainder
  ;; as one ordinary run.  Escape-led sequences are already framed by the
  ;; client and retain their existing CSI/Kitty handling below.
  (when (and (not raw-input) (session-mode session) (plusp (length bytes)) (/= (aref bytes 0) 27))
    (let ((width (key-width bytes)))
      (unless width
        (setf (session-key-fragment session) (copy-seq bytes)
              (session-key-fragment-mode session) (session-mode session))
        (return-from input-key))
      (when (> (length bytes) width)
        (let ((action (input-key session (subseq bytes 0 width)
                                (and (= width 1) (> (aref bytes 0) 127)))))
          (when (or (member action '(:detach :stop)) (command-pending-p session))
            (when (> (length bytes) width) (defer-input session 2 (subseq bytes width)))
            (return-from input-key action))
          (return-from input-key (input-key session (subseq bytes width)))))))
  (when (and (null (session-mode session)) (> (length bytes) 1) (/= (aref bytes 0) 27)
             (or (session-prefix session) (and (pane-copy-lines (focused-pane session))
                                             (not (pane-search-input (focused-pane session))))
                 (= (aref bytes 0) (option session :prefix 2))))
    (let ((action (input-key session (subseq bytes 0 1))))
      (when (or (member action '(:detach :stop)) (command-pending-p session))
        (when (> (length bytes) 1) (defer-input session 2 (subseq bytes 1)))
        (return-from input-key action))
      (return-from input-key (input-key session (subseq bytes 1)))))
  (let* ((read-bytes (when (session-input-read-framed session)
                       (prog1 (session-input-read-bytes session)
                         (setf (session-input-read-bytes session) nil))))
         (text (map 'string #'code-char bytes)) (esc (code-char 27))
         (kitty (and (> (length text) 3) (char= (char text 0) esc) (char= (char text 1) #\[)
                     (char= (char text (1- (length text))) #\u)))
         (params (when kitty (parameters (subseq text 2 (1- (length text))))))
         (code (if kitty (first params)
                   (if (session-mode session) (and (not raw-input) (utf8-codepoint bytes))
                       (and (= (length bytes) 1) (aref bytes 0)))))
         (modifiers (if kitty (1- (max 1 (or (second params) 1))) 0))
         (key (if (and code (logbitp 2 modifiers) (<= 64 code 127)) (logand code 31) code))
         (pane (nth (session-focus session) (session-panes session))))
    (when (session-mode session)
      (let* ((map (session-mode session)) (binding (key-binding session map (semantic-key bytes key)))
             (policy (find map (reverse (getf (session-registry session) :keymaps))
                           :key (lambda (m) (getf m :name)))))
        (cond ((and binding (getf binding :command))
               (dispatch-binding session map (semantic-key bytes key))
               (return-from input-key))
              ((dispatch-keymap-fallback session map (semantic-key bytes key) bytes read-bytes)
               (return-from input-key))
              ((eq (getf policy :unbound) :ignore) (return-from input-key)))))
    (cond
      ((and (null (session-mode session)) (session-prefix session))
       (setf (session-prefix session) nil)
       (if (eql key (option session :prefix 2))
           (pane-input pane (octets-from-list (list key)))
           (dispatch-binding session :prefix (semantic-key bytes key))))
      ((and (null (session-mode session)) (eql key (option session :prefix 2))) (setf (session-prefix session) t) nil)
      ((and (null (session-mode session)) (pane-search-input pane))
       (copy-search-input session (if (and kitty key (<= 0 key #x10ffff) (not (<= #xd800 key #xdfff)))
                                     (text-bytes (string (code-char key))) bytes)))
      ((and (null (session-mode session)) (pane-copy-lines pane)) (dispatch-binding session :copy (semantic-key bytes key)))
      (t
       (cond
         ((and kitty (zerop (first (terminal-keyboards (pane-vt pane)))))
          (when (and key (<= 0 key #x10ffff) (not (<= #xd800 key #xdfff)))
            (pane-input pane (text-bytes (concatenate 'string (if (logbitp 1 modifiers) (string esc) "")
                                                     (string (code-char key)))))))
         ((and (gethash 1 (terminal-modes (pane-vt pane))) (= (length bytes) 3)
               (= (aref bytes 0) 27) (= (aref bytes 1) 91) (find (code-char (aref bytes 2)) "ABCDHF"))
          (pane-input pane (octets-from-list (list 27 79 (aref bytes 2)))))
         (t (pane-input pane bytes))) nil))))
(defun octets-from-list (items) (coerce items '(vector (unsigned-byte 8))))
(defun input-mouse (session text)
  (let* ((args (parameters (subseq text 3 (1- (length text)))))
         (button (first args)) (x (second args)) (y (third args))
         (up (char= (char text (1- (length text))) #\m))
         (cw (session-cw session)) (ch (session-ch session)))
    (unless (and (= (length args) 3) (<= 0 button 255) (plusp x) (plusp y)) (return-from input-mouse))
    (let* ((hit (find-if (lambda (p)
                           (and (< (* (pane-x p) cw) x (1+ (* (+ (pane-x p) (terminal-cols (pane-vt p))) cw)))
                                (< (* (pane-y p) ch) y (1+ (* (+ (pane-y p) (terminal-rows (pane-vt p))) ch)))))
                         (visible-panes session)))
           (pane (or (session-drag session) hit)))
      (when (and pane (not up) (zerop (logand button 96)) (< (logand button 3) 3))
        (set-focus session (position pane (session-panes session))) (setf (session-drag session) pane))
      (when (and pane (pane-copy-lines pane))
        (when (and (not up) (logtest button 64))
          (move-copy pane (+ (pane-copy-cursor pane) (if (oddp button) 3 -3)))
          (incf (session-revision session)))
        (when up (setf (session-drag session) nil))
        (return-from input-mouse))
      (when pane
        (let* ((vt (pane-vt pane)) (modes (terminal-modes vt))
               (px (max 1 (min (* (terminal-cols vt) cw) (- x (* (pane-x pane) cw)))))
               (py (max 1 (min (* (terminal-rows vt) ch) (- y (* (pane-y pane) ch))))))
          (when (or (gethash 1003 modes) (and (gethash 1002 modes) (or (session-drag session) (zerop (logand button 32))))
                    (and (gethash 1000 modes) (zerop (logand button 32))))
            (unless (gethash 1016 modes) (setf px (ceiling px cw) py (ceiling py ch)))
            (when (gethash 1006 modes)
              (pane-input pane (text-bytes (format nil "~C[<~D;~D;~D~C" (code-char 27) button px py (if up #\m #\M))))))))
      (when up (setf (session-drag session) nil)))))
(defun pane-lines (vt)
  (loop for y below (terminal-rows vt) collect
    (let ((runs nil) (start 0) (attr nil) (chars (make-string-output-stream)))
      (loop for x below (terminal-cols vt) for cell = (aref (terminal-cells vt) (+ x (* y (terminal-cols vt)))) do
        (unless (equal attr (second cell))
          (when attr (push (list start (get-output-stream-string chars) attr) runs))
          (setf start x attr (second cell)))
        (write-string (first cell) chars))
      (when attr (push (list start (get-output-stream-string chars) attr) runs))
      (nreverse runs))))
(defun decoration-content-p (pane x y width)
  (and (< (pane-x pane) (+ x width))
       (< x (+ (pane-x pane) (terminal-cols (pane-vt pane))))
       (< (pane-y pane) (1+ y))
       (< y (+ (pane-y pane) (terminal-rows (pane-vt pane))))))
(defun decoration-cell-free-p (session panes x y width)
  (and (<= 0 x) (< x (session-cols session)) (<= 0 y) (< y (session-rows session))
       (<= (+ x width) (session-cols session))
       (not (some (lambda (pane) (decoration-content-p pane x y (max 1 width))) panes))))
(defun clip-decoration (session panes span)
  (let ((cursor (getf span :x)) (y (getf span :y)) (sgr (copy-list (getf span :sgr)))
        (run-x nil) (run-width 0) (run nil) (out nil))
    (labels ((flush ()
               (when run
                 (push (list run-x y (coerce (nreverse run) 'string) (copy-list sgr)) out)
                 (setf run nil run-x nil run-width 0))))
      (loop for char across (getf span :text)
            for width = (ekko/vt::character-width char) do
              ;; Combining marks do not claim a new cell. Keep them with an
              ;; accepted base glyph, and drop leading marks so a clipped
              ;; span cannot affect an unrelated cell.
              (cond
                ((zerop width) (when run (push char run)))
                ((decoration-cell-free-p session panes cursor y width)
                 (unless (and run-x (= cursor (+ run-x run-width))) (flush))
                 (unless run-x (setf run-x cursor))
                 (push char run) (incf run-width width))
                (t (flush)))
              (incf cursor width))
      (flush))
    (nreverse out)))
(defun scene-decorations (session)
  (let ((panes (visible-panes session)))
    ;; Registry component order is the layer order. Contributions are stored
    ;; by owner for replacement, so their completion order must not change
    ;; which decoration wins an overlap on the client.
    (let* ((components (getf (session-registry session) :components))
           (declared (mapcar (lambda (component) (getf component :id)) components))
           (owners (append declared
                           (loop for entry in (session-decorations session)
                                 unless (member (car entry) declared :test #'equal)
                                   collect (car entry)))))
      (loop for owner in owners
            for entry = (assoc owner (session-decorations session) :test #'equal)
            when entry append (loop for span in (cdr entry)
                                    append (loop for row from (getf span :y)
                                                  below (+ (getf span :y) (getf span :rows 1))
                                                  append (clip-decoration
                                                           session panes
                                                           (list :x (getf span :x) :y row
                                                                 :text (getf span :text)
                                                                 :sgr (getf span :sgr)))))))))
(defun scene-data (session)
  (list +wire-version+ (session-cols session) (session-rows session) (session-cw session) (session-ch session)
        (pane-id (nth (session-focus session) (session-panes session)))
        (loop for pane in (visible-panes session) for vt = (pane-vt pane) collect
          (list (pane-id pane) (pane-x pane) (pane-y pane) (terminal-cols vt) (terminal-rows vt)
                (if (pane-copy-lines pane) (format nil "~A [copy ~D/~D]" (pane-label pane)
                          (1+ (pane-copy-cursor pane)) (length (pane-copy-lines pane))) (pane-label pane)) (pane-status pane) (min (1- (terminal-cols vt)) (terminal-x vt))
                (terminal-y vt) (and (not (pane-copy-lines pane)) (terminal-visible vt))
                (if (pane-copy-lines pane) (copy-display-lines pane) (pane-lines vt))
                (loop for image being the hash-values of (store-images (pane-graphics pane))
                      when (and (not (pane-copy-lines pane)) (image-visible image) (eq (image-screen image) (terminal-screen vt))) collect
                        (list (image-id image) (image-generation image) (image-x image) (image-y image)
                              (image-cols image) (image-rows image)))
                (list (pane-outer-x pane) (pane-outer-y pane)
                      (pane-outer-cols pane) (pane-outer-rows pane))))
        (multiple-value-bind (viewport pane gaps width height) (session-geometry session)
          (declare (ignore pane width height))
          (list :status (status-text session) :style (option session :status-style '(0 30 47))
                :viewport-insets viewport :split-gaps gaps :decorations (scene-decorations session)
                :exit-text (option session :viewer-exit-text nil)))))
(defun checked-startup-viewport (viewport)
  (when viewport
    (unless (and (listp viewport) (= (length viewport) 4)
                 (every #'integerp viewport))
      (error "Invalid startup viewport ~S" viewport))
    (destructuring-bind (cols rows cw ch) viewport
      (unless (and (<= 5 cols 500) (<= 4 rows 300)
                   (<= 1 cw 128) (<= 1 ch 256))
        (error "Invalid startup viewport ~S" viewport))
      (list cols rows cw ch))))
(defun session-stamp (session)
  (list (session-revision session)
        (loop for pane in (session-panes session) collect
          (list (terminal-revision (pane-vt pane)) (store-revision (pane-graphics pane)) (pane-status pane)))))
(defun publish-scene (session wire)
  (let ((stamp (session-stamp session)))
    (when (and (null (wire-queue wire)) (null (wire-awaiting-scene wire))
               (not (equal stamp (wire-revision wire))))
      (let ((live (make-hash-table :test 'equal)))
        (dolist (pane (visible-panes session))
          (maphash (lambda (id image)
                     (when (and (not (pane-copy-lines pane)) (image-visible image) (eq (image-screen image) (terminal-screen (pane-vt pane))))
                       (setf (gethash (list (pane-id pane) id) live) t)))
                   (store-images (pane-graphics pane))))
        (maphash (lambda (key value) (declare (ignore value))
                   (unless (gethash key live) (remhash key (wire-known wire)))) (wire-known wire)))
      (dolist (pane (visible-panes session))
        (maphash (lambda (id image)
                   (let ((key (list (pane-id pane) id)))
                     (when (and (not (pane-copy-lines pane)) (image-visible image) (eq (image-screen image) (terminal-screen (pane-vt pane)))
                                (not (eql (gethash key (wire-known wire)) (image-generation image))))
                       (let ((data (image-data image))
                             (metadata (integers (list (pane-id pane) id (image-generation image)
                                                       (image-width image) (image-height image) (image-format image)))))
                         (send-packet wire (if (local-asset-p data) 13 11)
                           (concatenate '(vector (unsigned-byte 8)) metadata
                             (if (local-asset-p data) (text-bytes (local-asset-path data)) data))))
                       (setf (gethash key (wire-known wire)) (image-generation image)))))
                 (store-images (pane-graphics pane))))
      (dolist (pane (visible-panes session))
        (maphash (lambda (id image) (declare (ignore id))
                   (when (and (not (pane-copy-lines pane)) (image-visible image)
                              (eq (image-screen image) (terminal-screen (pane-vt pane)))
                              (local-asset-p (image-data image)))
                     (push (retain-asset (image-data image)) (wire-leases wire))))
                 (store-images (pane-graphics pane))))
      (let ((scene (scene-data session)))
        (setf (first scene) (wire-version wire))
        (send-packet wire 12 (encode-scene scene)))
      (setf (wire-awaiting-scene wire) (now))
      (setf (wire-revision wire) stamp))))
(defun status-json (session)
  (json-value
    (list :object :wire_version +wire-version+ :session (session-name session)
          :daemon_pid (sb-posix:getpid)
          :extension_pid (when (session-worker session) (sb-ext:process-pid (extension-worker-process (session-worker session))))
          :allocated_bytes (sb-ext:get-bytes-consed)
          :gc_seconds (coerce (/ sb-ext:*gc-run-time* internal-time-units-per-second) 'double-float)
          :snapshot_bytes ekko/platform::*asset-bytes* :attached (if (session-writer session) t :false)
          :focus (pane-id (focused-pane session))
          :panes (loop for p in (session-panes session) for vt = (pane-vt p) for g = (pane-graphics p) collect
                  (list :object :id (pane-id p) :pid (pane-pid p) :label (pane-label p) :exit_code (pane-status p)
                        :cols (terminal-cols vt) :rows (terminal-rows vt) :x (pane-x p) :y (pane-y p)
                        :history_rows (if (and (terminal-history vt)
                                               (eq (terminal-screen vt) :main))
                                          (history-count (terminal-history vt)) 0)
                        :copy_mode (if (pane-copy-lines p) t :false)
                        :images (hash-table-count (store-images g)) :frames (store-frames g)
                        :graphics_errors (store-errors g) :image_bytes (store-bytes g)
                        :pty_output_bytes (pane-output-bytes p)
                        :local_images (loop for image being the hash-values of (store-images g)
                                            count (local-asset-p (image-data image))))))))
(defun server-packet (session wire packet)
  (let ((kind (aref packet 0)) (data (subseq packet 1)))
    (when (and (member kind '(2 4 5 6 16)) (eq (session-writer session) wire) (command-pending-p session))
      (defer-input session kind data) (return-from server-packet))
    (case kind
      (1
       (unless (and (= (length data) 20) (member (u32 data 0) (list 6 7 +wire-version+)))
         (send-packet wire 21 (text-bytes "Incompatible Ekko wire version")) (return-from server-packet))
       (when (and (session-writer session) (not (eq wire (session-writer session))))
         (send-packet wire 21 (text-bytes "This session already has an attached client")) (return-from server-packet))
       (let ((cols (u32 data 4)) (rows (u32 data 8)) (cw (u32 data 12)) (ch (u32 data 16)))
         (unless (and (<= 5 cols 500) (<= 4 rows 300) (<= 1 cw 128) (<= 1 ch 256)) (error "Invalid viewport"))
         (unless (eq (session-writer session) wire)
           (setf (session-input-read-framed session) nil
                 (session-input-read-bytes session) nil))
         (setf (wire-version wire) (u32 data 0)
               (session-cols session) cols (session-rows session) rows (session-cw session) cw (session-ch session) ch
               (session-writer session) wire (wire-attached wire) t)
         (layout session)))
      (15
       (unless (and (= (length data) 8) (wire-attached wire)
                    (eq (session-writer session) wire))
         (error "Unexpected reported cell size"))
       (let ((cw (u32 data 0)) (ch (u32 data 4)))
         (unless (and (<= 1 cw 128) (<= 1 ch 256))
           (error "Invalid reported cell size"))
         (setf (session-reported-cw session) cw (session-reported-ch session) ch)
         (incf (session-revision session))))
      (14 (unless (and (= (length data) 0) (wire-attached wire) (wire-awaiting-scene wire))
            (error "Unexpected scene acknowledgement"))
          (acknowledge-scene wire))
      (2 (when (eq (session-writer session) wire)
           (let ((action (input-key session data)))
             (case action (:detach (send-packet wire 22)) (:stop :stop)))))
      (4 (when (eq (session-writer session) wire)
           (setf (session-input-read-bytes session) nil)
           (input-mouse session (bytes-text data))))
      (16 (when (eq (session-writer session) wire)
            (unless (wire-attached wire) (error "Input read frame requires an attached writer"))
            (unless (<= 1 (length data) 65536) (error "Invalid input read frame"))
            (when (> (+ (length (session-input-read-bytes session)) (length data)) 65536)
              (error "Input read frame exceeds 64 KiB"))
            (setf (session-input-read-framed session) t
                  (session-input-read-bytes session)
                  (concatenate '(vector (unsigned-byte 8))
                               (or (session-input-read-bytes session) (octets 0)) data))))
      (5 (when (eq (session-writer session) wire)
           (setf (session-input-read-bytes session) nil)
           (let* ((begin (equalp data (text-bytes (format nil "~C[200~~" (code-char 27)))))
                  (end (equalp data (text-bytes (format nil "~C[201~~" (code-char 27)))))
                  (pane (or (session-paste-target session) (nth (session-focus session) (session-panes session))))
                  (fallback (or (session-paste-fallback session)
                                (and (session-paste-target session) :forward)
                                (paste-policy session))))
             (cond
               ((and begin (or (stringp fallback) (eq fallback :ignore)))
                (setf (session-paste-fallback session) fallback
                      (session-paste-buffer session) (octets 0)
                      (session-paste-overflow session) nil))
               ((session-paste-fallback session)
                (unless (or begin end (eq (session-paste-fallback session) :ignore)
                            (session-paste-overflow session))
                  (if (<= (+ (length (session-paste-buffer session)) (length data)) 4096)
                      (setf (session-paste-buffer session)
                            (concatenate '(vector (unsigned-byte 8))
                                         (session-paste-buffer session) data))
                      (progn (setf (session-paste-overflow session) t)
                             (note-error session "Fallback paste exceeds 4096 bytes"))))
                (when end (finish-paste-fallback session)))
               ((stringp fallback)
                (when (<= (length data) 4096)
                  (request-command session fallback
                                   (list :key nil :bytes (coerce data 'list) :paste t) nil))
                (when (> (length data) 4096)
                  (note-error session "Fallback paste exceeds 4096 bytes")))
               ((eq fallback :ignore))
               (t
                (when begin (setf (session-paste-target session) pane))
                (when (or (not (or begin end)) (gethash 2004 (terminal-modes (pane-vt pane))))
                  (pane-input pane data))
                (when end (setf (session-paste-target session) nil)))))))
      (6 (when (eq (session-writer session) wire)
           (setf (session-input-read-bytes session) nil)
           (let ((pane (nth (session-focus session) (session-panes session))))
             (when (gethash 1004 (terminal-modes (pane-vt pane))) (pane-input pane data)))))
      (7 (handler-case
             (let* ((parts (split-arguments data)) (name (first parts)))
               (request-command session name (list :arguments (rest parts)) wire))
           (error (e) (command-reply wire (princ-to-string e) t))))
      (3 (let ((command (bytes-text data)))
           (cond ((string= command "status") (send-packet wire 20 (text-bytes (status-json session))))
                 ((string= command "stop") (send-packet wire 20 (text-bytes "{}")) (flush-wire wire) :stop)
                 ((string= command "reload")
                  (handler-case (start-reload session wire)
                    (error (e) (note-error session e) (command-reply wire (princ-to-string e) t))))
                 ((string= command "inspect") (send-packet wire 20 (text-bytes (inspect-json session))))
                 ((string= command "buffer") (send-packet wire 20 (text-bytes (session-clipboard session))))
                 (t (error "Unknown control command")))))
      (otherwise (error "Unknown IPC message")))))
(defun serve (name commands &optional startup-viewport)
  (initialize) (server-signals)
  (let* ((startup-viewport (checked-startup-viewport startup-viewport))
         (path (socket-path name)) (lock (checked (lock-file (concatenate 'string path ".lock")) "session lock"))
         (listener nil) (session (make-session :name name
                                               :cols (or (first startup-viewport) 120)
                                               :rows (or (second startup-viewport) 36)
                                               :cw (or (third startup-viewport) 8)
                                               :ch (or (fourth startup-viewport) 16)))
         (peers nil) (buffer (octets 65536)) (running t))
    (dolist (sig (list sb-posix:sigterm sb-posix:sighup))
      (sb-sys:enable-interrupt sig (lambda (&rest arguments) (declare (ignore arguments)) (setf running nil))))
    (unwind-protect
         (progn
           (initialize-assets (concatenate 'string path ".frames/"))
           (when (probe-file path) (delete-file path))
           (setf (session-worker session)
                 (load-worker (config-source (config-path)) (config-path) (concatenate 'string path ".extensions.log")))
           (install-registry session (extension-worker-registry (session-worker session)))
           (let ((initial (option session :initial-layout)))
             (when (and initial
                        (/= (length commands) (length (ekko/extensions::initial-layout-leaves initial))))
               (error "Initial layout must contain one slot per startup command")))
           (sb-posix:setenv "EKKO_SESSION_NAME" name 1)
           (sb-posix:setenv "TERM" "xterm-256color" 1)
           (sb-posix:unsetenv "TMUX") (sb-posix:unsetenv "STY")
           ;; Build the pane tree with inert one-cell terminals first.  Layout
           ;; can then derive each pane's actual first PTY size from the loaded
           ;; public options before any child is allowed to write.
           (loop for argv in commands for id from 1 do
             (push (make-pane :id id :activation-order (incf (session-activation-sequence session))
                              :vt (make-terminal :cols 1 :rows 1
                                                          :cw (session-cw session) :ch (session-ch session))
                              :argv (copy-list argv) :label (file-namestring (first argv))
                              :launch-kind :command :creation-position id)
                   (session-panes session)))
           (setf (session-panes session) (nreverse (session-panes session))
                 (session-next-pane-id session) (1+ (length commands))
                 (session-tree session) (pane-id (first (session-panes session))))
           (if (option session :initial-layout)
               (setf (session-tree session) (copy-tree (option session :initial-layout)))
               (loop for pane in (rest (session-panes session)) for previous = (first (session-panes session)) then pane do
                 (setf (session-tree session) (ekko/layout:split-pane (session-tree session) (pane-id previous) (pane-id pane) :columns))))
           (record-activation session (focused-pane session))
           (layout session)
           (loop for argv in commands for pane in (session-panes session) do
             (let ((vt (pane-vt pane)))
               (multiple-value-bind (fd pid)
                   (multiple-value-call #'spawn argv (terminal-cols vt) (terminal-rows vt)
                     (pty-cell-size session))
                 (setf (pane-io pane) (make-wire :fd fd) (pane-pid pane) pid
                       (pane-pty-size pane)
                       (pty-size-for session (terminal-cols vt) (terminal-rows vt))))))
           (setf listener (checked (listen-local path) "listen"))
           (labels ((drop-peer (peer)
                      (when (eq peer (session-writer session))
                        (setf (session-writer session) nil (session-prefix session) nil (session-drag session) nil
                              (session-paste-target session) nil
                              (session-paste-fallback session) nil
                              (session-paste-buffer session) nil
                              (session-paste-overflow session) nil
                              (session-key-fragment session) nil
                              (session-key-fragment-mode session) nil
                              (session-input-read-framed session) nil
                              (session-input-read-bytes session) nil))
                      (close-wire peer) (setf peers (remove peer peers))))
             (loop while (and running (not (session-stopping session))) do
               (expire-pane-notes session)
               (service-extensions session buffer)
               (reap-retired session)
               (dolist (pane (session-panes session))
                 (expire-upload (pane-graphics pane))
                 (when (null (pane-status pane))
                   (let ((exit (reap (pane-pid pane))))
                     (when (>= exit 0) (setf (pane-status pane) exit) (incf (session-revision session))))))
               (dolist (peer (copy-list peers))
                 (handler-case
                     (progn
                       (when (and (wire-awaiting-scene peer) (> (- (now) (wire-awaiting-scene peer)) 10))
                         (error "Presentation acknowledgement timed out"))
                       (when (wire-attached peer) (publish-scene session peer))
                       (when (and (not (wire-attached peer)) (>= (- (now) (wire-at peer)) 10)) (drop-peer peer)))
                   (error (e) (format *error-output* "client: ~A~%" e) (drop-peer peer))))
               ;; Housekeeping needs to run at the next upload/peer timeout, and
               ;; periodically to notice exited children.  Avoid waking every
               ;; frame while retaining prompt protocol timeout handling.
               (let* ((current (now))
                      (deadline (+ current 1)))
                 (dolist (note (session-pane-notes session))
                   (setf deadline (min deadline (getf note :until))))
                 (dolist (worker (list (session-worker session) (session-candidate session)))
                   (when (and worker (extension-worker-request worker))
                     (setf deadline (min deadline (extension-worker-deadline worker)))))
                 (dolist (pane (session-panes session))
                   (let ((pending (store-pending (pane-graphics pane))))
                     (when pending
                       (setf deadline (min deadline (+ (ekko/graphics::upload-at pending) 10))))))
                 (dolist (peer peers)
                   (unless (wire-attached peer)
                     (setf deadline (min deadline (+ (wire-at peer) 10)))))
                 (dolist (event (poll-fds
                              (append (list (cons listener 1))
                                      (worker-events (session-worker session)) (worker-events (session-candidate session))
                                      (loop for p in (session-panes session) when (pane-io p)
                                            collect (cons (wire-fd (pane-io p)) (wire-events (pane-io p))))
                                      (loop for peer in peers collect (cons (wire-fd peer) (wire-events peer))))
                              (max 0 (ceiling (* 1000 (- deadline current))))))
                 (let* ((fd (car event)) (flags (cdr event))
                        (pane (find fd (session-panes session) :key (lambda (p) (when (pane-io p) (wire-fd (pane-io p)))))))
                   (cond
                     ((= fd listener)
                      (let ((accepted (accept-local listener)))
                        (when (>= accepted 0)
                          (if (< (length peers) 8) (push (make-wire :fd accepted) peers) (close-fd accepted)))))
                     (pane
                      (handler-case
                          (progn
                            (when (logtest flags 4) (flush-wire (pane-io pane)))
                            (when (logtest flags 25)
                              (let ((n (read-fd fd buffer)))
                                (cond ((plusp n)
                                       (incf (pane-output-bytes pane) n)
                                       (feed (pane-vt pane) (subseq buffer 0 n) (lambda (k v) (pane-event pane k v))))
                                      ((not (member n '(-11 -4))) (close-wire (pane-io pane)) (setf (pane-io pane) nil))))))
                        (error (e) (format *error-output* "pane ~D: ~A~%" (pane-id pane) e) (close-pane pane))))
                     (t (let ((peer (find fd peers :key #'wire-fd)))
                          (when peer
                            (handler-case
                                (progn
                                  (when (logtest flags 4) (flush-wire peer))
                                  (when (logtest flags 25)
                                    (dolist (packet (receive-packets peer buffer))
                                      (when (eq :stop (server-packet session peer packet)) (setf running nil)))))
                              (error (e)
                                (unless (search "disconnected" (princ-to-string e)) (format *error-output* "client: ~A~%" e))
                                (drop-peer peer))))))))))))
      (stop-worker (session-worker session)) (stop-worker (session-candidate session))
      (dolist (retired (session-retired session)) (signal-group (pane-pid (car retired)) 9) (reap (pane-pid (car retired))))
      (dolist (peer peers) (close-wire peer))
      (dolist (pane (session-panes session))
        (close-pane pane)
        (clear-screen (pane-graphics pane) :main)
        (clear-screen (pane-graphics pane) :alternate))
      (let ((deadline (+ (now) 1)))
      (loop while (and (< (now) deadline)
                       (some (lambda (p) (and (pane-pid p) (= -11 (reap (pane-pid p)))))
                             (session-panes session)))
              do (poll-fds nil 20)))
      (dolist (pane (session-panes session))
        (when (and (pane-pid pane) (= -11 (reap (pane-pid pane))))
          (signal-group (pane-pid pane) 9)))
      (when listener (close-fd listener))
      (when (probe-file path) (delete-file path)) (close-fd lock)))
  0))
