(in-package #:ekko/runtime)

;; Pane content survives every view. Nothing below aliases interaction fields
;; into a pane or temporarily installs a view into shared workspace state.
;; One daemon owns one workspace: every pane, view and component lives there.
(defstruct pane id daemon pid io vt (graphics (make-store)) argv label status floating
  (launch-kind :command) (creation-position 0) name pty-size sync-until
  (output-bytes 0) (application-focused nil) row-cache)
(defstruct store-state entries)
(defstruct pane-view pane-id (x 0) (y 0) (cols 0) (rows 0)
  (outer-x 0) (outer-y 0) (outer-cols 0) (outer-rows 0)
  minimized (activation-order 0) (unseen-output nil)
  copy-cells copy-pointer copy-anchor copy-end copy-flash-until copy-lines
  (copy-cursor 0) (copy-top 0) copy-mark search-input (search-text ""))
(defstruct view daemon wire id (epoch 0) focus-id
  (cols 120) (rows 36) (cw 8) (ch 16) reported-cw reported-ch
  pty-reported-cw pty-reported-ch
  (host-focused t) (revision 0) (activation-sequence 0)
  (pane-states (make-hash-table)) mode zoom prefix
  drag window-drag window-hover chrome-press popup transition paste-target last-click
  paste-fallback paste-buffer paste-overflow key-fragment key-fragment-mode
  input-read-framed input-read-bytes input-queue (input-bytes 0)
  (notice "") error geometry-contributions contributions decorations pane-notes
  component-state hook-context hooks (layout-state (make-layout-state))
  layout-placements (camera-x 0) (camera-y 0) motions tweens glows ghosts slides redecorated popup-ghost animating
  initialized extension-initialized initialization-failure quarantined)
(defstruct command-origin daemon view epoch target-pane-id peer config-generation layout)
(defstruct command-request origin name event snapshot)
(defstruct hook-request origin owner snapshot)
(defstruct pending-split pane origin owner actions)

(defun daemon-store-entries (daemon)
  (store-state-entries (daemon-store daemon)))
(defun (setf daemon-store-entries) (entries daemon)
  (setf (store-state-entries (daemon-store daemon)) entries))
(defun pane-by-id (daemon id)
  (find id (daemon-panes daemon) :key #'pane-id))
(defun view-panes (view)
  (daemon-panes (view-daemon view)))
(defun pane-state (view id &optional (create t))
  (or (gethash id (view-pane-states view))
      (let ((pane (pane-by-id (view-daemon view) id)))
        (unless pane (error "Unknown pane: ~S" id))
        (let ((state (make-pane-view :pane-id id)))
          (when create (setf (gethash id (view-pane-states view)) state))
          state))))
(defun focused-pane (view)
  (pane-by-id (view-daemon view) (view-focus-id view)))
(defun capture-origin (view &optional peer target)
  (make-command-origin :daemon (view-daemon view) :view view :epoch (view-epoch view)
                       :target-pane-id (or target (view-focus-id view)) :peer peer
                       :config-generation (daemon-config-generation (view-daemon view))
                       :layout (copy-tree (daemon-tree (view-daemon view)))))
(defun origin-current-p (origin)
  (let ((view (command-origin-view origin)) (daemon (command-origin-daemon origin)))
    (and (eq daemon (view-daemon view)) (member view (daemon-views daemon))
         (= (command-origin-epoch origin) (view-epoch view))
         (= (command-origin-config-generation origin) (daemon-config-generation daemon))
         (not (daemon-stopping daemon)))))
(defun origin-target (origin)
  (or (pane-by-id (command-origin-daemon origin) (command-origin-target-pane-id origin))
      (error "Command target pane no longer exists")))
(defun initialize-view (view)
  (let ((daemon (view-daemon view)))
    (pushnew view (daemon-views daemon))
    (unless (daemon-home-view daemon) (setf (daemon-home-view daemon) view))
    (unless (view-focus-id view)
      (setf (view-focus-id view) (and (first (view-panes view)) (pane-id (first (view-panes view))))))
    (dolist (pane (view-panes view)) (pane-state view (pane-id pane)))
    (unless (view-initialized view)
      (setf (view-mode view) (option daemon :initial-keymap)
            (view-initialized view) t)
      (pushnew view (daemon-initialization-queue daemon)))
    (layout view))
  view)
(defun reset-view-input (view &optional preserve-queue)
  (setf (view-prefix view) nil (view-drag view) nil (view-window-drag view) nil
        (view-window-hover view) nil (view-chrome-press view) nil (view-popup view) nil
        (view-transition view) nil (view-paste-target view) nil (view-paste-fallback view) nil
        (view-paste-buffer view) nil (view-paste-overflow view) nil
        (view-key-fragment view) nil (view-key-fragment-mode view) nil
        (view-input-read-framed view) nil (view-input-read-bytes view) nil)
  (unless preserve-queue (setf (view-input-queue view) nil (view-input-bytes view) 0)))
(defun attach-view (daemon wire id cols rows cw ch &optional existing-view)
  (let* ((home (daemon-home-view daemon))
         (view (or existing-view home
                   (make-view :daemon daemon :id id :cols cols :rows rows :cw cw :ch ch))))
    (unless (eq daemon (view-daemon view)) (error "View belongs to another daemon"))
    ;; One attached client at a time: an attach takes over the session view.
    ;; A wired view's client drains to a clean disconnect rather than an
    ;; error, which its attach loop would retry into a steal-back.
    (dolist (other (daemon-views daemon))
      (when (and (not (eq other view)) (view-wire other))
        (setf (wire-closing (view-wire other)) t)
        (detach-view other)))
    (when (view-wire view)
      (setf (wire-closing (view-wire view)) t)
      (detach-view view))
    (setf (view-wire view) wire (wire-view wire) view (view-host-focused view) t)
    (initialize-view view)
    (resize-view view cols rows cw ch)
    (update-application-focus daemon)
    view))
(defun detach-view (view)
  (let ((wire (view-wire view)) (daemon (view-daemon view)))
    (when wire (setf (wire-view wire) nil))
    (setf (view-wire view) nil (view-host-focused view) nil)
    (incf (view-epoch view))
    (reset-view-input view)
    (setf (view-hooks view) nil (view-hook-context view) nil)
    (reconcile-size daemon)
    (update-application-focus daemon)
    ;; The workspace persists across detach: PTYs outlive every client.
    ;; Only `stop', the last pane exiting, or a signal tears it down.
    (trim-detached-views daemon)))
(defun resize-view (view cols rows cw ch)
  (setf (view-cols view) cols (view-rows view) rows (view-cw view) cw (view-ch view) ch)
  (layout view))
(defun view-live-p (view)
  (not (null (view-wire view))))
(defun update-application-focus (daemon)
  (dolist (pane (daemon-panes daemon))
    (let ((focused (not (null (pane-watched-p daemon pane)))))
      (unless (eql focused (pane-application-focused pane))
        (setf (pane-application-focused pane) focused)
        (when focused (change-notifications daemon :read-pane (pane-id pane)))
        (when (gethash 1004 (terminal-modes (pane-vt pane)))
          (pane-input pane (text-bytes (format nil "~C[~A" #\Esc (if focused "I" "O")))))))))
(defun note-pane-output (daemon pane)
  (dolist (view (daemon-views daemon))
    (when (and (member pane (view-panes view)) (not (eql (pane-id pane) (view-focus-id view))))
      (setf (pane-view-unseen-output (pane-state view (pane-id pane))) t))))
(defun pane-watched-p (daemon pane)
  (some (lambda (view) (and (view-live-p view) (view-host-focused view)
                            (eql (view-focus-id view) (pane-id pane))))
        (daemon-views daemon)))
(defun notification-text (text limit)
  (let ((clean (substitute-if #\Space (lambda (c) (or (< (char-code c) 32) (<= 127 (char-code c) 159)))
                              (string-trim '(#\Space) (or text "")))))
    (subseq clean 0 (min limit (length clean)))))
(defun record-notification (pane message)
  "Keep the newest 64 notifications. MESSAGE is (title body), or nil for BEL.
A bell from a pane someone is watching is only a beep; an explicit message
from it is stored already read. Repeated unread bells coalesce."
  (let* ((daemon (pane-daemon pane)) (watched (pane-watched-p daemon pane))
         (live (remove-if-not (lambda (n) (pane-by-id daemon (getf n :pane)))
                              (daemon-notifications daemon)))
         (previous (find (pane-id pane) live :key (lambda (n) (getf n :pane)))))
    (cond ((and (null message) watched))
          ((and (null message) previous (getf previous :bell) (not (getf previous :read)))
           (setf (getf previous :time) (get-universal-time))
           (incf (getf previous :count))
           (setf (daemon-notifications daemon) (cons previous (remove previous live))))
          (t
           (push (list :id (daemon-next-notification-id daemon) :pane (pane-id pane)
                       :time (get-universal-time) :bell (null message) :count 1
                       :title (notification-text (first message) 80)
                       :body (notification-text (second message) 240)
                       :read (not (null watched)))
                 live)
           (incf (daemon-next-notification-id daemon))
           (setf (daemon-notifications daemon) (subseq live 0 (min 64 (length live))))))))
(defun change-notifications (daemon op &optional id)
  "Apply OP (:read, :dismiss, :read-pane, :read-all or :clear) to ID."
  (let ((key (if (eq op :read-pane) :pane :id)))
    (ecase op
      (:clear (setf (daemon-notifications daemon) nil))
      (:dismiss (setf (daemon-notifications daemon)
                      (remove id (daemon-notifications daemon) :key (lambda (n) (getf n :id)))))
      ((:read :read-pane :read-all)
       (dolist (n (daemon-notifications daemon))
         (when (or (eq op :read-all) (eql id (getf n key)))
           (setf (getf n :read) t)))))))
(defun prune-view-pane (view id)
  (unless (or (gethash id (view-pane-states view)) (eql id (view-focus-id view)))
    (return-from prune-view-pane))
  (remhash id (view-pane-states view))
  (setf (view-layout-placements view)
        (remove id (view-layout-placements view) :key (lambda (p) (getf p :pane))))
  (when (eql (view-focus-id view) id)
    (setf (view-focus-id view) (and (first (view-panes view)) (pane-id (first (view-panes view))))))
  (reset-view-input view)
  (expire-pane-notes view)
  (incf (view-revision view)))
