(in-package #:ekko/runtime)

;; Pane content survives every view. Nothing below aliases interaction fields
;; into a pane or temporarily installs a view into a shared session.
(defstruct pane id session pid io vt (graphics (make-store)) argv label status floating
  (launch-kind :command) (creation-position 0) name pty-size sync-until
  (output-bytes 0) (application-focused nil))
(defstruct store-state entries)
(defstruct session daemon name (incarnation 0) panes tree (next-pane-id 1)
  views home-view launch-directory launch-environment config-path
  (store-state (make-store-state))
  (revision 0) (started (now)) retired worker candidate registry
  (config-generation 0) config-error command-queue disabled-hooks hook-failures
  (work-turn 0) dispatch-cursors (recovery-budget 0)
  reload-peer initialization-queue candidate-views candidate-results candidate-contexts candidate-layouts candidate-stage candidate-members pending-splits
  (clipboard "") stopping)
(defstruct pane-view pane-id (x 0) (y 0) (cols 0) (rows 0)
  (outer-x 0) (outer-y 0) (outer-cols 0) (outer-rows 0)
  minimized (activation-order 0) (unseen-output nil)
  copy-cells copy-pointer copy-anchor copy-end copy-flash-until copy-lines
  (copy-cursor 0) (copy-top 0) copy-mark search-input (search-text ""))
(defstruct view session wire id (epoch 0) focus-id
  (cols 120) (rows 36) (cw 8) (ch 16) reported-cw reported-ch
  pty-reported-cw pty-reported-ch
  (host-focused t) (revision 0) (activation-sequence 0)
  (pane-states (make-hash-table)) mode zoom prefix
  drag window-drag window-hover chrome-press popup transition paste-target last-click
  paste-fallback paste-buffer paste-overflow key-fragment key-fragment-mode
  input-read-framed input-read-bytes input-queue (input-bytes 0)
  (notice "") error geometry-contributions contributions decorations pane-notes
  component-state hook-context hooks (layout-state (make-layout-state))
  layout-placements (camera-x 0) (camera-y 0) initialized extension-initialized initialization-failure quarantined)
(defstruct command-origin session view epoch target-pane-id peer config-generation layout)
(defstruct command-request origin name event snapshot)
(defstruct hook-request origin owner snapshot)
(defstruct pending-split pane origin owner actions)

(defun session-store (session)
  (store-state-entries (session-store-state session)))
(defun (setf session-store) (entries session)
  (setf (store-state-entries (session-store-state session)) entries))
(defun pane-by-id (session id)
  (or (find id (session-panes session) :key #'pane-id)
      (find id (session-all-panes session) :key #'pane-id)))
(defun view-panes (view &optional (registry (session-registry (view-session view))))
  (let ((session (view-session view)))
    (if (eq (getf (getf registry :options) :workspace-scope :session) :all-panes)
        (session-all-panes session)
        (session-panes session))))
(defun pane-state (view id &optional (create t))
  (or (gethash id (view-pane-states view))
      (let ((pane (pane-by-id (view-session view) id)))
        (unless pane (error "Unknown pane: ~S" id))
        (let ((state (make-pane-view :pane-id id)))
          (when create (setf (gethash id (view-pane-states view)) state))
          state))))
(defun focused-pane (view)
  (pane-by-id (view-session view) (view-focus-id view)))
(defun capture-origin (view &optional peer target)
  (make-command-origin :session (view-session view) :view view :epoch (view-epoch view)
                       :target-pane-id (or target (view-focus-id view)) :peer peer
                       :config-generation (session-config-generation (view-session view))
                       :layout (copy-tree (session-tree (view-session view)))))
(defun origin-current-p (origin)
  (let ((view (command-origin-view origin)) (session (command-origin-session origin)))
    (and (eq session (view-session view)) (member view (session-views session))
         (= (command-origin-epoch origin) (view-epoch view))
         (= (command-origin-config-generation origin) (session-config-generation session))
         (not (session-stopping session)))))
(defun origin-target (origin)
  (or (pane-by-id (command-origin-session origin) (command-origin-target-pane-id origin))
      (error "Command target pane no longer exists")))
(defun initialize-view (view)
  (let ((session (view-session view)))
    (pushnew view (session-views session))
    (unless (session-home-view session) (setf (session-home-view session) view))
    (unless (view-focus-id view)
      (setf (view-focus-id view) (and (first (view-panes view)) (pane-id (first (view-panes view))))))
    (dolist (pane (view-panes view)) (pane-state view (pane-id pane)))
    (unless (view-initialized view)
      (setf (view-mode view) (option session :initial-keymap)
            (view-initialized view) t)
      (pushnew view (session-initialization-queue session)))
    (layout view))
  view)
(defun reset-view-input (view &optional preserve-queue)
  (setf (view-prefix view) nil (view-drag view) nil (view-window-drag view) nil
        (view-window-hover view) nil (view-chrome-press view) nil (view-popup view) nil
        (view-transition view) nil (view-paste-target view) nil (view-paste-fallback view) nil
        (view-paste-buffer view) nil (view-paste-overflow view) nil
        (view-key-fragment view) nil (view-key-fragment-mode view) nil
        (view-input-read-framed view) nil (view-input-read-bytes view) nil)
  (unless preserve-queue (setf (view-input-queue view) nil (view-input-bytes view) 0)))
(defun attach-view (session wire id cols rows cw ch &optional existing-view)
  (let* ((home (session-home-view session))
         (view (or existing-view (and home (null (view-wire home)) home)
                   (make-view :session session :id id :cols cols :rows rows :cw cw :ch ch))))
    (when (view-wire view) (error "View ~D already has an attached client" (view-id view)))
    (unless (eq session (view-session view)) (error "View belongs to another session"))
    (setf (view-wire view) wire (wire-view wire) view (view-host-focused view) t)
    (initialize-view view)
    (resize-view view cols rows cw ch)
    (update-application-focus session)
    view))
(defun detach-view (view)
  (let ((wire (view-wire view)) (session (view-session view)))
    (when wire (setf (wire-view wire) nil))
    (setf (view-wire view) nil (view-host-focused view) nil)
    (incf (view-epoch view))
    (reset-view-input view)
    (setf (view-hooks view) nil (view-hook-context view) nil)
    (reconcile-session-size session)
    (update-application-focus session)
    (when (session-daemon session) (trim-detached-views session))))
(defun resize-view (view cols rows cw ch)
  (setf (view-cols view) cols (view-rows view) rows (view-cw view) cw (view-ch view) ch)
  (layout view))
(defun view-live-p (view)
  (not (null (view-wire view))))
(defun update-application-focus (session)
  (dolist (pane (session-all-panes session))
    (let ((focused (not (null (some (lambda (view)
                                    (and (view-live-p view) (view-host-focused view)
                                         (eql (view-focus-id view) (pane-id pane))))
                                  (session-all-views session))))))
      (unless (eql focused (pane-application-focused pane))
        (setf (pane-application-focused pane) focused)
        (when (gethash 1004 (terminal-modes (pane-vt pane)))
          (pane-input pane (text-bytes (format nil "~C[~A" #\Esc (if focused "I" "O")))))))))
(defun view-consumes-session-p (view session)
  (or (eq (view-session view) session)
      (eq (option (view-session view) :workspace-scope :session) :all-panes)))
(defun note-pane-output (session pane)
  (dolist (view (session-all-views session))
    (when (and (member pane (view-panes view)) (not (eql (pane-id pane) (view-focus-id view))))
      (setf (pane-view-unseen-output (pane-state view (pane-id pane))) t))))
(defun prune-view-pane (view id)
  (unless (or (gethash id (view-pane-states view)) (eql id (view-focus-id view)))
    (return-from prune-view-pane))
  (remhash id (view-pane-states view))
  (setf (view-layout-placements view)
        (remove id (view-layout-placements view) :key (lambda (p) (getf p :pane))))
  (when (eql (view-focus-id view) id)
    (setf (view-focus-id view) (and (first (view-panes view)) (pane-id (first (view-panes view))))))
  (reset-view-input view)
  (expire-pane-notes view)
  (incf (view-revision view)))
