(defpackage #:ekko/vt
  (:use #:cl)
  (:export #:make-terminal #:feed #:resize-terminal #:terminal-cols #:terminal-rows
           #:terminal-cw #:terminal-ch #:terminal-x #:terminal-y #:terminal-cells
           #:terminal-modes #:terminal-keyboards #:terminal-revision #:terminal-screen
           #:terminal-parser #:terminal-buffer #:terminal-visible #:terminal-title
           #:parameters))
(in-package #:ekko/vt)

(defstruct (terminal (:constructor %make-terminal))
  (cols 80) (rows 24) (cw 8) (ch 16) (x 0) (y 0) (saved '(0 0))
  cells main-cells history (screen :main) (top 0) (bottom 23) (visible t)
  (rendition '(0)) (modes (make-hash-table)) (keyboards '(0))
  (parser :ground) (buffer (make-array 0 :element-type '(unsigned-byte 8)
                                     :adjustable t :fill-pointer 0))
  (utf-code 0) (utf-left 0) (utf-min 0) (revision 0) (title ""))
(defun blank-cells (cols rows) (make-array (* cols rows) :initial-element '(" " (0))))
(defun make-terminal (&key (cols 80) (rows 24) (cw 8) (ch 16))
  (%make-terminal :cols cols :rows rows :cw cw :ch ch :bottom (1- rows)
                  :cells (blank-cells cols rows)))
(defun resize-terminal (vt cols rows cw ch)
  (labels ((resized (old)
             (when old
               (let ((cells (blank-cells cols rows)))
                 (loop for y below (min rows (terminal-rows vt)) do
                   (loop for x below (min cols (terminal-cols vt)) do
                     (let ((cell (aref old (+ x (* y (terminal-cols vt))))))
                       ;; Do not leave half a wide glyph at the new right edge.
                       (unless (and (= x (1- cols)) (plusp (length (first cell)))
                                    (= 2 (character-width (char (first cell) 0))))
                         (setf (aref cells (+ x (* y cols))) cell))))) cells))))
    (setf (terminal-cells vt) (resized (terminal-cells vt))
          (terminal-main-cells vt) (resized (terminal-main-cells vt))
          (terminal-cols vt) cols (terminal-rows vt) rows (terminal-cw vt) cw (terminal-ch vt) ch
          (terminal-top vt) 0 (terminal-bottom vt) (1- rows)
          (terminal-x vt) (min (terminal-x vt) (1- cols))
          (terminal-y vt) (min (terminal-y vt) (1- rows)))
    (incf (terminal-revision vt))))
(defun parameters (text &optional (separator #\;))
  (loop for start = 0 then (1+ end) for end = (position separator text :start start)
        for item = (subseq text start end)
        collect (if (zerop (length item)) 0 (or (parse-integer item :junk-allowed t) 0))
        while end))
(defun clear-range (vt start end)
  (fill (terminal-cells vt) (list " " (terminal-rendition vt)) :start start :end end)
  (incf (terminal-revision vt)))
(defun scroll-lines (vt amount emit)
  (let* ((cols (terminal-cols vt)) (cells (terminal-cells vt))
         (top (* cols (terminal-top vt))) (end (* cols (1+ (terminal-bottom vt))))
         (n (* cols (min (abs amount) (- (1+ (terminal-bottom vt)) (terminal-top vt))))))
    (when (and (plusp amount) (eq (terminal-screen vt) :main)
               (zerop (terminal-top vt)) (= (terminal-bottom vt) (1- (terminal-rows vt))))
      (loop for offset from 0 below n by cols do
        (remember-row vt (subseq cells offset (+ offset cols)))))
    (if (plusp amount)
        (progn (replace cells cells :start1 top :start2 (+ top n) :end2 end)
               (clear-range vt (- end n) end))
        (progn (replace cells cells :start1 (+ top n) :end1 end :start2 top :end2 (- end n))
               (clear-range vt top (+ top n)))))
  (funcall emit :scroll (list (terminal-top vt) (terminal-bottom vt) amount)))
(defun newline (vt emit)
  (if (= (terminal-y vt) (terminal-bottom vt)) (scroll-lines vt 1 emit)
      (setf (terminal-y vt) (min (1- (terminal-rows vt)) (1+ (terminal-y vt))))))
(defun character-width (char)
  (cond ((member (sb-unicode:general-category char) '(:mn :me :cf)) 0)
        ((member (sb-unicode:east-asian-width char) '(:w :f)) 2) (t 1)))
(defun put-character (vt char emit)
  (let* ((width (character-width char))
         (cols (terminal-cols vt)))
    (when (zerop width)
      (when (plusp (terminal-x vt))
        (let* ((index (+ (* cols (terminal-y vt)) (min (1- cols) (1- (terminal-x vt)))))
               (cell (aref (terminal-cells vt) index)))
          (setf (aref (terminal-cells vt) index)
                (list (concatenate 'string (first cell) (string char)) (second cell)))
          (incf (terminal-revision vt))))
      (return-from put-character))
    (when (> (+ (terminal-x vt) width) cols)
      (setf (terminal-x vt) 0) (newline vt emit))
    (when (<= width cols)
      (let ((index (+ (* cols (terminal-y vt)) (terminal-x vt))))
        (setf (aref (terminal-cells vt) index) (list (string char) (terminal-rendition vt)))
        (when (= width 2) (setf (aref (terminal-cells vt) (1+ index)) (list "" (terminal-rendition vt)))))
      (incf (terminal-x vt) width) (incf (terminal-revision vt)))))
(defun text-byte (vt byte emit)
  (cond
    ((plusp (terminal-utf-left vt))
     (if (<= #x80 byte #xbf)
         (progn
           (setf (terminal-utf-code vt) (+ (ash (terminal-utf-code vt) 6) (logand byte 63)))
           (when (zerop (decf (terminal-utf-left vt)))
             (let ((code (terminal-utf-code vt)))
               (put-character vt (if (and (<= (terminal-utf-min vt) code #x10ffff)
                                         (not (<= #xd800 code #xdfff)))
                                    (code-char code) #\Replacement_Character) emit))))
         (progn (setf (terminal-utf-left vt) 0)
                (put-character vt #\Replacement_Character emit) (text-byte vt byte emit))))
    ((< byte 128) (put-character vt (code-char byte) emit))
    ((<= #xc2 byte #xdf) (setf (terminal-utf-left vt) 1 (terminal-utf-code vt) (logand byte 31) (terminal-utf-min vt) #x80))
    ((<= #xe0 byte #xef) (setf (terminal-utf-left vt) 2 (terminal-utf-code vt) (logand byte 15) (terminal-utf-min vt) #x800))
    ((<= #xf0 byte #xf4) (setf (terminal-utf-left vt) 3 (terminal-utf-code vt) (logand byte 7) (terminal-utf-min vt) #x10000))
    (t (put-character vt #\Replacement_Character emit))))
(defun reply (emit control &rest args)
  (funcall emit :reply (apply #'format nil control args)))
(defun update-rendition (current args)
  (let ((state (make-hash-table)))
    (dolist (codes (list current args))
      (loop while codes for code = (pop codes) do
        (cond
          ((zerop code) (clrhash state))
          ((member code '(38 48 58))
           (let* ((mode (pop codes)) (count (case mode (2 3) (5 1))))
             (when (and count (>= (length codes) count))
               (let ((values (loop repeat count collect (pop codes))))
                 (when (every (lambda (n) (<= 0 n 255)) values)
                   (setf (gethash code state) (append (list code mode) values)))))))
          ((or (<= 30 code 37) (<= 90 code 97)) (setf (gethash 38 state) (list code)))
          ((or (<= 40 code 47) (<= 100 code 107)) (setf (gethash 48 state) (list code)))
          ((member code '(39 49 59)) (remhash (1- code) state))
          ((member code '(22 23 24 25 27 28 29 55))
           (dolist (key (case code (22 '(1 2)) (23 '(3)) (24 '(4 21)) (25 '(5))
                                  (27 '(7)) (28 '(8)) (29 '(9)) (55 '(53)))) (remhash key state)))
          ((member code '(1 2 3 4 5 7 8 9 21 53)) (setf (gethash code state) (list code))))))
    (cons 0 (loop for key in (sort (loop for key being the hash-keys of state collect key) #'<)
                  append (gethash key state)))))
(defun csi (vt text emit)
  (let* ((final (char text (1- (length text)))) (body (subseq text 0 (1- (length text))))
         (private (and (plusp (length body)) (find (char body 0) "?<>=!")))
         (args (parameters (if private (subseq body 1) body)))
         (n (max 1 (first args))) (cols (terminal-cols vt)) (rows (terminal-rows vt))
         (cursor (+ (* cols (terminal-y vt)) (min (terminal-x vt) (1- cols))))
         (esc (code-char 27)))
    (case final
      ((#\H #\f) (setf (terminal-y vt) (min (1- rows) (1- n))
                          (terminal-x vt) (min (1- cols) (max 0 (1- (or (second args) 1))))))
      (#\A (setf (terminal-y vt) (max 0 (- (terminal-y vt) n))))
      ((#\B #\e) (setf (terminal-y vt) (min (1- rows) (+ (terminal-y vt) n))))
      ((#\C #\a) (setf (terminal-x vt) (min (1- cols) (+ (terminal-x vt) n))))
      (#\D (setf (terminal-x vt) (max 0 (- (terminal-x vt) n))))
      (#\G (setf (terminal-x vt) (min (1- cols) (1- n))))
      (#\d (setf (terminal-y vt) (min (1- rows) (1- n))))
      (#\J (case (first args)
              (0 (clear-range vt cursor (* cols rows)))
              (1 (clear-range vt 0 (1+ cursor)))
              ((2 3) (clear-range vt 0 (* cols rows)))))
      (#\K (let ((start (* cols (terminal-y vt))))
              (case (first args) (0 (clear-range vt cursor (+ start cols)))
                    (1 (clear-range vt start (1+ cursor))) (2 (clear-range vt start (+ start cols))))))
      (#\X (clear-range vt cursor (min (+ cursor n) (* cols (1+ (terminal-y vt))))))
      ((#\P #\@)
       (let ((end (* cols (1+ (terminal-y vt)))) (cells (terminal-cells vt)))
         (setf n (min n (- end cursor)))
         (if (char= final #\P)
             (progn (replace cells cells :start1 cursor :start2 (+ cursor n) :end2 end)
                    (clear-range vt (- end n) end))
             (progn (replace cells cells :start1 (+ cursor n) :end1 end :start2 cursor :end2 (- end n))
                    (clear-range vt cursor (+ cursor n))))))
      ((#\S #\T) (scroll-lines vt (if (char= final #\S) n (- n)) emit))
      ((#\L #\M)
       (when (<= (terminal-top vt) (terminal-y vt) (terminal-bottom vt))
         (let ((old (terminal-top vt)))
           (setf (terminal-top vt) (terminal-y vt))
           (scroll-lines vt (if (char= final #\M) n (- n)) emit)
           (setf (terminal-top vt) old))))
      (#\r (let ((bottom (if (plusp (or (second args) 0)) (second args) rows)))
              (when (< n bottom (1+ rows))
                (setf (terminal-top vt) (1- n) (terminal-bottom vt) (1- bottom)
                      (terminal-x vt) 0 (terminal-y vt) 0))))
      (#\m (unless private
              (setf (terminal-rendition vt) (update-rendition (terminal-rendition vt) args))))
      ((#\h #\l)
       (when (eql private #\?)
         (dolist (mode args)
           (let ((on (char= final #\h)))
             (setf (gethash mode (terminal-modes vt)) on)
             (case mode
               (25 (setf (terminal-visible vt) on))
               ((47 1047 1049)
                (cond ((and on (eq (terminal-screen vt) :main))
                       (setf (terminal-main-cells vt) (terminal-cells vt)
                             (terminal-saved vt) (list (terminal-x vt) (terminal-y vt))
                             (terminal-cells vt) (blank-cells cols rows) (terminal-screen vt) :alternate
                             (terminal-x vt) 0 (terminal-y vt) 0))
                      ((and (not on) (eq (terminal-screen vt) :alternate))
                       (setf (terminal-cells vt) (or (terminal-main-cells vt) (blank-cells cols rows))
                             (terminal-main-cells vt) nil (terminal-screen vt) :main
                             (terminal-x vt) (min (1- cols) (first (terminal-saved vt)))
                             (terminal-y vt) (min (1- rows) (second (terminal-saved vt))))))
                (funcall emit :screen (terminal-screen vt)) (incf (terminal-revision vt))))))))
      (#\p (when (and (eql private #\?) (find #\$ body))
              (reply emit "~C[?~D;~D$y" esc (first args)
                     (cond ((member (first args) '(1000 1002 1003 1004 1006 1016 2004 2026))
                            (if (gethash (first args) (terminal-modes vt)) 1 2)) (t 0)))))
      (#\u (case private
              (#\? (reply emit "~C[?~Du" esc (first (terminal-keyboards vt))))
              (#\> (when (< (length (terminal-keyboards vt)) 16) (push (first args) (terminal-keyboards vt))))
              (#\< (dotimes (i (min n (1- (length (terminal-keyboards vt))))) (pop (terminal-keyboards vt))))
              (#\= (setf (first (terminal-keyboards vt)) (first args)))
              (otherwise (setf (terminal-x vt) (first (terminal-saved vt)) (terminal-y vt) (second (terminal-saved vt))))))
      (#\s (setf (terminal-saved vt) (list (terminal-x vt) (terminal-y vt))))
      (#\n (case (first args) (5 (reply emit "~C[0n" esc))
                  (6 (reply emit "~C[~D;~DR" esc (1+ (terminal-y vt)) (1+ (min (1- cols) (terminal-x vt)))))))
      (#\c (reply emit (if (eql private #\>) "~C[>0;1;0c" "~C[?62;22c") esc))
      (#\t (case (first args)
              (14 (reply emit "~C[4;~D;~Dt" esc (* rows (terminal-ch vt)) (* cols (terminal-cw vt))))
              (16 (reply emit "~C[6;~D;~Dt" esc (terminal-ch vt) (terminal-cw vt)))
              (18 (reply emit "~C[8;~D;~Dt" esc rows cols)))))))
(defun osc (vt bytes emit)
  (let* ((text (handler-case (ekko/platform:bytes-text bytes) (error () "")))
         (semi (position #\; text)))
    (when semi
      (let ((code (parse-integer text :end semi :junk-allowed t)) (body (subseq text (1+ semi))) (esc (code-char 27)))
        (cond ((and (member code '(10 11)) (string= body "?"))
               (reply emit "~C]~D;rgb:~A~C\\" esc code (if (= code 10) "dddd/dddd/dddd" "1111/1515/1b1b") esc))
              ((and (eql code 4) (search ";?" body))
               (let ((index (parse-integer body :junk-allowed t)))
                 (when (and index (<= 0 index 255)) (reply emit "~C]4;~D;rgb:8888/8888/8888~C\\" esc index esc))))
              ((member code '(0 2))
               (setf (terminal-title vt) (subseq (remove-if (lambda (c) (< (char-code c) 32)) body) 0 (min 120 (length (remove-if (lambda (c) (< (char-code c) 32)) body)))))))))))
(defun feed (vt bytes emit)
  (declare (optimize (speed 3) (safety 2))
           (type (vector (unsigned-byte 8)) bytes))
  (labels ((reset-parser () (setf (terminal-parser vt) :ground (fill-pointer (terminal-buffer vt)) 0))
           (append-byte (b limit discard)
             (if (< (length (terminal-buffer vt)) limit) (vector-push-extend b (terminal-buffer vt))
                 (setf (terminal-parser vt) discard (fill-pointer (terminal-buffer vt)) 0)))
           (end-string (kind)
             (case kind (:osc (osc vt (terminal-buffer vt) emit))
                   (:apc (funcall emit :graphics (copy-seq (terminal-buffer vt)))))
             (reset-parser)))
    (loop for index from 0 below (length bytes) for byte = (aref bytes index) do
      (case (terminal-parser vt)
        (:ground
         (case byte
           (27 (setf (terminal-parser vt) :escape))
           ((10 11 12) (newline vt emit))
           (13 (setf (terminal-x vt) 0))
           (8 (setf (terminal-x vt) (max 0 (1- (terminal-x vt)))))
           (9 (setf (terminal-x vt) (min (1- (terminal-cols vt)) (* 8 (1+ (floor (terminal-x vt) 8))))))
           (otherwise (when (>= byte 32) (unless (= byte 127) (text-byte vt byte emit))))))
        (:escape
         (reset-parser)
         (case byte
           (91 (setf (terminal-parser vt) :csi)) (93 (setf (terminal-parser vt) :osc))
           (95 (setf (terminal-parser vt) :apc)) ((80 94 88) (setf (terminal-parser vt) :discard))
           ((40 41 42 43 35) (setf (terminal-parser vt) :charset))
           (55 (setf (terminal-saved vt) (list (terminal-x vt) (terminal-y vt))))
           (56 (setf (terminal-x vt) (first (terminal-saved vt)) (terminal-y vt) (second (terminal-saved vt))))
           (68 (newline vt emit)) (69 (setf (terminal-x vt) 0) (newline vt emit))
           (77 (if (= (terminal-y vt) (terminal-top vt)) (scroll-lines vt -1 emit) (setf (terminal-y vt) (max 0 (1- (terminal-y vt))))))
           (99 (clear-range vt 0 (length (terminal-cells vt))) (setf (terminal-x vt) 0 (terminal-y vt) 0) (funcall emit :reset nil))))
        (:charset (reset-parser))
        (:csi
         (cond ((= byte 27) (setf (terminal-parser vt) :escape (fill-pointer (terminal-buffer vt)) 0))
               ((<= 64 byte 126)
                (append-byte byte 1024 :discard-csi)
                (unless (eq (terminal-parser vt) :discard-csi)
                  (csi vt (map 'string #'code-char (terminal-buffer vt)) emit)) (reset-parser))
               ((<= 32 byte 63) (append-byte byte 1024 :discard-csi))))
        (:discard-csi (when (<= 64 byte 126) (reset-parser)))
        (:apc
         ;; Graphics payloads are ASCII runs terminated by ESC. Copy each run
         ;; once, retaining the same control-string limit and split-ST state.
         (let* ((end (or (position 27 bytes :start index) (length bytes)))
                (buffer (terminal-buffer vt))
                (used (length buffer)) (required (+ used (- end index)))
                (overflow (> required 16384)))
           (if overflow
               (setf (fill-pointer buffer) 0 (terminal-parser vt) :discard)
               (progn
                 (when (> required (array-total-size buffer))
                   (setf buffer (adjust-array buffer (min 16384 (max required (* 2 (array-total-size buffer)))))
                         (terminal-buffer vt) buffer))
                 (setf (fill-pointer buffer) required)
                 (replace buffer bytes :start1 used :start2 index :end2 end)))
           (if (< end (length bytes))
               (setf index end (terminal-parser vt) (if overflow :discard-escape :apc-escape))
               (setf index (1- end)))))
        ((:osc :discard)
         (cond ((= byte 27) (setf (terminal-parser vt) (case (terminal-parser vt) (:osc :osc-escape) (:apc :apc-escape) (t :discard-escape))))
               ((and (= byte 7) (eq (terminal-parser vt) :osc)) (end-string :osc))
               ((not (eq (terminal-parser vt) :discard)) (append-byte byte 16384 :discard))))
        ((:osc-escape :apc-escape :discard-escape)
         (if (= byte 92)
             (end-string (case (terminal-parser vt) (:osc-escape :osc) (:apc-escape :apc)))
             (setf (terminal-parser vt) :discard)))))))
