(in-package #:ekko/runtime)

;; Geometry and gesture state belong to the daemon. Profiles declare which
;; spans are handles; applications retain their ordinary mouse protocol.
(defstruct window-drag owner pane kind x y from preview target edge moved split tree)

(defun tiled-border-split (tree rectangles pane edge)
  "Find the actual visible split at PANE's edge, retaining its full-tree node.
Hidden leaves have no rectangles, so restoring them keeps their own ratios."
  (let ((rect (cdr (assoc pane rectangles))))
    (labels ((bounds (node)
               (let ((rects (loop for id in (layout-pane-ids node)
                                  for r = (cdr (assoc id rectangles)) when r collect r)))
                 (when rects
                   (list (reduce #'min rects :key #'first) (reduce #'min rects :key #'second)
                         (reduce #'max rects :key (lambda (r) (+ (first r) (third r))))
                         (reduce #'max rects :key (lambda (r) (+ (second r) (fourth r))))))))
             (walk (node)
               (unless (integerp node)
                 (or (walk (third node)) (walk (fourth node))
                     (let* ((columns (eq (first node) :columns))
                            (index (if columns 0 1))
                            (a (bounds (third node))) (b (bounds (fourth node)))
                            (before (member edge '(:right :bottom)))
                            (side (if before (third node) (fourth node))))
                       (when (and a b (member pane (layout-pane-ids side))
                                  (if columns (member edge '(:left :right)) (member edge '(:top :bottom)))
                                  (= (+ (nth index rect) (if before (nth (+ index 2) rect) 0))
                                     (if before (nth (+ index 2) a) (nth index b))))
                         (let ((cut (- (nth (+ index 2) a) (nth index a))))
                           (list node (+ cut (- (nth (+ index 2) b) (nth index b))) cut))))))))
      (when rect (walk tree)))))

(defun window-resize-split (session pane kind)
  (unless (or (pane-floating pane) (session-zoom session) (eq kind :move))
    (tiled-border-split (session-tree session)
                       (remove-if (lambda (r) (pane-floating (pane-by-id session (first r))))
                                  (session-rectangles session))
                       (pane-id pane) kind)))
(defun window-intersects-p (pane x y &optional (width 1))
  (and pane (< (pane-outer-x pane) (+ x width))
       (< x (+ (pane-outer-x pane) (pane-outer-cols pane)))
       (<= (pane-outer-y pane) y) (< y (+ (pane-outer-y pane) (pane-outer-rows pane)))))
(defun window-at (session x y)
  (find-if (lambda (p) (window-intersects-p p x y)) (reverse (visible-panes session))))
(defun begin-window-drag (session owner span x y)
  (let ((pane (pane-by-id session (getf span :pane))))
    (when pane
      (let* ((kind (getf span :drag)) (split (window-resize-split session pane kind)))
        (set-focus session (position pane (session-panes session)))
        (unless (or (eq kind :move) (pane-floating pane) split)
          (setf (session-chrome-press session) :dismiss)
          (return-from begin-window-drag))
        (setf (session-window-drag session)
              (make-window-drag :owner owner :pane pane :kind kind :x x :y y :split split
                                :tree (session-tree session)
                                :from (pane-outer-rect pane) :preview (pane-outer-rect pane)))))))

(defun tiled-drag-tree (drag dx dy)
  (destructuring-bind (node available cut) (window-drag-split drag)
    (let* ((delta (if (eq (first node) :columns) dx dy))
           (ratio (max 1 (min 99 (ceiling (* 100 (+ cut delta)) available)))))
      (if (zerop delta) (window-drag-tree drag)
          (subst (list (first node) ratio (third node) (fourth node)) node
                 (window-drag-tree drag) :test #'eq)))))

(defun tiled-drag-rectangles (session drag dx dy)
  (session-rectangles session nil (tiled-tree session (tiled-drag-tree drag dx dy))))
(defun drag-snap-target (session drag x y)
  (let ((target (find-if (lambda (p) (and (not (eq p (window-drag-pane drag)))
                                         (not (pane-floating p)) (window-intersects-p p x y)))
                         (reverse (visible-panes session)))))
    (when target
      (destructuring-bind (ox oy w h) (pane-outer-rect target)
        (let ((edge (cond ((< (- x ox) (max 2 (floor w 5))) :left)
                          ((< (- (+ ox w) x) (max 2 (floor w 5))) :right)
                          ((< (- y oy) (max 2 (floor h 5))) :top)
                          ((< (- (+ oy h) y) (max 2 (floor h 5))) :bottom)
                          ((not (pane-floating (window-drag-pane drag))) :center))))
          (when edge
            (values target edge
              (case edge
                (:left (list ox oy (max 1 (floor w 2)) h))
                (:right (list (+ ox (floor w 2)) oy (- w (floor w 2)) h))
                (:top (list ox oy w (max 1 (floor h 2))))
                (:bottom (list ox (+ oy (floor h 2)) w (- h (floor h 2))))
                (otherwise (pane-outer-rect target))))))))))
(defun viewport-snap-rect (session x y)
  "Content-area snap at the outermost cell: the top edge maximizes, the sides take a half."
  (multiple-value-bind (viewport pane gaps width height) (session-geometry session)
    (declare (ignore pane gaps))
    (let* ((left (fourth viewport)) (top (first viewport))
           (right (+ left width)) (half (max 12 (floor width 2))))
      (cond ((<= y top) (list left top width height))
            ((<= x left) (list left top half height))
            ((>= x (1- right)) (list (- right half) top half height))
            (t nil)))))
(defun floating-drag-rect (session drag dx dy)
  (destructuring-bind (ox oy w h) (window-drag-from drag)
    (let ((kind (window-drag-kind drag)))
      (if (eq kind :move)
          (clamp-window-rect session (list (+ ox dx) (+ oy dy) w h))
          (multiple-value-bind (viewport pane gaps width height) (session-geometry session)
            (declare (ignore pane gaps))
            (let* ((left (member kind '(:left :top-left :bottom-left)))
                   (right (member kind '(:right :top-right :bottom-right)))
                   (top (member kind '(:top :top-left :top-right)))
                   (bottom (member kind '(:bottom :bottom-left :bottom-right)))
                   (minw (min width 12)) (minh (min height 4))
                   (dx (cond (left (max (- (fourth viewport) ox) (min dx (- w minw))))
                             (right (max (- minw w) (min dx (- (+ (fourth viewport) width) ox w))))
                             (t 0)))
                   (dy (cond (top (max (- (first viewport) oy) (min dy (- h minh))))
                             (bottom (max (- minh h) (min dy (- (+ (first viewport) height) oy h))))
                             (t 0))))
              (list (if left (+ ox dx) ox) (if top (+ oy dy) oy)
                    (if left (- w dx) (+ w dx)) (if top (- h dy) (+ h dy)))))))))

(defun window-drag-mouse (session button x y up)
  (let ((drag (session-window-drag session)))
    (when drag
      (let ((dx (- x (window-drag-x drag))) (dy (- y (window-drag-y drag))))
        (when (or (window-drag-moved drag)
                  (>= (+ (abs dx) (abs dy)) (if (eq (window-drag-kind drag) :move) 2 1)))
          (setf (window-drag-moved drag) t)
          (if (window-drag-split drag)
              (setf (window-drag-preview drag)
                    (tiled-drag-rectangles session drag dx dy))
              (progn
                (setf (window-drag-target drag) nil (window-drag-edge drag) nil
                      (window-drag-preview drag) (floating-drag-rect session drag dx dy))
                (when (eq (window-drag-kind drag) :move)
                  (let ((snap (viewport-snap-rect session x y)))
                    (if snap
                        (setf (window-drag-target drag) nil (window-drag-edge drag) nil
                              (window-drag-preview drag) snap)
                        (multiple-value-bind (target edge preview) (drag-snap-target session drag x y)
                          (when target
                            (setf (window-drag-target drag) target (window-drag-edge drag) edge
                                  (window-drag-preview drag) preview))))))))
          (incf (session-revision session)))
        (when up
          (setf (session-window-drag session) nil)
          (when (and (not (window-drag-moved drag)) (= (logand button 3) 0)
                     (eq (window-drag-kind drag) :move))
            (let* ((id (pane-id (window-drag-pane drag))) (last (session-last-click session))
                   (again (and last (eql (car last) id) (< (- (now) (cdr last)) 0.4))))
              (if again
                  (progn (setf (session-last-click session) nil)
                         (handler-case
                             (apply-actions session (window-drag-owner drag)
                                            (list (list :zoom :pane id)) nil nil)
                           (error (e) (note-error session e))))
                  (setf (session-last-click session) (cons id (now))))))
          (when (and (= (logand button 3) 0) (window-drag-moved drag))
            (handler-case
                (apply-actions session (window-drag-owner drag)
                  (list (cond ((window-drag-split drag)
                               (list :set-layout :tree (tiled-drag-tree drag dx dy)))
                              ((window-drag-target drag)
                               (list :place-window :pane (pane-id (window-drag-pane drag))
                                     :target (pane-id (window-drag-target drag)) :edge (window-drag-edge drag)))
                              (t (list :float :pane (pane-id (window-drag-pane drag))
                                       :rect (window-drag-preview drag)))))
                  nil nil)
              (error (e) (note-error session e))))
          (incf (session-revision session))))
      t)))
(defun outline-spans (rect sgr)
  (destructuring-bind (x y w h) rect
    (append (list (list x y (make-string w :initial-element #\─) sgr))
            (when (> h 1) (list (list x (+ y h -1) (make-string w :initial-element #\─) sgr)))
            (loop for row from (1+ y) below (+ y h -1)
                  append (list (list x row "│" sgr) (list (+ x w -1) row "│" sgr))))))
(defun filled-rect-spans (rect sgr)
  (destructuring-bind (x y width height) rect
    (when (and (plusp width) (plusp height))
      (loop for row from y below (+ y height)
            collect (list x row (make-string width :initial-element #\Space) sgr)))))
(defun window-drag-overlays (session)
  (let ((drag (session-window-drag session)))
    (when (and drag (window-drag-moved drag))
      (graphics-safe-outlines session
        (if (window-drag-split drag)
            (loop for (id . rect) in (window-drag-preview drag)
                  unless (equal rect (pane-outer-rect (pane-by-id session id)))
                  append (outline-spans rect '(0 1 38 5 117 48 5 235)))
            (let ((rect (window-drag-preview drag))
                  (sgr (if (window-drag-target drag) '(0 1 38 5 117 48 5 235) '(0 38 5 250 48 5 235))))
              (append (filled-rect-spans rect '(0 48 5 236))
                      (outline-spans rect sgr))))
        (when (window-drag-split drag) (remove-if-not #'pane-floating (visible-panes session)))))))

(defun update-window-hover (session button x y up)
  (let ((hover
          (when (and (= button 35) (not up) (not (session-popup session))
                     (not (session-window-drag session)) (not (session-drag session)))
            (multiple-value-bind (span owner) (decoration-at session x y)
              (when (and span owner
                         (or (getf span :hover-sgr)
                             (let ((pane (pane-by-id session (getf span :pane))))
                               (and pane (getf span :drag) (not (eq (getf span :drag) :move))
                                    (or (pane-floating pane)
                                        (window-resize-split session pane (getf span :drag)))))))
                (list owner span))))))
    (unless (equal hover (session-window-hover session))
      (setf (session-window-hover session) hover)
      (incf (session-revision session)))))

(defun expand-span-rows (span)
  (loop for row from (getf span :y) below (+ (getf span :y) (getf span :rows 1))
        collect (list (getf span :x) row (getf span :text) (getf span :sgr))))
(defun window-hover-overlays (session)
  (destructuring-bind (&optional owner span) (session-window-hover session)
    (let* ((spans (cdr (assoc owner (session-decorations session) :test #'equal)))
           (pane (pane-by-id session (getf span :pane)))
           (occluders (and pane (rest (member pane (visible-panes session)))))
           (hover (getf span :hover-sgr)))
      (when (and span (member span spans :test #'equal) (not (session-popup session)))
        (graphics-safe-outlines session
          (loop for (x y text sgr) in (expand-span-rows span)
                collect (list x y text (or hover '(0 1 38 5 117 48 5 235))))
          occluders)))))

(defun graphics-safe-outlines (session spans &optional occluders)
  ;; Transient strokes leave image placements intact; committed floating
  ;; geometry and menus still occlude images normally.
  (let ((graphics (remove-if-not
                   (lambda (p) (loop for image being the hash-values of (store-images (pane-graphics p))
                                     thereis (image-visible image))) (visible-panes session))))
    (loop for (x y text sgr) in spans append
      (clip-decoration session graphics (list :x x :y y :text text :sgr sgr) occluders))))
