(defpackage #:ekko/runtime
  (:use #:cl #:ekko/platform #:ekko/vt #:ekko/graphics)
  (:export #:run #:serve #:attach #:control #:restore-terminal #:extension-worker-main #:initialize #:config-path #:load-worker #:config-source #:install-registry #:make-daemon #:extension-worker-registry #:stop-worker #:*instance* #:*bare* #:checked-name #:note-client-error #:version-mismatch-p #:emergency-restore))
(in-package #:ekko/runtime)

;; Version 16 removes session routing: one daemon hosts one workspace and every
;; peer attaches to it. Input transactions stay bound to connection generations
;; and pane identities remain daemon-global.
(defconstant +wire-version+ 18)
(defvar *instance* "default")
(defvar *bare* nil)
(defconstant +queue-limit+ (* 8 1024 1024))
(define-condition wire-protocol-error (simple-error) ())
(defun reject-protocol (message)
  (error 'wire-protocol-error :format-control message :format-arguments nil))
(defstruct wire fd (version +wire-version+) (packet-limit +queue-limit+) (queue nil) (queue-tail nil) (queued 0) (offset 0) (prefix (octets 4))
  (prefix-used 0) body (body-used 0) (known (make-hash-table :test 'equal))
  greeted selected-view-id view closing
  (binding-generation 0) binding-accepted
  attached revision awaiting-scene (frame-due 0) deferred (leases nil) (at (now)))
(defun u32 (bytes offset)
  (+ (ash (aref bytes offset) 24) (ash (aref bytes (+ offset 1)) 16)
     (ash (aref bytes (+ offset 2)) 8) (aref bytes (+ offset 3))))
(defun put-u32 (bytes offset value)
  (dotimes (i 4) (setf (aref bytes (+ offset i)) (ldb (byte 8 (* 8 (- 3 i))) value))))
(defun integers (values)
  (let ((out (octets (* 4 (length values)))))
    (loop for value in values for offset from 0 by 4 do (put-u32 out offset value)) out))
(defun queue-bytes (wire data)
  (when (> (+ (wire-queued wire) (length data)) +queue-limit+) (error "Output queue limit exceeded"))
  (let ((cell (list data)))
    (if (wire-queue-tail wire)
        (setf (rest (wire-queue-tail wire)) cell)
        (setf (wire-queue wire) cell))
    (setf (wire-queue-tail wire) cell))
  (incf (wire-queued wire) (length data)))
(defun send-packet (wire type &optional (data (octets 0)))
  (let ((packet (octets (+ 5 (length data)))))
    (put-u32 packet 0 (1+ (length data))) (setf (aref packet 4) type)
    (replace packet data :start1 5) (queue-bytes wire packet)))
(defun flush-wire (wire)
  (loop repeat 16 while (wire-queue wire) for data = (first (wire-queue wire))
        for n = (write-fd (wire-fd wire) data (wire-offset wire)) do
    (cond ((member n '(-11 -4)) (return)) ((<= n 0) (error "Output disconnected"))
          (t (incf (wire-offset wire) n) (decf (wire-queued wire) n)
             (when (= (wire-offset wire) (length data))
               (pop (wire-queue wire))
               (when (null (wire-queue wire)) (setf (wire-queue-tail wire) nil))
               (setf (wire-offset wire) 0))))))
(defun wire-feed (wire bytes count)
  (let ((offset 0) (packets nil))
    (loop while (< offset count) do
      (if (wire-body wire)
          (let ((n (min (- count offset) (- (length (wire-body wire)) (wire-body-used wire)))))
            (replace (wire-body wire) bytes :start1 (wire-body-used wire) :start2 offset :end2 (+ offset n))
            (incf offset n) (incf (wire-body-used wire) n)
            (when (= (wire-body-used wire) (length (wire-body wire)))
              (push (wire-body wire) packets)
              (setf (wire-body wire) nil (wire-body-used wire) 0 (wire-prefix-used wire) 0)))
          (let ((n (min (- count offset) (- 4 (wire-prefix-used wire)))))
            (replace (wire-prefix wire) bytes :start1 (wire-prefix-used wire) :start2 offset :end2 (+ offset n))
            (incf offset n) (incf (wire-prefix-used wire) n)
            (when (= (wire-prefix-used wire) 4)
              (let ((size (u32 (wire-prefix wire) 0)))
                (unless (<= 1 size (wire-packet-limit wire)) (error "Invalid IPC frame size"))
                (setf (wire-body wire) (octets size)))))))
    (nreverse packets)))
(defun receive-packets (wire buffer)
  (let ((n (read-fd (wire-fd wire) buffer)))
    (cond ((member n '(-11 -4)) nil) ((<= n 0) (error "Input disconnected"))
          (t (setf (wire-at wire) (now)) (wire-feed wire buffer n)))))
(defun wire-events (wire) (logior 1 (if (wire-queue wire) 4 0)))
(defun acknowledge-scene (wire)
  (dolist (asset (wire-leases wire)) (release-asset asset))
  (setf (wire-leases wire) nil (wire-awaiting-scene wire) nil))
(defun close-wire (wire) (close-fd (wire-fd wire)) (setf (wire-fd wire) -1)
  (setf (wire-queue wire) nil (wire-queue-tail wire) nil (wire-body wire) nil)
  (clrhash (wire-known wire)) (acknowledge-scene wire))
(defun checked-name (name &optional (kind "Instance"))
  (unless (and (stringp name) (<= 1 (length name) 40)
               (every (lambda (c) (or (find c "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789")
                                     (find c "_-"))) name))
    (error "~A names must contain 1–40 ASCII letters, digits, underscores or hyphens" kind))
  name)
(defun socket-path ()
  (checked-name *instance* "Instance")
  (let* ((base (uiop:getenv "XDG_RUNTIME_DIR"))
         (dir (if (and base (plusp (length base)))
                  (format nil "~A/ekko/" (string-right-trim "/" base))
                  (format nil "/tmp/ekko-~D/" (sb-posix:getuid)))))
    (ensure-directories-exist dir)
    (let ((st (sb-posix:lstat (string-right-trim "/" dir))))
      (unless (and (= (sb-posix:stat-uid st) (sb-posix:getuid))
                   (sb-posix:s-isdir (sb-posix:stat-mode st))) (error "Unsafe daemon directory")))
    (sb-posix:chmod dir #o700)
    (format nil "~A~A.sock" dir (if (string= *instance* "default") "ekko"
                                   (concatenate 'string "instance-" *instance*)))))
(defun send-route (wire &optional view-id)
  (send-packet wire 0 (encode-scene (list +wire-version+ view-id))))
(defun standard-text (value)
  (with-standard-io-syntax (let ((*print-readably* t) (*print-pretty* nil)) (write-to-string value))))
(defun plain-keyword-p (symbol)
  (let ((name (symbol-name symbol)))
    (and (keywordp symbol) (plusp (length name)) (char<= #\A (char name 0) #\Z)
         (every (lambda (c) (or (char<= #\A c #\Z) (char<= #\0 c #\9) (char= c #\-))) name))))
(defstruct (sink (:constructor make-sink ())) (bytes (octets 4096) :type (simple-array (unsigned-byte 8) (*)))
  (fill 0 :type fixnum))
(declaim (inline sink-byte))
(defun sink-byte (sink byte)
  (let ((bytes (sink-bytes sink)) (fill (sink-fill sink)))
    (when (= fill (length bytes))
      (setf bytes (replace (octets (* 2 (length bytes))) bytes) (sink-bytes sink) bytes))
    (setf (aref bytes fill) byte (sink-fill sink) (1+ fill))))
(defun sink-char (sink char)
  (let ((code (char-code char)))
    (cond ((< code #x80) (sink-byte sink code))
          ((< code #x800) (sink-byte sink (logior #xc0 (ash code -6))) (sink-byte sink (logior #x80 (logand code #x3f))))
          ((<= #xd800 code #xdfff) (error "Unable to encode character ~D as :UTF-8." code))
          ((< code #x10000) (sink-byte sink (logior #xe0 (ash code -12)))
           (sink-byte sink (logior #x80 (logand (ash code -6) #x3f))) (sink-byte sink (logior #x80 (logand code #x3f))))
          (t (sink-byte sink (logior #xf0 (ash code -18))) (sink-byte sink (logior #x80 (logand (ash code -12) #x3f)))
             (sink-byte sink (logior #x80 (logand (ash code -6) #x3f))) (sink-byte sink (logior #x80 (logand code #x3f)))))))
(defun sink-text (sink string)
  (loop for char across string do (sink-char sink char)))
(defun sink-decimal (sink n)
  (declare (type (signed-byte 62) n))
  (when (minusp n) (sink-byte sink 45) (setf n (- n)))
  (if (< n 10) (sink-byte sink (+ 48 n))
      (multiple-value-bind (high low) (floor n 10) (sink-decimal sink high) (sink-byte sink (+ 48 low)))))
(defun sink-octets (sink) (subseq (sink-bytes sink) 0 (sink-fill sink)))
(defvar *scene-sink* (make-sink))
(defun encode-scene (scene)
  "SCENE as the UTF-8 bytes WRITE-TO-STRING prints it with standard, readable syntax."
  (let ((sink *scene-sink*))
    (setf (sink-fill sink) 0)
    (labels ((emit (value)
               (typecase value
                 (null (sink-text sink "NIL"))
                 (cons (sink-byte sink 40)
                  (loop (emit (car value))
                        (setf value (cdr value))
                        (cond ((null value) (return))
                              ((consp value) (sink-byte sink 32))
                              (t (sink-text sink " . ") (emit value) (return))))
                  (sink-byte sink 41))
                 ((signed-byte 62) (sink-decimal sink value))
                 (simple-string (sink-byte sink 34)
                  (loop for char across value
                        do (when (or (char= char #\") (char= char #\\)) (sink-byte sink 92)) (sink-char sink char))
                  (sink-byte sink 34))
                 (symbol (cond ((eq value t) (sink-byte sink 84))
                               ((plain-keyword-p value) (sink-byte sink 58) (sink-text sink (symbol-name value)))
                               (t (sink-text sink (standard-text value)))))
                 (t (sink-text sink (standard-text value))))))
      (emit scene)
      (sink-octets sink))))
(defun decode-scene (bytes)
  "Read the one datum in BYTES as READ-FROM-STRING does with standard syntax and no #. evaluation."
  (when (> (length bytes) (* 1024 1024)) (error "Scene metadata too large"))
  (let ((value (read-plain-datum bytes)))
    (if (eq value :fallback)
        (with-standard-io-syntax (let ((*read-eval* nil)) (read-from-string (bytes-text bytes))))
        value)))
(defun read-plain-datum (bytes)
  "The datum in BYTES when it is only lists, fixnums, strings, NIL, T and plain
keywords over well-formed UTF-8; :FALLBACK for anything else."
  (declare (optimize (speed 3) (safety 1)))
  (let* ((bytes (coerce bytes '(simple-array (unsigned-byte 8) (*)))) (end (length bytes)) (pos 0))
    (declare (type (simple-array (unsigned-byte 8) (*)) bytes) (type fixnum end pos))
    (macrolet ((fail () '(return-from read-plain-datum :fallback)))
      (labels ((space-p (byte) (declare (type (unsigned-byte 8) byte)) (or (= byte 32) (<= 9 byte 10) (<= 12 byte 13)))
               (delimiter-p (byte)
                 (declare (type (unsigned-byte 8) byte))
                 (or (space-p byte) (= byte 40) (= byte 41) (= byte 34) (= byte 59) (= byte 39) (= byte 96) (= byte 44)))
               (skip (at) (declare (type fixnum at))
                 (loop while (and (< at end) (space-p (aref bytes at))) do (incf at)) at)
               (tail-byte (at) (declare (type fixnum at))
                 (if (< at end)
                     (let ((byte (aref bytes at))) (if (= (logand byte #xc0) #x80) (logand byte #x3f) (fail)))
                     (fail)))
               (code-at (at)
                 (declare (type fixnum at))
                 (let ((lead (aref bytes at)))
                   (cond ((< lead #x80) (values lead (+ at 1)))
                         ((<= #xc2 lead #xdf) (values (logior (ash (logand lead #x1f) 6) (tail-byte (+ at 1))) (+ at 2)))
                         ((<= #xe0 lead #xef)
                          (let ((code (logior (ash (logand lead #x0f) 12) (ash (tail-byte (+ at 1)) 6) (tail-byte (+ at 2)))))
                            (when (or (< code #x800) (<= #xd800 code #xdfff)) (fail))
                            (values code (+ at 3))))
                         ((<= #xf0 lead #xf4)
                          (let ((code (logior (ash (logand lead #x07) 18) (ash (tail-byte (+ at 1)) 12)
                                              (ash (tail-byte (+ at 2)) 6) (tail-byte (+ at 3)))))
                            (unless (<= #x10000 code #x10ffff) (fail))
                            (values code (+ at 4))))
                         (t (fail)))))
               (read-string ()
                 (let ((at pos) (count 0) (plain t))
                   (declare (type fixnum at count))
                   (loop (when (>= at end) (fail))
                         (let ((byte (aref bytes at)))
                           (cond ((= byte 34) (return))
                                 ((< byte #x80) (when (= byte 92) (setf plain nil) (incf at) (when (>= at end) (fail)))
                                  (setf at (nth-value 1 (code-at at))))
                                 (t (setf plain nil at (nth-value 1 (code-at at))))))
                         (incf count))
                   (let ((string (make-string count)))
                     (if plain
                         (dotimes (i count) (setf (schar string i) (code-char (aref bytes (+ pos i)))))
                         (let ((from pos))
                           (declare (type fixnum from))
                           (dotimes (i count)
                             (when (= (aref bytes from) 92) (incf from))
                             (multiple-value-bind (code next) (code-at from)
                               (setf (schar string i) (code-char code) from next)))))
                     (setf pos (1+ at))
                     string)))
               (read-token ()
                 (let ((start pos))
                   (declare (type fixnum start))
                   (loop while (and (< pos end) (not (delimiter-p (aref bytes pos)))) do (incf pos))
                   (let* ((sign (if (and (< start pos) (or (= (aref bytes start) 43) (= (aref bytes start) 45))) 1 0))
                          (digits (+ start sign)))
                     (declare (type fixnum digits))
                     (cond ((= start pos) (fail))
                           ((and (< digits pos) (<= (- pos digits) 18)
                                 (loop for i of-type fixnum from digits below pos always (<= 48 (aref bytes i) 57)))
                            (let ((n 0))
                              (declare (type (unsigned-byte 62) n))
                              (loop for i of-type fixnum from digits below pos
                                    do (setf n (+ (* n 10) (- (aref bytes i) 48))))
                              (if (and (= sign 1) (= (aref bytes start) 45)) (- n) n)))
                           ((and (= (- pos start) 3) (= (aref bytes start) 78) (= (aref bytes (+ start 1)) 73)
                                 (= (aref bytes (+ start 2)) 76))
                            nil)
                           ((and (= (- pos start) 1) (= (aref bytes start) 84)) t)
                           ((and (= (aref bytes start) 58) (< (1+ start) pos) (<= 65 (aref bytes (1+ start)) 90)
                                 (loop for i of-type fixnum from (1+ start) below pos
                                       always (let ((byte (aref bytes i))) (or (<= 65 byte 90) (<= 48 byte 57) (= byte 45)))))
                            (let ((name (make-string (- pos start 1) :element-type 'base-char)))
                              (loop for i of-type fixnum from (1+ start) below pos
                                    for j of-type fixnum from 0
                                    do (setf (schar name j) (code-char (aref bytes i))))
                              (values (intern name :keyword))))
                           (t (fail))))))
               (read-list ()
                 (let ((head nil) (tail nil))
                   (loop
                     (setf pos (skip pos))
                     (when (>= pos end) (fail))
                     (let ((byte (aref bytes pos)))
                       (cond ((= byte 41) (incf pos) (return head))
                             ((and (= byte 46) tail (< (1+ pos) end) (delimiter-p (aref bytes (1+ pos))))
                              (incf pos)
                              (setf (cdr tail) (read-datum) pos (skip pos))
                              (unless (and (< pos end) (= (aref bytes pos) 41)) (fail))
                              (incf pos)
                              (return head))
                             (t (let ((cell (list (read-datum))))
                                  (if tail (setf (cdr tail) cell) (setf head cell))
                                  (setf tail cell))))))))
               (read-datum ()
                 (setf pos (skip pos))
                 (when (>= pos end) (fail))
                 (let ((byte (aref bytes pos)))
                   (cond ((= byte 40) (incf pos) (read-list))
                         ((= byte 34) (incf pos) (read-string))
                         ((= byte 41) (fail))
                         (t (read-token))))))
        (let ((datum (read-datum)))
          (unless (= (skip pos) end) (fail))
          datum)))))
