(defpackage #:ekko/runtime
  (:use #:cl #:ekko/platform #:ekko/vt #:ekko/graphics)
  (:export #:run-session #:serve #:attach-session #:control-session #:restore-terminal))
(in-package #:ekko/runtime)

(defconstant +wire-version+ 2)
(defconstant +queue-limit+ (* 8 1024 1024))
(defstruct wire fd (queue nil) (queue-tail nil) (queued 0) (offset 0) (prefix (octets 4))
  (prefix-used 0) body (body-used 0) (known (make-hash-table :test 'equal))
  attached revision awaiting-scene (leases nil) (at (now)))
(defun u32 (bytes offset)
  (loop for i from offset below (+ offset 4) for value = (aref bytes i) then (+ (ash value 8) (aref bytes i)) finally (return value)))
(defun put-u32 (bytes offset value)
  (dotimes (i 4) (setf (aref bytes (+ offset i)) (ldb (byte 8 (* 8 (- 3 i))) value))))
(defun integers (values)
  (let ((out (octets (* 4 (length values)))))
    (loop for value in values for offset from 0 by 4 do (put-u32 out offset value)) out))
(defun queue-bytes (wire data)
  (when (> (+ (wire-queued wire) (length data)) +queue-limit+) (error "Output queue limit exceeded"))
  (let ((cell (list data)))
    (if (wire-queue-tail wire)
        (setf (cdr (wire-queue-tail wire)) cell)
        (setf (wire-queue wire) cell))
    (setf (wire-queue-tail wire) cell))
  (incf (wire-queued wire) (length data)))
(defun send-packet (wire type &optional (data (octets 0)))
  (let ((packet (octets (+ 5 (length data)))))
    (put-u32 packet 0 (1+ (length data))) (setf (aref packet 4) type)
    (replace packet data :start1 5) (queue-bytes wire packet)))
(defun flush-wire (wire)
  (loop repeat 16 while (wire-queue wire) for data = (first (wire-queue wire))
        for n = (write-fd (wire-fd wire) data (wire-offset wire)) do
    (cond ((member n '(-11 -4)) (return)) ((<= n 0) (error "Output disconnected"))
          (t (incf (wire-offset wire) n) (decf (wire-queued wire) n)
             (when (= (wire-offset wire) (length data))
               (pop (wire-queue wire))
               (when (null (wire-queue wire)) (setf (wire-queue-tail wire) nil))
               (setf (wire-offset wire) 0))))))
(defun wire-feed (wire bytes count)
  (let ((offset 0) (packets nil))
    (loop while (< offset count) do
      (if (wire-body wire)
          (let ((n (min (- count offset) (- (length (wire-body wire)) (wire-body-used wire)))))
            (replace (wire-body wire) bytes :start1 (wire-body-used wire) :start2 offset :end2 (+ offset n))
            (incf offset n) (incf (wire-body-used wire) n)
            (when (= (wire-body-used wire) (length (wire-body wire)))
              (push (wire-body wire) packets)
              (setf (wire-body wire) nil (wire-body-used wire) 0 (wire-prefix-used wire) 0)))
          (let ((n (min (- count offset) (- 4 (wire-prefix-used wire)))))
            (replace (wire-prefix wire) bytes :start1 (wire-prefix-used wire) :start2 offset :end2 (+ offset n))
            (incf offset n) (incf (wire-prefix-used wire) n)
            (when (= (wire-prefix-used wire) 4)
              (let ((size (u32 (wire-prefix wire) 0)))
                (unless (<= 1 size +queue-limit+) (error "Invalid IPC frame size"))
                (setf (wire-body wire) (octets size)))))))
    (nreverse packets)))
(defun receive-packets (wire buffer)
  (let ((n (read-fd (wire-fd wire) buffer)))
    (cond ((member n '(-11 -4)) nil) ((<= n 0) (error "Input disconnected"))
          (t (setf (wire-at wire) (now)) (wire-feed wire buffer n)))))
(defun wire-events (wire) (logior 1 (if (wire-queue wire) 4 0)))
(defun acknowledge-scene (wire)
  (dolist (asset (wire-leases wire)) (release-asset asset))
  (setf (wire-leases wire) nil (wire-awaiting-scene wire) nil))
(defun close-wire (wire) (close-fd (wire-fd wire))
  (setf (wire-queue wire) nil (wire-queue-tail wire) nil (wire-body wire) nil)
  (clrhash (wire-known wire)) (acknowledge-scene wire))
(defun socket-path (name)
  (unless (and (<= 1 (length name) 40) (every (lambda (c) (or (alphanumericp c) (find c "_-"))) name))
    (error "Session names must contain 1–40 letters, digits, underscores or hyphens"))
  (let* ((base (or (uiop:getenv "XDG_RUNTIME_DIR") (format nil "/tmp/ekko-v2-~D" (sb-posix:getuid))))
         (dir (format nil "~A/ekko-v2/" base)))
    (ensure-directories-exist dir)
    (let ((st (sb-posix:lstat (string-right-trim "/" dir))))
      (unless (and (= (sb-posix:stat-uid st) (sb-posix:getuid))
                   (sb-posix:s-isdir (sb-posix:stat-mode st))) (error "Unsafe session directory")))
    (sb-posix:chmod dir #o700)
    (format nil "~A~A.sock" dir name)))
(defun encode-scene (scene)
  (text-bytes (with-standard-io-syntax (let ((*print-readably* t) (*print-pretty* nil)) (write-to-string scene)))))
(defun decode-scene (bytes)
  (when (> (length bytes) (* 1024 1024)) (error "Scene metadata too large"))
  (with-standard-io-syntax (let ((*read-eval* nil)) (read-from-string (bytes-text bytes)))))
